### ISSUE TITLE
the video is lagging

### ISSUE THREAD

**Issue by byMohamedali** [kingslay/KSPlayer#1]
Hi,

I try the demo with swiftUI but the video is lagging do you know how to fix it or are you aware of this problem ? 

please check the video 
https://vimeo.com/user109748579/review/397841983/c8bdb8dcf0
Thank you

**Comment by kingslay** [comment]
https://vimeo.com/user109748579/review/397841983/c8bdb8dcf0: Invalid data found when processing input

![20200316101821](https://user-images.githubusercontent.com/3964055/76717738-85150700-676f-11ea-88cb-9a03ddca16d5.png)

**Comment by byMohamedali** [comment]
Sorry I thought it was uploaded please check here 
https://youtu.be/fUShiySHMS8

**Comment by byMohamedali** [comment]
Also I got this error when I try to play a stream, it's working fine first but after few seconds it the video stop I got this error in the log

`KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 1

KSPlayer: MEPlayerItem.swift:93 init(url:options:) | ct_type:0 pic_struct:1

KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 9(AUD), nal_ref_idc: 0

KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 6(SEI), nal_ref_idc: 0

KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 1

KSPlayer: MEPlayerItem.swift:93 init(url:options:) | ct_type:0 pic_struct:2

KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 9(AUD), nal_ref_idc: 0

KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 6(SEI), nal_ref_idc: 0

KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 1

KSPlayer: MEPlayerItem.swift:93 init(url:options:) | ct_type:0 pic_struct:1

KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 9(AUD), nal_ref_idc: 0

KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 6(SEI), nal_ref_idc: 0

KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 1

KSPlayer: MEPlayerItem.swift:93 init(url:options:) | ct_type:0 pic_struct:2

KSPlayer: MEPlayerItem.swift:93 init(url:options:) | bytestream overread -3

KSPlayer: MEPlayerItem.swift:93 init(url:options:) | bytestream overread -3

KSPlayer: MEPlayerItem.swift:93 init(url:options:) | bytestream overread -3

KSPlayer: MEPlayerItem.swift:93 init(url:options:) | bytestream overread -3

KSPlayer: MEPlayerItem.swift:93 init(url:options:) | bytestream overread -3

KSPlayer: MEPlayerItem.swift:93 init(url:options:) | bytestream overread -5

KSPlayer: MEPlayerItem.swift:93 init(url:options:) | error while decoding MB 21 23, bytestream -5`

**Comment by kingslay** [comment]
> Also I got this error when I try to play a stream, it's working fine first but after few seconds, the video stop and I got this error in the log
> 
> `KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 1
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | ct_type:0 pic_struct:1
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 9(AUD), nal_ref_idc: 0
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 6(SEI), nal_ref_idc: 0
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 1
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | ct_type:0 pic_struct:2
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 9(AUD), nal_ref_idc: 0
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 6(SEI), nal_ref_idc: 0
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 1
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | ct_type:0 pic_struct:1
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 9(AUD), nal_ref_idc: 0
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 6(SEI), nal_ref_idc: 0
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 1
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | ct_type:0 pic_struct:2
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | bytestream overread -3
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | bytestream overread -3
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | bytestream overread -3
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | bytestream overread -3
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | bytestream overread -3
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | bytestream overread -5
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | error while decoding MB 21 23, bytestream -5`



> Also I got this error when I try to play a stream, it's working fine first but after few seconds, the video stop and I got this error in the log
> 
> `KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 1
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | ct_type:0 pic_struct:1
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 9(AUD), nal_ref_idc: 0
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 6(SEI), nal_ref_idc: 0
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 1
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | ct_type:0 pic_struct:2
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 9(AUD), nal_ref_idc: 0
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 6(SEI), nal_ref_idc: 0
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 1
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | ct_type:0 pic_struct:1
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 9(AUD), nal_ref_idc: 0
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 6(SEI), nal_ref_idc: 0
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 1
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | ct_type:0 pic_struct:2
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | bytestream overread -3
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | bytestream overread -3
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | bytestream overread -3
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | bytestream overread -3
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | bytestream overread -3
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | bytestream overread -5
> 
> KSPlayer: MEPlayerItem.swift:93 init(url:options:) | error while decoding MB 21 23, bytestream -5`

can you  provide the video url ？

**Comment by byMohamedali** [comment]
Please send me a mail or provide me something where I can join you privately, because the url it's an iptv link that I bought, I will send it to you in private.

moha.by@icloud.com

**Comment by kingslay** [comment]
> Please send me a mail or provide me something where I can join you privately, because the url it's an iptv link that I bought, I will send it to you in private.
> 
> [moha.by@icloud.com](mailto:moha.by@icloud.com)

the latest code i increase the timeout and rw_timeout.  can you try again?

**Comment by byMohamedali** [comment]
Thank you it's working, You rocks ! Thanks 😁
