### ISSUE TITLE
Unable to build on Apple Silicon M1

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#102]
I get the following error when trying to build on the new Apple Silicon M1 chipset :

`warning: [CP] Unable to find matching .xcframework slice in '/Users/blah/Programming/myCode/blah/Pods/KSPlayer/Sources/FFmpeg.xcframework FFmpeg framework tvos-x86_64-simulator tvos-arm64' for the current build architectures (arm64).
`

This is for simulator.

**Comment by wertpoiu** [comment]
Hi @kingslay please sort this out.

**Comment by snappycode1** [comment]
I guess development has stalled on this.  7 days without reply to this and other issues.  Please @kingslay, reply to us :)

**Comment by kingslay** [comment]
this is need the ffmpeg and openssl can build on Apple Silicon M1. you can change the Script/build-ffmpeg.sh and Script /build-openssl.sh  to adaptation  Apple Silicon M1

**Comment by snappycode1** [comment]
Thanks for the reply but it means nothing to me.  I don't understand.  Are you likely to fix this for Apple Silicon for us? Do you need remote access to an M1 machine?  I can help with that.

**Comment by wertpoiu** [comment]
Hi @kingslay any update on this?
