### ISSUE TITLE
How do I play a list of videos like Playlist?

### ISSUE THREAD

**Issue by ZUCheema** [kingslay/KSPlayer#107]

**Comment by kingslay** [comment]
Does not support this feature

**Comment by ZUCheema** [comment]
Any chances to add it? 
As its using AVPlayer and AVPlayer does support playing a queue!

**Comment by kingslay** [comment]
what do you mean is  AVQueuePlayer?

**Comment by ZUCheema** [comment]
Yes, AVQueuePlayer.
