### ISSUE TITLE
latest commit ffmpeg error

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#109]
I've just checked out the latest commits and get the following error when doing a pod update

```
Update all pods
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `KSPlayer` from `https://github.com/kingslay/KSPlayer.git`, branch `develop`
Pre-downloading: `OpenSSL` from `https://github.com/kingslay/KSPlayer.git`, branch `develop`
[!] The platform of the target `myApp` (tvOS 13.0) is not compatible with `FFmpeg (2.8.3)`, which does not support `tvOS`.
```

**Comment by kingslay** [comment]
pod 'KSPlayer',:git => 'https://github.com/kingslay/KSPlayer.git', :branch => 'develop'
    pod 'FFmpeg',:git => 'https://github.com/kingslay/KSPlayer.git', :branch => 'develop'
    pod 'Openssl',:git => 'https://github.com/kingslay/KSPlayer.git', :branch => 'develop'

**Comment by UnknownCoder807** [comment]
Thanks, that works.
