### ISSUE TITLE
how to select audio track

### ISSUE THREAD

**Issue by prikshitgupta** [kingslay/KSPlayer#11]
How do i select audio track if video has several audio tracks?

**Comment by kingslay** [comment]
Selecting Tracks
```
  let player: MediaPlayerProtocol
  let tracks = player.tracks(mediaType: .audio)
  let track = tracks[1]
  /// the name of the track
  let name = track.name
  /// the language of the track
  let language = track.language
  /// selecting the one
	player.select(track: track)
```

**Comment by byMohamedali** [comment]
`player.select(track: track)` work only if we seek the player after changing the track, it doesn't change  by calling calling this function. It is a wanted behavior ?

**Comment by kingslay** [comment]
yes. There's a bit of a delay in switching tracks.

**Comment by kingslay** [comment]
i fixed. after select(track) I seek the player
