### ISSUE TITLE
How to detect if media is HRD or SDR

### ISSUE THREAD

**Issue by Alanko5** [kingslay/KSPlayer#112]
Please, how can I find out if the content is HDR or SDR?

**Comment by Alanko5** [comment]
Please create delegateMethod for notify framerate and HDR content:
```
enum DynamicRange {
    case SDR
    case HDR
    case HDR10
    case DolbyVision 
    case Unknown
}
func mediaDidChange(player: MediaPlayerProtocol, fps: Int, contentMode: DynamicRange)
```
This delegate should always call after loading the stream.

In appleTv need switch TV colors to HDR mode and display refresh rate.

https://video.stackexchange.com/questions/22059/how-to-identify-hdr-video

**Comment by Alanko5** [comment]
PLS how to use colorDepth?
What do hou mean if colorDepth == 8? 
And other values?

**Comment by kingslay** [comment]
SDR: colorDepth == 8
HDR10 : colorDepth == 10
DolbyVision : colorDepth == 12

**Comment by Alanko5** [comment]
Exists colors:
SDR
HDR10
HDR10+
DolbyVision
HLG
AHDR

can you provide me with all this information please?
