### ISSUE TITLE
Q: Swift Package

### ISSUE THREAD

**Issue by Alanko5** [kingslay/KSPlayer#113]
It is possible to make a Swift Package?

FFMPEG comming son
https://github.com/tanersener/mobile-ffmpeg/pull/599
SSL
https://github.com/apple/swift-nio-ssl
https://github.com/krzyzanowskim/OpenSSL

**Comment by kingslay** [comment]
KSPlayer is support Swift Package. you can open  Package.swift

**Comment by Alanko5** [comment]
I try it. THX
