### ISSUE TITLE
Xcode 12, building for tvOS, but linking in object file built for tvOS Simulator, for architecture arm64

### ISSUE THREAD

**Issue by WaheedAbbas** [kingslay/KSPlayer#114]
I am using KSPlayer in tvOS. The code successfully runs on a tvOS simulator. The library also works great on iOS in both debug and release modes. But when I try to create an archive, I get the following error:
` /Users/waheedabbas/Library/Developer/Xcode/DerivedData/storyinternet-ott-tvOS-hcllvitprlaliufwseqqdmffqhdi/Build/Intermediates.noindex/ArchiveIntermediates/app_5f2ac7f61ca6e5d82a91ee24/BuildProductsPath/app_5f2ac7f61ca6e5d82a91ee24_release-appletvos/Libcrypto.framework/Libcrypto(aes_cbc.o), building for tvOS, but linking in object file (/Users/waheedabbas/Library/Developer/Xcode/DerivedData/storyinternet-ott-tvOS-hcllvitprlaliufwseqqdmffqhdi/Build/Intermediates.noindex/ArchiveIntermediates/app_5f2ac7f61ca6e5d82a91ee24/BuildProductsPath/app_5f2ac7f61ca6e5d82a91ee24_release-appletvos/Libcrypto.framework/Libcrypto(aes_cbc.o)) built for tvOS Simulator, file '/Users/waheedabbas/Library/Developer/Xcode/DerivedData/storyinternet-ott-tvOS-hcllvitprlaliufwseqqdmffqhdi/Build/Intermediates.noindex/ArchiveIntermediates/app_5f2ac7f61ca6e5d82a91ee24/BuildProductsPath/app_5f2ac7f61ca6e5d82a91ee24_release-appletvos/Libcrypto.framework/Libcrypto' for architecture arm64
`
I tried many things from [this](https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios) post but nothing works. Can you please provide some help on this?
Thank you

**Comment by kingslay** [comment]
you can  try update cocoapods  to 1.9.3

**Comment by WaheedAbbas** [comment]
> you can try update cocoapods to 1.9.3

Thank you. Upgrading cocoa pods solved it.
