### ISSUE TITLE
HDR content wrong colors

### ISSUE THREAD

**Issue by Alanko5** [kingslay/KSPlayer#115]
@kingslay I test your last updates.

I see many issues:
 1. bad Colors for some HDR content
 2. wrong representation "fps" but use int, right values are 24, 25, 30,50,60, you return. you should round up, not down.
 3. content not playing or too long start or playback is not smooth 
 4. missing setting for HDR+ / LGH (Hybrid Log-Gamma)

**WRONG Colors - Tested URL:**
https://sylvan.apple.com/Aerials/2x/Videos/LA_A006_C008_2K_HDR_HEVC.mov
**player:** 
KSMEPlayer
**Colors in TV:**
![IMG_0189](https://user-images.githubusercontent.com/71501260/106142796-36e3d900-6172-11eb-8011-c572ade00c2b.jpg)
Colors in simulator is OK

**Playback is not smooth tested URL in VLCapp player playing ok**
 - http://media.developer.dolby.com/DolbyVision_Atmos/mp4/P81_GlassBlowing2_3840x2160%4059.94fps_15200kbps_fmp4.mp4
 - http://media.developer.dolby.com/DolbyVision_Atmos/profile5_HLS/master.m3u8

**This content is DollbyVision and you mark as HDR**
http://media.developer.dolby.com/DolbyVision_Atmos/mp4/P81_GlassBlowing2_3840x2160%4059.94fps_15200kbps_fmp4.mp4

**NotPlayng on atv and in Simulator have bad colors:**
http://itsvet.net/KODI/ATV_SCC/exaples/Countdown-v1-Dolby-thedigitaltheater.mp4
![Simulator Screen Shot](https://user-images.githubusercontent.com/71501260/106145389-c8087f00-6175-11eb-887c-47c13ba83059.png)

**Comment by Alanko5** [comment]
I go download last commit:
https://github.com/kingslay/KSPlayer/commit/0d3901e83100198fe00dbd399555cd574fd4f1d4

when I try I will give you information

**Comment by Alanko5** [comment]
In new wersion is same problems

Only HDR colors litle change.
**Tested URL:**
https://sylvan.apple.com/Aerials/2x/Videos/LA_A006_C008_2K_HDR_HEVC.mov

![IMG_0190](https://user-images.githubusercontent.com/71501260/106161453-4de0f600-6187-11eb-9082-214f5211cc0f.jpg)

**Comment by Alanko5** [comment]
**Informations for mov file:**
<img width="338" alt="Screenshot 2021-01-28 at 16 46 34" src="https://user-images.githubusercontent.com/71501260/106162423-630a5480-6188-11eb-8039-074dd1d5eb80.png">

**Comment by MarkyAli** [comment]
LA_A006_C008_2K_HDR_HEVC.mov is DolbyVision, you detect HDR not DolbyVision

**Comment by kingslay** [comment]
What software did you use to get this Informations from mov file

**Comment by Alanko5** [comment]
This screen is from QuickTime 

If you use let asset = AVAsset(url: url), then you read let criteria = asset.preferredDisplayCriteria. 

criteria.videoDynamicRange == 5 is DolbyVision


You must add header:
```
#ifndef AVDisplayCriteriaKS_h
#define AVDisplayCriteriaKS_h

#import <AVFoundation/AVDisplayCriteria.h>

@interface AVDisplayCriteria ()
@property(readonly) int videoDynamicRange;
@property(readonly, nonatomic) float refreshRate;
- (id)initWithRefreshRate:(float)arg1 videoDynamicRange:(int)arg2;
@end

#endif
```

Work only with Apple Supported formats.
I showing this information on right top.

First AVAsset criteria second is KSPlayer detect information.

**Comment by Alanko5** [comment]
Hi, @kingslay 

How are you doing with HDR repair?
Can I try the latest committees?
Or it still not correct?

THX

**Comment by kingslay** [comment]
you can try the commit. I had repair the  wrong colors.

**Comment by MarkyAli** [comment]
I test HDR10 content, I didn't see any color issues.
I'll try another TV later.

How do I know what colors to set for TV?

KSPlayer DolbyVision:
![IMG_0217](https://user-images.githubusercontent.com/9935527/108835818-4cf98380-75d0-11eb-8ca9-c3fd92c4cb2f.jpg)

Original:
![IMG_0216](https://user-images.githubusercontent.com/9935527/108835858-5be03600-75d0-11eb-93c1-918a3004f40b.jpg)

**Comment by Alanko5** [comment]
It's noticeably better than it was.

I test HDR10 content, I didn't see any color issues.
I'll try another TV later.

How do I know what colors to set for TV?

KSPlayer DolbyVision:
![108835818-4cf98380-75d0-11eb-8ca9-c3fd92c4cb2f](https://user-images.githubusercontent.com/71501260/108836739-8088dd80-75d1-11eb-821e-f28a743f8feb.jpg)

Original:
![108835858-5be03600-75d0-11eb-93c1-918a3004f40b](https://user-images.githubusercontent.com/71501260/108836762-87175500-75d1-11eb-8f9b-dbfde3cb9296.jpg)

**Comment by Alanko5** [comment]
If create creenshot on AppleTV, then colors is ok:
![Screen Shot 2021-02-23 at 12 06 52](https://user-images.githubusercontent.com/71501260/108837089-09077e00-75d2-11eb-9b85-f887a6851767.png)
I have to do a test on another TV as well.

**Comment by Alanko5** [comment]
KSPlayer HDR 10:
![Screen Shot 2021-02-23 at 19 45 45](https://user-images.githubusercontent.com/71501260/108893816-ce253a80-7611-11eb-8385-07f66f7af44f.png)

KSAVPlayer HDR10:
![Screen Shot 2021-02-23 at 19 44 20](https://user-images.githubusercontent.com/71501260/108893854-d8dfcf80-7611-11eb-8690-b5a058796600.png)

**Comment by Alanko5** [comment]
HDR10 tested on another TV:
![image0 2](https://user-images.githubusercontent.com/71501260/108907046-e604ba80-7621-11eb-8985-3b9c31135a1e.jpg)

**Comment by Alanko5** [comment]
Hi @kingslay, 
did you have time to look at Dolby Vision?
In what state we are?
Does HDR work correctly?

**Comment by kingslay** [comment]
yes. it can work for HDR. you can try the  latest code
