### ISSUE TITLE
On the last update the player cannot open any video due to an avformat error 

### ISSUE THREAD

**Issue by byMohamedali** [kingslay/KSPlayer#116]
Hi Kingslay,

On the last update the player cannot open any video due to an avformat error 

Error Domain=KSPlayerErrorDomain Code=2 "avformat can't open input" UserInfo={NSLocalizedDescription=avformat can't open input, NSUnderlyingError=0x2828cfa80 {Error Domain=FFmpegDomain Code=-1094995529 "Invalid data found when processing input" UserInfo={NSLocalizedDescription=Invalid data found when processing input}}}

**Comment by kingslay** [comment]
the commit is 8408f2b73c522dcc1e86c6cd00293f91ef7ee029 ?

**Comment by byMohamedali** [comment]
I just tested on this one f6d721a6069a355ac4513d47884bee65ee2182b3
It doesn't work

**Comment by kingslay** [comment]
you can remove Pods and run pod install  use cocoapods 1.10.1

**Comment by UnknownCoder807** [comment]
When I had this error, I had to remove the pods from the Podfile, pod install, to remove them

The readd them to the Podfile and pod install

**Comment by kingslay** [comment]
the Podfile is 
```
  pod 'KSPlayer',:git => 'https://github.com/kingslay/KSPlayer.git', :branch => 'develop'
    pod 'FFmpeg',:git => 'https://github.com/kingslay/KSPlayer.git', :branch => 'develop'
    pod 'Openssl',:git => 'https://github.com/kingslay/KSPlayer.git', :branch => 'develop'
```
?

**Comment by byMohamedali** [comment]
```
  pod 'KSPlayer',:git => 'https://github.com/kingslay/KSPlayer.git', :branch => 'develop', :commit => 'f6d721a6069a355ac4513d47884bee65ee2182b3'
  pod 'FFmpeg',:git => 'https://github.com/kingslay/KSPlayer.git', :branch => 'develop', :commit => 'f6d721a6069a355ac4513d47884bee65ee2182b3'
  pod 'OpenSSL',:git => 'https://github.com/kingslay/KSPlayer.git', :branch => 'develop', :commit => 'f6d721a6069a355ac4513d47884bee65ee2182b3'
```
Thank you guys, it's working 👍
