### ISSUE TITLE
Improvement for 4k Video

### ISSUE THREAD

**Issue by byMohamedali** [kingslay/KSPlayer#117]
Hi @kingslay,

When Watching 4k videos, the player is lagging, I know you are aware of this issue, is there any plan or solution to fix it. The library is good, it's the only thing pending to push it on production :)

**Comment by kingslay** [comment]
Does the latest code still have this problem?

**Comment by byMohamedali** [comment]
Yes it still happening, it's better than before but still lagging

**Comment by kingslay** [comment]
can you provide the video let me test？

**Comment by Paladinfeng** [comment]
### disable hardware decode is better, but still lagging

- playURL: https://upos-sz-mirrorkodo.bilivideo.com/upgcxcode/65/46/244954665/244954665-1-30120.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1612255126&gen=playurl&os=kodobv&oi=3683581502&trid=27113f80b47d456d9107cfb6db3094cau&platform=pc&upsig=02b6394bc94c9772668bb59e0fb1c895&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=1889710&orderid=0,3&agrr=1&logo=80000000
- You need set header before play
```
let options = KSOptions()
options.formatContextOptions["headers"] = "Referer: https://www.bilibili.com/"
```

**Comment by ivank00** [comment]
Hello!
Any updates here? Unfortunately, I'm facing the same problem. Video is lagging and after some time becomes desynchronized with audio. I'm trying to play a live-stream video in 4K.

**Comment by kingslay** [comment]
Can’t find an optimization solution yet

**Comment by jartas** [comment]
We have a new year 2022, There really is no solution that solves the problem by playing 4K movies ?? Thank you
