### ISSUE TITLE
Q: Convert video to supported formats 

### ISSUE THREAD

**Issue by MarkyAli** [kingslay/KSPlayer#119]
@kingslay 
Please, is it possible to convert an unsupported format (such as MKV) to an Apple supported format (such as MP4) and use a native player for playback? 

I mean real time convert wiithout last quality audio or video tracks. 

And use KSAVPleyr for playing any content.

**Comment by kingslay** [comment]
It is difficult to implement this function

**Comment by eximpression** [comment]
I think you can use ffmpeg to do covert works. But if you can play MKV directly, why are you need to convert to MP4 and then play. The player decode media to raw data that can play directly, but what you want is decode to raw data and encode to MP4 and then decode to raw data to play. What's the meaning?
