### ISSUE TITLE
How to enable the seek to view

### ISSUE THREAD

**Issue by snappycode1** [kingslay/KSPlayer#12]
How do I enable the seek to view function for when watching movies?  thanks.

**Comment by kingslay** [comment]
Update the latest code.

**Comment by kingslay** [comment]
You can seek through the progress bar. Or swipe left and right under the horizontal screen.

**Comment by snappycode1** [comment]
I see this works on the iOS demo but not the tvOS demo.  Is there something extra I need to do on TVOS to make the on screen controls appear?
