### ISSUE TITLE
audio passthrough

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#120]
My KSPlayer implementation plays movies that have a 5.1 audio track as 2.0 stereo.  Is there a setting to passthrough the 5.1 audio for the amp to decode instead?

**Comment by MarkyAli** [comment]
@UnknownCoder807 Did you solve it?

**Comment by UnknownCoder807** [comment]
I didn't unfortunately.  I'll reopen this and see if it's possible.

**Comment by eximpression** [comment]
This is hard. As I know, KSPlayer resample the audio to 2 channels with swresample. If you want raw audio data out with 5.1 channel layout. you need disable audio resample and make some change to set correct ASBD to remoteI/O audiounit.

**Comment by kingslay** [comment]
you can try to change the KSPlayerManager.audioPlayerMaximumChannels

**Comment by MarkyAli** [comment]
@kingslay 
KSPlayerManager.audioPlayerMaximumChannels = .max

<img width="1354" alt="Screenshot 2021-02-23 at 15 00 09" src="https://user-images.githubusercontent.com/9935527/108854163-d5375300-75e7-11eb-90f1-b12dcde6e38a.png">

**Comment by MarkyAli** [comment]
@kingslay 
KSPlayerManager.audioPlayerMaximumChannels = .init(12)
<img width="1347" alt="Screenshot 2021-02-23 at 15 07 16" src="https://user-images.githubusercontent.com/9935527/108855042-d3ba5a80-75e8-11eb-8aab-2d998e603182.png">

**Comment by MarkyAli** [comment]
KSPlayerManager.audioPlayerMaximumChannels = .init(8.2)

Do not crash.
But I dont have surround.
Therefore, I can't test the functionality.

**Comment by kingslay** [comment]
@MarkyAli 
KSPlayerManager.audioPlayerMaximumChannels = AVAudioChannelCount(6)

**Comment by Alanko5** [comment]
@kingslay maximum chanels is 5.1? KS not support 7.1ch audio?

**Comment by kingslay** [comment]
@MarkyAli you can try the latest code
