### ISSUE TITLE
Arithmetic overflow crash

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#122]
My app using KSPlayer is having several crashes due to the following error :

<img width="736" alt="Screenshot 2021-02-16 at 11 44 00" src="https://user-images.githubusercontent.com/56231066/108058920-a00d8c80-704c-11eb-94a3-bd10c45daf28.png">

<img width="1416" alt="Screenshot 2021-02-16 at 11 42 49" src="https://user-images.githubusercontent.com/56231066/108058931-a1d75000-704c-11eb-9ad5-a9b61f6e45c0.png">

**Comment by UnknownCoder807** [comment]
Sorry but this issue still exists.  Here is the latest stack trace which is slightly different to the previous one.

<img width="734" alt="Screenshot 2021-02-19 at 08 20 33" src="https://user-images.githubusercontent.com/56231066/108477819-a50c4f00-728b-11eb-904a-2b12770fe36e.png">

**Comment by kingslay** [comment]
@UnknownCoder807  you can try 7c29a23f57e0cc940fddcb88008a3618fb2dd0cd

**Comment by UnknownCoder807** [comment]
Thanks for the fix.  I am unable to test it myself as it is my users of my app that are having the crashes.

I will report in a day or 2 whether there are any more crashes and will provide any info needed.
