### ISSUE TITLE
XCFramework slices has missing Info.plist files

### ISSUE THREAD

**Issue by 0xacdc** [kingslay/KSPlayer#126]
Every .xcframework is missing Info.plist for every slice

<img width="341" alt="Screenshot 2021-02-27 at 10 56 25" src="https://user-images.githubusercontent.com/38544113/109382662-c7c8e400-78d9-11eb-9243-dc9f9782ecb1.png">

**Comment by kingslay** [comment]
fixed at 7dd149c823eb0fa31d4eec0d508c652df717ffa7
