### ISSUE TITLE
TvOS ViewController

### ISSUE THREAD

**Issue by Alanko5** [kingslay/KSPlayer#127]
@kingslay 
I am preparing a View Controller for tvOS.
Before I continue.
I want to make sure you're interested.

The controller will be displayed as a native tvOS player controller.
It will support audio track switching, subtitle switching, ResourceDefinition switching, etc.

Here I start to open it:
https://github.com/Alanko5/KSPlayer/tree/feature/tvOSViewController

**Comment by kingslay** [comment]
ok. thanks you. I is interested.

**Comment by Alanko5** [comment]
Ok, in that case I will continue, if it is ready I will create a pull request.
