### ISSUE TITLE
Crash in Simulator - MTLValidateFeatureSupport

### ISSUE THREAD

**Issue by Alanko5** [kingslay/KSPlayer#128]
MTLValidateFeatureSupport:3901: failed assertion `Linear textures from shared buffers is not supported on this device'

<img width="1872" alt="Screenshot 2021-02-27 at 10 13 38" src="https://user-images.githubusercontent.com/71501260/109383092-77a34f00-78e4-11eb-9b65-572f27645e32.png">

https://developer.apple.com/documentation/metal/developing_metal_apps_that_run_in_simulator

Texture Limitations
When working with textures in Simulator, follow these recommendations:
If you want to create a texture that shares storage with a buffer (using makeTexture(descriptor:offset:bytesPerRow:)), you must create the buffer with a private (MTLStorageMode.private) storage mode. Call minimumLinearTextureAlignment(for:) to determine the alignment requirements for the texture data; the alignment requirements are different in Simulator. When setting the texture's usage property, you can't include renderTarget as one of the uses.
Create depth, stencil, and MSAA textures only with private storage modes.
Don't use a sample count of 2 for MSAA textures.
Use only unified depth and stencil texture formats. Simulator doesn't support separate depth and stencil formats.
Don't use the following pixel formats: MTLPixelFormat.r8Unorm_srgb, MTLPixelFormat.b5g6r5Unorm, MTLPixelFormat.a1bgr5Unorm, MTLPixelFormat.abgr4Unorm, MTLPixelFormat.bgr5A1Unorm, or any XR10 or YUV formats.
Don't render to textures with a MTLPixelFormat.rgb9e5Float format.
You can't write to sRGB textures in Simulator.

**Comment by kingslay** [comment]
I know this issue. I must use real machine. 
when I create the buffer with a private (MTLStorageMode.private) storage mode.
I get it  
`-[MTLToolsResource validateCPUWriteable]:128: failed assertion `resourceOptions (0x20) specify MTLResourceStorageModePrivate, which is not CPU accessible.'`
