### ISSUE TITLE
MetalRender - library,  crashes on force unwrap 

### ISSUE THREAD

**Issue by 0xacdc** [kingslay/KSPlayer#129]
`library = device.makeDefaultLibrary()` is **nil** 
`let path = Bundle(for: MetalRender.self).path(forResource: "Metal", ofType: "bundle")` - is **nil** 

as result 
`Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file KSPlayer/MetalRender.swift, line 25`

**Comment by kingslay** [comment]
in  Podfile 

`use_frameworks! :linkage => :static
`

**Comment by 0xacdc** [comment]
I'm using  SwiftPM
