### ISSUE TITLE
video is starting from 10 mins not 0:00

### ISSUE THREAD

**Issue by prikshitgupta** [kingslay/KSPlayer#13]
Video not starting from 0:00 (Live video or VOD)

**Comment by kingslay** [comment]
update the laster code

**Comment by prikshitgupta** [comment]
> update the laster code

Issue is still there i updated the library

**Comment by kingslay** [comment]
Is it the develop branch?
the commit is fix startTime	81352a55916b7752f4cc30dc9a2049c2df450bb4

**Comment by prikshitgupta** [comment]
Its master

**Comment by prikshitgupta** [comment]
Its fixed thank you
