### ISSUE TITLE
Faded colours on 4K content

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#130]
When playing back true 4K content, the colours are faded.  It's like there is an opaque 30% white foreground on top of the video.

![20210301_115928](https://user-images.githubusercontent.com/56231066/109495040-a0634a00-7a86-11eb-9c1e-a0852976eef8.jpg)

![20210301_115934](https://user-images.githubusercontent.com/56231066/109495047-a22d0d80-7a86-11eb-8b26-9d37b1ae2e47.jpg)

**Comment by kingslay** [comment]
sorry.. I am aware of this problem. The color of HDR video will be problematic. I haven't found the reason yet.

**Comment by kingslay** [comment]
#115

**Comment by UnknownCoder807** [comment]
thanks, I understand.  Hopefully you can work your magic and make it work in the future.

**Comment by matteogobbi** [comment]
I have the same problem with a black faded layer on top
