### ISSUE TITLE
audio delay

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#131]
Is it possible to change the timing on the Audio track?  for example if the audio is a few ms before the video, add a delay to make it match the video and vice versa?

There seems to be a slight synchronisation issue on the video and audio when watching with dolby audio with some movies.

**Comment by kingslay** [comment]
This may be because the video decoding is too slow.  the video is 4K？

**Comment by kingslay** [comment]
you can try the vlc.  vlc also have this problem？

**Comment by UnknownCoder807** [comment]
My app has both VLC and KSPlayer and the users only report it happening with KSPlayer.  VLC plays it in sync.

On Apple TV.

**Comment by kingslay** [comment]
That may be caused by slow decoding. is using the latest code, I solved the problem of slow 4k video decoding two weeks ago

**Comment by UnknownCoder807** [comment]
It's on all media apparently.  I'm not seeing it myself, so I put it down to user setup issues.  Thanks.

**Comment by UnknownCoder807** [comment]
I've reopened this issue as I am seeing it myself on videos.  These aren't 4K video's.

The audio is ever so slightly ahead of the video.

**Comment by UnknownCoder807** [comment]
I can send you a stream URL via email where you can check

**Comment by kingslay** [comment]
Does vlc play this url won't have this problem ？

**Comment by UnknownCoder807** [comment]
VKC app plays the video fine.  KSPlayer on Apple TV has audio sync issues.

**Comment by kingslay** [comment]
ok. please send me the stream URL

**Comment by UnknownCoder807** [comment]
email sent

**Comment by UnknownCoder807** [comment]
@kingslay have you tried the sample stream and see the issue?

**Comment by kingslay** [comment]
I had download the video, and not this issue. I will try the online video

**Comment by UnknownCoder807** [comment]
You need to stream the URL as it's a live tv broadcast.  Using a real apple tv device.  The audio delay is very small.

**Comment by kingslay** [comment]
OK
