### ISSUE TITLE
Cannot compile the library with SPM

### ISSUE THREAD

**Issue by byMohamedali** [kingslay/KSPlayer#135]
![image](https://user-images.githubusercontent.com/6490189/109934458-00a3f700-7ce6-11eb-9a9e-5778e688dcad.png)

When I am trying to compile the project with SPM

**Comment by kingslay** [comment]
you can run again. This error will only be reported the first time

**Comment by byMohamedali** [comment]
I run again, it's working fine, thank you but I have another issue with catalysist, that is always occurring 
![image](https://user-images.githubusercontent.com/6490189/109937512-6d1ff580-7ce8-11eb-88d5-16caac43c278.png)

Any idea ?

**Comment by byMohamedali** [comment]
![image](https://user-images.githubusercontent.com/6490189/109937732-a48ea200-7ce8-11eb-8170-edc70a7a619d.png)


I precise as well that I import the library for macOS and iOS

**Comment by byMohamedali** [comment]
Here my config for the architecture 

![image](https://user-images.githubusercontent.com/6490189/109943139-4ebcf880-7cee-11eb-8ac6-085c4360f03b.png)


I tried this config as well 
![image](https://user-images.githubusercontent.com/6490189/109943240-6a280380-7cee-11eb-8edb-28784f87dece.png)

Environment Xcode 12.4 on macOS BigSur 11.2

**Comment by byMohamedali** [comment]
![image](https://user-images.githubusercontent.com/6490189/109948752-0e607900-7cf4-11eb-9453-b9c840134515.png)


Thanks it's fixed ! But Now I have an issue with code signing, I'm not sure how to fix that because I don't have access to the project with SPM
