### ISSUE TITLE
Crash when playing

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#136]
When I try and play a video I am getting the following crash since the latest commits

<img width="1408" alt="Screenshot 2021-03-04 at 08 58 52" src="https://user-images.githubusercontent.com/56231066/109938504-038fef00-7cc8-11eb-83d3-63b33e9612ba.png">

**Comment by kingslay** [comment]
```
  let loadedTime = capacitys.map { TimeInterval($0.packetCount + $0.frameCount) / TimeInterval($0.fps) }.min() ?? 0
 let progress = loadedTime * 100.0 / preferredForwardBufferDuration
```
can you  see the value of fps?

**Comment by UnknownCoder807** [comment]
Sorry I don't know what you are asking me.

**Comment by kingslay** [comment]
Can you reproduce this crash?

**Comment by UnknownCoder807** [comment]
Yes, when using "My Mac designed for iPad" compile option.  I doesn't happen when running on Apple TV or iPad itself.

**Comment by kingslay** [comment]
is？
![image](https://user-images.githubusercontent.com/3964055/109950106-20074800-7d17-11eb-8c22-31759226404e.png)

**Comment by UnknownCoder807** [comment]
No I don't.  I'm not compiling for mac catalyst.  On Apple Silicon you can compile for "My Mac" using the iPad source code.  This has been working fine until the recent commits.

I did a print of loadingState.progress and it returns nan

I'm concerned this crash might stop people from using the app on Apple Silicon macs (when using iPad compatibility and not mac catalyst)

**Comment by kingslay** [comment]
I do not  had a  Apple Silicon macs .
 you can did a print of fps  on 
` fps = assetTrack.nominalFrameRate`

**Comment by UnknownCoder807** [comment]
I get 24.0

**Comment by kingslay** [comment]
`        let progress = loadedTime * 100.0 / preferredForwardBufferDuration
`
you can did a print of loadedTime  and  preferredForwardBufferDuration

**Comment by UnknownCoder807** [comment]
Both are 0.0

**Comment by kingslay** [comment]
`    public var preferredForwardBufferDuration = KSOptions.preferredForwardBufferDuration
`

do you change the KSOptions.preferredForwardBufferDuration to 0.0

**Comment by UnknownCoder807** [comment]
aha, yes I do change this option.  I removed it and it now works.

Thanks for your help in narrowing this issue down for me.
