### ISSUE TITLE
DVB Subtitles

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#139]
I see that DVB subtitles are now supported which is great news.

On my test stream, when enabling subtitles, the first line of subtitles is shown, and remains on screen.  There are no further subtitles shown.  It's like it's frozen on the first line.

**Comment by UnknownCoder807** [comment]
Still not working for me.  No subtitles are shown at all now.  Maybe someone else can confirm this.

**Comment by kingslay** [comment]
can you provide the url?

**Comment by UnknownCoder807** [comment]
email sent with link.

**Comment by UnknownCoder807** [comment]
Been nearly a month since I reported this issue.  Is there any progress on fixing it ?  thanks
