### ISSUE TITLE
Orientation Issue

### ISSUE THREAD

**Issue by prikshitgupta** [kingslay/KSPlayer#14]
How to make it work in full screen on iphone it just changes the orientation of whole app. 
i dont want to change orientation of app i want to run it in full screen.

**Comment by kingslay** [comment]
I can't understand what you mean. Can you provide a screenshot?

**Comment by prikshitgupta** [comment]
Ok i will share video

**Comment by prikshitgupta** [comment]
https://youtu.be/cHHh2mbNMy8

Here is the video of orientation issue when i pressed full screen button it changed app orientation to landscape default behaviour should be it should goto full screen then user can rotate phone to goto ladscape.

**Comment by kingslay** [comment]
You can rewrite the button click event.
```
class CustomVideoPlayerView: IOSVideoPlayerView {
    override func updateUI(isLandscape: Bool) {
        super.updateUI(isLandscape: isLandscape)
        toolBar.playbackRateButton.isHidden = true
    }

    override func onButtonPressed(type: PlayerButtonType, button: UIButton) {
        if type == .landscape {
            // xx
        } else {
            super.onButtonPressed(type: type, button: button)
        }
    }
}
```

**Comment by prikshitgupta** [comment]
But how to make it go full screen?

**Comment by prikshitgupta** [comment]
> You can rewrite the button click event.
> 
> ```
> class CustomVideoPlayerView: IOSVideoPlayerView {
>     override func updateUI(isLandscape: Bool) {
>         super.updateUI(isLandscape: isLandscape)
>         toolBar.playbackRateButton.isHidden = true
>     }
> 
>     override func onButtonPressed(type: PlayerButtonType, button: UIButton) {
>         if type == .landscape {
>             // xx
>         } else {
>             super.onButtonPressed(type: type, button: button)
>         }
>     }
> }
> ```

But how to make it go full screen?

**Comment by kingslay** [comment]
You can adjust the layout of the view directly.

**Comment by prikshitgupta** [comment]
> You can adjust the layout of the view directly.

ok thanks

**Comment by ShahidIqbal452** [comment]
@prikshitgupta I also want the same functionality which you require. Can you please tell me how did you manage to go full screen please?
