### ISSUE TITLE
Crash on Apple TV

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#140]
I have the following crash happening on Apple TV real device.

I hope this is enough info.

<img width="810" alt="Screenshot 2021-03-10 at 18 22 53" src="https://user-images.githubusercontent.com/56231066/110678304-0dd15200-81ce-11eb-8096-b16adf468679.png">

<img width="1409" alt="Screenshot 2021-03-10 at 18 22 26" src="https://user-images.githubusercontent.com/56231066/110678322-132e9c80-81ce-11eb-85d6-bcb937c95085.png">

**Comment by kingslay** [comment]
Because I don't have real  Apple TV device. So please change this code
```
static func colorPixelFormat(bitDepth: Int32) -> MTLPixelFormat {
        if bitDepth == 10 {
            #if os(macOS) || targetEnvironment(macCatalyst)
            return .bgr10a2Unorm
            #else
            #if targetEnvironment(simulator)
            return .bgra8Unorm
            #else
            return .bgr10_xr_srgb
            #endif
            #endif
        } else {
            return .bgra8Unorm
        }
    }
```
to
```
  static func colorPixelFormat(bitDepth: Int32) -> MTLPixelFormat {
        return .bgr10_xr_srgb
 }
```
on Apple TV real device.

**Comment by UnknownCoder807** [comment]
ok thanks, I've changed it, but it will take a few days before I know if it works as it's my users who report it.

**Comment by kingslay** [comment]
Do you have this problem locally?

**Comment by Paladinfeng** [comment]
Apple TV 4K is fine
