### ISSUE TITLE
Another crash on Apple TV

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#141]
I am receiving these crash reports for the Apple TV.

Hopefully its enough information to go on

<img width="1014" alt="Screenshot 2021-03-13 at 11 04 23" src="https://user-images.githubusercontent.com/56231066/111028064-1d2de680-83ec-11eb-82f0-23164c5a4eed.png">

<img width="1400" alt="Screenshot 2021-03-13 at 11 03 50" src="https://user-images.githubusercontent.com/56231066/111028067-215a0400-83ec-11eb-9258-0c84bebdf144.png">

**Comment by kingslay** [comment]
This one does not have enough information to go on

**Comment by UnknownCoder807** [comment]
ok, thanks
