### ISSUE TITLE
Washed out colours on non-4k video

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#145]
I know there is an issue with 4K HDR vidoes that have a washed out look, but there is the same issue now on non-4K material.

This is what standard HD looks like

![2021032611382855](https://user-images.githubusercontent.com/56231066/112666764-6baf9c00-8e54-11eb-8e32-ec51c395562c.png)

and on vlc it looks like this

![2021032611390350](https://user-images.githubusercontent.com/56231066/112666805-7407d700-8e54-11eb-96df-de468869f6e8.png)

This is on a real apple tv device.

**Comment by kingslay** [comment]
you  can update the latest code

**Comment by UnknownCoder807** [comment]
I am using the latest code.   last commit was 2 days ago.

**Comment by kingslay** [comment]
Then I guess that video can’t be hardwareDecode. I is fix the video that can be hardwareDecode.

**Comment by UnknownCoder807** [comment]
It's all vidoes and affects at least 15 people.  even a new test project that just plays a video has the same issue.
