### ISSUE TITLE
Player Crash on Apple TV With Dolby

### ISSUE THREAD

**Issue by Paladinfeng** [kingslay/KSPlayer#146]
### There is Crash Stack, Playing Video With Dolby Vision & Dolby Atoms will Crash

![image](https://user-images.githubusercontent.com/15520106/113531159-96d77f80-95fa-11eb-9226-cd542ee5ce83.png)

**Comment by kingslay** [comment]
你是如何开启Dolby Atoms 的？

**Comment by Paladinfeng** [comment]
电视如果支持的话，AppleTV上会有相应的开关，自动开启

![image](https://user-images.githubusercontent.com/15520106/113656913-6ca3c180-96cf-11eb-92fb-f71a6542c71a.png)

**Comment by kingslay** [comment]
你可以看下 KSPlayerManager.audioPlayerMaximumChannels 这个值是多少

**Comment by Paladinfeng** [comment]
这个是收集上来的崩溃日志，我本地也没发开启 Dobly Atoms，我猜是7.1声道的
我是不是可以强制输出2.1声道啊？

**Comment by Paladinfeng** [comment]
如果手动设置成`KSPlayerManager.audioPlayerMaximumChannels = AVAudioChannelCount(10)`会崩溃

![image](https://user-images.githubusercontent.com/15520106/113712523-d09ea800-9718-11eb-9867-97f5efd92cce.png)
![image](https://user-images.githubusercontent.com/15520106/113712537-d6948900-9718-11eb-83df-38e9190bb98e.png)

**Comment by Alanko5** [comment]
AVAudioSession.sharedInstance().maximumOutputNumberOfChannels == 32
KSPlayerManager.audioPlayerSampleRate == 4000
descriptor.inputNumberOfChannels == 8
numberOfSamples == 512
swrContext == nil
av_get_default_channel_layout(Int32(KSPlayerManager.audioPlayerMaximumChannels)) == 0
av_get_default_channel_layout(Int32(descriptor.inputNumberOfChannels)) == 1599

```
    private func setup(descriptor: AudioDescriptor) -> Bool {
        let outChannel = av_get_default_channel_layout(Int32(KSPlayerManager.audioPlayerMaximumChannels))
        let inChannel = av_get_default_channel_layout(Int32(descriptor.inputNumberOfChannels))
        swrContext = swr_alloc_set_opts(nil, outChannel, AV_SAMPLE_FMT_FLTP, KSPlayerManager.audioPlayerSampleRate, inChannel, descriptor.inputFormat, descriptor.inputSampleRate, 0, nil)
        let result = swr_init(swrContext)
        if result < 0 {
            shutdown()
            return false
        } else {
            return true
        }
    }
```
result == -22

**Comment by Alanko5** [comment]
@Paladinfeng use this for HOT FIX:
```
    public static var audioPlayerMaximumChannels:AVAudioChannelCount {
        get {
            let count = AVAudioSession.sharedInstance().maximumOutputNumberOfChannels
            if count > 8 {
                return AVAudioChannelCount(8)
            }
            return AVAudioChannelCount(count)
        }
    }
```
But it only works like Dolby Audio.

And wait until @kingslay solves it.

**Comment by Paladinfeng** [comment]
@Alanko5 thank you, I had set audioPlayerMaximumChannels to AVAudioChannelCount(6), most of videos only support 2.1 channel

**Comment by Alanko5** [comment]
I have a lot of videos that contain eac3, ac3, TrueHD.
That is why we need passthrough/Dolby Atmos support.
