### ISSUE TITLE
Cannot compile for Apple TV

### ISSUE THREAD

**Issue by ivank00** [kingslay/KSPlayer#151]
I've integrated KSPlayer into my project using CocoaPods. I've tried to lauch it on real AppleTV 4K and I'm getting the following error. 
ld: in /.../Debug-appletvos/Libavcodec.framework/Libavcodec(aac_ac3_parser.o), building for tvOS, but linking in object file (/.../Debug-appletvos/Libavcodec.framework/Libavcodec(aac_ac3_parser.o)) built for tvOS Simulator, file '/.../Debug-appletvos/Libavcodec.framework/Libavcodec' for architecture arm64

Thanks in advance for any help!

**Comment by kingslay** [comment]
you must use CocoaPods 1.10.1

**Comment by ivank00** [comment]
Thank you very much for helping!
