### ISSUE TITLE
HDR/60fps image tearing

### ISSUE THREAD

**Issue by Alanko5** [kingslay/KSPlayer#152]
image tearing.
sample:
https://sheri.eu/testvideo/HDR10-Sony-Bravia-OLED-(www.demolandia.net).mp4

**Comment by kingslay** [comment]
I tried without this problem, can you provide a screenshot?

**Comment by Alanko5** [comment]
This video:
https://4kmedia.org/sony-bravia-uhd-hdr-4k-demo/

Now crashing on AppleTV 4k 2gen
Video is freez and audio playing.
in fiew seconds app crash...

[KSplayerCrash.txt](https://github.com/kingslay/KSPlayer/files/7813317/KSplayerCrash.txt)
