### ISSUE TITLE
iOS playbackRate not changed when set for hls or rtmp stream

### ISSUE THREAD

**Issue by ninoid** [kingslay/KSPlayer#153]
Hello. 
Thanks for this player which I found very convenient.
I have scenario where I need to play live rtmp or hls stream and sometimes need to set playback rate to "catch" playable time with current player time.
In other words when delay is more than eg. 5 seconds I am increasing playback rate to catch playable time and not allow delay to increase.
This is only player I found that have all properties and values expect when changing playback rate nothing happens. Playback rate remain same.
Can you please help me with this, any advice would be very appreciated.

**Comment by kingslay** [comment]
is only hls and  rtmp stream? Local video can be changed the playbackRate？
