### ISSUE TITLE
Can't Archive

### ISSUE THREAD

**Issue by 0xacdc** [kingslay/KSPlayer#154]
Can't Archive ! Compiling with Release and Debug works perfect, but when archiving I'm getting this:

`SourcePackages/checkouts/KSPlayer/Sources/FFmpeg/include/FFmpeg.h:7:9: 'libavutil/display.h' file not found`
<img width="1924" alt="Screenshot 2021-05-01 at 14 01 15" src="https://user-images.githubusercontent.com/38544113/116780473-99e45500-aa6c-11eb-9d34-3f4759d23910.png">

**Comment by UnknownCoder807** [comment]
I had this issue.  If you are using CocaPods to install KSPlayer, in the "Show Issue Navigator" on the left hand side, then select upgrade to recommended settings.  This fixed it for me.

![Screenshot 2021-05-01 at 12 10 59](https://user-images.githubusercontent.com/56231066/116780795-9eae0680-aa76-11eb-9ff0-51a92c58603a.png)

**Comment by 0xacdc** [comment]
Thanks Bro, but I'm using SPM

**Comment by kingslay** [comment]
> Thanks Bro, but I'm using SPM

iOS or tvOS？

**Comment by 0xacdc** [comment]
iOS, XCode 12.5

**Comment by kingslay** [comment]
> I had this issue. If you are using CocaPods to install KSPlayer, in the "Show Issue Navigator" on the left hand side, then select upgrade to recommended settings. This fixed it for me.
> 
> ![Screenshot 2021-05-01 at 12 10 59](https://user-images.githubusercontent.com/56231066/116780795-9eae0680-aa76-11eb-9ff0-51a92c58603a.png)

What is the recommended setting?

**Comment by UnknownCoder807** [comment]
![Screenshot 2021-05-04 at 11 20 02](https://user-images.githubusercontent.com/56231066/116990374-efb63880-acca-11eb-8b08-a4a6ab8c2f4e.png)

![Screenshot 2021-05-04 at 11 20 50](https://user-images.githubusercontent.com/56231066/116990395-f3e25600-acca-11eb-871d-d9eb3a491a29.png)

It maybe my Podfile that causes this update issue - but it's easily fixed.
