### ISSUE TITLE
Stereo Invalid On Apple TV

### ISSUE THREAD

**Issue by Paladinfeng** [kingslay/KSPlayer#156]
I test a stereo video in both my application and demo project

Connect Device: AirPods

### Simnlator
Stereo works normally

### Real Device
Stereo is mixed

I also test this video on iOS real device, Stereo works normally

**Comment by jartas** [comment]
Hi, it is possible to look at this problem and try to solve it. Thanks a lot

**Comment by kingslay** [comment]
If using an iPhone, the Connect Device are AirPods. Stereo is mixed? If there is, please tell me the video in the demo

**Comment by jartas** [comment]
Hi kingslay, I tested now sample stereo video on Apple TV and and it's okay. I think you can close this request. Thx for your time

https:/iscc.site/stereo.mp4
