### ISSUE TITLE
Audio Delay Cause Player State Wrong

### ISSUE THREAD

**Issue by Paladinfeng** [kingslay/KSPlayer#157]
KSPlayerState.playedToTheEnd Not Call When Video Play Finished

Code In Demo：
``` swift
let options = KSOptions()
options.audioDelay = -5
objects.append(KSPlayerResource(url: URL(fileURLWithPath: path), options: options, name: "本地视频", cover: nil, subtitleURL: nil))
```

To support AirPlay, I have to manually delay audio for 2s
```swift
let currentRoute = AVAudioSession.sharedInstance().currentRoute
        
for output in currentRoute.outputs {
    options.audioDelay = output.portType == .airPlay ? -2.0 : 0.0
}
```

**Comment by Paladinfeng** [comment]
Still has bug

`func player(layer: KSPlayerLayer, currentTime: TimeInterval, totalTime: TimeInterval)`

In this function, currentTime > totalTime if I delay audio

**Comment by Alanko5** [comment]
Vlc implementation for airplay latency delay

https://code.videolan.org/videolan/VLCKit/-/merge_requests/14/diffs?commit_id=e7525d9ad5e7ec85753ddd90b551ec0fd8ff2589
