### ISSUE TITLE
I can no longer go full screen

### ISSUE THREAD

**Issue by ShahidIqbal452** [kingslay/KSPlayer#159]
Hi,

There seems to be some issues in player controls. When I click the full screen button, its replaces itself with speed label and shows me the lock/unlock button. This is not full screen mode. I have just cropped the screenshot.
![Screenshot 2021-05-27 at 8 20 11 PM](https://user-images.githubusercontent.com/37539261/119852778-085fea00-bf29-11eb-94aa-57c9a5ee0139.png)

FYI: My app supports portrait mode only. I am using the default KSOptions.

**Comment by kingslay** [comment]
This is because the height of your video is greater than the width
