### ISSUE TITLE
Apple Tv controls or Button Options

### ISSUE THREAD

**Issue by prikshitgupta** [kingslay/KSPlayer#16]
Hi There is no default control options for apple tv.
Can you please guide how i can bring buttons in apple tv player.
Subtitle or Speed, there is no way to select those on apple tv.
(Like selecting quality as a example)

**Comment by snappycode1** [comment]
On the IOS demo, double tapping the screen brings up the controls. but there is no way to do this with the tvOS version.  All gestures are ignored.

Is this the issue you mean?

**Comment by prikshitgupta** [comment]
> On the IOS demo, double tapping the screen brings up the controls. but there is no way to do this with the tvOS version. All gestures are ignored.
> 
> Is this the issue you mean?

yes

**Comment by kingslay** [comment]
Update the code, please. i had add the gestures

**Comment by prikshitgupta** [comment]
did you update now?

> Update the code, please. i had add the gestures

**Comment by snappycode1** [comment]
Gestures working perfectly now for me, thanks for fixing.

**Comment by prikshitgupta** [comment]
> Gestures working perfectly now for me, thanks for fixing.

can you please guide me how to customize gestures?

**Comment by snappycode1** [comment]
I don't know how to customise gestures. All I have seen working is swiping left or right makes the video fast forward/rewind.  make sure that playerVideo.bottomMaskView is not hidden otherwise it wont work.

I don't see any other options than that.

Should there be more, like subtitles selection?

**Comment by prikshitgupta** [comment]
> I don't know how to customise gestures. All I have seen working is swiping left or right makes the video fast forward/rewind. make sure that playerVideo.bottomMaskView is not hidden otherwise it wont work.
> 
> I don't see any other options than that.
> 
> Should there be more, like subtitles selection?

Yes i want to add select quality feature subtitles and more but button dont work. Swiping for me is pausing and playing.

**Comment by snappycode1** [comment]
ah, I didn't know there was other options.  Hopefully Kingslay like be able to sort this rapidly like their other fixes.

**Comment by kingslay** [comment]
now the menu button can show and hide bottomMaskView. 

```
  override open func pressesBegan(_ presses: Set<UIPress>, with _: UIPressesEvent?) {
        guard let presse = presses.first else {
            return
        }
        switch presse.type {
        case .playPause:
            if playerLayer.state.isPlaying {
                pause()
            } else {
                play()
            }
        case .select:
            if !srtControl.view.isHidden {
                srtControl.view.isHidden = true
            }
        case .menu:
            isMaskShow.toggle()
        default: break
        }
    }
```

**Comment by prikshitgupta** [comment]
Great
