### ISSUE TITLE
Package XCFrameworks are build for arm64 only.

### ISSUE THREAD

**Issue by ShahidIqbal452** [kingslay/KSPlayer#160]
Hi,

I am using an intel based Macbook pro. When I add your package as dependency in my project, it works fine on simulator. But when I try to archive a release build, it gives me an error "No such module 'Libavcodec' ".
I checked the source folder of this framework and found out that it only supports arm64 to archive builds. I am attaching a picture to support what I am saying.

![Screenshot 2021-05-29 at 2 25 45 PM](https://user-images.githubusercontent.com/37539261/120065280-ddd97280-c089-11eb-90be-4eefecbf55f9.png)

Can we get x86 support to archive builds on intel based Mac OS please?

**Comment by kingslay** [comment]
you can use ios-x86_64-maccatalyst or macos-arm64_x86_64
