### ISSUE TITLE
TVOS+SwiftUI+Swift Packages Develop branch can not found IOSVideoPlayerView()

### ISSUE THREAD

**Issue by leeeboo** [kingslay/KSPlayer#161]
TVOS+SwiftUI+Swift Packages Develop branch can not found IOSVideoPlayerView()

**Comment by leeeboo** [comment]
<img width="1358" alt="CleanShot 2021-06-09 at 16 43 37@2x" src="https://user-images.githubusercontent.com/877939/121322813-e0698100-c941-11eb-8915-ba78f6c6acde.png">

**Comment by leeeboo** [comment]
TVOS 14.5

**Comment by leeeboo** [comment]
<img width="738" alt="CleanShot 2021-06-09 at 16 44 36@2x" src="https://user-images.githubusercontent.com/877939/121322953-fd05b900-c941-11eb-9e08-ec4c9e891179.png">
Already update to the lastest version.

**Comment by kingslay** [comment]
you need use VideoPlayerView in tvOS. the IOSVideoPlayerView is only iOS

**Comment by leeeboo** [comment]
> you need use VideoPlayerView in tvOS. the IOSVideoPlayerView is only iOS

THX
