### ISSUE TITLE
How to remove this object marked inside the picture? And how to disable seek control and hide the time bar?

### ISSUE THREAD

**Issue by leeeboo** [kingslay/KSPlayer#162]
![CleanShot 2021-06-10 at 08 04 07@2x](https://user-images.githubusercontent.com/877939/121444670-85c43980-c9c2-11eb-8280-0133d8eaf023.png)
Thank you!

**Comment by kingslay** [comment]
class CustomVideoPlayerView: VideoPlayerView {
    override func customizeUIComponents() {
        super.customizeUIComponents()
        toolBar.isHidden = true
        toolBar.timeSlider.isHidden = true
    }
}
