### ISSUE TITLE
try to run tvOS demo on device, but ld failed

### ISSUE THREAD

**Issue by iAladdin** [kingslay/KSPlayer#164]
```
ld: in /Users/aladdin/Library/Developer/Xcode/DerivedData/Demo-gmwpbeqzfteqtsbnrvdtjyirdtey/Build/Products/Debug-appletvos/Libssl.framework/Libssl(bio_ssl.o), building for tvOS, but linking in object file (/Users/aladdin/Library/Developer/Xcode/DerivedData/Demo-gmwpbeqzfteqtsbnrvdtjyirdtey/Build/Products/Debug-appletvos/Libssl.framework/Libssl(bio_ssl.o)) built for tvOS Simulator, file '/Users/aladdin/Library/Developer/Xcode/DerivedData/Demo-gmwpbeqzfteqtsbnrvdtjyirdtey/Build/Products/Debug-appletvos/Libssl.framework/Libssl' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by iAladdin** [comment]
and I try run demo on iOS device, almost same error 

`ld: in /Users/aladdin/Library/Developer/Xcode/DerivedData/Demo-gmwpbeqzfteqtsbnrvdtjyirdtey/Build/Products/Debug-iphoneos/Libavformat.framework/Libavformat(aacdec.o), building for iOS, but linking in object file (/Users/aladdin/Library/Developer/Xcode/DerivedData/Demo-gmwpbeqzfteqtsbnrvdtjyirdtey/Build/Products/Debug-iphoneos/Libavformat.framework/Libavformat(aacdec.o)) built for iOS Simulator, file '/Users/aladdin/Library/Developer/Xcode/DerivedData/Demo-gmwpbeqzfteqtsbnrvdtjyirdtey/Build/Products/Debug-iphoneos/Libavformat.framework/Libavformat' for architecture arm64`

**Comment by kingslay** [comment]
use pod 1.10.2
