### ISSUE TITLE
KSMEPlayer - 画面颜色问题

### ISSUE THREAD

**Issue by LinXunFeng** [kingslay/KSPlayer#165]
作者你好，使用 `KSMEPlayer` 这种播放内核会出现如下图所示的左边紫色右边绿色的情况，这种情况可以怎么解决呢？
![image](https://user-images.githubusercontent.com/19367531/128003731-e5788faf-d649-4010-9e35-2f3338966c29.png)

正常情况下画面应该是这样子
![image](https://user-images.githubusercontent.com/19367531/128003840-54fac35b-0c9b-4237-aa1b-bca1bf672ef9.png)

**Comment by kingslay** [comment]
能够提供下视频的url吗

**Comment by LinXunFeng** [comment]
> 能够提供下视频的url吗

```
https://video.591.com.tw/debug/target/house/hls/2021-07-14/130/stream_1.m3u8
```
