### ISSUE TITLE
Mac播放mp4正常，播放mkv格式没有视频画面。

### ISSUE THREAD

**Issue by loveq369** [kingslay/KSPlayer#168]

**Comment by kingslay** [comment]
能够提供下播放链接吗？我试下

**Comment by loveq369** [comment]
[tos.mkv.zip](https://github.com/kingslay/KSPlayer/files/7150074/tos.mkv.zip)
有声音，没有画面。x86 mac。
mkv都没有画面，不只是这个mkv视频。

**Comment by kingslay** [comment]
我用demo试了。是有画面的。你可以试下demo
