### ISSUE TITLE
Actions Don't Work After Adding KSPlayer to tvOS Swift Projects

### ISSUE THREAD

**Issue by davemen** [kingslay/KSPlayer#169]
Steps to recreate issue
1. Create a new tvOS project in Swift.
2. Add PodFile and install Pods.
3. Open ViewController from StoryBoard. Add a button.
4. Go to ViewController code and try to Control-drag from the button to the code. There are no action outlets available
<img width="593" alt="Screen Shot 2021-10-11 at 2 20 54 PM" src="https://user-images.githubusercontent.com/5728266/136857028-76ed7ef8-930a-487f-bb68-3d43674b3d5b.png">
.
<img width="299" alt="Screen Shot 2021-10-11 at 2 21 15 PM" src="https://user-images.githubusercontent.com/5728266/136857051-0569edce-1584-45c9-9207-660ef12be8e4.png">

**Comment by davemen** [comment]
@kingslay - Are you closing it because you can't reproduce it or for another reason? It seems like a valid bug.

**Comment by kingslay** [comment]
> @kingslay - Are you closing it because you can't reproduce it or for another reason? It seems like a valid bug.

I had fixed it
