### ISSUE TITLE
Feature Request-Drop down menu in player

### ISSUE THREAD

**Issue by prikshitgupta** [kingslay/KSPlayer#17]
Hi I have a feature request if you can add traditional drop down menu we see in every player in tvOS. I am attaching picture. Thats the easyway to handle meta data of video. plus any extra feature you wanna add like selecting audio, subtitle or video tracks.
![IMG_2443](https://user-images.githubusercontent.com/7194247/82740318-5a19d700-9d0d-11ea-8243-4a8978bca069.jpeg)
![IMG_2444](https://user-images.githubusercontent.com/7194247/82740319-5dad5e00-9d0d-11ea-86a8-f43fb5fb05b7.jpeg)
![IMG_2445](https://user-images.githubusercontent.com/7194247/82740320-5e45f480-9d0d-11ea-8b1c-14b3301e2ee0.jpeg)

**Comment by kingslay** [comment]
This is a great feature and may not be supported anytime soon. You can get the video, audio, and subtitle information by simply using tracks(mediaType: AVFoundation.AVMediaType)

**Comment by prikshitgupta** [comment]
ok but i am not abe to select button in tvos.

**Comment by kingslay** [comment]
you can add button directly through override func customizeUIComponents

**Comment by prikshitgupta** [comment]
ok i will try thanks
