### ISSUE TITLE
some videos don't display correct aspect ratio

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#174]
I have some video's (SD TV Channels) that do not display properly.  Am I doing something wrong or is there an issue?  In vlckit they display properly.  this is on apple tv

By default, they are compressed inwards, (image 1)

<img width="1218" alt="image1" src="https://user-images.githubusercontent.com/56231066/139482052-20ad1eb5-0949-4255-8fd3-1ae0f8cad2ba.png">

if I use the following code 

```
            let rate = sar.width * par.height / (sar.height * par.height)
            if rate < 5 / 4 {
                return CGSize(width: 5, height: 4)
            } else if rate < 4 / 3 {
                return CGSize(width: 4, height: 3)
            } else if rate < 16 / 9 {
                return CGSize(width: 16, height: 9)
            }
            return nil

```
then they look like image 2

<img width="1218" alt="image 2" src="https://user-images.githubusercontent.com/56231066/139482078-1e58b899-6618-4694-ac5a-9584191b5745.png">

**Comment by kingslay** [comment]
Can you provide a snippet of this video? I need to debug locally
