### ISSUE TITLE
Question : Filters

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#175]
On 7th August I noticed you added the deinterlace filters for video.  Do you have any example code for using this please?

**Comment by kingslay** [comment]
let options = KSOptions()
        options.videoFilters = "hflip,vflip"
        options.hardwareDecodeH264 = false
        objects.append(KSPlayerResource(url: URL(fileURLWithPath: path), options: options, name: "本地视频"))

**Comment by UnknownCoder807** [comment]
Thanks, are there any deinterlacing filters available?

**Comment by kingslay** [comment]
// filters
        "--disable-filters", "--enable-filter=amix", "--enable-filter=aforma", "--enable-filter=scale",
        "--enable-filter=format", "--enable-filter=aformat", "--enable-filter=fps", "--enable-filter=trim",
        "--enable-filter=atrim", "--enable-filter=vflip", "--enable-filter=hflip", "--enable-filter=transpose",
        "--enable-filter=rotate", "--enable-filter=yadif", "--enable-filter=pan", "--enable-filter=volume",
        "--enable-filter=aresample", "--enable-filter=atempo", "--enable-filter=asetrate", "--enable-filter=setpts",
        "--enable-filter=overlay", "--enable-filter=paletteuse", "--enable-filter=areverse", "--enable-filter=anull",
        "--enable-filter=palettegen", "--enable-filter=null",

**Comment by UnknownCoder807** [comment]
thanks

**Comment by UnknownCoder807** [comment]
@kingslay if I use

`KSOptions.videoFilters = "yadif"
`
How can I go back to the default videoFilter?  Is one of the above filters enabled by default?

**Comment by UnknownCoder807** [comment]
What am I doing wrong please?  SwiftUI Project.

<img width="1626" alt="Screenshot 2022-05-05 at 13 24 18" src="https://user-images.githubusercontent.com/56231066/166922448-456f06f0-b691-47a8-8347-cf640548fb69.png">

**Comment by UnknownCoder807** [comment]
Are there any other filters that can be added to ksplayer?  VLC has the ones in the following screenshots.  I am particularly interested in the Linear filter.  thanks

<img width="530" alt="Screenshot 2023-05-02 at 21 01 59" src="https://user-images.githubusercontent.com/56231066/235773461-50d14775-6deb-4817-b974-ca75c4a9a912.png">

**Comment by kingslay** [comment]
我看ffmpeg里面好像是没有提供这个filter. https://ffmpeg.org/ffmpeg-filters.html
