### ISSUE TITLE
Video Stuttering on tvOS

### ISSUE THREAD

**Issue by snappycode1** [kingslay/KSPlayer#18]
I am trying to play a remote MKV file and find it stutters when playing, like every frame has a twitch.
I am using an Apple TV (tvOS)

I can provide an example url for you via email if you want as I can't post it publicly.

**Comment by kingslay** [comment]
There's my email at the bottom of that readme.

**Comment by snappycode1** [comment]
Thanks, I have sent you an email with the link.

**Comment by snappycode1** [comment]
Did you get my email with the link?  is all ok?

**Comment by kingslay** [comment]
I got the link. There is indeed a problem. I'm watching.

**Comment by kingslay** [comment]
i fixed. please update the code tray again

**Comment by snappycode1** [comment]
Thanks, now working.
