### ISSUE TITLE
How to play H264 raw stream?

### ISSUE THREAD

**Issue by donly** [kingslay/KSPlayer#180]
I try play with the demo project, it can't play with these errors:

```
KSPlayer: KSPlayerLayer.swift:136 state | playerStateDidChange - error
KSPlayer: KSPlayerLayer.swift:313 finish(player:error:) | Error Domain=KSPlayerErrorDomain Code=2 "avformat can't open input" UserInfo={NSLocalizedDescription=avformat can't open input, NSUnderlyingError=0x6000013fc810 {Error Domain=FFmpegDomain Code=-1094995529 "Invalid data found when processing input" UserInfo={NSLocalizedDescription=Invalid data found when processing input}}}
```

How to play H264 raw stream please.

**Comment by kingslay** [comment]
Which link you are playing. It should be that the link has expired. Can't play it anymore. You can find a link that can be played and replace it

**Comment by donly** [comment]
The link can be play with ffplay.
Could you make sure that KSPlayer support H264 raw stream playing.

**Comment by kingslay** [comment]
Yes. KSPlayer support H264 raw stream. Can you provide the url?

**Comment by donly** [comment]
Sorry, this url is for local network use, I add this code to the iOS demo https://github.com/kingslay/KSPlayer/blob/develop/Demo/demo-iOS/demo-iOS/AppDelegate.swift#L64:

```swift
if let url = URL(string: "tcp://192.168.1.112:6060") {
        objects.append(KSPlayerResource(url: url, options: KSOptions(), name: "H264 Raw Stream"))
}
```

Something wrong here?

btw, this url is works with `ffplay -f h264 tcp://192.168.1.112:6060`

**Comment by donly** [comment]
Sorry, this url is for local network use, I add this code to the iOS demo https://github.com/kingslay/KSPlayer/blob/develop/Demo/demo-iOS/demo-iOS/AppDelegate.swift#L64:

```swift
if let url = URL(string: "tcp://192.168.1.112:6060") {
        objects.append(KSPlayerResource(url: url, options: KSOptions(), name: "H264 Raw Stream"))
}
```

Something wrong here?

btw, this url is works with `ffplay -f h264 tcp://192.168.1.112:6060`

**Comment by kingslay** [comment]
How do you convert a local video to tcp.I need environment to reproduce this problem

**Comment by donly** [comment]
You can use a pi camera and the command below to do that:

```sh
raspivid -n -ih -t 0 -rot 0 -w 1280 -h 720 -fps 15 -b 1000000 -o - | ncat -lkv4 5001
```
