### ISSUE TITLE
Green Artifacts on Highlights

### ISSUE THREAD

**Issue by StarPlayrX** [kingslay/KSPlayer#181]
Running a 4K Video gives off green artifacts in the high light area. Seems where things drop to zero. Looks like some type of masking issue. This is on Simulator. Will test again on tvOS / AppleTV.

![Simulator Screen Shot - AppleTV4K - 2021-11-24 at 15 39 03](https://user-images.githubusercontent.com/52664524/143310248-22f8c3b0-5c96-43b4-972b-b23cbce3337c.png)

**Comment by Alanko5** [comment]
Isn't it HDR but DV content?

**Comment by kingslay** [comment]
@StarPlayrX Can you provide a link to that video

**Comment by StarPlayrX** [comment]
When I see if again, I will. I switched to another IPTV provider. What is interesting is these artifacts only seem to show up on my 5K computer display. They do not show on my 4K AppleTV.
