### ISSUE TITLE
RTSP Stream

### ISSUE THREAD

**Issue by AlexAK77** [kingslay/KSPlayer#183]
Hello. 
I have problem with RTSP stream in MacOS. 

My sample. I turned off authorization.

```
let url = "rtsp://192.168.101.17/stream1"
if let url = URL(string: url.trimmingCharacters(in: .whitespacesAndNewlines)) {
           let options = KSOptions()
           options.formatContextOptions["timeout"] = 0
           options.audioDisable = true
            options.hardwareDecodeH264 = true
}
```

When i change url to mp4 link everything works.
What needs to be done for rtsp?

Thanks in advice !

**Comment by kingslay** [comment]
you can try only set 
`           options.formatContextOptions["timeout"] = 0
`
Don't set audioDisable = true
