### ISSUE TITLE
Universal UI

### ISSUE THREAD

**Issue by StarPlayrX** [kingslay/KSPlayer#187]
Would it be possible in the future to support the AVPlayer UI for AVPlayerView and AVPlayerController?

I'd like to have things uniform on my iOS clients and my visually impaired customers are already used to Apple's UI and accessibility that comes built in with it as opposed to a custom UI that may not be accessible.

**Comment by kingslay** [comment]
Yes, I plan to use KSPlayerLayer and Swift UI to build a UI interface like AVPlayerController

**Comment by kingslay** [comment]
I add KSVideoPlayer.swift use SwiftUI in the latest  code . You can help contribute code and improve it together
