### ISSUE TITLE
4K with EAC3, TRUEHD chopping

### ISSUE THREAD

**Issue by jartas** [kingslay/KSPlayer#188]
When playing 4k video with the EAC3 or TrueHD codec, there is a lot of video chopping.

There is video record from mobile for idea

https://youtu.be/qG9lLUxethw

Here is a link for direct playback from the link 4K, HEVC/EAC3

https://iscc.site/sample.mkv

**Comment by kingslay** [comment]
I can't download this video https://webshare.cz/#/file/u5rNznCQCX

 Can you put it on youtube. or email me

**Comment by jartas** [comment]
https://youtu.be/qG9lLUxethw

**Comment by Miroslavgapa** [comment]
@kingslay please try to resolve this problem
