### ISSUE TITLE
Overriding apple tv gestures

### ISSUE THREAD

**Issue by prikshitgupta** [kingslay/KSPlayer#19]
Hi can you please tell us how do we override apple tv gestures?

**Comment by kingslay** [comment]
you can override  func panGestureBegan, panGestureChanged, panGestureEnded
   /// Add Customize functions here
    open func customizeUIComponents() {
        tapGesture.addTarget(self, action: #selector(onTapGestureTapped(_:)))
        tapGesture.numberOfTapsRequired = 1
        addGestureRecognizer(tapGesture)
        panGesture.addTarget(self, action: #selector(panDirection(_:)))
        addGestureRecognizer(panGesture)
        doubleTapGesture.addTarget(self, action: #selector(doubleGestureAction))
        doubleTapGesture.numberOfTapsRequired = 2
        tapGesture.require(toFail: doubleTapGesture)
        addGestureRecognizer(doubleTapGesture)
    }
```

**Comment by prikshitgupta** [comment]
thank you, can you please look into my feature request?

**Comment by snappycode1** [comment]
Could you please give an example of how this works?  I'm having problems getting swipe up and down to execute my own code.

**Comment by kingslay** [comment]
i only has the tvos simulator. so i can't try the  Gesture

**Comment by snappycode1** [comment]
There is an option to display an on-screen apple remote, complete with gestures.

Window->Show Apple Remote

in the simulator window.

**Comment by prikshitgupta** [comment]
You have to press opt key to use gestures

**Comment by kingslay** [comment]
thank. i will try it.

**Comment by kingslay** [comment]
you can override func doubleTapGestureAction, tapGestureAction, panGestureAction
```
 @objc open func doubleTapGestureAction() {
        toolBar.playButton.sendActions(for: .primaryActionTriggered)
        isMaskShow = true
    }

    @objc open func tapGestureAction(_: UITapGestureRecognizer) {
        if srtControl.view.isHidden {
            isMaskShow.toggle()
        } else {
            srtControl.view.isHidden = true
        }
    }

    @objc private func panGestureAction(_ pan: UIPanGestureRecognizer) {
        // 播放结束时，忽略手势,锁屏状态忽略手势
        guard !replayButton.isSelected, !isLock else { return }
        // 根据上次和本次移动的位置，算出一个速率的point
        let velocityPoint = pan.velocity(in: self)
        switch pan.state {
        case .began:
            // 使用绝对值来判断移动的方向
            if abs(velocityPoint.x) > abs(velocityPoint.y) {
                scrollDirection = .horizontal
            } else {
                scrollDirection = .vertical
            }
            panGestureBegan(location: pan.location(in: self), direction: scrollDirection)
        case .changed:
            panGestureChanged(velocity: velocityPoint, direction: scrollDirection)
        case .ended:
            panGestureEnded()
        default:
            break
        }
    }

```
