### ISSUE TITLE
Cannot switch audio

### ISSUE THREAD

**Issue by jartas** [kingslay/KSPlayer#192]
The audio track cannot be switched during playback, the application will freeze after the change

**Comment by Miroslavgapa** [comment]
This issue is critical from side of user...other ways is player useless. Please if you are able if you could check this issue also...thanks in advance.

**Comment by jartas** [comment]
there seems to be some problem with the buffer, here is log from Xcode
[log.txt](https://github.com/kingslay/KSPlayer/files/7865171/log.txt)

**Comment by kingslay** [comment]
#194

**Comment by kingslay** [comment]
Duplicate of #194
