### ISSUE TITLE
TrueHD still not working

### ISSUE THREAD

**Issue by jartas** [kingslay/KSPlayer#195]
Hi Kingslay i tested last fix, and switch audio is OK thx for it, but last what I need is TrueHd support, still not working, video and audio is very chopping. I prepare other sample for test. Sample has 3 audio stop one is TrueHD

https://iscc.site/Endgame_TrueHD.mkv

**Comment by kingslay** [comment]
I have no problem downloading the video here and playing it locally. You can try to download the video locally and play it to see if there is any problem. If there is still a problem. Please record a screen for me. I'll take a look

**Comment by jartas** [comment]
Hi i tested local and same problem, when I build for simulator it is ok, but then build for ATV 4K, that video is freeze and audio is chopping. Here is record from mobile phone for idea and log from Xcode

https://www.youtube.com/watch?v=vhg882Z9Wtk
[log1.txt](https://github.com/kingslay/KSPlayer/files/7874995/log1.txt)
