### ISSUE TITLE
TrueHD - crackling sound

### ISSUE THREAD

**Issue by jartas** [kingslay/KSPlayer#196]
Thank you for your support. I tested the last fix and it's much better, but there's still a crackling sound and sometimes the video jerks. I enclose a sample on which it can be seen. Thx

https://iscc.site/Term.mkv

**Comment by kingslay** [comment]
you can try change the value to 64

`  
open func audioFrameMaxCount(fps _: Float) -> Int {
        32
    }
`

**Comment by jartas** [comment]
looks good, I will tested yet. Thx very much
