### ISSUE TITLE
Recording

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#198]
Any chance KSPlayer could support recording like VLC does?

**Comment by cdg90** [comment]
any updates regarding this feature?n @kingslay

**Comment by cdg90** [comment]
Hi @kingslay 

I found an article about live recording using FFMPEG.

https://mediarealm.com.au/articles/internet-stream-recorder-ffmpeg/

would be good to implement the recording feature in the ksplayer

**Comment by kingslay** [comment]
是的,通过命令行是可以的。但是我还没找到通过代码要如何实现

**Comment by ParthAlliancetek** [comment]
have you added Recording feature yet ?

**Comment by kingslay** [comment]
已经支持了
