### ISSUE TITLE
tvos: Seeking takes a really long in swiftui sample 

### ISSUE THREAD

**Issue by steffenmllr** [kingslay/KSPlayer#199]
First of all thanks for making KSPlayer - currently the only open source player for tvos that supports playing more formats and has a decent texture mapping for 4k!

When trying to seeking on a apple tv 4k (real device) the swiftui demo the player just hangs while the same file in the demo-tvOS works great and can be skipped within a couple of ms. Since the rest of my app is swift-ui I was wondering if there is a way to fix this.

test file is around 30GB mkv, DDP5.1 Atmos HDR H265, via https

**Comment by kingslay** [comment]
You can update the latest develop branch code, if it still doesn't work, download part of the video to the local. See if there is a problem with playing that video locally. If you still have problems, please send me this local video. I will debug

**Comment by steffenmllr** [comment]
Since I have a pretty stable fiber connection, I'm ruling out connectivity issues here. I was using the latest commit on develop (9e72a69). the video (codec) might also does not really matter only the size and the swiftui part. I had similar problems with vlckit on swiftui (different 4k video). Are there any reported problems with swiftui and metal ?

**Comment by kingslay** [comment]
I have non-swiftui in my demo. You can try it with a non-swiftui demo. See if there will be this problem, if there is still, it is not a problem of swiftui. Then you need to give me a local video clip and let me debug

**Comment by steffenmllr** [comment]
I did try it with your demo code - not my app. With `demo-SPM` seeking with big files takes a really long time and mostly hangs. `demo-tvOS` works fine for the same file. On a real device (appletv 4k). Sorry if that wan't clear.

**Comment by kingslay** [comment]
OK. I understand. I will debug
