### ISSUE TITLE
Project it's not building in Xcode 11.4

### ISSUE THREAD

**Issue by byMohamedali** [kingslay/KSPlayer#2]
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/6490189/76881695-f7323c80-6892-11ea-9eca-f0b149ea2680.png">

The project is not building on Xcode 11.4

**Comment by kingslay** [comment]
> <img alt="image" width="1435" src="https://user-images.githubusercontent.com/6490189/76881695-f7323c80-6892-11ea-9eca-f0b149ea2680.png">
> 
> The project is not building on Xcode 11.4

I had fix this problem. please you update the latest code

**Comment by byMohamedali** [comment]
Thank you
