### ISSUE TITLE
Fail force unwrapping of the AVAudioFormat

### ISSUE THREAD

**Issue by MatejkaMartin** [kingslay/KSPlayer#202]
Hello Sensei, 

please can you help me? I am getting error here. I dont know what is wrong
<img width="1396" alt="CleanShot 2022-01-31 at 18 20 27@2x" src="https://user-images.githubusercontent.com/17528892/151842069-7f01c0c4-c28f-4ea0-9ab9-994aafdb72e4.png">
.

**Comment by kingslay** [comment]
KSPlayerManager.audioPlayerMaximumChannels = AVAudioChannelCount(AVAudioSession.sharedInstance().outputNumberOfChannels)

**Comment by MatejkaMartin** [comment]
But it is falling some where in your library.

<img width="532" alt="CleanShot 2022-02-01 at 08 53 31@2x" src="https://user-images.githubusercontent.com/17528892/151931311-931abf5c-4d28-4799-ac4c-a3c7522e43c7.png">

The `maximumOutputNumberOfChannels` returns value 32. But i was able to initiate the value 
```
AVAudioFormat(commonFormat: .pcmFormatFloat32, sampleRate: Double(audioPlayerSampleRate), channels: 1, interleaved: false)!
```
only with `channes:`  1 or 2 otherwise the AVAudioFormat was nil.
