### ISSUE TITLE
Can't play rtsp

### ISSUE THREAD

**Issue by Danilevsss** [kingslay/KSPlayer#204]
Trying to play rtsp or m3u8 stream. It worked in previous versions. Log:

`KSPlayer: KSPlayerLayer.swift:118 player | player is KSPlayer.KSAVPlayer
KSPlayer: KSAVPlayer.swift:375 prepareToPlay() | prepareToPlay KSPlayer.KSAVPlayer
2022-02-04 19:47:22.686416+0300 DomIQ[12147:3050059] NSURLConnection finished with error - code -1002
2022-02-04 19:47:22.710998+0300 DomIQ[12147:3049813] NSURLConnection finished with error - code -1002
2022-02-04 19:47:23.178534+0300 DomIQ[12147:3049796] Metal GPU Frame Capture Enabled
2022-02-04 19:47:23.178873+0300 DomIQ[12147:3049796] Metal API Validation Enabled
KSPlayer: KSPlayerLayer.swift:118 player | player is <KSPlayer.KSMEPlayer: 0x281f54000>
KSPlayer: KSMEPlayer.swift:303 prepareToPlay() | prepareToPlay <KSPlayer.KSMEPlayer: 0x281f54000>
KSPlayer: MEPlayerItem.swift:82 init(url:options:) | The "timeout" option is deprecated: set maximum timeout (in seconds) to wait for incoming connections (-1 is infinite, imply flag listen) (deprecated, use listen_timeout)

KSPlayer: MEPlayerItem.swift:82 init(url:options:) | Starting connection attempt to 81.30.218.28 port 55554

KSPlayer: MEPlayerItem.swift:82 init(url:options:) | Successfully connected to 81.30.218.28 port 55554

KSPlayer: MEPlayerItem.swift:82 init(url:options:) | SDP:
v=0

o=- 1643993243489118 1643993243489118 IN IP4 127.0.0.1

s=Streamer 21.11

c=IN IP4 0.0.0.0

t=0 0

a=control:*

a=tool:Streamer 21.11

a=x-qt-text-nam:Streamer 21.11

a=x-qt-text-inf:h264

a=type:broadcast

a=range:npt=now-

m=video 0 RTP/AVP 96

a=control:trackID=1

a=rtpmap:96 H264/90000

a=cliprect:0,0,1280,720

a=framesize:96 1280-720

a=x-dimensions:1280,720

a=framerate:25.0

a=fmtp:96 packetization-mode=1;profile-level-id=4DE01F;sprop-parameter-sets=Z00AH52oFAFum4CAgIE=,aO48gA==

b=AS:571

2022-02-04 19:47:23.504715+0300 DomIQ[12147:3049813] [si_destination_compare] send failed: Invalid argument
2022-02-04 19:47:23.504955+0300 DomIQ[12147:3049813] [si_destination_compare] send failed: Undefined error: 0
KSPlayer: MEPlayerItem.swift:82 init(url:options:) | setting jitter buffer size to 500

KSPlayer: MEPlayerItem.swift:82 init(url:options:) | Could not find codec parameters for stream 0 (Video: h264, none, 1280x720): unspecified pixel format
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options

KSPlayer: KSPlayerLayer.swift:134 state | playerStateDidChange - readyToPlay
KSPlayer: KSPlayerLayer.swift:280 changeLoadState(player:) | ["findTime": 30.266842624987476, "decodeAudioTime": -269603.8899464167, "readAudioTime": -269603.8899464167, "firstTime": 30.278427583281882, "decodeVideoTime": -269603.8899464167, "prepareTime": 0.00027849996695294976, "openTime": 0.2670675833360292, "readVideoTime": -269603.8899464167]
KSPlayer: KSMEPlayer.swift:309 play() | play <KSPlayer.KSMEPlayer: 0x281f54000>
KSPlayer: KSPlayerLayer.swift:134 state | playerStateDidChange - bufferFinished
`

**Comment by kingslay** [comment]
can you get me the rtsp url?  I do not have rtsp test url
