### ISSUE TITLE
can't play video by URL

### ISSUE THREAD

**Issue by helmiAtech** [kingslay/KSPlayer#205]
i can play my video in your sample. but when i try implement the KSPlayer to my project it say. "KSPlayer: KSPlayerLayer.swift:334 finish(player:error:) | Error Domain=AVFoundationErrorDomain Code=-11850 "Operation Stopped" UserInfo={NSLocalizedFailureReason=The server is not correctly configured., NSLocalizedDescription=Operation Stopped, NSUnderlyingError=0x6000023abed0 {Error Domain=NSOSStatusErrorDomain Code=-12939 "(null)"}}"
can you help we how make it work like your sample

**Comment by kingslay** [comment]
`        KSPlayerManager.firstPlayerType = KSMEPlayer.self
`
