### ISSUE TITLE
tvos not supports ButtonToggleStyle of swiftUI

### ISSUE THREAD

**Issue by mringg** [kingslay/KSPlayer#206]
development system: macos 12.2
xcode: 13.2.1
tvos: 15.2 simulator

I'm in trouble when building the project. I found what the file(KSVideoPlayer.swift) uses ButtonToggleStyle, but it does support tvOS.

ButtonToggleStyle
https://developer.apple.com/documentation/swiftui/buttontogglestyle
It does not support for tvOS.

DefaultToggleStyle
https://developer.apple.com/documentation/swiftui/defaulttogglestyle
tvOS maybe use DefaultToggleStyle.

**Comment by jartas** [comment]
<img width="548" alt="image" src="https://user-images.githubusercontent.com/73786529/153406053-daa75569-62ba-4f2b-8cd2-df86160cbcce.png">
