### ISSUE TITLE
RTSP live streaming issues 

### ISSUE THREAD

**Issue by TeksunNj** [kingslay/KSPlayer#207]
**When I tried to add an RTSP live streaming URL, I received the message "avformat cannot open input".

Would you please look into this for me and help me?**

**This is error details**
KSPlayer: KSPlayerLayer.swift:334 finish(player:error:) 
| Error Domain=KSPlayerErrorDomain Code=2 "avformat can't open input" UserInfo={NSLocalizedDescription=avformat can't open input, NSUnderlyingError=0x282698630 {Error Domain=FFmpegDomain Code=-1094995529 "Invalid data found when processing input" UserInfo={NSLocalizedDescription=Invalid data found when processing input}}}

Testing device iPhone x
Xcode 13

**This is my code details**
//Also try //"rtsp://192.168.x.xx:xxx/playlist.m3u"
  if let url = URL(string: "http://192.168.x.xx:xxx/playlist.m3u") {
        let options = KSOptions()
        options.formatContextOptions["timeout"] = 0
        objects.append(KSPlayerResource(url: url, options: options, name: "rtsp video"))
    }

**pod file details** 

 pod 'SwiftLint'

  pod 'KSPlayer',:git => 'https://github.com/kingslay/KSPlayer.git', :branch => 'develop', :commit => 'f6d721a6069a355ac4513d47884bee65ee2182b3'

    pod 'FFmpeg',:git => 'https://github.com/kingslay/KSPlayer.git', :branch => 'develop', :commit => 'f6d721a6069a355ac4513d47884bee65ee2182b3'

    pod 'OpenSSL',:git => 'https://github.com/kingslay/KSPlayer.git', :branch => 'develop', :commit => 'f6d721a6069a355ac4513d47884bee65ee2182b3'

**Comment by MeriGarala09** [comment]
@kingslay  I am also facing the same issue. Video URL is not loaded. I want to play this RTSP URL: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_175k.mov 
Your quick help can save me lots of time. Thank you.

**Comment by kingslay** [comment]
> @kingslay I am also facing the same issue. Video URL is not loaded. I want to play this RTSP URL: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_175k.mov
> Your quick help can save me lots of time. Thank you.

I can play it in the the latest develop branch

**Comment by TeksunNj** [comment]
rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_175k.mov
@kingslay Thank you for the Quick reply above URL is working 

I'm using a 5MP 1080P Camera Raspberry Pi 3/4
My Internet speed is 120 Mbps
Testing device iPhone X (Xcode 13.0)
My URL:- "rtsp://192.168.3.1:8554/test" 

The above URL is my local hotspot connected then after play.
I got the live streaming on **KSPlayer** but Latency was about 4 to 8 seconds

So how to reduce latency Is there any way, please tell me.

**Comment by kingslay** [comment]
> rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_175k.mov @kingslay Thank you for the Quick reply above URL is working
> 
> I'm using a 5MP 1080P Camera Raspberry Pi 3/4 My Internet speed is 120 Mbps Testing device iPhone X (Xcode 13.0) My URL:- "rtsp://192.168.3.1:8554/test"
> 
> The above URL is my local hotspot connected then after play. I got the live streaming on **KSPlayer** but Latency was about 4 to 8 seconds
> 
> So how to reduce latency Is there any way, please tell me.

You use other players such as iina on mac. Will Latency was about 4 to 8 seconds?

**Comment by TeksunNj** [comment]
> You use other players such as iina on mac. Will Latency was about 4 to 8 seconds?

Latency was more than 8 seconds in **KSPlayer**
Before I used VLCKIT.

Players such as iina it's available for ios?
Can you share references or more details?

Any idea how to reduce latency in **KSPlayer**

**Comment by kingslay** [comment]
iina is available for macOS. 
You can try KSPlayer with iOS emulator. Will there be this problem too?

**Comment by MeriGarala09** [comment]
@kingslay We are testing in the real device and facing the latency issue in iPhone X. Is there any solution for how to reduce this latency issue using **KSPlayer**. And our app is for only iPhone, not for mac So how the iina app can be useful to us? 

Give more details on it. It will help us to fix latency issues.

**Comment by kingslay** [comment]
> @kingslay We are testing in the real device and facing the latency issue in iPhone X. Is there any solution for how to reduce this latency issue using **KSPlayer**. And our app is for only iPhone, not for mac So how the iina app can be useful to us?
> 
> Give more details on it. It will help us to fix latency issues.

I want to check whether it is the problem of this playback url, or the problem of KSPlayer. Does playing this link with VLCKIT on iPhone have this problem？

**Comment by TeksunNj** [comment]
> I want to check whether it is the problem of this playback url, or the problem of KSPlayer. Does playing this link with VLCKIT on iPhone have this problem？

@kingslay   We have a problem but latency in VLCKIT will be 3 seconds, not more than but in 
**KSPlayer** we have more than 8-10second latency

Please check from your end. because in the URL, there is no issue.
How to change FPS and resolution?

**Comment by MeriGarala09** [comment]
@kingslay  Above log file can be helpful to you? Let us know if you need more info.

**Comment by kingslay** [comment]
@MeriGarala09  It is because avformat_find_stream_info causes the first-time to slow down. You can adjust the values of probesize and maxAnalyzeDuration in KSOptions.

**Comment by MeriGarala09** [comment]
@kingslay  Hi, Thanks for the quick suggestions. Can you give exact information on these options? What value I can set for the probesize and maxAnalyzeDuration?
If you provide the exact info then it will save our time. Thank you.

**Comment by maulikTeksun** [comment]
> @kingslay Hi, Thanks for the quick suggestions. Can you give exact information on these options? What value I can set for the probesize and maxAnalyzeDuration?
> If you provide the exact info then it will save our time. Thank you.

Yes @kingslay Could you please explain us?, What's purpose of these two new options and their meaning

**Comment by kingslay** [comment]
```
 let options = KSOptions()
        options.probesize = 3_000_000
        options.maxAnalyzeDuration = 2_000_000
```
You can try using these two values. Then see if firstTime is reduced. You can try reducing the value of these two parameters. However, if the values of these two parameters are too low, the video may not be played. So you can adjust a suitable parameter value by yourself
@MeriGarala09 @maulikTeksun

**Comment by maulikTeksun** [comment]
@kingslay  Can you please explain us? What is probesize and maxAnalyzeDuration in brief?

**Comment by kingslay** [comment]
https://iosvideokit.com/2014/02/13/minimizing-the-initial-delay/

**Comment by maulikTeksun** [comment]
By using this values

let options = KSOptions()
     options.probesize = 3_000_000
    options.maxAnalyzeDuration = 2_000_000

@kingslay after some time the streaming gets very delay. For every launch it runs well ( about 2 to 4 second delay) But after spending some time the delay are increasing automatically.

**Comment by kingslay** [comment]
> By using this values
> 
> let options = KSOptions() options.probesize = 3_000_000 options.maxAnalyzeDuration = 2_000_000
> 
> @kingslay after some time the streaming gets very delay. For every launch it runs well ( about 2 to 4 second delay) But after spending some time the delay are increasing automatically.

If not set probesize and  maxAnalyzeDuration,  will the delay automatically increase after a period of time?

**Comment by maulikTeksun** [comment]
these params looks its only effect at initial time . Later on in both situation getting delays.(If we are using values or not)
