### ISSUE TITLE
IOSVideoPlayerView and VideoPlayerView issues

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#208]
I am using swiftui

If I use IOSVideoPlayer I can use .gesture(DragGesture().onEnded { value in

if I use VideoPlayerView I can't.  it's ignored.

If I use IOSVideoPlayer and rotate the device, the screen goes black but still audio plays.

If I use VideoPlayerView, rotating the device works fine.

Ideally, both these players should support DragGesture and rotating the device in swiftui.

Is it possible to fix this please?

**Comment by UnknownCoder807** [comment]
I took a look at the source for VideoPlayerView and found a temporary fix.

It's obviously not a satisfactory fix but it works for now.  Hopefully it points you in the right direction.

```
    open func customizeUIComponents() {
        tapGesture.addTarget(self, action: #selector(tapGestureAction(_:)))
        tapGesture.numberOfTapsRequired = 1
        controllerView.addGestureRecognizer(tapGesture)
//        panGesture.addTarget(self, action: #selector(panGestureAction(_:)))
//        controllerView.addGestureRecognizer(panGesture)
        doubleTapGesture.addTarget(self, action: #selector(doubleTapGestureAction))
        doubleTapGesture.numberOfTapsRequired = 2
        tapGesture.require(toFail: doubleTapGesture)
        controllerView.addGestureRecognizer(doubleTapGesture)
    }

```

**Comment by kingslay** [comment]
you can override 
`judgePanGesture`

**Comment by kingslay** [comment]
> I am using swiftui
> 
> If I use IOSVideoPlayer I can use .gesture(DragGesture().onEnded { value in
> 
> if I use VideoPlayerView I can't. it's ignored.
> 
> If I use IOSVideoPlayer and rotate the device, the screen goes black but still audio plays.
> 
> If I use VideoPlayerView, rotating the device works fine.
> 
> Ideally, both these players should support DragGesture and rotating the device in swiftui.
> 
> Is it possible to fix this please?

you can use KSVideoPlayer

**Comment by UnknownCoder807** [comment]
Thanks for the fix.

KSPlayerVideo is easier to use in SwiftUI but has controls over the screen.  Can they be removed so only video is displayed?

**Comment by kingslay** [comment]
> Thanks for the fix.
> 
> KSPlayerVideo is easier to use in SwiftUI but has controls over the screen. Can they be removed so only video is displayed?

you can modify VideoControllerView and pull requests
