### ISSUE TITLE
SwiftUI and Mac Catalyst

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#209]
I have a SwiftUI app that uses KSPlayer and when compiled for Mac Catalyst it crashes with the following error :

`setMaximumTrackTintColor: is not supported on KSPlayer.KSSlider when running Catalyst apps in the Mac idiom.
`

Is this a KSPlayer issue or mac catalyst support issue?

**Comment by kingslay** [comment]
swiftui recommends using KSVideoPlayer
