### ISSUE TITLE
How to change aspect ratio ?

### ISSUE THREAD

**Issue by snappycode1** [kingslay/KSPlayer#21]
Is there an option to change the aspect ratio of a playing video?

If so, can you please give an example of how to do it?

**Comment by prikshitgupta** [comment]
@snappycode1  #20 Player dont stopping n ios? Do you have this problem?

**Comment by snappycode1** [comment]
I don't use iOS, only tvOS, sorry.

**Comment by prikshitgupta** [comment]
> I don't use iOS, only tvOS, sorry.

oh ok thank you

**Comment by prikshitgupta** [comment]
@snappycode1 https://github.com/kingslay/KSPlayer/issues/17 are you implementing somthing like this?

**Comment by snappycode1** [comment]
Yes, thats exactly what I'm doing.  It works with pressing down/up on the keyboard but swipes are ignored.  I need to know how to override the gestures with an example because the previous answer didn't really help.

**Comment by prikshitgupta** [comment]
> Yes, thats exactly what I'm doing. It works with pressing down/up on the keyboard but swipes are ignored. I need to know how to override the gestures with an example because the previous answer didn't really help.
> 
> edit : keyboard input is now ignored (ie, broken) in the latest develop branch, so something has changed.

I think i am able to over ride will get back to you soon with explanation soon

**Comment by snappycode1** [comment]
Thanks, look forward to your reply.  I've tried a million ways to override these functions but keep getting Method does not override any method from its superclass.

**Comment by prikshitgupta** [comment]
> Thanks, look forward to your reply. I've tried a million ways to override these functions but keep getting Method does not override any method from its superclass.

would you like to connect through slack?

**Comment by snappycode1** [comment]
I've just installed slack, not sure how to use it though.

**Comment by prikshitgupta** [comment]
Signup and send me your email id i will invite you. its easy to share code on slack.

**Comment by snappycode1** [comment]
utonador@gmail.com

**Comment by prikshitgupta** [comment]
> Signup and send me your email id i will invite you. its easy to share code on slack.
> 
> > I've just installed slack, not sure how to use it though.


invite sent delete your email from here.



> I've just installed slack, not sure how to use it though.

**Comment by prikshitgupta** [comment]
@kingslay can you please answer?

**Comment by kingslay** [comment]
player.contentMode = .scaleAspectFit

**Comment by snappycode1** [comment]
thanks

**Comment by snappycode1** [comment]
I've now had time to implement aspect ratio changing.  The solution of  player.contentMode = .scaleAspectFit 
doesn't do what I expect.

If a video is in 4:3 format, I would like the option to stretch it to 16:9 (for example)

in vlckit it's as simple as calling "mediaPlayer.videoAspectRatio = blah"

is there a similar function on KSPlayer or am I using contentMode wrongly ?

**Comment by snappycode1** [comment]
is it possible to use 4:3 16:9 video aspect ratio ?
