### ISSUE TITLE
KSVideoPlayerView demo on tvOS

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#214]
I've had a chance to try the demo KSVideoPlayerView SwiftUI on Apple TV and it doesn't look pretty.

There is no way to navigate the focus to any of the buttons.

Have you any plans to make the UI useable?  Seems a shame as the IOS one is working so well.

**Comment by UnknownCoder807** [comment]
What I would like to create is something like the following picture

![IMG_8733](https://user-images.githubusercontent.com/56231066/156261349-a4363b59-5b4d-4bec-be9c-9ce776c0f550.jpg)

have it appear on a press of the menu button for example, and exit when a button is clicked

**Comment by UnknownCoder807** [comment]
Thank you for the fix.  It now works fine.

Is picture in picture supposed to work on a real apple tv device?  the button doesn't do anything, but does on iOS.

**Comment by kingslay** [comment]
> Just one final thought. have you considered how to make the UI appear and disappear on tvOS? I know on iOS you can tap the screen, but that's not possible on tvOS.
> 
> Maybe it's possible to implement UITapGesture into the demo somehow?

You can see how other apps make the UI appear and disappear on tvos, I don't have tvos here.

**Comment by UnknownCoder807** [comment]
The problem is, tvos doesn't have swipe gestures or tap gestures when using SwiftUI.  The only way to implement them is to integrate UIKIt UIGestures into swift ui.  I can do this with a standard UIRepresentable View but I don't know if it's possible using your implementation.  It's rather more complicated. 

You don't need a real tvOS device, use the simulator and turn on show apple tv remote.

**Comment by kingslay** [comment]
I want you to look at other apps on tvOS. See how they make the UI appear and disappear.  the simulator can not download other apps

**Comment by UnknownCoder807** [comment]
I know how other apps do it, I know how to repeat it in UIKit/storyboard.  I have a tvOS app that has KSPlayer and uses UIKit/Storyboard and it works well.  It works like other apps do.  swipe down to show the controls UI.  Swipe up to hide them.

I can't replicate this in SwiftUI KSVideoPlayerView demo because there are no gestures available.  I need to know how to implement them in your demo app.   

I have a demo app of my own which uses SwiftUI and KSPlayer and I can get gestures to work.  Using UIGestureRecogniser in UIRepresentable view.  The problem is, my attempt is very basic compared to yours.  PiP etc not working.

I would like to use your demo as a base for making my app work on tvOS.  I don't understand how your demo works,  sadly the demo is useless on tvOS without a way to show/hide it. which is what I want gestures for.

**Comment by UnknownCoder807** [comment]
It's not ideal, but I have implemented the demo in the link below.  The control UI is hidden by default.  You swipe down on the remote to make it visible.  then use the X in the top left to hide the control UI.  (I really should change this icon).  When the control UI is visible, swiping up, down, left, right work as expected, and you can select buttons.

https://collect.wetransfer.com/board/stlox1ug7qn05al9520220303092836

It's not the best quality video (shakes a bit) but shows it working.  It doesn't work on the simulator hence the dodgy video quality.

I have also changed the buttons so they look like iOS ones.

What I hope to do is detect when the buttons at the top of the screen are selected and if you swipe up again, the controls UI is hidden.

**Comment by UnknownCoder807** [comment]
Thank you for the most recent commits.  It's a much neater implemention than the one I did.

There is one issue I can't seem to resolve.  On the demo before these commits I was able to add .edgesIgnoringSafeArea(.all) to make the video full screen.  I can't seem to do this now.  it's either ignored or i'm doing it in the wrong place.

**Comment by UnknownCoder807** [comment]
As there is no native Slider() for tvOS, there is this addon

https://github.com/zattoo/TvOSSlider/issues

I use it in my UIKit/Storyboard app.

Do you think it would be possible to include it in the demo?  Because being able to fast forward/rewind is important for movie playback.

**Comment by UnknownCoder807** [comment]
TvOSSlider does work.  Again its a hack I have done

https://collect.wetransfer.com/board/stlox1ug7qn05al9520220303092836/latest

**Comment by cdg90** [comment]
Hello @kingslay , thank you for all the hard work you have done so far. I would like to know when and how you will implement the slider support in the demo player of your app. I understand that maybe your focus is more on ios, but without that slider support, it would be impossible to browse the the played video. I hope you will find asap a solution for that :)

**Comment by kingslay** [comment]
> Hello @kingslay , thank you for all the hard work you have done so far. I would like to know when and how you will implement the slider support in the demo player of your app. I understand that maybe your focus is more on ios, but without that slider support, it would be impossible to browse the the played video. I hope you will find asap a solution for that :)

you can use Swipeleft and Swiperight
```

  #if os(tvOS)
            .onSwipe { direction in
                if direction == .down {
                    model.isMaskShow.toggle()
                } else if direction == .left {
                    config.playerLayer.seek(time: model.currentTime - 15, autoPlay: true)
                } else if direction == .right {
                    config.playerLayer.seek(time: model.currentTime + 15, autoPlay: true)
                }
            }
            #endif
```

**Comment by cdg90** [comment]
Thank you for the code, however, 
What if I want to navigate through the navigation bar and fast forward 9 minutes instantly. With every video player (apps, web streaming platforms, etc) the purpose of the navigation bar is also to resume playing at the time the viewer want (so to drag to any time of the video). Would you please implement a feature like this? Thanks @kingslay

**Comment by cdg90** [comment]
> > Hello @kingslay , thank you for all the hard work you have done so far. I would like to know when and how you will implement the slider support in the demo player of your app. I understand that maybe your focus is more on ios, but without that slider support, it would be impossible to browse the the played video. I hope you will find asap a solution for that :)
> 
> you can use Swipeleft and Swiperight
> 
> ```
> 
>   #if os(tvOS)
>             .onSwipe { direction in
>                 if direction == .down {
>                     model.isMaskShow.toggle()
>                 } else if direction == .left {
>                     config.playerLayer.seek(time: model.currentTime - 15, autoPlay: true)
>                 } else if direction == .right {
>                     config.playerLayer.seek(time: model.currentTime + 15, autoPlay: true)
>                 }
>             }
>             #endif
> ```

Thank you for the code, however,
What if I want to navigate through the navigation bar and fast forward 9 minutes instantly. With every video player (apps, web streaming platforms, etc) the purpose of the navigation bar is also to resume playing at the time the viewer want (so to drag to any time of the video). Would you please implement a feature like this? Thanks @kingslay

**Comment by UnknownCoder807** [comment]
I agree @cdg90 it's a must have thing to have. If only Apple provided the UISlider for tvOS.

**Comment by kingslay** [comment]
> I agree @cdg90 it's a must have thing to have. If only Apple provided the UISlider for tvOS.

I had add the Slider for tvOS.  but I can not set the Slider 's frame. Can you help me see how to change it? @UnknownCoder807

**Comment by UnknownCoder807** [comment]
Nice work @kingslay .  I aded 

.frame(height: 110)

to line 199 

and it made the slider have the same frame height as the buttons.

**Comment by UnknownCoder807** [comment]
Just tried the new demo on tvOS and it's brilliant.  There are 3 issues though :

1) When the slider has focus, if you swipe up and down, it has the same behaviour of swiping left and right.

2) When the slider has focus, you can't lose focus and be able to select the buttons to the left and right of the slider.  Once the slider has focus, it keeps focus.  maybe add a onTap gesture to say scrolling has finished?

3) When the slider has focus, you can't swipe up to to go the top tow of buttons.

**Comment by cdg90** [comment]
> Just tried the new demo on tvOS and it's brilliant. There are 3 issues i've encountered though :
> 
> 1. When the slider has focus, if you swipe up and down, it has the same behaviour of swiping left and right.
> 2. When the slider has focus, you can't lose focus and be able to select the buttons to the left and right of the slider.  Once the slider has focus, it keeps focus.  maybe add a onTap gesture to say scrolling has finished?
> 3. When the slider has focus, you can't swipe up to to go the top tow of buttons.

@kingslay 

when you use the slider, is it possible to show the time above the slider, like it does on iptvx. otherwise you dont know what position you are sliding to.
Here is a video to show you how it works:

https://collect.wetransfer.com/board/s5a8bejpkthb5bjox20220306081838/latest?token=98dff656-fbfc-4bbd-a5eb-951222609efd

**Comment by UnknownCoder807** [comment]
Regarding my 3 issues above, I have managed to solve issue 3)

At the moment, if you have the slider focused, you cannot swipe up to the top row of buttons.  If the play/pause button has focus you can swipe to to the top row, because there is a direct focus path.

However,  now, after you have finished swiping and tapped the ok/select button, you can swipe up to the buttons on the top row.

Add
             .focusSection()

to line 159

This makes the top buttons focusable from the slider when it has focus.
