### ISSUE TITLE
KSVideoPlayerView demo. iOS and Subtitles/Audio Tracks

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#215]
I'm considering using ksplayer with my next swiftui app.  I can use your swiftui app on iOS devices which works perfectly for me in a demo I knocked up.

I am wondering, how would I implement internal subtitles and audio tracks ?  I can do it on UIKit/Storyboard but not so sure on your swiftui demo.  It's a lot more complicated than I am used to.

Thanks if you can help.

**Comment by UnknownCoder807** [comment]
Any help with this please @kingslay ?

**Comment by UnknownCoder807** [comment]
brilliant, thanks.

**Comment by kingslay** [comment]
fixed by fc2e456820752ca6458fccc646d9cbeea8cd3380

**Comment by UnknownCoder807** [comment]
Thanks for the code.  It works well except when I select a subtitle language it doesn't seem to display any subtitles.

I can send you the .mkv url via email if this helps.

**Comment by kingslay** [comment]
ok, please send it to me

**Comment by UnknownCoder807** [comment]
Thanks again.  Subtitles appear automatically when the stream starts.  If I change the subtitles to another language the subtitles stop working, they just freeze on whatever was last displayed.

        KSPlayerManager.autoSelectEmbedSubtitle = false

seems to have no effect.

**Comment by UnknownCoder807** [comment]
Thank for the updated code.

After enabling a subtitle and leaving the controls UI visible the following happens

![Simulator Screen Shot - iPhone 13 Pro Max - 2022-03-13 at 08 28 48](https://user-images.githubusercontent.com/56231066/158051646-1d8cb6ed-dc0c-43b9-a665-347252303fce.png)

When the next subtitle appears on the screen, the UI controls go back to how they should be.  This alternates every time a subtitle changes.

**Comment by UnknownCoder807** [comment]
Latest update has the issue of subtitles being displayed by default when the stream opens.  You fixed it in an earlier commit, so seems to be unfixed now.

**Comment by kingslay** [comment]
> Latest update has the issue of subtitles being displayed by default when the stream opens. You fixed it in an earlier commit, so seems to be unfixed now.

`KSOptions.autoSelectEmbedSubtitle = false`

**Comment by UnknownCoder807** [comment]
![Untitled](https://user-images.githubusercontent.com/56231066/158068279-17b3311f-bbbd-4470-b67e-d46c0c998d44.jpg)

**Comment by kingslay** [comment]
`options.autoSelectEmbedSubtitle`

**Comment by kingslay** [comment]
you can change the value of autoSelectEmbedSubtitle

**Comment by UnknownCoder807** [comment]
I don't know where that goes.  I'd have thought KSOptions() was the best place.

**Comment by UnknownCoder807** [comment]
If I download a .srt subtitle file, how can I assign it as the active subtitle?

In uikit/storyboard i could use something like 

`asset?.subtitle = KSURLSubtitle(url: subtitleFileURL, encoding: .ascii)
`
Is there a way to do it with swiftui version?

**Comment by kingslay** [comment]
subtitleModel.selectedSubtitle = KSURLSubtitle(url: url)
