### ISSUE TITLE
怎么可以拿到实时字幕内容呢，我想自己自定义显示字幕

### ISSUE THREAD

**Issue by buzai** [kingslay/KSPlayer#217]
我想屏蔽掉内部的显示。但是需要把显示什么string，实时回调到外面，让外部自定义view显示。

**Comment by kingslay** [comment]
你是用swiftui 版本的KSVideoPlayerView

**Comment by buzai** [comment]
@kingslay 是的，我用的swiftUI的demo

**Comment by buzai** [comment]
@kingslay 我看一下，多谢
