### ISSUE TITLE
crashes on ios 12.4 isformatSampleRateAndChannelCountValid(format)

### ISSUE THREAD

**Issue by jamariyaatwork** [kingslay/KSPlayer#218]
Tested on ios 12.4 and it's crashes with following error log:

https://github.com/kingslay/KSPlayer/blob/efc40b970c47d22e8f0ed7207b534fd2f30de578/Sources/KSPlayer/MEPlayer/AudioEnginePlayer.swift#L162

<img width="1307" alt="Screenshot 2022-03-23 at 8 48 59 PM" src="https://user-images.githubusercontent.com/69639881/159733712-282c86c9-735a-4796-bf80-4586aa6c47fd.png">

**Comment by kingslay** [comment]
can you print the value of format.channelLayout ?

**Comment by jamariyaatwork** [comment]
Hi Thank you for quick reply.

Printing description of format:
(AVAudioFormat) format = 0x000000028219a760 {
  baseNSObject@0 = {
    isa = AVAudioFormat
  }
  _layout = 0x00000002802a2ec0 {
    baseNSObject@0 = {
      isa = AVAudioChannelLayout
    }
    _layoutTag = 6619138
    _reserved = 0x0000000000000000
  }
  _commonFormat = 1
  _reserved = 0x0000000000000000
}

**Comment by kingslay** [comment]
can you print the value of  format.channelLayout?.channelCount ?

**Comment by jamariyaatwork** [comment]
Hi, Yes

Format ==> Optional(<AVAudioFormat 0x282498a00:  2 ch,  44100 Hz, Float32, non-inter>)
(lldb) po print(format?.channelLayout?.channelCount)
Optional(2)
0 elements

(lldb)
