### ISSUE TITLE
Video - ContentMode

### ISSUE THREAD

**Issue by DineshkumarKandasamy** [kingslay/KSPlayer#222]
Hi @kingslay Can we set content mode as `fill` while we use in portrait mode. I have tried below options, but not working. Please guide me

```
ksplayerViewItem.playerLayer.player?.contentMode = .scaleAspectFill
ksplayerViewItem.playerLayer.contentMode = .scaleAspectFill
ksplayerViewItem.contentMode = .scaleAspectFill
```

**Comment by kingslay** [comment]
you can see the swiftui demo  KSVideoPlayer in the develop branth

`                playerLayer?.player?.contentMode = isScaleAspectFill ? .scaleAspectFill : .scaleAspectFit
`
