### ISSUE TITLE
MetalPlayView deinit crash

### ISSUE THREAD

**Issue by snapwoodapps** [kingslay/KSPlayer#228]
Regarding PR #227 

The change made in [d5c5331](https://github.com/kingslay/KSPlayer/commit/d5c5331b3057950ea17dc29fd2861bbb6e927d9b) has introduced a crash in the deinit of MetalPlayView:

<pre><code>Thread 1 Queue : com.apple.main-thread (serial)
#0	0x0000000107ac45bc in _dispatch_queue_xref_dispose.cold.1 ()
#1	0x0000000107a93474 in _dispatch_queue_xref_dispose ()
#2	0x0000000107a8ca58 in -[OS_dispatch_source _xref_dispose] ()
#3	0x00000001012656d0 in @objc MetalPlayView.__ivar_destroyer ()
#4	0x00000001867c2ddc in object_cxxDestructFromClass(objc_object*, objc_class*) ()
#5	0x00000001867d9494 in objc_destructInstance ()
#6	0x00000001867e0af0 in _objc_rootDealloc ()
#7	0x00000001c6373324 in -[UIResponder dealloc] ()
#8	0x00000001ab6b20b4 in -[UIResponderAccessibility dealloc] ()
#9	0x00000001c67f8fd0 in -[UIView dealloc] ()
#10	0x00000001012655bc in MetalPlayView.__deallocating_deinit at /Users/bwood/Library/Developer/Xcode/DerivedData/picante-asmnmdsvkaelqibzvbpcutkedyjt/SourcePackages/checkouts/KSPlayer/Sources/KSPlayer/MEPlayer/MetalPlayView.swift:116
#11	0x0000000101265648 in @objc MetalPlayView.__deallocating_deinit ()
#12	0x0000000101238974 in @objc KSMEPlayer.__ivar_destroyer ()
#13	0x00000001867c2ddc in object_cxxDestructFromClass(objc_object*, objc_class*) ()
#14	0x00000001867d9494 in objc_destructInstance ()
#15	0x00000001867e0af0 in _objc_rootDealloc ()
#16	0x00000001012388e8 in KSMEPlayer.__deallocating_deinit at /Users/bwood/Library/Developer/Xcode/DerivedData/picante-asmnmdsvkaelqibzvbpcutkedyjt/SourcePackages/checkouts/KSPlayer/Sources/KSPlayer/MEPlayer/KSMEPlayer.swift:92
#17	0x0000000101238914 in @objc KSMEPlayer.__deallocating_deinit ()
#18	0x00000001011e9044 in outlined destroy of MediaPlayerProtocol? ()
#19	0x00000001011e1a4c in @objc KSPlayerLayer.__ivar_destroyer ()
#20	0x00000001867c2ddc in object_cxxDestructFromClass(objc_object*, objc_class*) ()
#21	0x00000001867d9494 in objc_destructInstance ()
#22	0x00000001867e0af0 in _objc_rootDealloc ()
#23	0x00000001c6373324 in -[UIResponder dealloc] ()
#24	0x00000001ab6b20b4 in -[UIResponderAccessibility dealloc] ()
#25	0x00000001c67f8fd0 in -[UIView dealloc] ()
#26	0x00000001011e1960 in KSPlayerLayer.__deallocating_deinit at /Users/bwood/Library/Developer/Xcode/DerivedData/picante-asmnmdsvkaelqibzvbpcutkedyjt/SourcePackages/checkouts/KSPlayer/Sources/KSPlayer/AVPlayer/KSPlayerLayer.swift:167
</code></pre>
<br>

**Comment by kingslay** [comment]
Is there a path to reproduce this crash in the demo? I can't find a way to reproduce
