### ISSUE TITLE
Please tell me about how to change streams smoothly like you

### ISSUE THREAD

**Issue by minhtoantm** [kingslay/KSPlayer#23]
Hi kingslay.
Thank for awsome player.
I am maintancing and develop hls play function for ijkplayer, but I have stuck in bellow issues.
If you don't mind, please tell me some solution because KSPLayer is awsome player and I want ijkplayer is good for hls too.

1. With m3u8 contains many variants like: 240p, 360p, 480p. We have 6 streams (audio & video). With default, 240p (stream 0&1) will played. When I switch to 360P, I using method "ffp_set_stream_selected" to change stream, it changed but has stuck when off old stream and open new stream. There are discontinuous phenomenon in playing HLS stream when changing another bitrate stream.
In KSPlayer, I don't see this stuck, it is very smooth.
→ Can you told me solution for this?

Thank you.

**Comment by kingslay** [comment]
i use stream.pointee.discard = AVDISCARD_ALL
```

    private func adaptable(track: PlayerItemTrackProtocol, loadingState: LoadingState) {
        guard var videoAdaptation = videoAdaptation, track.mediaType == .video, !loadingState.isFinished else {
            return
        }
        videoAdaptation.loadedCount = track.packetCount + track.frameCount
        videoAdaptation.currentPlaybackTime = currentPlaybackTime
        guard let (oldBitRate, newBitrate) = options.adaptable(state: videoAdaptation) else {
            return
        }
        assetTracks.first { $0.mediaType == .video && $0.bitRate == oldBitRate }?.stream.pointee.discard = AVDISCARD_ALL
        assetTracks.first { $0.mediaType == .video && $0.bitRate == newBitrate }?.stream.pointee.discard = AVDISCARD_DEFAULT
        let bitRateState = VideoAdaptationState.BitRateState(bitRate: newBitrate, time: CACurrentMediaTime())
        self.videoAdaptation?.bitRateStates.append(bitRateState)
        delegate?.sourceDidChange(oldBitRate: oldBitRate, newBitrate: newBitrate)
    }
```

**Comment by minhtoantm** [comment]
Thank for your reply.

I read your code and found it, but when I change AVDISCARD_ALL and AVDISCARD_DEFAULT for new stream, nothing happen.
Do you open all stream and only switch flag discard when change stream?

**Comment by kingslay** [comment]
I add a seek 
```
 func select(track: MediaPlayerTrack) {
        if let track = track as? TrackProtocol {
            assetTracks.filter { $0.mediaType == track.mediaType }.forEach { $0.stream.pointee.discard = AVDISCARD_ALL }
            track.stream.pointee.discard = AVDISCARD_DEFAULT
            seek(time: currentPlaybackTime, completion: nil)
        }
    }
```

**Comment by minhtoantm** [comment]
Can you tell me class name of hls player?

**Comment by kingslay** [comment]
KSMEPlayer

**Comment by minhtoantm** [comment]
Thank you very much.
