### ISSUE TITLE
Set videoGravity for playerLayer

### ISSUE THREAD

**Issue by DineshkumarKandasamy** [kingslay/KSPlayer#231]
@kingslay  I have tried to change videoGravity value. But I am getting error. Could you please help me put?

ksplayerViewItem.playerLayer.videoGravity = .resizeAspectFill

**Comment by kingslay** [comment]
you can see the swiftUI demo(iOS)
![image](https://user-images.githubusercontent.com/3964055/166406050-b617bb49-e608-48aa-94de-24a8d438cf4a.png)
![image](https://user-images.githubusercontent.com/3964055/166406066-0e52df73-e92b-434f-b37f-966e216f8038.png)
