### ISSUE TITLE
FFmpeg Cache

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#235]
I noticed in another issue posted here that Cache is enabled in FFmpeg.

An app I use also uses FFmpeg and has some advanced cache options.  which can be seen in this screenshot.

![40C6FFE0-3088-4E44-A476-59E1F959ADF2](https://user-images.githubusercontent.com/56231066/167287615-bed4a579-b346-43ec-9fb4-1225811a7c3b.png)

Is it possible to access the FFmpeg cache so I can provide some of these options when using KSPlayer ?

**Comment by kingslay** [comment]
the ffmpeg cache only support  http. 

```
//    ffmpeg only cache http
    public var cache = false 
```

**Comment by UnknownCoder807** [comment]
ok, thanks
