### ISSUE TITLE
setting syncDecodeAudio & syncDecodeVideo not working

### ISSUE THREAD

**Issue by cuongtv51** [kingslay/KSPlayer#236]
I read code & try to change some settings in KSOptions
when i change syncDecodeAudio = true & syncDecodeVideo = true, it not working, demo also not working.

**Comment by kingslay** [comment]
you need override 
`    open func playable(capacitys: [CapacityProtocol], isFirst: Bool, isSeek: Bool) -> LoadingState? {
`

**Comment by kingslay** [comment]
Generally used syncDecodeAudio = true  in audio-only situations.   used syncDecodeVideo = true  in video-only situations.
