### ISSUE TITLE
Delay in stream

### ISSUE THREAD

**Issue by MiladCyrus** [kingslay/KSPlayer#237]
KSPlayer is a nice player, although it needs to be more optimized but I really enjoy working with it.

I managed to play a local SRT Stream using KSPlayer. but delay was too much. by changing `preferredForwardBufferDuration = 0.01` is still around 3 second delay. 

is there any buffer size that I can change to reduce latency to minimum?

**Comment by kingslay** [comment]
you can override
`playable(capacitys: [CapacityProtocol], isFirst: Bool, isSeek: Bool)`

**Comment by kingslay** [comment]
you can try the latest code for develop branch

**Comment by MiladCyrus** [comment]
Thanks @kingslay 
I tried new changes but same result. Could you please show me exact changes or overrides I should make to see effect?

**Comment by kingslay** [comment]
fixed by 4b1f0fe21fb4f8ae010ca736d3143fe3499088d0

**Comment by kingslay** [comment]
> I get 3 second delays over AirPlay. Any idea why this might be? I'm not an iOS Audio Engineer by any means but I would love to help if I can.

This should be a problem with AirPlay itself. Because AirPlay is closed source. We can't understand the operation logic inside. Can't make any changes to this either
