### ISSUE TITLE
Video skipping itself

### ISSUE THREAD

**Issue by prikshitgupta** [kingslay/KSPlayer#24]
Big issue with player video is skipping itself when playing vod. Please sort this out @kingslay

**Comment by kingslay** [comment]
Can you provide the play URL?

**Comment by prikshitgupta** [comment]
> Can you provide the play URL?

Ok i will email you. Its skipped in apple tv.

**Comment by prikshitgupta** [comment]
Did you fix it?

**Comment by kingslay** [comment]
I can't reproduce it. You use the latest develop branch try again. Maybe I have fixed it

**Comment by prikshitgupta** [comment]
Ok i will try thanks
