### ISSUE TITLE
Libcrypto - 19 duplicate symbols for architecture arm64

### ISSUE THREAD

**Issue by 0xacdc** [kingslay/KSPlayer#240]
Added KSPlayer via SPM. tag: 1.4.0 (branch: develop - same result)

`ld: 19 duplicate symbols for architecture arm64`

duplicate symbol '_bn_mul_mont' in:
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(libcrypto-lib-armv8-mont.o)  
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(liblegacy-lib-armv8-mont.o)  
duplicate symbol '_bn_div_words' in:
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(libcrypto-lib-bn_asm.o)
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(liblegacy-lib-bn_asm.o)
duplicate symbol '_bn_sqr_words' in:
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(libcrypto-lib-bn_asm.o)
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(liblegacy-lib-bn_asm.o)
duplicate symbol '_bn_mul_words' in:
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(libcrypto-lib-bn_asm.o)
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(liblegacy-lib-bn_asm.o)
duplicate symbol '_bn_add_words' in:
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(libcrypto-lib-bn_asm.o)
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(liblegacy-lib-bn_asm.o)
duplicate symbol '_bn_mul_add_words' in:
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(libcrypto-lib-bn_asm.o)
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(liblegacy-lib-bn_asm.o)
duplicate symbol '_bn_sub_words' in:
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(libcrypto-lib-bn_asm.o)
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(liblegacy-lib-bn_asm.o)
duplicate symbol '_bn_sqr_comba8' in:
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(libcrypto-lib-bn_asm.o)
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(liblegacy-lib-bn_asm.o)
duplicate symbol '_bn_mul_comba8' in:
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(libcrypto-lib-bn_asm.o)
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(liblegacy-lib-bn_asm.o)
duplicate symbol '_bn_sqr_comba4' in:
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(libcrypto-lib-bn_asm.o)
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(liblegacy-lib-bn_asm.o)
duplicate symbol '_bn_mul_comba4' in:
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(libcrypto-lib-bn_asm.o)
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(liblegacy-lib-bn_asm.o)
duplicate symbol '_DES_ncbc_encrypt' in:
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(libcrypto-lib-des_enc.o)
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(liblegacy-lib-des_enc.o)
duplicate symbol '_DES_ede3_cbc_encrypt' in:
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(libcrypto-lib-des_enc.o)
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(liblegacy-lib-des_enc.o)
duplicate symbol '_DES_SPtrans' in:
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(libcrypto-lib-des_enc.o)
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(liblegacy-lib-des_enc.o)
duplicate symbol '_DES_encrypt3' in:
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(libcrypto-lib-des_enc.o)
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(liblegacy-lib-des_enc.o)
duplicate symbol '_DES_decrypt3' in:
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(libcrypto-lib-des_enc.o)
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(liblegacy-lib-des_enc.o)
duplicate symbol '_DES_encrypt2' in:
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(libcrypto-lib-des_enc.o)
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(liblegacy-lib-des_enc.o)
duplicate symbol '_DES_encrypt1' in:
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(libcrypto-lib-des_enc.o)
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(liblegacy-lib-des_enc.o)
duplicate symbol '_fcrypt_body' in:
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(libcrypto-lib-fcrypt_b.o)
   Build/Products/Debug-iphoneos/Libcrypto.framework/Libcrypto(liblegacy-lib-fcrypt_b.o)

**Comment by talshr** [comment]
Hey, I'm seeing this too. Remember what solved it?

**Comment by 0xacdc** [comment]
Hey, take a look where are you importing this package. If you'll import it directly in the app, it should not giving you any errors. Otherwise you may really have duplicate symbols ?

**Comment by talshr** [comment]
Using Cocoapods. I think it's related somehow to my specific project, can't figure out yet why. I've tried imported the same pods on a side project and it works fine.

**Comment by 0xacdc** [comment]
My issue was related to SPM

**Comment by talshr** [comment]
My issue was about project configuration. I removed redundant frameworks information and it fixed it.
