### ISSUE TITLE
HardwareDecode & Asynchronous Decompression problem

### ISSUE THREAD

**Issue by Datastore24Kirill** [kingslay/KSPlayer#241]
The following options are missing in the latest version:
        options.hardwareDecodeH264 = true
        options.hardwareDecodeH265 = true
        options.asynchronousDecompression = true
        
        Without these options, our RTSP stream loads very slowly. What do you advise?

**Comment by kingslay** [comment]
I switched to using ffmpeg for hard decoding. ffmpeg does not support asynchronousDecompression which makes decoding slower. I can add asynchronousDecompression back.

**Comment by Datastore24Kirill** [comment]
> I switched to using ffmpeg for hard decoding. ffmpeg does not support asynchronousDecompression which makes decoding slower. I can add asynchronousDecompression back.

You can return all these parameters, since with them the video stream was loaded up to 2 seconds, and now up to 20 seconds

**Comment by Datastore24Kirill** [comment]
And what about the parameters:
options.hardwareDecodeH264 = true
options.hardwareDecodeH265 = true
    
    Without them, the video also loads for about 20 seconds.

**Comment by Datastore24Kirill** [comment]
My configuration of player:
options.isAccurateSeek = true
        options.asynchronousDecompression = true
        options.formatContextOptions["fps_probe_size"] = 1
        options.formatContextOptions["reconnect"] = 3
        options.formatContextOptions["analyzeduration"] = 0
        options.formatContextOptions["probe_size"] = 5000 
        options.formatContextOptions["rtsp_transport"] = "tcp"
        options.formatContextOptions["codec"] = "avcodec"
        options.formatContextOptions["rtsp_flags"] = "prefer_tcp"
        
        options.formatContextOptions["infbuff"] = 1
        options.formatContextOptions["flush_packets"] = 1
        options.formatContextOptions["packet_buffering"] = 0
        options.formatContextOptions["an"] = 1
        options.formatContextOptions["framedrop"] = 1
        
        options.formatContextOptions["rec_buffer_size"] = 20000
        
        options.decoderOptions["framedrop"] = "1"
        
       
        options.preferredForwardBufferDuration = 1
        options.maxBufferDuration = 5
        options.isAutoPlay = true

**Comment by Datastore24Kirill** [comment]
At the beginning I have many many messages running in the console:

**_KSPlayer: MEPlayerItem.swift:91 init(url:options:) | hardware accelerator failed to decode picture_**

After that, the video turns on after 25 seconds

**Comment by kingslay** [comment]
can you get my the play url

**Comment by Datastore24Kirill** [comment]
> can you get my the play url

rtsp://85.140.46.69:554/av0_1&user=user&password=user

**Comment by Datastore24Kirill** [comment]
> can you get my the play url

Any news on the video stream?

**Comment by kingslay** [comment]
This video uses VideoHardwareDecode to perform hard decoding and an error is reported. The previous code should not be hard to solve.

**Comment by Datastore24Kirill** [comment]
> This video uses VideoHardwareDecode to perform hard decoding and an error is reported. The previous code should not be hard to solve.

Tell me, what parameters should I use so that the video download occurs as before? Download speed used to be 3-5 seconds, now 25

**Comment by Datastore24Kirill** [comment]
@kingslay up

**Comment by kingslay** [comment]
you can try this code
```
 override func enableHardwareDecode() -> Bool {
        return false
    }
```
