### ISSUE TITLE
KSPlayerLayer and selecting subtitles

### ISSUE THREAD

**Issue by skrew** [kingslay/KSPlayer#244]
Hi,

I need a mostly pure metal / view player because i have my own interface and gestures.
So i'm using `KSPlayerLayer` (it's the good one to use in my case ?)

All looks fine except selecting a subtitle.

I have added / handled the subtitle code, and i can see the first [0] subtitles on my view.

But selecting another subtitle have no effect, what i'm missing ?

```
func player(layer: KSPlayerLayer, state: KSPlayerState) {
    if state == .readyToPlay, let player = layer.player {
        embedSubtitleDataSouce = layer.player?.subtitleDataSouce
        (...)
        let tracks = player.tracks(mediaType: .subtitle)
        let track = tracks[1]
        player.select(track: track)
    }
}
```

**EDIT**:
I can change the track with this code, but.. it's kinda strange ?
```
let infos = self.srtControl.filterInfos { $0.subtitleDataSouce === self.embedSubtitleDataSouce }
if let track = infos[safe: 1] {
    self.srtControl.view.selectedInfo.wrappedValue = track
}
```

Thanks

**Comment by kingslay** [comment]
track?.subtitle?.enableSubtitle { result in
                        subtitleModel.selectedSubtitle = try? result.get()
}

**Comment by skrew** [comment]
Ok fixed. Thanks
