### ISSUE TITLE
Xcode 14 issue in KSMEPlayer

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#246]
I realise Xcode 14 is new and only in beta, but this might be an issue when it goes out of beta.

<img width="1900" alt="Screenshot 2022-06-06 at 20 48 10" src="https://user-images.githubusercontent.com/56231066/172353076-6997546c-ef08-4f1d-9ad6-dcf7cf62a0ec.png">

**Comment by UnknownCoder807** [comment]
Still an issue in beta 2.  Any chance of an idea to make it work?

**Comment by skrew** [comment]
You can comment out those 2 lines and set iOS 16 as deployment while waiting for the fixes

**Comment by UnknownCoder807** [comment]
There are several new instances of these errors.  Any chance you can install Xcode 14 Beta and see if you get anything to compile for tvOS ?  thanks.

**Comment by UnknownCoder807** [comment]
My app has severe UI issues on tvOS 16 beta and I would like to fix them, but KSPlayer won't compile for tvOS 16 on Xcode 14 beta.  Please can you look into this as I am sure the changes Apple made will be here to stay and will stop KSPlayer working in the future.
