### ISSUE TITLE
[Question] Multistream Audio

### ISSUE THREAD

**Issue by ronnie-codes** [kingslay/KSPlayer#247]
Hey there. We're integrating your player into our iOS app over here at https://aaptiv.com. `AVPlayer` won't let us mix multiple HLS audio streams without creating a second player instance, and `AirPlay 2` will only cast 1 `AVPlayer` instance, so a second player instance is out of the question. Your `AVAudioEngine` based solution solves our problem. 

Moving on.. I was able to open up your `AudioEnginePlayer` and support more than one instance of `AVAudioSourceNode`. Basically, I added an initializer that asks for an array of `MEPlayerItem`, and a source node is created for each item.

I would love to contribute this feature back into your player after getting it done right. 

My first question to you is: Do you see any drawbacks with my approach? Does having more than one MEPlayerItem running audio have any unintended side effects? 

My second question is: Would like us to contribute back with the following features?
1. AudioEnginePlayer is made public and available to those that want to only leverage your audio engine and not the video + audio player.
2. AudioEnginePlayer supports multiple mixed audio streams.

We could also create an audio only player that wraps AudioEnginePlayer, like KSMEPlayer but audio only. This way we don't have to make the engine public. Then we could even add a demo to the project of an audio only HLS player that can mix streams.

Thoughts? Thank you and great work.

**Comment by kingslay** [comment]
There are no side effects for creating multiple MEPlayerItems. But for pure audio you can set KSOptionssyncDecodeAudio to true. This reduces thread switching. Performance will be better. Finally, you are welcome to contribute this feature back into KSPlayer

**Comment by ronnie-codes** [comment]
When I set `KSOptionssyncDecodeAudio` to true, I experience artifacts in the audio whenever a new HLS segment is loaded. 

Basically, anytime I see this in the console 

```
KSPlayer: MEPlayerItem.swift:96 init(url:options:) | HLS request for url 'https://aaptiv-audio-cdn.aaptiv.com/workout-audio/5f33e976f18cb9ed15bac4a6/stream_music_en_imperial_1597846081477_128-00048.ts', offset 0, playlist 1
```

the audio also "blips" briefly. This doesn't happen when this flag is set to false. I am however setting `options.videoDisable` to true.

I have some more questions.

1. When seeking two player items, they become slightly off. Maybe like a 50ms drift. If you play 2 voice tracks on top of each other and seek it results in what sounds like reverb. Any idea why this might be happening?

2. Would you prefer making `AudioEnginePlayer` publicly available, or wrapping it something like `KSMEPlayer` and calling it maybe `MEPlayer`?

Thank you for your time.

**Comment by kingslay** [comment]
I feel like it might be because the time between the two tracks is out of sync. 
I had changed AudioEnginePlayer to public
