### ISSUE TITLE
Ksplayer out of sync when playing 4K UHD stream

### ISSUE THREAD

**Issue by cdg90** [kingslay/KSPlayer#249]
Hello @kingslay ,

when I play a 4K UHD stream with a specific codec on tvos, the video is out of sync.
The stream plays without any issue with ksplayer on ios, the issue is only on tvos. Besides, the live stream plays well on VLC tvos.

https://collect.wetransfer.com/board/se2cdnszoa5pn3qem20220612112524/latest?token=b38d14aa-d27a-43c9-b1ae-eae001ab0ef0

**Comment by kingslay** [comment]
can you provide me that play link？

**Comment by cdg90** [comment]
skips to the else, so not using videotoolbox 

<img width="1894" alt="Screenshot_2022-06-13_at_08 26 14" src="https://user-images.githubusercontent.com/100095878/173308028-15f5a0e1-9150-4f62-af14-265299f0c4ec.png">

**Comment by kingslay** [comment]
Then you can see if iOS is  using videotoolbox

**Comment by cdg90** [comment]
same result with iOS, goes to the else

**Comment by cdg90** [comment]
The new ffmpeg update solved the issue. Stream plays flawlessly. Thanks!
