### ISSUE TITLE
Please tell me the way to debug in ffmpeg

### ISSUE THREAD

**Issue by minhtoantm** [kingslay/KSPlayer#25]
Hi @kingslay .
Please tell me the way to debug in ffmpeg, I want to debug to know some value of variants.
Thank you very much for greate player.

**Comment by kingslay** [comment]
https://github.com/kingslay/KSPlayer/blob/develop/documents/%E8%B0%83%E8%AF%95FFmpeg.md

**Comment by minhtoantm** [comment]
Thank you very much.
I read your code and develop "hls adaptive bitrate" for ijkplayer.
But i have an issue when change stream by set discard=AVDISCARD_DEFAULT like you:
In KSPlayer, i see log is: decode_slide_header error. -> no frame! -> Reinit context to 640x368
But in ijkplayer, stream is paused.

Do you know cause of this issue? or tell me any solution for this?
Again, thank you very much.

**Comment by minhtoantm** [comment]
> https://github.com/kingslay/KSPlayer/blob/develop/documents/%E8%B0%83%E8%AF%95FFmpeg.md

Sorry but when i rebuild ffmpeg, i get this error: ERROR: libxml-2.0 not found using pkg-config
Althought I installed: "brew install libxml2" and  "brew install sdl2"
But error still happens.

**Comment by kingslay** [comment]
brew install pkg-config

**Comment by kingslay** [comment]
> Thank you very much.
> I read your code and develop "hls adaptive bitrate" for ijkplayer.
> But i have an issue when change stream by set discard=AVDISCARD_DEFAULT like you:
> In KSPlayer, i see log is: decode_slide_header error. -> no frame! -> Reinit context to 640x368
> But in ijkplayer, stream is paused.
> 
> Do you know cause of this issue? or tell me any solution for this?
> Again, thank you very much.

ijkplayer uses an older version of ffmpeg, and has modified it itself. So there's no way to know for sure what this one is about. You can use KSPlayer.KSPlayer uses ffmpeg which is the latest

**Comment by minhtoantm** [comment]
I build successfull, but can not debug line by line with clear code.
Can you have any solution for this? or if you have any link to research this, please give for me.
Thanks.

![image](https://user-images.githubusercontent.com/5442921/83853145-0bbdfc80-a73f-11ea-9784-a789b6a6f7d0.png)

**Comment by kingslay** [comment]
you need use Mac Catalyst 
![image](https://user-images.githubusercontent.com/3964055/83940541-9114e000-a817-11ea-8d26-6757cb506f7f.png)
