### ISSUE TITLE
期望有自定义UI的demo

### ISSUE THREAD

**Issue by lxm1799** [kingslay/KSPlayer#250]
视频播放器起来非常流畅。不过我希望有更丰富的示范
例如：
1、自定义toolBar、自定义navigationBar,
2、通过继承做一些UI上的调整frame、icon

**Comment by kingslay** [comment]
你可以基于KSPlayerLayer来写一个自己的播放器UI。基于KSPlayerLayer你可以用SwiftUI或UIKit来写自定义UI。你也可以改下IOSVideoPlayerView的代码，然后发起push request
