### ISSUE TITLE
无法获取到naturalSize

### ISSUE THREAD

**Issue by chenfengfeng** [kingslay/KSPlayer#251]
获取naturalSize的时候返回都是0，我用demo测试也是一样的结果
以下是测试的url：
https://cache.m3u8.shenglinyiyang.cn/duoduo/20220703/d4b94ee820dd205c717947c9cd4cb5b1.m3u8?st=IQe5GsgWbhdw75XvEwDUUw&e=1656843113

如果URL过期我再更新下，我用系统的播放器测试是能获取到分辨率尺寸的

**Comment by chenfengfeng** [comment]
经过测试，发现是使用系统的AVPlayer内核的时候，无法获取到naturalSize的值，使用KSMEPlayer就可以，但这个也是个问题，如果可以的话，就修复一下，因为URL容易过期，我看到回复后会马上给你个新地址，你可以测试下

**Comment by kingslay** [comment]
naturalSize这个是从系统的方法里面取的
`        naturalSize = track.assetTrack?.naturalSize ?? .zero
`
所以如果AVPlayerItemTrack里面没有这个信息的话。那就无法取到这个值

**Comment by chenfengfeng** [comment]
@kingslay emm这个我再多做点测试，看看是什么问题，然后提供给你，因为我发现我这边所有的url资源，使用avplayer都无法获取到值

**Comment by chenfengfeng** [comment]
@kingslay 还有个问题，因为你的横屏是基于naturalSize来判断的，这就导致，如果视频还没加载，我就点击切换横屏，那么就会获取不到size导致无法横屏，这个在你提供的demo就能复现，有些url的加载确实会慢很多，切换横屏的判断能改其他的判断吗？

**Comment by kingslay** [comment]
fix 236c12a8d5a098a6e41dcadc263de71b5edafa06
