### ISSUE TITLE
KSPlayer looses track of segment number when switching VBR stream variant

### ISSUE THREAD

**Issue by CatchupTV-net** [kingslay/KSPlayer#256]
Dear developer I have a VBR stream which does not play in KSPlayer. Traffic analysis reveals segments are not played in order.

The stream is geolocked so a Danish (Denmark) VPN is required for you to test it.

This link http://catchuptv.net/catchuptv/catchuptv/1?utc=1657448100

Redirects to a link with session information

http://catchuptv.net/DRTV/rdpolk4a9lk815gcrhvclgej3t/dr1.m3u8?utc=1657448100 

which holds the stream variants information:

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:BANDWIDTH=8905600,AVERAGE-BANDWIDTH=9081600,CODECS="avc1.64002a,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=50.000
http://catchuptv.net/DRTV/rdpolk4a9lk815gcrhvclgej3t/dr1/8000.m3u8?utc=1657448100
#EXT-X-STREAM-INF:BANDWIDTH=6210600,AVERAGE-BANDWIDTH=6331600,CODECS="avc1.640029,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=50.000
http://catchuptv.net/DRTV/rdpolk4a9lk815gcrhvclgej3t/dr1/5500.m3u8?utc=1657448100
#EXT-X-STREAM-INF:BANDWIDTH=3731200,AVERAGE-BANDWIDTH=3801600,CODECS="avc1.640029,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=50.000
http://catchuptv.net/DRTV/rdpolk4a9lk815gcrhvclgej3t/dr1/3200.m3u8?utc=1657448100
#EXT-X-STREAM-INF:BANDWIDTH=2296800,AVERAGE-BANDWIDTH=2340800,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1024x576,FRAME-RATE=25.000
http://catchuptv.net/DRTV/rdpolk4a9lk815gcrhvclgej3t/dr1/2000.m3u8?utc=1657448100
#EXT-X-STREAM-INF:BANDWIDTH=1326600,AVERAGE-BANDWIDTH=1350800,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=768x432,FRAME-RATE=25.000
http://catchuptv.net/DRTV/rdpolk4a9lk815gcrhvclgej3t/dr1/1100.m3u8?utc=1657448100
#EXT-X-STREAM-INF:BANDWIDTH=679800,AVERAGE-BANDWIDTH=690800,CODECS="avc1.77.30,mp4a.40.2",RESOLUTION=640x360,FRAME-RATE=25.000
http://catchuptv.net/DRTV/rdpolk4a9lk815gcrhvclgej3t/dr1/500.m3u8?utc=1657448100

From there KSPlayer calls the 500 kbit/s variant

http://catchuptv.net/DRTV/rdpolk4a9lk815gcrhvclgej3t/dr1/500.m3u8?utc=1657448100

Which informs it of the first three segments

#EXTM3U
#EXT-X-PLAYLIST-TYPE:EVENT
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:114297
#EXTINF:4.0000,
https://drlive01hls.akamaized.net/hls/live/2014185/drlive01/master500-41_114297.ts
#EXTINF:4.0000,
https://drlive01hls.akamaized.net/hls/live/2014185/drlive01/master500-41_114298.ts
#EXTINF:4.0000,
https://drlive01hls.akamaized.net/hls/live/2014185/drlive01/master500-41_114299.ts

It then plays correctly the master500-41_114299.ts segment.

Now KSPlayer asked for the 2000 kbit/s variant

http://catchuptv.net/DRTV/rdpolk4a9lk815gcrhvclgej3t/dr1/2000.m3u8?utc=1657448100

Which - because it is no longer the first call - returns all the segments of the event playlist

#EXTM3U
#EXT-X-PLAYLIST-TYPE:EVENT
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:114297
#EXTINF:4.0000,
https://drlive01hls.akamaized.net/hls/live/2014185/drlive01/master2000-41_114297.ts
#EXTINF:4.0000,
https://drlive01hls.akamaized.net/hls/live/2014185/drlive01/master2000-41_114298.ts
#EXTINF:4.0000,
https://drlive01hls.akamaized.net/hls/live/2014185/drlive01/master2000-41_114299.ts
#EXTINF:4.0000,
https://drlive01hls.akamaized.net/hls/live/2014185/drlive01/master2000-41_114300.ts
#EXTINF:4.0000,
https://drlive01hls.akamaized.net/hls/live/2014185/drlive01/master2000-41_114301.ts
...
...

#EXT-X-ENDLIST

Now according to the spec your player should play the following segment master2000-41_114298.ts but it appears to jump to the 3rd last segment of the event master2000-41_115194.ts

This causes erratic playback in KSPlayer.

Stream plays well in GSE IPTV and VLC.

B.r.
CatchupTV

PS if you don't follow up in a few days please put a more recent UTC timestamp at the end of the initial link to test this
![14ACD9A5-8ADF-4D72-9104-F03096D4AA5F](https://user-images.githubusercontent.com/103790736/178151350-cc49043a-fd2a-4896-9c3e-4470e3e1d61a.png)

**Comment by kingslay** [comment]
You can try to use FFPlay will you have this problem

**Comment by CatchupTV-net** [comment]
I was not able to run FFPlay over SSH connection so I cannot tell you if it has the same problem. Players like GSE IPTV, VLC and IPTV Smarters did not have problems.

However I decided to change my server to deliver playlist type VOD instead of EVENT streams, and now they work in KSPlayer too so I am satisfied.


14. jul. 2022 11.41 af ***@***.***:

**Comment by kingslay** [comment]
You can try` options.videoAdaptable = false` and see if there will be this problem

**Comment by fedalcode** [comment]
@kingslay you can close this thread. No issue anymore
