### ISSUE TITLE
Is support hwaccel VP9 and ProRes?

### ISSUE THREAD

**Issue by Alanko5** [kingslay/KSPlayer#265]
ffmpeg now support hw acceleration for VP9 and ProRes

https://www.ffmpeg.org -> January 17th, 2022, FFmpeg 5.0 "Lorentz"
VideoToolbox VP9 hwaccel
VideoToolbox ProRes hwaccel

**Comment by kingslay** [comment]
support hwaccel VP9 and ProRes
