### ISSUE TITLE
Error in BuildFFmpeg

### ISSUE THREAD

**Issue by MiladCyrus** [kingslay/KSPlayer#278]
There is a problem with the build script after your recent changes.
`sudo arch -x86_64 swift run build-FFmpeg enable-openssl enable-libsrt`

Terminal Output:
[Terminal_Saved_Output.txt](https://github.com/kingslay/KSPlayer/files/9353360/Terminal.Saved.Output.txt)

**Comment by kingslay** [comment]
目前libsrt只支持了iOS。你可以修改下BuildFFmpeg，让libsrt变成支持所有的平台。也可以改成用
` run build-FFmpeg enable-openssl`
不加 enable-libsrt

**Comment by kingslay** [comment]
fileprivate let platforms = [PlatformType.ios]
