### ISSUE TITLE
Inheritance Issue 

### ISSUE THREAD

**Issue by wertpoiu** [kingslay/KSPlayer#28]
Set first player as a avplayer
inherit iosvideoplayer class

Avplayer audio will never stops even player player is removed from view.

when first player is ksmeplayer there is no issue.

**Comment by wertpoiu** [comment]
@kingslay can you please fix this?

**Comment by kingslay** [comment]
How did you  removed the player from view？

**Comment by wertpoiu** [comment]
> How did you removed the player from view？

I didnt, i thought resetplayer function will remove it.

**Comment by kingslay** [comment]
I've fixed the bug. Please update the develop branch.

**Comment by wertpoiu** [comment]
> I've fixed the bug. Please update the develop branch.

it is still there.

**Comment by kingslay** [comment]
do you have commit 903578ecb9fdcadb607b721526fa28445ba04d2a

**Comment by wertpoiu** [comment]
> do you have commit [903578e](https://github.com/kingslay/KSPlayer/commit/903578ecb9fdcadb607b721526fa28445ba04d2a)

Yes i have latest

**Comment by kingslay** [comment]
please clean build folder.and try again

**Comment by wertpoiu** [comment]
> please clean build folder.and try again

did clean it, still the same.

**Comment by kingslay** [comment]
Can you provide a demo?

**Comment by wertpoiu** [comment]
> Can you provide a demo?

ok will email you

**Comment by wertpoiu** [comment]
Sent you the code

**Comment by wertpoiu** [comment]
now ksmeplayer also doing same thing

**Comment by wertpoiu** [comment]
Can you please fix it?

**Comment by kingslay** [comment]
Please see if you can get to this line of code.
```
    deinit {
        resetPlayer()
    }
```

**Comment by wertpoiu** [comment]
Yes i am, but audio starts again after 2 second

**Comment by wertpoiu** [comment]
> Please see if you can get to this line of code.
> 
> ```
>     deinit {
>         resetPlayer()
>     }
> ```

I have emailed you my code can you please check that?

**Comment by wertpoiu** [comment]
AudioObjectRemovePropertyListener: no object with given ID 0

Constantly getting this message in console

**Comment by kingslay** [comment]
after resetPlayer().  you can check to see  if you've get to this line of code.
`public func set(url: URL, options: KSOptions) {`

**Comment by kingslay** [comment]
> > Please see if you can get to this line of code.
> > ```
> >     deinit {
> >         resetPlayer()
> >     }
> > ```
> 
> I have emailed you my code can you please check that?

The code is incomplete and can't be run

**Comment by wertpoiu** [comment]
ok i will make whole demo then
