### ISSUE TITLE
KSVideoPlayerView swiftui and audio/video/subtitles issues

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#280]
I am trying to customize the settings screen on the KSVideoPlayerView swiftui file.

I have the following code (which is your code) and when I select None as the audio track, I would expect the audio to be cut off (in effect muted).   The same for video and subtitles.  nothing happens when an option is selected.

```
Picker("Audio Tracks", selection: Binding(get: {
                    config.selectedAudioTrack?.trackID
                }, set: { value in
                    config.selectedAudioTrack = config.audioTracks.first { $0.trackID == value }
                })) {
                    Text("None").tag(nil as Int32?)
                    ForEach(config.audioTracks, id: \.trackID) { track in
                        Text(track.name).tag(track.trackID as Int32?)
                    }
                }
                .pickerStyle(.inline)
```

Is this code broken or is there something else I need to do to make it reflect the users choice?

**Comment by kingslay** [comment]
fix by 99b8caa751e747285d7f621c3976dc7c61b9278c

**Comment by UnknownCoder807** [comment]
Thanks for the fix.  Its almost perfect.

On a filename.m3u8 file the toggling of audio and video doesn't work.  filename.ts    filename,avi filename.mkv filename.mp4 all work fine.

**Comment by UnknownCoder807** [comment]
Another small issue, I resume that subtitles can be turned on/off the same way ?

playerLayer?.options?.subtitleDisable = false / true

If so, I tried it and although they can be enabled, if I click on None they don't turn off.

**Comment by UnknownCoder807** [comment]
Thanks again for the fixes.  Subtitles now turn on/off ok

However, filename.m3u8 still doesn't let me toggle the audio or video.

On another related note to settings, if I were to write to config.playerLayer.options from the same VideoSettings view, will the player respect this change or does it require further work? ( want to have toggles to turn/on video filters for example)

`config.playerLayer?.options?.videoFilters = "yadif"
`

**Comment by UnknownCoder807** [comment]
can you please tell me what does "you need set enableHardwareDecode to false" mean in relation to my last post?  

I'm confused.

**Comment by kingslay** [comment]
因为目前硬解码之后无法应用filter。我还没找到解决方案。所以只能用软接

**Comment by UnknownCoder807** [comment]
ok, I understand, thanks.

Any ideas on why m3u8 (hls) streams wont let me toggle audio or video?  every other video/audio format works.  thanks
