### ISSUE TITLE
selected audio and video stream details

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#281]
Is it possible to get the number of audio channels the selected stream has?  Something like "2 Channels"

Is it possible to get the codec info for audio and video?  Something like "H264 MPEG 4 AVC" and "MPEG AAC AUDIO" ?

Thanks

**Comment by UnknownCoder807** [comment]
Thanks @kingslay but how do I use it? thanks.

**Comment by kingslay** [comment]
> Thanks @kingslay but how do I use it? thanks.

let selectedAudioTrack = config.audioTracks.first { $0.isEnabled }

**Comment by UnknownCoder807** [comment]
Yeah I have that part, but how do I get the codec info in the format mentioned in my first post?  

`selectedAudio.track.????????`

I tried .mediaSubType.desription but it gives a 0x000 type response.  thanks

**Comment by kingslay** [comment]
let codec = track.mediaSubType.rawValue.string
let channels  = track.audioStreamBasicDescription?.mChannelsPerFrame

**Comment by UnknownCoder807** [comment]
Thanks, getting closer, but still not working for me.

`Text(config.selectedVideoTrack?.mediaSubType.rawValue.string ?? "Unknown")`

returns an empty string.  I have tried with hls stream, mp4 and mkv.

If I remove the .string I get the following error

`Initializer 'init(_:)' requires that 'FourCharCode?' (aka 'Optional<UInt32>') conform to 'StringProtocol'
`
so I assume .string is necessary.

mChannelsPerFrame also returns nothing.

**Comment by UnknownCoder807** [comment]
The recent commits to this have largely been positive, but there is still an intermittent issue.  The exact same live tv stream (filensme.ts) can work 3 times out of 5. 

I sent you a link to stream that has this issue.  Does the video have to parse for x seconds before calling the functions to display fps and codec info?

**Comment by kingslay** [comment]
没有一个固定时间的，这个主要依赖网络的时间。解析完之后，会有函数的回调
   public func player(layer: KSPlayerLayer, state: KSPlayerState) {
            if state == .readyToPlay, let player = layer.player {
// do something
   videoTracks = player.tracks(mediaType: .video)
                audioTracks = player.tracks(mediaType: .audio)
             }
        }

**Comment by UnknownCoder807** [comment]
Thanks, I have that code already.  It doesn't matter where I put the Text() or print() to output the FPS, it's never always displayed.  In your demo app are you seeing the FPS all the time?

**Comment by kingslay** [comment]
你可以重新发给我那个链接。我多试几次
