### ISSUE TITLE
Render subs as images

### ISSUE THREAD

**Issue by andrefmsilva** [kingslay/KSPlayer#283]
It is possible to render the subtitles inside the metal view as images? 
I'm asking this because i can't find a way to put the subtitles inside the video image and make them resize when you move from landscape to portrait.

**Comment by csmagics** [comment]
不得不说你的app很粗糙，为啥搞图片，搞个text放上面得了，搞图片可以试试vlckit那玩意是用图片的，不过支持并不很好

**Comment by kingslay** [comment]
我是文字字幕和图片字幕都支持的。如果视频里面是文字字幕的话 那就会用text。我的那个只是一个demo。所以很粗糙。你感兴趣的话 可以来改下代码

**Comment by csmagics** [comment]
@kingslay 我是说提问那个人的app，他那个播放器需要5美元…
