### ISSUE TITLE
Video Filters

### ISSUE THREAD

**Issue by cdg90** [kingslay/KSPlayer#285]
Hello Kingslay,

While I was looking for the de-interlace filters in your code (BuildFFmpeg.swift) I figured out that you only added the "Yadif" Filter.
On ios devices, the performance is not affected, but on AppleTv, yadif filter is very demanding on the processor, and for that reason it may cause lag on video streams.

For that reason, can you please add the other deinterlacing filters that are on ffmpeg:

Bob Weaver Deinterlacing Filter (https://www.ffmpeg.org/ffmpeg-filters.html#bwdif)
Edge Slope Tracing Deinterlacing Filter (https://www.ffmpeg.org/ffmpeg-filters.html#estdif)
Weston 3 Field Deinterlacing Filter (https://www.ffmpeg.org/ffmpeg-filters.html#w3fdif)

Thank you

**Comment by almagest21** [comment]
Hi, is there any way to know Interlaced or not Interlaced about playing video item? Also how to specify these filter options when playing?
Recently I recognize this problem with when some mpg video playing with KSMEPlayer. If anyone knows, I would be very grateful if you could let me know.
Thank you.

**Comment by cdg90** [comment]
> Hi, is there any way to know Interlaced or not Interlaced about playing video item? Also how to specify these filter options when playing?
> Recently I recognize this problem with when some mpg video playing with KSMEPlayer. If anyone knows, I would be very grateful if you could let me know.
> Thank you.

@kingslay 

I found a blog post, where it says that there is a command in ffmpeg that detects if the stream is interlaced or not:

http://www.aktau.be/2013/09/22/detecting-interlaced-video-with-ffmpeg/


—

It turns out that ffmpeg has a filter called idet that (tries to) detect interlaced frames, and in my experience is quite good at it. You’ll need a pretty recent version of ffmpeg for this (later 2012 I believe, the one in the debian wheezy repository is not recent enough). Here’s an example of how to use it and what happens when I try it on an interlaced and non-interlaced file:

# detect interlacing with the ffmpeg "idet" filter, the more frames
# you extract, the better, though it's never 100% accurate

ffmpeg -filter:v idet \
    -frames:v 100 \
    -an \
    -f rawvideo -y /dev/null \
    -i ~/Downloads/some_interlaced_video.mkv
# Example output (this is interlaced, TFF style)
# [Parsed_idet_0 @ 0x1ccf7c0] Single frame detection: TFF:167 BFF:0 Progressive:1 Undetermined:0
# [Parsed_idet_0 @ 0x1ccf7c0] Multi frame detection: TFF:168 BFF:0 Progressive:0 Undetermined:0

ffmpeg -filter:v idet \
    -frames:v 100 \
    -an \
    -f rawvideo -y /dev/null \
    -i ~/Downloads/some_non_interlaced_video.mkv
# Example output (this is not interlaced):
# [Parsed_idet_0 @ 0x1bcf720] Single frame detection: TFF:0 BFF:0 Progressive:564 Undetermined:84
# [Parsed_idet_0 @ 0x1bcf720] Multi frame detection: TFF:0 BFF:0 Progressive:623 Undetermined:25

# flags:
# -an            = discard audio, we don't need it
# -f rawvideo    = output raw video
# -y /dev/null   = discard the output
# -i ...         = the input file to check
# -frames:v 100  = extract the first 100 frames
# -filter:v idet = insert the "idet" filter, which will output whether it has detected interlaced frames
If you see many frames next to TFF or BFF, that means a video is interlaced.
—

maybe @kingslay will have a look and add it

**Comment by almagest21** [comment]
@cdg90 Thank you for detailed explanation, I understood ffmpeg has much capabilities well. I guess the ffmpeg version is specified in ffmpeg.podspec, but do you know it is same or not when using the Swift package manager?
I hope KSPlayer will be able to take advantage of this detection and various de-interlacing filter. @kingslay  Please consider it if possible.

**Comment by cdg90** [comment]
@almagest21 @kingslay 

I guess this github link is cleaner:

https://gist.github.com/codyopel/718fea0621ed87c87aaa
