### ISSUE TITLE
Use Apple's AVPlayerView UI instead of custom UI

### ISSUE THREAD

**Issue by macOS26** [kingslay/KSPlayer#286]
I thought I put in a ticket for this about a year ago, but haven't seen it.

Is it possible to use Apple's AVPlayerView UI instead of a custom overlay?  

Apple's UI seems more solid and consistent. 

Most of my live streams can use AVPlayerView. But recorded stream use KSPlayer but doing so gives a mixed UI across my streaming video applications so I am hesitant to have KSPlayer for 1 thing and AVPlayerView for another. This has forced me to use KSPlayer across my entire AppleTV app and because there is a such a contrast, I only use live channels on my macOS and iOS apps using AVPlayerView and I don't use KSPlayer on those.

Let me know if this is possible or if there will be an update to KSPlayer to allow this.  Ton AppleTV, KSPlayer's overlay GUI with the giant slider that updates late when seeking is the most atrocious thing. I'd rather have Apple's UI across tvOS, macOS and iOS.

**Comment by kingslay** [comment]
you can use KSVideoPlayer. KSVideoPlayer is written in swiftui. Then the goal of KSVideoPlayer is that the ui is the same as the AVPlayerView ui. There may still be some partial inconsistencies. you can modify it together

**Comment by kingslay** [comment]
很抱歉不能帮到你。是的，AVPlayerView的UI的是很好的。但是AVPlayerView无法把播放内核切换成FFmpeg。所以只能自己用KSPlayerLayer来实现一个类似AVPlayerView的UI界面。这部分的工作量比较大，需要有人来一起贡献这个代码。我目前主要工作还是集中在播放器内核里面。

**Comment by kingslay** [comment]
AVPlayerView is only macos. ios and tvos not have AVPlayerView
