### ISSUE TITLE
ass字幕能增加使用libass渲染吗？

### ISSUE THREAD

**Issue by cxfksword** [kingslay/KSPlayer#288]
现在播放器已经很好用了，但ass字幕现在的渲染方式会丢失高级特效，能像mpv一样增加使用libass渲染吗？

**Comment by kingslay** [comment]
可以修改下AssParse里面的代码，把对应的ass转为NSMutableAttributedString。可以先坚持简单的特效。

**Comment by cxfksword** [comment]
> 可以修改下AssParse里面的代码，把对应的ass转为NSMutableAttributedString。可以先坚持简单的特效。

每个电影的字幕特效都很大不同，自己实现是只能做些简单的效果，能使用libass的话就好了

**Comment by kingslay** [comment]
用libass的话，是把文字渲染成位图，性能没有直接用NSMutableAttributedString的好。我们只要支持简单的效果就好了。这个库还要支持iOS和tvos。他们的性能没有那么好。

**Comment by cxfksword** [comment]
好，原来是生成图片的方式实现

**Comment by cxfksword** [comment]
试了下，使用NSMutableAttributedString实现不了字幕偏移的效果，看其他app使用mpv的，在tvos性能好像没什么问题，能提供一个使用libass渲染的开关选项吗，让有需要的再打开
