### ISSUE TITLE
De-interlace auto detect

### ISSUE THREAD

**Issue by fedalcode** [kingslay/KSPlayer#289]
Hello @kingslay 

in ffmpeg there is a command that auto detects if the content is interlaced.

the command is “idet”

can you incorporate the command in your player?

http://www.aktau.be/2013/09/22/detecting-interlaced-video-with-ffmpeg/

https://gist.github.com/codyopel/718fea0621ed87c87aaa

**Comment by cdg90** [comment]
Hi @kingslay Thanks for adding the filter.

How should I use the idet filter in the SwiftUI untouched ksplayer?

should I use the filter like here (https://gist.github.com/codyopel/718fea0621ed87c87aaa)
Or there is another command?

thank you

**Comment by kingslay** [comment]
我这边也还不知道怎么样把idet 结合到swiftui里面。其他播放器是怎么样的搞的呢？你有了解过吗？

**Comment by cdg90** [comment]
@kingslay 

In general, the player settings is like this:

interlace settings: always ON / Always OFF / Automatic
Interlace method: method A / Method B / etc


On the backend, players do like this:

For automatic deinterlace mode,
1- player analyses the first 100 frames.
2- If the idet command says that the video is not interlaced, then interlace filter is not activated;
3- if the idet command says that the video is interlaced, then the player uses the interlace filter method chosen by the user

**Comment by kingslay** [comment]
能否提供一个测试视频呢？我来试下

**Comment by cdg90** [comment]
This is the ffmpeg idet command line for interlace detection:
http://www.aktau.be/2013/09/22/detecting-interlaced-video-with-ffmpeg/

here is the MPV Player auto de-interlace code:
https://github.com/mpv-player/mpv/blob/6265724f3331e3dee8d9ec2b6639def5004a5fa2/TOOLS/lua/autodeint.lua


The video player I used during the screen recording:
https://github.com/zaps166/QMPlay2

here are the screen recording from qmplay2 app, and deinterlace settings from a media player app that uses ffmpeg:
https://collect.wetransfer.com/board/sgh4gpuxt4qgxzn4920220926145712/latest?token=e0b4a6ff-9a97-4ad2-957a-0b3109a288b5

**Comment by andrefmsilva** [comment]
Hi, i'm the dev of that app...
@cdg90 that config was for VLC engine and is not yet fully working for the FFMPEG/MPV engine. 

But depending of your usage (that i think is similar to mine) you can consider that only live stream can be interlaced.

**Comment by andrefmsilva** [comment]
I still need to check the VLC code but from their [wiki](https://wiki.videolan.org/Deinterlacing/) looks like they use video metadata ( maybe with Mediainfo) to detect if  it's interlaced.



```
In the mode Automatic, VLC will check the stream flags (technical term for information embedded in the video) and automatically set deinterlacing on or off, depending on if the current video is marked as interlaced even in animated movies on DVDs. However, the detection is not always reliable. If the setting is On, VLC will apply deinterlacing even if the original is not interlaced (which is a really bad idea). The setting Off, respectively, always keeps deinterlacing off.

The most reliable choice is to switch deinterlacing on/off manually when needed.
```

**Comment by kingslay** [comment]
@cdg90 能够把这两个视频发给我吗？我来测试下
![image](https://user-images.githubusercontent.com/3964055/192421634-8c15858e-0f91-432e-9931-ccb3fc750d4b.png)

**Comment by cdg90** [comment]
@kingslay please check your e-mail

**Comment by UnknownCoder807** [comment]
I just tried this useful feature and I get a crash on tvOS.  iOS is ok.

<img width="1517" alt="Screenshot 2022-10-02 at 18 23 11" src="https://user-images.githubusercontent.com/56231066/193467471-37758d27-25d9-4ffd-9007-4f394b61270b.png">

**Comment by kingslay** [comment]
你更新下代码 已经改好了
