### ISSUE TITLE
Error when play hls hevc: https://bitmovin-a.akamaihd.net/content/dataset/multi-codec/hevc/stream_fmp4.m3u8

### ISSUE THREAD

**Issue by minhtoantm** [kingslay/KSPlayer#29]
Hi kingslay.
Please check with hls hevc link: https://bitmovin-a.akamaihd.net/content/dataset/multi-codec/hevc/stream_fmp4.m3u8
After 4s, audio is playing but video is freeze.
Thank you.

**Comment by kingslay** [comment]
i have fixed

**Comment by minhtoantm** [comment]
Have you pushed source code to github?
I have just checked with commit "15551dc75091d61533a6088a6e52a7e65980dc75", I saw black screen.
Please check it again.

**Comment by kingslay** [comment]
yes. commit is 15551dc75091d61533a6088a6e52a7e65980dc75.

**Comment by minhtoantm** [comment]
Can you check it again?
I run it on iPhone SE (2nd generation), and can not play.
Black screen only.

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-06-26 at 15 45 46](https://user-images.githubusercontent.com/5442921/85838711-2c202a80-b7c4-11ea-9eb5-ec4dca570517.png)

**Comment by kingslay** [comment]
fixed it. commit is ac9c3e8be49949043a544f0944e16362c5408aab

**Comment by minhtoantm** [comment]
Thank for fixing it.
But when I check, it only play to 4-5s, and freeze.
Do you have this issue?

**Comment by kingslay** [comment]
because the simulator can't hardwareDecode hevc. you user real machine can hardwareDecode hevc

**Comment by minhtoantm** [comment]
I tested on my iPhone 8Plus iOS 13.5.1, It still contains error: After 4s, audio is playing but video is freeze.
Can you check it again?
Thanks.

**Comment by kingslay** [comment]
i tested on my iPhone 7Plus iOS 13.5.1. it is ok. you can check KSOptions.hardwareDecodeH265  is true? Can get to this function HardwareDecode.doDecode

**Comment by kingslay** [comment]
@minhtoantm I fixed it again. you can try again
