### ISSUE TITLE
Video properties (resolution and fps info) not fetched from Ksplayer

### ISSUE THREAD

**Issue by cdg90** [kingslay/KSPlayer#291]
Hi @kingslay ,

I am using your swiftui player and the video settings view is identical to your player except for the addition of fps

Since the last ksplayer update, in almost all the live streams I play, I can’t get the resolution and FPS info. 

For that reason, I also suspect that the frame rate matching does not work.

The content matching works, as my appleTV output settings is set to 50 fps HDR, every time I open a SDR stream, the player forces the AppleTV to output in SDR.

For the live stream media info fetching; this is the code I use:

Text("\(config.selectedVideoTrack?.nominalFrameRate ?? 0.0) fps")

Would you please check?

Thank you

**Comment by kingslay** [comment]
你可以提供对应的url吗？ 我调试下
