### ISSUE TITLE
MU38/HLS multi resolution video issue and FPS data not displayed

### ISSUE THREAD

**Issue by cdg90** [kingslay/KSPlayer#294]
Hello @kingslay 

maybe this is an easy question to respond:

I have a stream (HLS) that has multi-resolution.

http://catchuptv.net/live/catchuptv/catchuptv/16.ts

How can I choose between the resolutions in your SwiftUI demo player?

Also, in your untouched SwiftUI video player I can’t get the FPS info. You can try the link above.

thank you

**Comment by kingslay** [comment]
VideoSettingView 这个view就可以选择不同分辨率的视频了。 selectedVideoTrack

**Comment by cdg90** [comment]
@kingslay 

Here is the code I use from the untouched ksplayer swiftUI:

Picker("video tracks", selection: Binding(get: {
                    config.selectedVideoTrack?.trackID
                }, set: { value in
                    config.selectedVideoTrack = config.videoTracks.first { $0.trackID == value }
                })) {
                    Text("None").tag(nil as Int32?)
                    ForEach(config.videoTracks, id: .trackID) { track in
                        Text(track.description).tag(track.trackID as Int32?)
                    }
                }
                .pickerStyle(.inline)
                .tabItem {
                    Text("video")
                }

but I can't get all resolutions.

By the way, I accidently put the .ts link. here is the HLS stream: http://catchuptv.net/live/catchuptv/catchuptv/16.m3u8

**Comment by kingslay** [comment]
![image](https://user-images.githubusercontent.com/3964055/190848217-cd877fae-1be4-4c19-9f79-2f6db0179137.png)
KSOptions.videoAdaptable 这个为true。就会自动根据网络来选择分辨率

**Comment by UnknownCoder807** [comment]
I have an interest in this post, as I too have a problem with this.  I created a test project with the following contentview and an unmodified KSVideoPlayerView file.  I used the url posted above and it has the same issue as I have.   

```
struct ContentView: View {
    let url = "http://catchuptv.net/live/catchuptv/catchuptv/16.m3u8"
    let myOptions = KSOptions()

    init() {
        myOptions.isAutoPlay = true
        myOptions.videoAdaptable = true
        KSPlayerManager.firstPlayerType = KSAVPlayer.self
        KSPlayerManager.secondPlayerType = KSMEPlayer.self
    }
    
    var body: some View {
        NavigationView {
            VStack {
                NavigationLink(destination: KSVideoPlayerView(url: URL(string: url)!, options: myOptions)) {
                    Text("Play some video")
                }
            }
        }
        .navigationViewStyle(StackNavigationViewStyle())
    }
}
```

This is what I see

![Simulator Screen Shot - iPhone 11 Pro Max - 2022-09-17 at 09 50 41](https://user-images.githubusercontent.com/56231066/190848916-00a7db1d-c5af-417f-a36b-b5088d8057d1.png)

Is there some setting or code I am missing to get output like yours?

**Comment by kingslay** [comment]
KSPlayerManager.firstPlayerType = KSMEPlayer.self

**Comment by UnknownCoder807** [comment]
Thanks, this fixed the issue.  but has created other issues which I post about in a new post

**Comment by cdg90** [comment]
@kingslay 
Thank you your commit fixed the issue

@UnknownCoder807 thank you for the contribution!
