### ISSUE TITLE
KSMEPlayer and audio keeps playing

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#297]
Using a test app that does nothing other than play a video and an unmodified KSVideoPlayerView swift file.

Usually I have 

```
        KSPlayerManager.firstPlayerType = KSAVPlayer.self
        KSPlayerManager.secondPlayerType = KSMEPlayer.self
```

But to fix another issue with multistream m3u8's I now just use

`        KSPlayerManager.firstPlayerType = KSMEPlayer.self
`

The problem is, when I click on the X to exit the stream playback, the audio is still playing.

This is on a real iPhone device.  On the simulator it works ok.

**Comment by kingslay** [comment]
我用真机 iphone xs max 是不会有这个问题的。你的url可以给我下吗？

**Comment by UnknownCoder807** [comment]
It does it on any url that is played with KSMEPlayer

http://catchuptv.net/live/catchuptv/catchuptv/16.m3u8 has the issue

(thanks to @cdg90 for the url from other posts)

**Comment by UnknownCoder807** [comment]
I reverted my app to an earlier version that was working and it now also has the same issue.

The only difference is that I now use iOS 16 - Are you using iOS 16 @kingslay  ?

**Comment by UnknownCoder807** [comment]
I created a new iOS project, added KSPlayer via CocaPods and entered the following in ContentView.swift

```
struct ContentView: View {

    let url = "http://catchuptv.net/live/catchuptv/catchuptv/16.m3u8"
    
    let myOptions = KSOptions()

    init() {
        myOptions.isAutoPlay = true
        myOptions.videoAdaptable = true

        KSPlayerManager.firstPlayerType = KSMEPlayer.self
    }
    
    var body: some View {
        NavigationView {
            VStack {
                NavigationLink(destination: KSVideoPlayerView(url: URL(string: url)!, options: myOptions)) {
                    Text("Play some video")
                }
            }
        }
        .navigationViewStyle(StackNavigationViewStyle())
    }
}
```

The video plays, I click on the X in the top right and the video exists to the main screen, but the audio remains playing.

This is on a real device, iPhone 14 Pro Max, with iOS 16.0.1

**Comment by UnknownCoder807** [comment]
Thanks @kingslay this has fixed the issue for me.
