### ISSUE TITLE
Latest commits have broken custom KSVideoPlayerView

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#299]
I noticed that you have moved the player code from the KSVideoPlayer.swift file

This has broken my app.

I get the following errors.  Can you help?

<img width="361" alt="Screenshot 2022-09-18 at 11 09 03" src="https://user-images.githubusercontent.com/56231066/190897172-e4f456e9-c37e-4f7a-80ed-b6591a642dff.png">

<img width="1787" alt="Screenshot 2022-09-18 at 11 09 28" src="https://user-images.githubusercontent.com/56231066/190897174-c54d05b7-7814-43f8-b1bf-7837ee5cff3d.png">

**Comment by UnknownCoder807** [comment]
Thanks for the fix, all but one error is fixed

<img width="1787" alt="Screenshot 2022-09-18 at 11 52 13" src="https://user-images.githubusercontent.com/56231066/190898759-d536561a-223e-493e-8814-b48e83e7dae3.png">

**Comment by kingslay** [comment]
selectedSubtitleTrack had public . you can clean build
   @Published public var selectedSubtitleTrack: MediaPlayerTrack? {
            didSet {
                if let track = selectedSubtitleTrack {
                    playerLayer?.player?.select(track: track)
                } else {
                    oldValue?.setIsEnabled(false)
                }
            }
        }
