### ISSUE TITLE
如何同时加载视频和音轨

### ISSUE THREAD

**Issue by qdsfdhvh** [kingslay/KSPlayer#3]
```js
{
    "dash": {
        "video":["http://upos-hz-mirrorks3u.acgvideo.com/upgcxcode/18/58/77995818/77995818-1-30015.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&deadline=1551113319&gen=playurl&nbs=1&oi=3670888782&os=ks3u&platform=android&trid=925269b941bf4883ac9ec92c6ab5af4e&uipk=5&upsig=82bc845bce9f22b731b062bf83fa000f"],
        "audio":["http://upos-hz-mirrorks3u.acgvideo.com/upgcxcode/18/58/77995818/77995818-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&deadline=1551113319&gen=playurl&nbs=1&oi=3670888782&os=ks3u&platform=android&trid=925269b941bf4883ac9ec92c6ab5af4e&uipk=5&upsig=33273eaf403739d9f51304509f55589e"]
    }
}
```
如上，在线视频的画面和音频分了两个链接，请问大佬这样改如何处理？

**Comment by kingslay** [comment]
> ```js
> {
>     "dash": {
>         "video":["http://upos-hz-mirrorks3u.acgvideo.com/upgcxcode/18/58/77995818/77995818-1-30015.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&deadline=1551113319&gen=playurl&nbs=1&oi=3670888782&os=ks3u&platform=android&trid=925269b941bf4883ac9ec92c6ab5af4e&uipk=5&upsig=82bc845bce9f22b731b062bf83fa000f"],
>         "audio":["http://upos-hz-mirrorks3u.acgvideo.com/upgcxcode/18/58/77995818/77995818-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&deadline=1551113319&gen=playurl&nbs=1&oi=3670888782&os=ks3u&platform=android&trid=925269b941bf4883ac9ec92c6ab5af4e&uipk=5&upsig=33273eaf403739d9f51304509f55589e"]
>     }
> }
> ```
> 
> 如上，在线视频的画面和音频分了两个链接，请问大佬这样改如何处理？

一个正常的dash链接就是下载mpd文件，例如http://dash.edgesuite.net/akamai/bbb_30fps/bbb_30fps.mpd。你这个不是一个das播放链接

**Comment by qdsfdhvh** [comment]
上面的JSON详细大概是这样的[bilibili_player_api_videoplayurl](https://gitee.com/seduce/boke/blob/master/player_api_videoplayurl.json)。
它把视频和音频分成了两个url，我搜到一个大佬用VLC这样处理的[VideoPlayViewController.swift](https://github.com/sauvignon1989/Alibili/blob/develop/Alibili/VideoPlayViewController.swift#132)
```swift
 let video = videoArray[0]["base_url"].stringValue
let audio = json["data"]["dash"]["audio"][0]["baseUrl"].stringValue
self.videoLength = CUnsignedLongLong(json["data"]["timelength"].rawString()!)!/1000
let videoMedia = VLCMedia(url: URL(string: video)!)
self.player.media = videoMedia
self.player.addPlaybackSlave(URL(string: audio)!, type: VLCMediaPlaybackSlaveType.audio, enforce: true)
self.player.drawable = self.mediaView
self.player.play()
```

**Comment by kingslay** [comment]
> 上面的JSON详细大概是这样的[bilibili_player_api_videoplayurl](https://gitee.com/seduce/boke/blob/master/player_api_videoplayurl.json)。
> 它把视频和音频分成了两个url，我搜到一个大佬用VLC这样处理的[VideoPlayViewController.swift](https://github.com/sauvignon1989/Alibili/blob/develop/Alibili/VideoPlayViewController.swift#L132)
> 
> ```swift
> let video = videoArray[0]["base_url"].stringValue
> let audio = json["data"]["dash"]["audio"][0]["baseUrl"].stringValue
> self.videoLength = CUnsignedLongLong(json["data"]["timelength"].rawString()!)!/1000
> let videoMedia = VLCMedia(url: URL(string: video)!)
> self.player.media = videoMedia
> self.player.addPlaybackSlave(URL(string: audio)!, type: VLCMediaPlaybackSlaveType.audio, enforce: true)
> self.player.drawable = self.mediaView
> self.player.play()
> ```
> 
> 该怎么添加一个音频

目前不支持手动增加音频

**Comment by qdsfdhvh** [comment]
> > 上面的JSON详细大概是这样的[bilibili_player_api_videoplayurl](https://gitee.com/seduce/boke/blob/master/player_api_videoplayurl.json)。
> > 它把视频和音频分成了两个url，我搜到一个大佬用VLC这样处理的[VideoPlayViewController.swift](https://github.com/sauvignon1989/Alibili/blob/develop/Alibili/VideoPlayViewController.swift#L132)
> > ```swift
> > let video = videoArray[0]["base_url"].stringValue
> > let audio = json["data"]["dash"]["audio"][0]["baseUrl"].stringValue
> > self.videoLength = CUnsignedLongLong(json["data"]["timelength"].rawString()!)!/1000
> > let videoMedia = VLCMedia(url: URL(string: video)!)
> > self.player.media = videoMedia
> > self.player.addPlaybackSlave(URL(string: audio)!, type: VLCMediaPlaybackSlaveType.audio, enforce: true)
> > self.player.drawable = self.mediaView
> > self.player.play()
> > ```
> > 
> > 
> > 该怎么添加一个音频
> 
> 目前不支持手动增加音频

了解了，感谢大佬抽空解答。

**Comment by wanwe** [comment]
我也对这个feature很感兴趣，请问有计划添加这个吗?

**Comment by kingslay** [comment]
没有计划支持这个。你可以把他包装成dash的格式，这样就同时加载视频和音频的。dash格式是支持音视频分离的。

**Comment by wanwe** [comment]
> 没有计划支持这个。你可以把他包装成dash的格式，这样就同时加载视频和音频的。dash格式是支持音视频分离的。

多谢指点 ！
