### ISSUE TITLE
求助, 我想构建在iOS上使用的Player, 协议是SRT

### ISSUE THREAD

**Issue by jokester-joestar** [kingslay/KSPlayer#301]
我使用的是macbook pro, intel版
我参考了 #226 
我运行的命令是
`swift run build-FFmpeg enable-openssl enable-libsrt `
ffmpeg.log中提示, pkg-config没有找到openssl.pc
然后我查询了各种有关pkg-config添加openssl.pc的问题,始终无法解决.
我是个新手.
完全不知道该怎么做.
可以帮助我吗? 十分感谢.
关于srt启用的ffmpeg, 如果你有编译好的可以分享给我一份吗?
我的邮箱是smalldanhuang@163.com

**Comment by kingslay** [comment]
需要改 
    fileprivate let platforms = [PlatformType.ios]

**Comment by kingslay** [comment]
swift run build-FFmpeg  enable-openssl enable-libsrt  platform=ios

**Comment by jokester-joestar** [comment]
`xcrun -sdk iphoneos clang -arch arm64e -L/Users/mac/Downloads/KSPlayer-develop/Script/SSL/ios/thin/arm64e/lib -L/Users/mac/Downloads/KSPlayer-develop/Script/SRT/ios/thin/arm64e/lib -march=armv8.3-a -Wl,-dynamic,-search_paths_first -o /tmp/ffconf.3LqaIN1d/test /tmp/ffconf.3LqaIN1d/test.o
require_pkg_config libsrt srt >= 1.3.0 srt/srt.h srt_socket
check_pkg_config libsrt srt >= 1.3.0 srt/srt.h srt_socket
test_pkg_config libsrt srt >= 1.3.0 srt/srt.h srt_socket
pkg-config --exists --print-errors srt >= 1.3.0
Package libssl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libssl.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libssl', required by 'openssl', not found
ERROR: srt >= 1.3.0 not found using pkg-config`

还是没有解决这个问题....

**Comment by kingslay** [comment]
你是用最新的develop分支来运行的吗？ 我已经改成有传递PKG_CONFIG_PATH 这个环境变量了。我这边试了是可以的。我的是intel版本的
   if FileManager.default.fileExists(atPath: opensslPath.path) {
            pkgConfigPath += "\(opensslPath.path)/lib/pkgconfig:"
            ffmpegcflags.append("--enable-openssl")
        }
        let srtPath = URL.currentDirectory + ["SRT", platform.rawValue, "thin", arch.rawValue]
        if FileManager.default.fileExists(atPath: srtPath.path) {
            pkgConfigPath += "\(srtPath.path)/lib/pkgconfig:"
            ffmpegcflags.append("--enable-libsrt")
            ffmpegcflags.append("--enable-protocol=libsrt")
        }

**Comment by kingslay** [comment]
你看下对应的编译产物的目录下有没有libssl.pc 这个文件

**Comment by jokester-joestar** [comment]
谢谢你, 接下来我会尝试新的develop分支.
在这之前, 我确认了Script/SSL/ios/thin/arm64/lib/pkgconfig下有openssl.pc
但不知道为什么, pkgconfig像个盲人.....
尝试后我会回复.

**Comment by jokester-joestar** [comment]
十分感谢, 看起来似乎是成功了.
我该怎么做才能使用新生成的framework呢?
我想验证下srt协议是否可以播放.确保我真的成功了.

**Comment by kingslay** [comment]
直接找一个srt协议的播放链接在demo里面进行播放就可以了。

**Comment by jokester-joestar** [comment]
当我打开Demo工程并且build时, 会出现错误.
`
Showing All Errors Only
Ld /Users/mac/Library/Developer/Xcode/DerivedData/Demo-ashngfkagjzywjgdsvymjettjyrg/Build/Products/Debug-iphoneos/demo-iOS.app/demo-iOS normal (in target 'demo-iOS' from project 'demo-iOS')
    cd /Users/mac/Downloads/KSPlayer-develop/Demo/demo-iOS
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios13.0 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.0.sdk -L/Users/mac/Library/Developer/Xcode/DerivedData/Demo-ashngfkagjzywjgdsvymjettjyrg/Build/Intermediates.noindex/EagerLinkingTBDs -L/Users/mac/Library/Developer/Xcode/DerivedData/Demo-ashngfkagjzywjgdsvymjettjyrg/Build/Products/Debug-iphoneos -L/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.0.sdk/usr/lib/swift -F/Users/mac/Library/Developer/Xcode/DerivedData/Demo-ashngfkagjzywjgdsvymjettjyrg/Build/Intermediates.noindex/EagerLinkingTBDs -F/Users/mac/Library/Developer/Xcode/DerivedData/Demo-ashngfkagjzywjgdsvymjettjyrg/Build/Products/Debug-iphoneos -F/Users/mac/Library/Developer/Xcode/DerivedData/Demo-ashngfkagjzywjgdsvymjettjyrg/Build/Products/Debug-iphoneos/FFmpeg-iOS -F/Users/mac/Library/Developer/Xcode/DerivedData/Demo-ashngfkagjzywjgdsvymjettjyrg/Build/Products/Debug-iphoneos/KSPlayer-iOS -F/Users/mac/Downloads/KSPlayer-develop/Demo/demo-iOS/../Pods/../../Sources -F/Users/mac/Library/Developer/Xcode/DerivedData/Demo-ashngfkagjzywjgdsvymjettjyrg/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/FFmpeg/FFmpeg -F/Users/mac/Library/Developer/Xcode/DerivedData/Demo-ashngfkagjzywjgdsvymjettjyrg/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/OpenSSL/OpenSSL -filelist /Users/mac/Library/Developer/Xcode/DerivedData/Demo-ashngfkagjzywjgdsvymjettjyrg/Build/Intermediates.noindex/demo-iOS.build/Debug-iphoneos/demo-iOS.build/Objects-normal/arm64/demo-iOS.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/mac/Library/Developer/Xcode/DerivedData/Demo-ashngfkagjzywjgdsvymjettjyrg/Build/Intermediates.noindex/demo-iOS.build/Debug-iphoneos/demo-iOS.build/Objects-normal/arm64/demo-iOS_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-link-runtime -L/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/mac/Library/Developer/Xcode/DerivedData/Demo-ashngfkagjzywjgdsvymjettjyrg/Build/Intermediates.noindex/demo-iOS.build/Debug-iphoneos/demo-iOS.build/Objects-normal/arm64/demo_iOS.swiftmodule -ObjC -lbz2 -liconv -lxml2 -lz -framework AVFoundation -framework AudioToolbox -framework FFmpeg -framework Foundation -framework KSPlayer -framework Libavcodec -framework Libavfilter -framework Libavformat -framework Libavutil -framework Libcrypto -framework Libssl -framework Libswresample -framework Libswscale -framework UIKit -framework VideoToolbox -weak_framework MetalKit -framework Pods_demo_iOS -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/mac/Library/Developer/Xcode/DerivedData/Demo-ashngfkagjzywjgdsvymjettjyrg/Build/Intermediates.noindex/demo-iOS.build/Debug-iphoneos/demo-iOS.build/Objects-normal/arm64/demo-iOS_dependency_info.dat -o /Users/mac/Library/Developer/Xcode/DerivedData/Demo-ashngfkagjzywjgdsvymjettjyrg/Build/Products/Debug-iphoneos/demo-iOS.app/demo-iOS

Undefined symbols for architecture arm64:
  "_srt_accept", referenced from:
      _libsrt_open in Libavformat(libsrt.o)
  "_srt_bind", referenced from:
      _libsrt_open in Libavformat(libsrt.o)
  "_srt_cleanup", referenced from:
      _libsrt_open in Libavformat(libsrt.o)
      _libsrt_close in Libavformat(libsrt.o)
  "_srt_close", referenced from:
      _libsrt_open in Libavformat(libsrt.o)
      _libsrt_close in Libavformat(libsrt.o)
  "_srt_connect", referenced from:
      _libsrt_open in Libavformat(libsrt.o)
  "_srt_create_socket", referenced from:
      _libsrt_open in Libavformat(libsrt.o)
  "_srt_epoll_add_usock", referenced from:
      _libsrt_open in Libavformat(libsrt.o)
  "_srt_epoll_create", referenced from:
      _libsrt_open in Libavformat(libsrt.o)
  "_srt_epoll_release", referenced from:
      _libsrt_open in Libavformat(libsrt.o)
      _libsrt_close in Libavformat(libsrt.o)
  "_srt_epoll_wait", referenced from:
      _libsrt_network_wait_fd_timeout in Libavformat(libsrt.o)
  "_srt_getlasterror", referenced from:
      _libsrt_open in Libavformat(libsrt.o)
      _libsrt_read in Libavformat(libsrt.o)
      _libsrt_write in Libavformat(libsrt.o)
      _libsrt_network_wait_fd_timeout in Libavformat(libsrt.o)
  "_srt_getlasterror_str", referenced from:
      _libsrt_open in Libavformat(libsrt.o)
      _libsrt_read in Libavformat(libsrt.o)
      _libsrt_write in Libavformat(libsrt.o)
      _libsrt_network_wait_fd_timeout in Libavformat(libsrt.o)
  "_srt_getsockopt", referenced from:
      _libsrt_open in Libavformat(libsrt.o)
  "_srt_listen", referenced from:
      _libsrt_open in Libavformat(libsrt.o)
  "_srt_recvmsg", referenced from:
      _libsrt_read in Libavformat(libsrt.o)
  "_srt_sendmsg", referenced from:
      _libsrt_write in Libavformat(libsrt.o)
  "_srt_setsockopt", referenced from:
      _libsrt_open in Libavformat(libsrt.o)
  "_srt_startup", referenced from:
      _libsrt_open in Libavformat(libsrt.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Undefined symbol: _srt_accept

Undefined symbol: _srt_bind

Undefined symbol: _srt_cleanup

Undefined symbol: _srt_close

Undefined symbol: _srt_connect

Undefined symbol: _srt_create_socket

Undefined symbol: _srt_epoll_add_usock

Undefined symbol: _srt_epoll_create

Undefined symbol: _srt_epoll_release

Undefined symbol: _srt_epoll_wait

Undefined symbol: _srt_getlasterror

Undefined symbol: _srt_getlasterror_str

Undefined symbol: _srt_getsockopt

Undefined symbol: _srt_listen

Undefined symbol: _srt_recvmsg

Undefined symbol: _srt_sendmsg

Undefined symbol: _srt_setsockopt

Undefined symbol: _srt_startup

`




详细如下:
[Build demo-iOS_2022-09-26T18-02-07.txt](https://github.com/kingslay/KSPlayer/files/9645179/Build.demo-iOS_2022-09-26T18-02-07.txt)


之前在运行`swift run build-FFmpeg enable-openssl enable-libsrt platform=ios`我在的shell输入如下:
[shell_log.txt](https://github.com/kingslay/KSPlayer/files/9645197/shell_log.txt)


我不明白哪里出错了.....

**Comment by jokester-joestar** [comment]
是的, 出现这个错误时, 我添加Libsrt.xcframework到Pods→FFmpeg→TARGETS→FFmpeg-iOS→Frameworks and Libraries中
但没有效果,之后我又将他添加到了TARGETS→demo-iOS中, 也没有效果.

**Comment by jokester-joestar** [comment]
我接着尝试了pods的方式添加libsrt
修改文件`/Users/mac/Downloads/KSPlayer-develop/Demo/Pods/Local Podspecs/FFmpeg.podspec.json`
在subspecs→vendored_frameworks中添加`"Sources/Libsrt.xcframework"`
并执行pod update
这次OpenSSL不见了.
我想按照预期添加Libsrt.xcframework
如果你有好的办法, 可以分享给我吗?

**Comment by jokester-joestar** [comment]
我自己创建了一个工程, 逐步引入xframework和KSPlayer等等.
发现错误并不是复杂的引用关系造成的.
似乎是build libsrt.xframework的时候, arm64失败了.

**Comment by kingslay** [comment]
你试着build 一下

**Comment by kingslay** [comment]
模拟器是可以的吗？

**Comment by jokester-joestar** [comment]
我的产物似乎没有包含模拟器.

Showing All Errors Only
/Users/mac/Downloads/KSPlayer-develop/Sources/Libcrypto.xcframework:1:1: While building for iOS Simulator, no library for this platform was found in '/Users/mac/Downloads/KSPlayer-develop/Sources/Libcrypto.xcframework'.

/Users/mac/Downloads/KSPlayer-develop/Sources/Libavcodec.xcframework:1:1: While building for iOS Simulator, no library for this platform was found in '/Users/mac/Downloads/KSPlayer-develop/Sources/Libavcodec.xcframework'.

/Users/mac/Downloads/KSPlayer-develop/Sources/Libswresample.xcframework:1:1: While building for iOS Simulator, no library for this platform was found in '/Users/mac/Downloads/KSPlayer-develop/Sources/Libswresample.xcframework'.

/Users/mac/Downloads/KSPlayer-develop/Sources/Libssl.xcframework:1:1: While building for iOS Simulator, no library for this platform was found in '/Users/mac/Downloads/KSPlayer-develop/Sources/Libssl.xcframework'.

/Users/mac/Downloads/KSPlayer-develop/Sources/Libavformat.xcframework:1:1: While building for iOS Simulator, no library for this platform was found in '/Users/mac/Downloads/KSPlayer-develop/Sources/Libavformat.xcframework'.

/Users/mac/Downloads/KSPlayer-develop/Sources/Libavutil.xcframework:1:1: While building for iOS Simulator, no library for this platform was found in '/Users/mac/Downloads/KSPlayer-develop/Sources/Libavutil.xcframework'.

/Users/mac/Downloads/KSPlayer-develop/Sources/Libswscale.xcframework:1:1: While building for iOS Simulator, no library for this platform was found in '/Users/mac/Downloads/KSPlayer-develop/Sources/Libswscale.xcframework'.

/Users/mac/Downloads/KSPlayer-develop/Sources/Libavfilter.xcframework:1:1: While building for iOS Simulator, no library for this platform was found in '/Users/mac/Downloads/KSPlayer-develop/Sources/Libavfilter.xcframework'.

/Users/mac/Downloads/KSPlayer-develop/Sources/Libcrypto.xcframework:1:1: While building for iOS Simulator, no library for this platform was found in '/Users/mac/Downloads/KSPlayer-develop/Sources/Libcrypto.xcframework'.

/Users/mac/Downloads/KSPlayer-develop/Sources/Libavcodec.xcframework:1:1: While building for iOS Simulator, no library for this platform was found in '/Users/mac/Downloads/KSPlayer-develop/Sources/Libavcodec.xcframework'.

/Users/mac/Downloads/KSPlayer-develop/Sources/Libswresample.xcframework:1:1: While building for iOS Simulator, no library for this platform was found in '/Users/mac/Downloads/KSPlayer-develop/Sources/Libswresample.xcframework'.

/Users/mac/Downloads/KSPlayer-develop/Sources/Libssl.xcframework:1:1: While building for iOS Simulator, no library for this platform was found in '/Users/mac/Downloads/KSPlayer-develop/Sources/Libssl.xcframework'.

/Users/mac/Downloads/KSPlayer-develop/Sources/Libavformat.xcframework:1:1: While building for iOS Simulator, no library for this platform was found in '/Users/mac/Downloads/KSPlayer-develop/Sources/Libavformat.xcframework'.

/Users/mac/Downloads/KSPlayer-develop/Sources/Libavutil.xcframework:1:1: While building for iOS Simulator, no library for this platform was found in '/Users/mac/Downloads/KSPlayer-develop/Sources/Libavutil.xcframework'.

/Users/mac/Downloads/KSPlayer-develop/Sources/Libswscale.xcframework:1:1: While building for iOS Simulator, no library for this platform was found in '/Users/mac/Downloads/KSPlayer-develop/Sources/Libswscale.xcframework'.

/Users/mac/Downloads/KSPlayer-develop/Sources/Libavfilter.xcframework:1:1: While building for iOS Simulator, no library for this platform was found in '/Users/mac/Downloads/KSPlayer-develop/Sources/Libavfilter.xcframework'.


对于上面我的反馈, 我又尝试使用lipo合并arm64和arm64e两个libsrt.a
用传统的方式引入到工程里.
接下来又按照错误提示添加了libc++, libz, libxml2
Xcode Build顺利的完成了.
但执行完Xcode Run之后, 程序崩溃了.似乎是framework的错误.
这些xframework可以作为独立的item直接使用吗?


`dyld: Symbol not found: __ZTTNSt3__118basic_stringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE
  Referenced from: /private/var/containers/Bundle/Application/FA33DF31-B500-4B75-BF97-04888D39B174/SRTPlayer.app/SRTPlayer
  Expected in: /usr/lib/libc++.1.dylib
 in /private/var/containers/Bundle/Application/FA33DF31-B500-4B75-BF97-04888D39B174/SRTPlayer.app/SRTPlayer
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib:/usr/lib/libMTLCapture.dylib`

**Comment by jokester-joestar** [comment]
由于我的环境看起来有点糟糕.
所以我将Build Phases→Link Binary with Libraries中的每一项framework都改成了Optional
`Libcrypto.xcframework
libc++.1.tbd
libz.tbd
libc++.tbd
Libavcodec.xcframework
libsrt.a
Libswresample.xcframework
Libssl.xcframework
Libavformat.xcframework
Libavutil.xcframework
Libswscale.xcframework
Libavfilter.xcframework
libxml2.tbd`
我在这里留下记录, 希望会对其他人有帮助.

我的简易代码就像中文.md中那样.
我测试了http://xxxx.mp4和rtmp两种情况, 看起来很棒.
当我测试到srt协议时, 他崩溃在了MEPlayerItem.swift的170行

KSPlayer_MEPlayerItem_open (4): EXC_BAD_ACCESS (code=1, address=0x8)

log如下:

`2022-09-27 14:55:54.399744+0900 SRTPlayer[22020:295082] [TableView] Warning once only: UITableView was told to layout its visible cells and other contents without being in the view hierarchy (the table view or one of its superviews has not been added to a window). This may cause bugs by forcing views inside the table view to load and perform layout without accurate information (e.g. table view bounds, trait collection, layout margins, safe area insets, etc), and will also cause unnecessary performance overhead due to extra layout passes. Make a symbolic breakpoint at UITableViewAlertForLayoutOutsideViewHierarchy to catch this in the debugger and see what caused this to occur, so you can avoid this action altogether if possible, or defer it until the table view has been added to a window. Table view: <UITableView: 0x107095400; frame = (375 0; 360 812); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x281815590>; animations = { bounds.origin=<CABasicAnimation: 0x28166a260>; bounds.size=<CABasicAnimation: 0x28166a2a0>; position=<CABasicAnimation: 0x28166a300>; }; layer = <CALayer: 0x281669600>; contentOffset: {0, 0}; contentSize: {360, 44}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <SRTPlayer.KSSubtitleView: 0x10a4512e0; baseClass = UIControl; frame = (0 0; 375 812); hidden = YES; userInteractionEnabled = NO; layer = <CALayer: 0x281669b40>>>
KSPlayer: KSAVPlayer.swift:391 prepareToPlay() | prepareToPlay SRTPlayer.KSAVPlayer
2022-09-27 14:55:54.552345+0900 SRTPlayer[22020:295269] NSURLConnection finished with error - code -1002
2022-09-27 14:55:54.578580+0900 SRTPlayer[22020:295260] NSURLConnection finished with error - code -1002
2022-09-27 14:55:54.777251+0900 SRTPlayer[22020:295082] Metal GPU Frame Capture Enabled
2022-09-27 14:55:54.777479+0900 SRTPlayer[22020:295082] Metal API Validation Enabled
KSPlayer: KSPlayerLayer.swift:156 player | player is <SRTPlayer.KSMEPlayer: 0x28247af40>
KSPlayer: KSMEPlayer.swift:311 prepareToPlay() | prepareToPlay <SRTPlayer.KSMEPlayer: 0x28247af40>`

**Comment by jokester-joestar** [comment]
关于我的srt推流获取.
我使用的是本地推流.
https://github.com/Edward-Wu/srt-live-server

**Comment by jokester-joestar** [comment]
很抱歉, 没有最新的进展了.
目前, 我无法再进行下去.
我甚至不知道错在哪里.
是我的ffmpeg编译出错了吗?

**Comment by kingslay** [comment]
> 很抱歉, 没有最新的进展了. 目前, 我无法再进行下去. 我甚至不知道错在哪里. 是我的ffmpeg编译出错了吗?
你可以试着用swiftpm来引用KSPlayer。我的Package.swift支持了srt了。你只要把里面注释掉的代码打开就可以了
