### ISSUE TITLE
如何手动遍历字幕呢

### ISSUE THREAD

**Issue by csmagics** [kingslay/KSPlayer#304]
通过 enableSubtitle 方法貌似只能通过时间查询，可以加一个访问原始字幕数组的方法吗

**Comment by csmagics** [comment]
@kingslay 我要对字幕进行翻译，如果时时翻译我发现有时候速度来不及，需要提前处理好

**Comment by csmagics** [comment]
@kingslay 其实只想用于本地视频，或者那种分离的字幕可以直接下载的，至于那种需要持续播放获取的不支持

**Comment by kingslay** [comment]
分离视频的话，那可以从KSSubtitle.part获取到所有的字幕

**Comment by csmagics** [comment]
@kingslay 可我发现     func enableSubtitle(completion: @escaping (Result<KSSubtitleProtocol, NSError>) -> Void)
返回都是 KSSubtitleProtocol ，拿不到那个 KSSubtitle.part
