### ISSUE TITLE
如果能从iOS11开始支持, 相信这个库可以大有作为

### ISSUE THREAD

**Issue by MQL9011** [kingslay/KSPlayer#306]

**Comment by Kimentanm** [comment]
没有必要……

**Comment by kingslay** [comment]
> _No description provided._

最开始就是从iOS11开始支持的。但是因为现在都到iOS16了。所以就升级到了iOS13了。

**Comment by kingslay** [comment]
@MQL9011 你可以用tag 1.3.0。 这个是支持iOS11的。
