### ISSUE TITLE
Enabled framerate matching and dynamic range matching and getting warning

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#307]
I enabled framerate and dynamic range matching for my app, using the following code

```
class meOptions: KSOptions {
        #if os(tvOS)
        override open func preferredDisplayCriteria(refreshRate: Float, videoDynamicRange: Int32) -> AVDisplayCriteria? {
            AVDisplayCriteria(refreshRate: refreshRate, videoDynamicRange: videoDynamicRange)
        }
        #endif
}
    
let myOptions = meOptions()
```

When archiving and submitting my app to Apple for testflight I get the following warning 

`The app references non-public selectors in Payload/XXXXX.app/XXXXXX: initWithRefreshRate:videoDynamicRange:`

The app is still available for download, but I'm worried it will be rejected by Apple for using private selectors when the time comes to submit it for release.

edit :

Could it be related to this?

https://developer.apple.com/documentation/avfoundation/avasset/2935636-preferreddisplaycriteria?language=swift

**Comment by UnknownCoder807** [comment]
Sorry @kingslay still getting this warning.

**Comment by kingslay** [comment]
是的，我提交的代码是解决 #308 这个bug。你可以看下是否可以审核通过。不能通过的话，那就只能把代码删除掉
```
@interface AVDisplayCriteria ()
@property(readonly) int videoDynamicRange;
@property(readonly, nonatomic) float refreshRate;
- (id)initWithRefreshRate:(float)arg1 videoDynamicRange:(int)arg2;
@end

```

**Comment by UnknownCoder807** [comment]
Thanks, I can't submit it yet as the app is nowhere near ready.  I'll come back to this thread when/if there is an issue with Apple in the future.
