### ISSUE TITLE
Framerate Matching & Match Dynamic Range issue

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#308]
My app uses Framerate Matching & Match Dynamic Range.  When KSPlayer is called to play the media, it correctly switches the Framerate & Dynamic Range to the correct values.

However, when playback stops, the original Framerate & Dynamic Range settings are not restored.

Is this a KSPlayer or my App issue ?  thanks

**Comment by kingslay** [comment]
fix by 1b2d2e12d0485dce853257a8020b43337e989b24
