### ISSUE TITLE
Ksplayer does not resume playing when AppleTV is in screen saver mode

### ISSUE THREAD

**Issue by cdg90** [kingslay/KSPlayer#310]
Hello Kingslay,

in your untouched swiftUI video player, the issue happens this way:

1- I pause the video
2- AppleTV opens the screen saver.
3- when I hit play, the stream does not resume

My AppleTV output settings are: 4K + HDR.

The content I am playing is SDR.

I sent to you the screen record link and the video stream link via e-mail

**Comment by kingslay** [comment]
不好意思。我只有tvos的模拟器，没有真机。在模拟器上无法显示屏保

**Comment by kingslay** [comment]
你可以试下demo-tvOS 这个demo。看下会不会有这个问题，如果没有的话，那就是swfitui的问题了

**Comment by cdg90** [comment]
Sorry @kingslay it was an issue with a rogue .id(UUID()) in my code.

Issue solved
