### ISSUE TITLE
Dropped frames in 4K UHD .mkv file playback

### ISSUE THREAD

**Issue by cdg90** [kingslay/KSPlayer#311]
Hello Kingslay,

in your untouched swiftUI video player, I have dropped frames when I try to play a 4K UHD .mkv file.

When I play the same video link in VLC tvos version, the video is smooth.
Also, when I play the video link with a tvos program that uses MPV player, the video is smooth. (The colour output is not correct, but the video is smooth).

I sent you the video link via e-mail

Thank you

**Comment by skrew** [comment]
Hi,

It's almost good, but i still see some lags every seconds, looks like a problem with the AFR.

I can provide you a link to a video where the problem is easy to see (mail ?)

**Comment by fedalcode** [comment]
@skrew 
He checks regularly his e-mail (Email : kingslay@icloud.com)
When I send an e-mail I always include the issue title and the #

**Comment by skrew** [comment]
Thanks, mail sent

**Comment by skrew** [comment]
It's ok for me on this video, thanks 👍🏻
