### ISSUE TITLE
Subtitles on Live TV

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#312]
I am having an issue with subtitles on a live tv stream.

A filename.ts stream does not display anything at all.  A filename.m3u8 does display something but its out of sync with the video and audio.

The exact same code playing a filename.mkv file displays the subtitles perfectly.

I am using SwiftUI and the SwiftUI player file you provide.
When playing filename.m3u8 and enabling subtitles, the aspect ratio of the video is broken, it’s too zoomed in.  

I can provide you with a live tv streak link via email if you require one.

The issue is on both iOS and tvOS. Thanks

**Comment by kingslay** [comment]
好的 你发给我下 我看下

**Comment by UnknownCoder807** [comment]
Thanks.

On tvOS subtitles work although they only display in a fraction of the screen width.

On IOS, there are two issues.  One is the size and positioning of the subtitle is wrong.  The other is, the aspect ratio of the video seems to zoom in. which I think affects the subtitles position

![IMG_0035](https://user-images.githubusercontent.com/56231066/193453609-9410155a-5b7f-4dfb-9f46-265daf0b83a3.png)

**Comment by kingslay** [comment]
@UnknownCoder807 视频的比率是因为VideoSubtitleView里面的 Image(uiImage: image)
                    .scaledToFit()布局有问题。如果限制了最大宽度就不会有问题了。我还没想到在swiftui里面要如何让图片的宽度和高度不会超过屏幕的宽度和高度。如果你找到方法的话，可以发给我

**Comment by UnknownCoder807** [comment]
Thanks again.  There is an issue where the subtitles don't appear for around 1 -2 minutes.  When you do, when there is a single line of text, there is green bar behind it.

Also, the timing seems to be out.  I think its around 1 second too quick compared to the video.

Text is still cut off at the top like in my previous post. Not every time, but it does happen.  thanks

![Simulator Screen Shot - Apple TV 4K (2nd generation) - 2022-10-02 at 16 52 25](https://user-images.githubusercontent.com/56231066/193463694-494d3b99-c3fc-4629-a4b8-f4994866e51d.png)

**Comment by kingslay** [comment]
you can try clean build and set KSOptions.subtitleDelay = 1
