### ISSUE TITLE
KSVideoPlayerView And KSOptions()

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#313]
With a video playing within KSVideoPlayerView Is it possible to modify the options variable (KSOptions()) in real time?  I’d like to change options.subtitleDelay for example and have the player respond to it in real time.  Thanks.

**Comment by UnknownCoder807** [comment]
Thanks, that was very useful.

On a related note, is it possible to update VideoSubtitleView() from within VideoSettingView()?

Say I wanted to have a subtitle colour option in VideoSettingView(), is it possible to have the VideoSubtitleView() update in realtime when the colour was changed? thanks

**Comment by kingslay** [comment]
是可以的，你直接往SubtitleModel里面加一个colour option就可以了

**Comment by UnknownCoder807** [comment]
Sorry I don't understand.  I just need to be able to change some variables in the SubtitleView() from the VideoSettingsView()

```
} else if let text = model.text {
                Text(AttributedString(text))
                    .multilineTextAlignment(.center)
                    .font(currentFont)
                    .foregroundColor(currentTextColour).shadow(color: .black.opacity(0.9), radius: 1, x: 1, y: 1)
                    .padding(.bottom, CGFloat(positionFromBottom))
}
```

Do I need to do this with Bindings.  Or is there a much simpler way.  I tried with bindings, but the foregroundColor() of the Text() didn't update.  Does the SubtitleView() need to reload?  Sorry for the questions.  Thanks
