### ISSUE TITLE
Adding readNextFrame and readPreviousFrame

### ISSUE THREAD

**Issue by skrew** [kingslay/KSPlayer#314]
Hi,

In my app, i'd added a way to let the user to read something frame by frame.
It would be nice to have a function to read the next / previous frame when the player state is "paused"

Thanks

**Comment by kingslay** [comment]
获取NextFrame和PreviousFrame是为了让用户可以对比下画面吗？或是要用在什么场景呢？

**Comment by skrew** [comment]
No, just a player behavior, look this video:

https://skrobs.com/player_fbf.mov

**Comment by kingslay** [comment]
readNextFrame 是可以的。但是readPreviousFrame还不大行，因为PreviousFrame在被播放之后，就可能被丢弃了。需要自己在保存下历史的CVPixelBuffer。这样会导致内存增加太多 @skrew

**Comment by skrew** [comment]
Thanks but `readNextFrame()` is not accessible ?

**Comment by kingslay** [comment]
他们都是public的方法的啊。你需要进行转换下，把MediaPlayerProtocol 转为KSMEPlayer

**Comment by skrew** [comment]
Ok it's works, thanks 👍🏻
