### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#315]
On the latest commit the swiftui KSVideoPlayerView() is broke when building.

<img width="1525" alt="Screenshot 2022-10-06 at 08 16 48" src="https://user-images.githubusercontent.com/56231066/194242269-e3a4deef-a7e7-4801-aa91-707c2439e661.png">

**Comment by kingslay** [comment]
我已经修复好了。你在更新下代码

**Comment by UnknownCoder807** [comment]
I am on the latest commit

da679461108abab24272cc1f07e98fe40de7cae4

**Comment by UnknownCoder807** [comment]
Nevermind, there is a newer commit since I posted.

**Comment by kingslay** [comment]
e8b0498ab0584c93ac92d93fc920ec5aadb7f55a
