### ISSUE TITLE
Logging warning ?

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#317]
When I have auto deinterace enabled I see the following in my debug logs several times a second, which means hundreds/thousands of instances.

`KSPlayer: MEPlayerItem.swift:119 init(url:options:) | Impossible to convert between the formats supported by the filter 'in' and the filter 'auto_scale_0'
`
Something to fix or just ignore?

**Comment by skrew** [comment]
Something to fix, it's spam the logs at every frames ! :)

**Comment by kingslay** [comment]
如果用到videoFilters 需要把hardwareDecode设置为false
