### ISSUE TITLE
Auto deinterlace/ 4K UHD video out of sync

### ISSUE THREAD

**Issue by fedalcode** [kingslay/KSPlayer#319]
Hello Kingslay,
For auto deinterlace, I use “myOptions.autoDeInterlace = true” and the code was working but now, it seems that it does not work anymore.

In fact,
1- in real 4K UHD live streams, the streams are encoded this way: h256 50/60P. Due to that real 4K UGH streams are not interlaced.

2- because the stream (link sent via e-mail) is not interlaced, Ksplayer should “say”; “do not use deinterlace filter” for this case

Instead, here, because the player uses deinterlace filter, there are not enough CPU power to play the video smooth enough

I also sent you a screenshot of the deinterlace options of the app.

**Comment by kingslay** [comment]
我用你发给我的ulr，判断出来的是progressive。
但是最好也不要用autoDeInterlace ，因为用filter的话，就要把hardwareDecode设置为false。这对性能有比较大的影响。我现在改成用视频的meta信息来进行判断。虽然这个不会非常的准。但是我猜测vlc也是用这个判断方式的

class MEOptions: KSOptions {
    override func process(assetTrack: MediaPlayerTrack) {
        if assetTrack.mediaType == .video {
            if [FFmpegFieldOrder.bb, .bt, .tt, .tb].contains(assetTrack.fieldOrder){
                videoFilters = "yadif=mode=0:parity=auto:deint=0"
                hardwareDecode = false
            }
        }
    }

**Comment by fedalcode** [comment]
thank you for your guidance
