### ISSUE TITLE
overriding pressedEnded

### ISSUE THREAD

**Issue by snappycode1** [kingslay/KSPlayer#32]
I am trying to allow keyboard control using the pressesEnded func.  It works on vlckit but on KSPlayer the keyboard presses are ignored. I am also using tvOS.  Keyboard control is vital for allowing universal remotes to work as they send keypresses.

Here is my code

```
override func pressesEnded(_ presses: Set<UIPress>, with event: UIPressesEvent?) {
        for press in presses {
            if (press.type == .select) {
                // Select is pressed
                print("select pressed")
            }  else if (press.type == .downArrow) {
                print("down arrow pressed")
            }
        }
}

```
How can I make this work please?

**Comment by kingslay** [comment]
you can user pressesBegan

**Comment by snappycode1** [comment]
pressesBegan doesn't work either.

**Comment by snappycode1** [comment]
ok, I have managed to get pressesEnded to at least be recognised but there is a major problem.

The press type is not recognised for most keys.  Pressing right arrow works but no other directional keys work.

This is a problem only in KSPlayer as I use the exact same code using VLCKit as the media player and it works perfectly.

This is using tvOS but I suspect the same issue is there with iPad + external keyboard.

```
    override func pressesEnded(_ presses: Set<UIPress>, with event: UIPressesEvent?) {
        print("got here")
        guard let press = presses.first else { return }

        if press.type == .downArrow {
            print("down arrow pressed")
        }  else {
            super.pressesEnded(presses, with: event)
        }
    }

```

**Comment by snappycode1** [comment]
ok, I have found the issue and I wonder if it's something you will implement into the core code ?

in Pods/KSPlayer/Sources/KSPlayer/Video/VideoPlayerView.swift

Change the pressesBegan func to the following :

```
    #if !os(macOS) && !targetEnvironment(macCatalyst)
//    override open func pressesBegan(_ presses: Set<UIPress>, with _: UIPressesEvent?) {
    override open func pressesBegan(_ presses: Set<UIPress>, with event: UIPressesEvent?) {
        guard let presse = presses.first else {
            return
        }
        switch presse.type {
        case .playPause:
            if playerLayer.state.isPlaying {
                pause()
            } else {
                play()
            }
//        default: break
        default : super.pressesBegan(presses, with: event)
        }
    }
    #endif

```

As you can see I just changed 2 lines.  This allows pressesEnded to work properly...

**Comment by kingslay** [comment]
OK. thank you. i will change it

**Comment by snappycode1** [comment]
thanks
