### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by skrew** [kingslay/KSPlayer#320]
Hi,

There is a memory leak (tested on tvOS), you can see it in tracy player, just play the Al jazeera English (1080p)) and you can see a leak of about 0.2mo / second to 1mo/s according to some streams.

Application will crash with "out of memory error" after 10-20 minutes

Edit: The Al jazeera sample is not a good stream to test, i will send to you a better link, where it's more visible

**Comment by kingslay** [comment]
是的,这个链接是会导致内存泄漏.我用ffplay和iina试了都会有这个问题,所以我猜测这个是ffmepg内部的问题. 我会跟踪下这个问题

**Comment by JUSTINMKAUFMAN** [comment]
Great library @kingslay! Unfortunately I'm also running into this issue. Any idea what's going on?

**Comment by fedalcode** [comment]
@kingslay ffmpeg has been updated to 5.1.2
Perhaps this update solves the memory leak issue?

https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff/eacfcbae690f914a4b1b4ad06999f138540cc3d8

**Comment by kingslay** [comment]
我现在就是用5.1.2版本的

**Comment by fedalcode** [comment]
@kingslay It looks like the memory leak issue is solved.
@skrew can you also please check with the streams you have that causes the memory leak?

**Comment by matteogobbi** [comment]
Has this been fixed?
I also can see a memory leak: the audio keeps playing although the player has been closed, which indicates it has not been deallocated.

I used multiple players under my app in production, and they are memory leak free. So I think there's some leak coming specifically from this library.

Thank you!

**Comment by kingslay** [comment]
> Has this been fixed? I also can see a memory leak: the audio keeps playing although the player has been closed, which indicates it has not been deallocated.
> 
> I used multiple players under my app in production, and they are memory leak free. So I think there's some leak coming specifically from this library.
> 
> Thank you!

你在demo里面可以复现这个问题吗？有对应的链接。我们目前遇到的内存泄漏是ffmpeg里面的对象没有释放掉。但是音频是结束了。所以你这个应该是另外一个问题

**Comment by matteogobbi** [comment]
It might be not related then. Thx.

**Comment by matteogobbi** [comment]
Although doing another test, it seems my player wrapper is deallocated, but the `KSPlayerLayer` remains allocated

<img width="887" alt="Screenshot 2023-04-05 at 11 57 17 PM" src="https://user-images.githubusercontent.com/1998171/230295855-1208f2f0-5964-46fa-bbea-ee12ca7ac072.png">

**Comment by matteogobbi** [comment]
Please see this ^

**Comment by kingslay** [comment]
我看demo里面的IOSVideoPlayerView是可以进行释放的。你不是继承IOSVideoPlayerView吗？

**Comment by matteogobbi** [comment]
Yes that's what I did. There must be something however that keeps the layer allocated. My wrapper though is deallocated.
