### ISSUE TITLE
Subtitle take 5-10 secs to display

### ISSUE THREAD

**Issue by skrew** [kingslay/KSPlayer#321]
Hi,

After selected an Subtitle track, it take 5-10 seconds to start displaying.
I'm not sure if it's a problem with my app, as tracy player don't be able to select track and get out of the menu without stopping the video

Thanks

**Comment by kingslay** [comment]
如果是图片字幕的话 那是需要等一会儿才能显示的 文字字幕不会有这个问题。这个是跟vlc对齐的。如果图片字幕想要马上就显示的话 那就需要进行seek

**Comment by skrew** [comment]
I still have the problem with bitmap subs.
When i'm playing a file or select a sub, it start displaying after 30-35 seconds.
But, if i seek in the file, they appear immediately.

For example, with the problem:
- Start a video with selected sub
- Wait 30-35 seconds, sub start displaying.

Workaround:
- Start a video with selected sub
- Immediately seek backward to start: subs appears immediately.

For info, it's working fine with subs text.

for the users, subs simply doesn't works, as no one wait 30 seconds to get the subs displayed.

**Comment by kingslay** [comment]
这个是已知问题，如果想要图片字幕马上就加载出来的话，那就需要seek一下。就会卡一下。如果你想要这个功能的话，那我可以做成一个开关。
