### ISSUE TITLE
rtsp链接播放时会崩溃

### ISSUE THREAD

**Issue by Kimentanm** [kingslay/KSPlayer#322]
发生错误的位置定位在 MEPlayerItem 中的 reading()方法的pb对象为空
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/25970284/196595962-45d919a3-736f-411d-96ab-a6ce34374e32.png">

我搭建了一个测试使用的公网可访问的rtsp链接：rtsp://42.194.130.113:8554/test
你可以使用它进行测试

**Comment by kingslay** [comment]
rtsp://42.194.130.113:8554/test: Server returned 404 Not Found

**Comment by Kimentanm** [comment]
刚挂了，现在可以再试试

**Comment by Kimentanm** [comment]
还有，我发现注释这一行之后，播放rtsp链接会导致内存溢出
初步定为是MEPlayerItem.swift文件中的 av_log_set_callback 导致的

**Comment by kingslay** [comment]
最新的代码我修复了pb为空的问题了。但是我用demo TracyPlayer试着播放你的链接。没有看到内存溢出。你是demo来进行播放的吗？是用demo里面的macos吗？还是用那个

**Comment by Kimentanm** [comment]
我用demo试试
