### ISSUE TITLE
Orientation issue

### ISSUE THREAD

**Issue by shivam6900** [kingslay/KSPlayer#323]
when i click on full screen player goes in landscape mode with full screen and then click to back then it's goes to actual size but when we again trying to go it full screen it moves in landscape mode but not in full screen only the framesize is as it was in potrait mode

**Comment by kingslay** [comment]
你是指swiftui的demo吗？可以给个截图吗？

**Comment by shivam6900** [comment]
No its swift

**Comment by kingslay** [comment]
我用demo- iOS 试了不会有你说的问题
