### ISSUE TITLE
Request: HDR 10+ support for the new Apple TV

### ISSUE THREAD

**Issue by skrew** [kingslay/KSPlayer#325]
Hi,

Just for the todo list, the support of HDR 10+

**Comment by Alanko5** [comment]
In new tvos need bind right values for dynamic range.

**Comment by kingslay** [comment]
> In new tvos need bind right values for dynamic range.

那你知道在新的tvos里,  dynamic range的值要怎么样改吗?

**Comment by fedalcode** [comment]
I don’t know if this thread might help you:

https://github.com/quietvoid/hdr10plus_tool

@kingslay

**Comment by Alanko5** [comment]
https://code.videolan.org/videolan/vlc/-/issues/21909

**Comment by Alanko5** [comment]
Need extrakt and shape side data:
https://github.com/kingslay/KSPlayer/issues/190#issuecomment-1322684278

**Comment by kingslay** [comment]
@Alanko5  非常感谢你提供的资料。我周末的时候看下要怎么样集成到这个项目里面

**Comment by Alanko5** [comment]
> Hi,
> 
> Just for the todo list, the support of HDR 10+

please, can you give me an example?

**Comment by fedalcode** [comment]
> > Hi,
> > Just for the todo list, the support of HDR 10+
> 
> please, can you give me an example?

https://ff.de/hdr10plus-metadata-test/

**Comment by JeremTM93** [comment]
The HDR10+ mode is perfectly detected on my TV with the AppleTV 2022 on all the compatible videos that I have read, great job 👌

![PXL_20221229_123458441 MP](https://user-images.githubusercontent.com/121438307/209952242-41ea410c-d8e0-47f2-bfcc-b5dfb6c8d6a7.jpg)

**Comment by fedalcode** [comment]
@kingslay you can close this thread as completed/fixed

**Comment by Alanko5** [comment]
@JeremTM93 
are you sure the colors are correct?  
app always switch the TV correctly.  
But the image may not be displayed correctly. 
 can you add a screenshot from Infuse?

**Comment by JeremTM93** [comment]
@Alanko5 

I'm sure, I tested a hundred HDR10+ videos. My Panasonic Oled TV detects HDR10+ and no color and brightness problems. I compare easily with a firestick 4k max with the Exoplayer player.
I have the same result with the prime video app.

Also, I tested with an AppleTV 2021 and an LG Oled TV (no HDR10+ compatibility) and the TV plays well in HDR10 (or DV when the HDR profile of the video is Hybrid). No difference in brightness with a Shield pro.

For Infuse, as for Plex, it would seem that the player is MPV. The HDR10+ is not functional, the video plays in simple hdr10. I will test with infuse to confirm or not.

**Comment by Alanko5** [comment]
yes, if the TV supports DV and not HDR10+, it should switch to DV.  But I'm just assuming, I don't have access to any hdr10+ tv.
I have a test video that can also be played in the native player, and the difference was obvious.
I don't have access to a macbook at the moment.  late post so you can try it out.

**Comment by JeremTM93** [comment]
@Alanko5 

It depends on the profile, there are HDR10+ exclusives which will be broadcast in simple HDR10 if television is not compatible.

I tested Infuse and the player handles HDR10+ unlike Plex's MPV fork.

I also compared an HDR10+ video between KSplayer and the Prime Video application for the same result.

See photos below, I disabled the improvements on my Pixel so as not to distort the comparison.
by eye, no difference is also found.

**Comment by JeremTM93** [comment]
![IMG_20230101_182718_636](https://user-images.githubusercontent.com/121438307/210179613-a63fa231-1580-465c-9464-0362beaaed72.jpg)
![IMG_20230101_182718_298](https://user-images.githubusercontent.com/121438307/210179615-5fe78026-5821-4c0e-8c55-b449411c14f9.jpg)
