### ISSUE TITLE
The slider's progress problem with apple silicon m1

### ISSUE THREAD

**Issue by WEyrebaLeo** [kingslay/KSPlayer#326]
Hello, I met some stranger problems when I was using this plugin, could you please help me about this.

Problem Description:
Here is the screencut when I tried this program in mac mini 2020 with Apple Silicon M1, when the video start to play, the slider's position was not right. And no matter how I dragged it, it always restarted again.
![image](https://user-images.githubusercontent.com/111826861/198923522-57f8f90d-4c2e-4e47-83d4-12e1d16bad6e.png)

But it's played well in my macbook with Intel CPU with the same code, just like the following screencut:
![image](https://user-images.githubusercontent.com/111826861/198923849-c073d58c-d361-4fc7-9f05-03b4201998c1.png)
I don't know what i should do to resolve this problem.

Environment:
Mac mini 2020:
CPU: Apple Silicon M1
OS:  MacOS 12.6.1
Xcode:  14.0.1

Macbook pro 2019:
CPU: Intel i7
OS: MacOS 12.6
Xcode: 14.0.1

Video Source:
The video is an online video from a webdav server, and it's mkv

I am looking forward to your help

**Comment by kingslay** [comment]
不好意思.我这边没有M1的 macbook. 所以我这边无法debug. 你可以看下这两行代码.看设置的值对不对. 是不是要同时进行设置.目前是分开单独设置的.
timeSlider.maximumValue = Float(totalTime)
timeSlider.value = Float(currentTime)

**Comment by kingslay** [comment]
你也可以用swiftui版本的 KSVideoPlayerView .看下会不会有这个问题.

**Comment by WEyrebaLeo** [comment]
> 不好意思.我这边没有M1的 macbook. 所以我这边无法debug. 你可以看下这两行代码.看设置的值对不对. 是不是要同时进行设置.目前是分开单独设置的. timeSlider.maximumValue = Float(totalTime) timeSlider.value = Float(currentTime)

感谢您的回复，我尝试一下debug这两行代码

**Comment by WEyrebaLeo** [comment]
> 你也可以用swiftui版本的 KSVideoPlayerView .看下会不会有这个问题.

我尝试debug了那两行代码，总时长和当前时间的设置应该是没有问题的，感觉问题可能出现在slider这个组件上。在这个组件上的任何操作，包括拖拽，点击进度条的某一点，都会导致视频从头开始播放，如果不操作它的话，它也可以正常的把视频播放完，只是slider是从之前截图的位置开始直到结束。通过键盘的左右方向键控制视频播放的进度是可以的。

之前没有注意到有Swift UI版本的，接下来我打算尝试一下使用该版本的播放器。

再次感谢您的帮助

**Comment by kingslay** [comment]
那你看下M1芯片的是不是用的是 NSSlider

```
public extension NSSlider {
    var minimumTrackTintColor: UIColor? {
        get {
            trackFillColor
        }
        set {
            trackFillColor = newValue
        }
    }

    var maximumTrackTintColor: UIColor? {
        get {
            nil
        }
        set {}
    }

    @IBInspectable var maximumValue: Float {
        get {
            Float(maxValue)
        }
        set {
            maxValue = Double(newValue)
        }
    }

    @IBInspectable var minimumValue: Float {
        get {
            Float(minValue)
        }
        set {
            minValue = Double(newValue)
        }
    }

    @IBInspectable var value: Float {
        get {
            floatValue
        }
        set {
            floatValue = newValue
        }
    }
}
```

**Comment by WEyrebaLeo** [comment]
> timeSlider

在M1芯片用的确实是NSSlider，在Intel芯片下用的是UXSlider

**Comment by WEyrebaLeo** [comment]
> 你也可以用swiftui版本的 KSVideoPlayerView .看下会不会有这个问题.

SwiftUI版本的KSVidePlayerView目前没有这个问题

**Comment by Alanko5** [comment]
@WEyrebaLeo i trying fix it, please test it on Intel.
THX
