### ISSUE TITLE
tvOS, SwiftUI Issue

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#327]
I am having a problem where the Play/Pause button on the tvos remote (in simulator too) doesn't always work.

I think I have narrowed it down to when

`config.isLoading`

is equal to true

I have a ProgressView displayed like this :

`ProgressView().opacity(config.isLoading ? 1 : 0)`

Whenever this spinning progress icon is displayed, the Play/Pause button doesn't work.  

The video can be playing ok but the spinning progressview icon is still showing.

It is very intermittent. 

Any ideas?

**Comment by UnknownCoder807** [comment]
I forgot to add, this also happens when using your untouched KSVideoPlayerView() swiftui file.

**Comment by fedalcode** [comment]
Dear @kingslay Kingslay,
I also have the same play/pause issue when I use your untouched SwiftUI player on TVOS

**Comment by UnknownCoder807** [comment]
I am pleased to see someone see someone else also has this issue (in the sense that I'm not alone).  Any ideas @kingslay ?

**Comment by kingslay** [comment]
这周末我的电脑有点问题。所以我还无法解决这个问题。我下周再看下。抱歉

**Comment by UnknownCoder807** [comment]
> 这周末我的电脑有点问题。所以我还无法解决这个问题。我下周再看下。抱歉

Fair enough, hoe you fix it soon.

**Comment by kingslay** [comment]
当config.isLoading = true的时候。这是代表视频在进行下载数据，是无法进行play的。只能pause。你说视频在播放的时候。progressview也还是展示着。这个问题我这边没有复现出这个case。如果你遇到这个情况的话，那你可以看下config.isLoading 是不是等于true，还有config.playerLayer?.state 是不是等于.buffering

**Comment by UnknownCoder807** [comment]
I did as you asked and found that .state is not buffering but config.isLoading is always true regardless if video is playing or not.

The top right of this image shows that its not buffering but config.isLoading is still true.  Even if I use your own untouched swiftui player view, it has the exact same issue.  I have tried loads of different videos and always the same issue.  

![Simulator Screen Shot - Apple TV 4K (2nd generation) - 2022-11-09 at 12 29 59](https://user-images.githubusercontent.com/56231066/200831144-f4f0021e-857d-45f6-afbd-399f4b7e1082.png)

**Comment by kingslay** [comment]
你可以看下有没有走到这个方法，对isLoading进行更新
 public func player(layer: KSPlayerLayer, state: KSPlayerState) {
        if state == .readyToPlay {
            subtitleTracks = layer.player.tracks(mediaType: .subtitle)
            videoTracks = layer.player.tracks(mediaType: .video)
            audioTracks = layer.player.tracks(mediaType: .audio)
        } else {
            isLoading = state == .buffering
            isPlay = state.isPlaying
        }
        onStateChanged?(layer, state)
    }

**Comment by UnknownCoder807** [comment]
I added some debug code to that function and found that isLoading returns **false** after 

`isLoading = state == .buffering`

is called.

So I don't know what's happening (or not happening) to make it not work for me.  Maybe isLoading is a red herring.

It can't anything in my own implementation of the swiftui player because if I change it to your untouched player view, it has the same problem.  I'll have to keep plugging away and see if I can debug it some more.
