### ISSUE TITLE
Player stops after Siri interruption

### ISSUE THREAD

**Issue by talshr** [kingslay/KSPlayer#329]
Hi,
I've noticed the player stops and doesn't resume after a "Hi Siri"/Call session (not sure they are the same class of interruption). Maybe some interruption handling hooks should be implemented.

**Comment by kingslay** [comment]
你是用SwiftUI版本（KSVideoPlayerView），还是UIKit版本(IOSVideoPlayerView)呢

**Comment by talshr** [comment]
I'm using audio-only, so neither...

**Comment by kingslay** [comment]
https://developer.apple.com/documentation/avfaudio/avaudiosession/responding_to_audio_session_interruptions

**Comment by talshr** [comment]
OK cool, should I open a PR for this or you consider this an "outside" feature?

**Comment by kingslay** [comment]
我会修复这个问题，我在PlayerView已经有加了interruptionNotification了。我到时把它移到KSPlayerLayer。这样你用KSPlayerLayer的话，就能够有这个功能了
