### ISSUE TITLE
Spatial Audio and Airpods Pro Gyro Position Support

### ISSUE THREAD

**Issue by fedalcode** [kingslay/KSPlayer#330]
Hello @kingslay 

I was wondering if you plan to support Spatial Audio and Airpods Pro Gyro Position in your SwiftUI player.

I found documentation about this (look at the last post):

https://developer.apple.com/forums/thread/650737

Thank you!

**Comment by kingslay** [comment]
我看CMHeadphoneMotionManager只是用来显示耳机的运动。你想要的Spatial Audio应该只要对应的音频格式支持，那就会自动有空间音频的能力吧。不需要开发者额外做什么。我也不知道我这个理解对不对，可以一起探讨下，我对音频没有那么的熟悉

**Comment by fedalcode** [comment]
there is no doubt that KSplayer supports multi-channel audio; you can see it from the media info details.

However there is a catch:

When I play a content from the Netflix App, on the notification center, next to Spacial Audio settings it is mentioned "Dolby Atmos" / "Multi Channel"
On the Contrary, when I open a content (Multi Channel ) from Ksplayer, it is written "Stereo".

I sent you the screenshots via e-mail.

Also I found this video, that might give you an idea about spacial audio:
https://developer.apple.com/videos/play/wwdc2021/10265/

**Comment by kingslay** [comment]
你可以修改KSOptions.channelLayout 目前默认是Stereo

**Comment by fedalcode** [comment]
It looks like, only NativePlayer can only do it at the moment (https://developer.apple.com/documentation/avfaudio/avaudiosessionportdescription/3850454-spatialaudioenabled?language=objc)

and I also found this thread on the MPV player:
https://github.com/mpv-player/mpv/issues/9252

**Comment by fedalcode** [comment]
Dear @kingslay 

Infuse media player app (which uses an advanced player) supports Spatial Audio and Head Tracking.

The application has a 7 days trial after the first installation.

I assume Infuse implemented the "AVSampleBufferAudioRenderer" API in order to get the Spatial Audio
https://community.firecore.com/t/spatial-audio-for-airpods-pro/21726/123
https://community.firecore.com/t/spatial-audio-for-airpods-pro/21726/161
https://firecore.com/blog/25044

When I open the same content with KSplayer, I only see the "Stereo" info, whereas in Infuse it says "Multi-Channel"

(Screenshots and test video link were sent via e-mail)

**Comment by kingslay** [comment]
目前我的音频播放是通过AVAudioEngine来进行播放的，他可以支持更灵活的配置，例如threshold，expansionRatio，overallGain。AVSampleBufferAudioRenderer就比较难做那么多的配置。但是我也会尝试用AVSampleBufferAudioRenderer进行音频输出，并且做成开关，让开发者自己继续选择。但是目前我还不知道AVSampleBufferAudioRenderer要如何跟ffmpeg输出的音频进行集成。网上这块的资料比较少。其实我很早就有注意到AVSampleBufferAudioRenderer。因为视频输出我有切换成用AVSampleBufferDisplayLayer了，而不是用metal了，对应的音频输出就是AVSampleBufferAudioRenderer了。如果你好的资料，或是有demo的，那可以分享给我。我有空的话，会做下这块的工作。非常感谢你对我这个项目感兴趣，并且提供了很多信息给我。

**Comment by fedalcode** [comment]
The spatial audio feature implementation into advanced players is a complete mystery to everyone.

The known thing is, for video playback Netflix uses the Quicktime player in the Native Player with a custom UI in order to get the Spatial Audio.

Only Infuse, as an advanced player managed to do it. I don't know if it is possible to merge the native player features like `AVSampleBufferAudioRenderer` into KSplayer.

If I find a test project (by luck) I will definitely share it with you.

In the meantime, I am wondering if it is possible to add a new audio track using the native player into KSplayer in order to use the Spatial Audio?
https://stackoverflow.com/questions/11779490/how-to-add-a-new-audio-not-mixing-into-a-video-using-ffmpeg

**Comment by fedalcode** [comment]
@kingslay Is there enything to enable in order to use AudioRenderer? Or I keep as it is?
Also is there any downside of keeping AudioRenderer active all the time?

Thanks

**Comment by UnknownCoder807** [comment]
I'm curious about this new 'feature' - Is it safe to always have it = true ?  or is it not recommended?

**Comment by kingslay** [comment]
目前测试发现在7.1音频会有一点点杂音。在1和2音轨都是可以的。可以多进行测试下

**Comment by fedalcode** [comment]
Dear @kingslay 
I confirm that spatial audio works, but there are 2 things to fix:

1- with the new ksplayer, the video playback is not smooth anymore. 

2- if spatial audio is available, the device should activate it automatically. I guess the issue is that because ios displays the sound as Stereo, insteas of Multi Channel / Dolby Atmos.

screenshots and video link were sent via e-mail

**Comment by UnknownCoder807** [comment]
I have enabled this setting and found 2 issues

1) .ts streams do not play, they show one frane and thats it.

here is the log

```
KSPlayer: Resample.swift:283 channel | KSOptions channelLayout: AudioChannelLayout(mChannelLayoutTag: 6619138, mChannelBitmap: __C.AudioChannelBitmap(rawValue: 0), mNumberChannelDescriptions: 0, mChannelDescriptions: __C.AudioChannelDescription(mChannelLabel: 0, mChannelFlags: __C.AudioChannelFlags(rawValue: 1798882240), mCoordinates: (7.5262e-41, 6.3e-44, 0.0)))
KSPlayer: Resample.swift:241 init(codecpar:) | out channelLayout: AVChannelLayout(order: __C.AVChannelOrder(rawValue: 1), nb_channels: 2, u: __C.AVChannelLayout.__Unnamed_union_u(), opaque: nil)
KSPlayer: KSPlayerLayer.swift:149 state | playerStateDidChange - readyToPlay
KSPlayer: KSMEPlayer.swift:332 play() | play <KSPlayer.KSMEPlayer: 0x600004ab6d00>
KSPlayer: KSPlayerLayer.swift:149 state | playerStateDidChange - buffering
KSPlayer: MEPlayerItem.swift:127 init(url:options:) | Failed setup for format videotoolbox_vld: hwaccel initialisation returned error.

KSPlayer: KSPlayerLayer.swift:364 changeLoadState(player:) | ["readVideoTime": 0.1420721666654572, "initTime": 0.031087791663594544, "readAudioTime": 0.1421038749977015, "openTime": 0.6876366666656395, "decodeVideoTime": 0.10404712500167079, "decodeAudioTime": 0.0378447083348874, "findTime": 0.39077833333431045, "firstTime": 1.9772727499985194, "tcpTime": 0.10695762500108685, "dnsTime": 1.4375000318977982e-05, "readyTime": 0.015514041668211576]
KSPlayer: KSPlayerLayer.swift:149 state | playerStateDidChange - bufferFinished
```

2) mkv/mp4 files show video but have no audio.

**Comment by fedalcode** [comment]
@kingslay
Same issue on TVOS, video files do not have sound. I only get sound when I use my airpodsPRO.

besides, it is more clear to understand with tvOS UI:
AudioRenderer works fine, as it enables the spatial audio when I activate it, but the sound sent via AudioRenderer is Stereo.

![29222C2D-EE20-43F9-AE92-3AC532509887](https://user-images.githubusercontent.com/100095878/206263129-493e27bc-5898-4ee3-930d-212aa84ed535.jpeg)

**Comment by fedalcode** [comment]
Here is the issue I have:
1- I start playing a movie, the sound is playing
2- I put my airpods, I get sound for a fraction of second and then there is no sound anymore.
3- after the sound issue, I can't use playback buttons (play/pause - forward - rewind) I can only use the X button

5- the output sound is stereo, not multichannel

**Comment by fedalcode** [comment]
Hello @kingslay thank you very much for your hard work!

Now Ksplayer fully supports Spatial Audio and the player sees the "multichannel"

However, when you watch something with earphones (can be another brand as Airpods Pro), the dialogues come from the left if the content if 5.1 and higher. for Stereo, the sound comes as it should be.

I have shared with you 2 video links via e-mail, so you can try.

Thank you again for your hard work!

**Comment by UnknownCoder807** [comment]
I've managed to do some testing with my airpods pro and  found an issue when watching an mkv with the following codec info.  There is no sound other than a very faint background noise, which seems to be more dominant in the left air pod.  

I have KSOptions.isUseAudioRenderer = true 

![Simulator Screen Shot - iPad Pro (11-inch) (4th generation) - 2022-12-12 at 14 08 41](https://user-images.githubusercontent.com/56231066/207067299-cb90b32c-be36-42fd-9e47-06224d245a0a.png)

Here is the log

```
KSPlayer: Resample.swift:285 channelLayout(channelCount:) | KSOptions channelLayout: AudioChannelLayout(mChannelLayoutTag: 4294901760, mChannelBitmap: __C.AudioChannelBitmap(rawValue: 0), mNumberChannelDescriptions: 0, mChannelDescriptions: __C.AudioChannelDescription(mChannelLabel: 0, mChannelFlags: __C.AudioChannelFlags(rawValue: 78677792), mCoordinates: (3.367e-41, 1.74e-43, 0.0)))
KSPlayer: Resample.swift:243 init(codecpar:outChannel:outSampleRate:) | out channelLayout: AVChannelLayout(order: __C.AVChannelOrder(rawValue: 1), nb_channels: 8, u: __C.AVChannelLayout.__Unnamed_union_u(), opaque: nil)
KSPlayer: KSPlayerLayer.swift:364 changeLoadState(player:) | ["decodeAudioTime": 0.0008600833243690431, "readAudioTime": 1.566670708329184, "openTime": 1.7203634166507982, "tcpTime": 0.07234004169004038, "readyTime": 0.00039187498623505235, "firstTime": 4.83656825000071, "decodeVideoTime": 0.0059020833286922425, "dnsTime": 2.812498132698238e-05, "findTime": 1.0149571666843258, "readVideoTime": 1.5571803333295975, "initTime": 0.0013812083343509585]
KSPlayer: KSPlayerLayer.swift:149 state | playerStateDidChange - bufferFinished

```

**Comment by fedalcode** [comment]
> 

@Alanko5 do you also have this sound issue, since I saw you are active now in the repo, I wanted to ask you too

Thank you

**Comment by Alanko5** [comment]
> @Alanko5 do you also have this sound issue, since I saw you are active now in the repo, I wanted to ask you too
> 
> Thank you

I dont have any device with spatial audio.
