### ISSUE TITLE
macOS编译的FFmepg开启了AVDevice但是没导出xcframework

### ISSUE THREAD

**Issue by strangeliu** [kingslay/KSPlayer#333]
跟其他库混编时检测到有avdevice，会link失败

**Comment by Alanko5** [comment]
@kingslay after this update, I have this problem:

<img width="1151" alt="Snímka obrazovky 2022-12-15 o 13 33 04" src="https://user-images.githubusercontent.com/71501260/207860217-7826f88b-7215-4e19-9d70-37c0f75bf86f.png">

**Comment by kingslay** [comment]
我拆成两个库了。有另外一个FFmpegKit的库

**Comment by Alanko5** [comment]
How should I proceed to solve it?

**Comment by kingslay** [comment]
你是用pod 还好 spm   如果是spm的话 会自动下载。如果是pod的话 那就要改podfile
你可以看我demo里面的podfile 然后pod install 下

**Comment by Alanko5** [comment]
Now it works!
THX
