### ISSUE TITLE
DV profile 5 support

### ISSUE THREAD

**Issue by skrew** [kingslay/KSPlayer#335]
Hi,

User reported that DolbyVision with profile 5 is greenish.

I can send a file to you if needed.

**Comment by kingslay** [comment]
好的 麻烦你

**Comment by kingslay** [comment]
看了下，是因为这个视频是 DOVI导致的，我看mpv和vlc也都有这个问题，这个需要等待ffmpeg支持

**Comment by Alanko5** [comment]
Profile 5 and progile 8 is native support for playing.
@skrew pls send an example source

**Comment by skrew** [comment]
kingslay have a sample video

**Comment by JeremTM93** [comment]
Salut. Je rebondis sur ce sujet. Les problèmes de colométrie verdâtre sont manifestement réglés chez moi avec mes AppleTV.
Par contre, il y a encore des soucis de colométrie (ton vert et violet). C'est toujours avec le profil DV 5 (plus précisément dvhe.05.06 BL+RPU) avec gamma bt.1886 encodé en bt.601-525 peu importe le levels (limited ou full). Si cela peut aider je peux fournir quelques mediainfo des flux concernés par ce problème de colométrie.
