### ISSUE TITLE
DV 7 profile jerky

### ISSUE THREAD

**Issue by skrew** [kingslay/KSPlayer#336]
Hi,

User reported videos with DV 7 profile is jerky.

I send to you a link by mail.

Thanks

**Comment by skrew** [comment]
On a real Apple TV, it doesn't works (i have send a video to you showing the problem)
It's not a CPU problem (it's around 68%)

**Comment by Alanko5** [comment]
Hello, I have the same problem.

If the player reaches 100MB (for HW decoding / 900MB for SW decoding) of memory, it starts tearing.

[LOG](https://github.com/kingslay/KSPlayer/files/10235132/DoVi_VideoProblem.txt)


<img width="1395" alt="Snímka obrazovky 2022-12-15 o 9 18 08" src="https://user-images.githubusercontent.com/71501260/207809025-dccd8cf5-3102-40f9-af06-75d4f75fe96f.png">

<img width="1408" alt="Snímka obrazovky 2022-12-15 o 9 18 53" src="https://user-images.githubusercontent.com/71501260/207809013-c7aa51f0-d988-4086-b5b3-03681eb7db57.png">

<img width="1416" alt="Snímka obrazovky 2022-12-15 o 9 18 44" src="https://user-images.githubusercontent.com/71501260/207809020-97535681-8048-4700-a6b7-584480501a11.png">
