### ISSUE TITLE
最新版没法显示字幕

### ISSUE THREAD

**Issue by cxfksword** [kingslay/KSPlayer#337]
最新版这个测试视频显示不出字幕，但 aabae3f93abfb46be0730c36df8216c9c90984d1 之前的版本是正常的

[test.mkv.zip](https://github.com/kingslay/KSPlayer/files/10201675/test.mkv.zip)

**Comment by kingslay** [comment]
我用其他的视频试了，是可以显示字幕的。我看了这个视频有时会无法解码字幕出来。感觉是ffmpeg的问题。你可以找一个其他的dvb字幕试下。

**Comment by cxfksword** [comment]
我调试了下，发现是commit https://github.com/kingslay/KSPlayer/commit/cc53002cc7df32d044c099c9d98457cf6e91e806 删除了这句导致的，能不删吗？
![SCR-20221212-suh](https://user-images.githubusercontent.com/718792/207048680-3521cccb-79c8-4ea2-a8a8-0683bb11b2c0.png)

**Comment by kingslay** [comment]
@cxfksword 谢谢你的帮忙排查。我修复好了
