### ISSUE TITLE
多行图片字幕显示居中问题

### ISSUE THREAD

**Issue by cxfksword** [kingslay/KSPlayer#338]
ksplayer播放dvb图片字幕视频时，假如只有一行字幕，图片大小和文字尺寸是一致的，直接居中显示没问题
<img src="https://user-images.githubusercontent.com/718792/206892254-5339ae8c-9514-4de9-a9b7-75328ebb8e69.png" alt="PlTgc2" width="720"/>

但同时有多行图片字幕时，合成的图片会带透明margin，导致没法居中，是不是去掉margin更好？
<img src="https://user-images.githubusercontent.com/718792/206892269-5cecf263-d76f-4861-a949-1d3c544b5f50.png" alt="e15iTV" width="720"/>

不过去掉透明margin后，一些在特殊位置的特效字幕又很难定位对齐了。。。
<img src="https://cdn.jsdelivr.net/gh/kozalak-robot/assets@main/img/97IOOZ.png" alt="97IOOZ" width="720"/>

**Comment by kingslay** [comment]
嗯。只有一行的话，那我会去除margin的。多行就没有办法了

**Comment by cxfksword** [comment]
多行的我有实现去掉margin，不过只适用于居中情况，特效字幕就没办法了，我提个PR？

**Comment by kingslay** [comment]
可以。到时做成一个开关，让用户自己决定

**Comment by strangeliu** [comment]
字幕有没有办法通过原始的rect直接用Metal去渲染

**Comment by kingslay** [comment]
@strangeliu 目前是把多个图片合成一个图片，然后用UIImage进行渲染。要用rect的话，那还需要考虑视频界面的缩放才可以。

**Comment by strangeliu** [comment]
> @strangeliu 目前是把多个图片合成一个图片，然后用UIImage进行渲染。要用rect的话，那还需要考虑视频界面的缩放才可以。

可以把合成后的rect也传出去，播放器根据rect和画面的缩放自己去计算正确的位置

**Comment by kingslay** [comment]
合成后就只有size了。没有origin了。相当于origin就是.zero

**Comment by strangeliu** [comment]
@kingslay 这个可以计算出来，origin.x就是所有rect里面最小的minX, y就是最小的minY

**Comment by kingslay** [comment]
我看合成的图片里面是有margin的。所以合成的图片里面已经把origin算进去了。
  for (rect, cgImage) in images {
                context.draw(cgImage, in: CGRect(x: rect.origin.x, y: CGFloat(height) - rect.maxY, width: rect.width, height: rect.height))
            }

**Comment by cxfksword** [comment]
要定位准的话，单图和多图是保持一致好些，要不都加margin，要不都去掉，再返回下偏移坐标

不过好像没法拿到图片字幕原始大小，缩放比例不知怎计算

**Comment by kingslay** [comment]
单图会返回origin了，多图的话的话，origin就是为zero了
