### ISSUE TITLE
SwiftUI Player view and changing url

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#342]
I am playing a video using the SwiftUI player view and have an option within the onscreen UI to change the video url. (for example, to play a different live tv channel).  Is it possible to have the SwiftUI player view change the active url in realtime? thanks

I currently play the original url with

```
KSVideoPlayer(coordinator: playerCoordinator, url: url, options: options).onPlay { }
```

**Comment by UnknownCoder807** [comment]
Never mind, I figured it out eventually,

**Comment by jackiossy** [comment]
> Never mind, I figured it out eventually,

I have same question, Can you help me how to changing url ?

**Comment by UnknownCoder807** [comment]
> > Never mind, I figured it out eventually,
> 
> I have same question, Can you help me how to changing url ?

In my case, I just change the value of "url"

I pass it to my onscreen UI via a binding and changing the value, causes ksplayer to play the new url.

**Comment by nazar-41** [comment]
@UnknownCoder807 code example please
