### ISSUE TITLE
Crash in AWFAudio

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#344]
I am seeing the same crash a few times in my app.  I don't have debug logs as they are from customers who have downloaded from the app store.

<img width="662" alt="Screenshot 2022-12-19 at 17 54 59" src="https://user-images.githubusercontent.com/56231066/208489701-a43d7036-17ed-45c8-ada1-0d52cda1de77.png">

<img width="1140" alt="Screenshot 2022-12-19 at 17 55 35" src="https://user-images.githubusercontent.com/56231066/208489709-f8b0ebf6-9ca6-43ab-84f7-4c3ed29c2229.png">

**Comment by skrew** [comment]
I have the same crash for a while now, already reported. It happen when i'm switching between 2 files

```
KSPlayer: AudioEnginePlayer.swift:274 channelLayout | audio unit channelLayout tag: 0
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'error -10868'
SWIFT TASK CONTINUATION MISUSE: seek(time:) leaked its continuation!
SWIFT TASK CONTINUATION MISUSE: seek(time:) leaked its continuation!
SWIFT TASK CONTINUATION MISUSE: seek(time:) leaked its continuation!
SWIFT TASK CONTINUATION MISUSE: seek(time:) leaked its continuation!
SWIFT TASK CONTINUATION MISUSE: seek(time:) leaked its continuation!
SWIFT TASK CONTINUATION MISUSE: seek(time:) leaked its continuation!
SWIFT TASK CONTINUATION MISUSE: seek(time:) leaked its continuation!
SWIFT TASK CONTINUATION MISUSE: seek(time:) leaked its continuation!
SWIFT TASK CONTINUATION MISUSE: seek(time:) leaked its continuation!
terminating with uncaught exception of type NSException
```

**Comment by kingslay** [comment]
这个是偶现的吗？还是某个url就一定会出现crash呢？

**Comment by UnknownCoder807** [comment]
In my case, I have no idea about the URL.  It's unknown customers of my app that have the crash.  Maybe @skrew has a url?

**Comment by skrew** [comment]
I can reproduce it everytime with 2 specifics urls but only on a real Apple TV device (it don't crash on the simulator)

@kingslay Do you already have an Apple TV ?

**Comment by skrew** [comment]
Also note, if i'm playing thoses 2 files, it will works fine, it only crash when i play file 1 then file 2.

Maybe you need some close / dealloc when stop playing and reinit at start for another file ?

**Comment by kingslay** [comment]
我现在有Apple TV 了

**Comment by kingslay** [comment]
@skrew 麻烦发给我那两个file 。我debug下

**Comment by skrew** [comment]
Mail sent. I hope you will enjoy your Apple TV 😀

**Comment by kingslay** [comment]
@skrew 我尝试修复了下。我看你发的url里面有一个是多音轨的，我想问下，你是不是配置了多音轨设备。然后针对这个问题我尝试修复了。麻烦你试下，是否还有问题。

**Comment by skrew** [comment]
It doesn't crash anymore but i only have sound from the 2nd item, the image is from the first item, freezed

I don't have a "multi track" device, only my stereo sound bar, if it's your question.

**Comment by UnknownCoder807** [comment]
This is still an issue for me.  It's crashing for several of my customers.  Al I have is the crash log as supplied by apple.  I don't have a url.

<img width="960" alt="Screenshot 2023-01-14 at 18 56 19" src="https://user-images.githubusercontent.com/56231066/212491704-63c40ced-3ffa-48d1-b4ca-a4ff39dba1af.png">

**Comment by UnknownCoder807** [comment]
@kingslay I have sent you an email, I had this crash happen to me just now, sent you the screenshot of xcode as it stood at the crash.

```
KSPlayer: MEPlayerItem.swift:127 init(url:options:) | Could not find codec parameters for stream 1 (Audio: mp3 (mp3float) ([3][0][0][0] / 0x0003), 0 channels, fltp): unspecified frame size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options

KSPlayer: AVFFmpegExtension.swift:397 layoutTag | FFmepg channelLayout: stereo order: AVChannelOrder(rawValue: 1)
KSPlayer: AudioEnginePlayer.swift:151 prepare(options:audioDescriptor:) | outputFormat channelLayout tag: 6619138
KSPlayer: AudioEnginePlayer.swift:152 prepare(options:audioDescriptor:) | outputFormat channelLayout channelDescriptions: []
2023-01-15 12:38:58.445336+0000 Snappier IPTV[88145:6053741] [avae]            AVAEInternal.h:76    required condition is false: [AVAudioEngineGraph.mm:2128:_Connect: (IsFormatSampleRateAndChannelCountValid(format))]
```
