### ISSUE TITLE
Problem reading Dolby Vision file in MP4 (buffering, jerks & freeze frame, colorimetry OK)

### ISSUE THREAD

**Issue by JeremTM93** [kingslay/KSPlayer#347]
Tested on AppleTV4k 2021 & 2022, iPad and iPhone.

Stream type : 

Format/protocol : mov,mp4,m4a,3gp,3g2,mj2
Vidéo : HEVC
Profil DV : dvhe.05.06, BL+RPU
Pixel format : nv12
Primaries : bt.2020
Colormatrix : bt.2020-ncl
Levels : limited
Gamma : PQ (HDR Peak : 49.26)

[Demonstration video](https://vimeo.com/784782942)

**Comment by kingslay** [comment]
@JeremTM93 这个视频可以传到github吗？你给的这个链接无法在播放器播放。

**Comment by cdguy** [comment]
@kingslay please check your mail box. I will send you a link in a few minutes

**Comment by JeremTM93** [comment]
Thanks you @cdguy 🙏

**Comment by kingslay** [comment]
这个链接我无法打开，你是否可以用ffmpeg把这个视频截取成一分钟以内的小视频，然后上传到github。

**Comment by cdguy** [comment]
@kingslay 

The source has those properties:

Metadata:
[SAR 1:1 DAR 16:9], 16035 kb/s, 23.98 fps, 23.98 tbr, 24k tbn (default)
    Metadata:
      creation_time   : 2021-03-10T16:16:24.000000Z
      handler_name    : encode 4K HDR Dolby Vision x265 BL+RPU FrIeNdS - Source UHD BD PRECELL (Thx)
      vendor_id       : [0][0][0][0]
      encoder         : DOVI Coding
    Side data:
      DOVI configuration record: version: 1.0, profile: 5, level: 6, rpu flag: 1, el flag: 0, bl flag: 1, compatibility id: 0


and when I downloaded the first 5 minutes of the movie using:

`ffmpeg -i http://example.com/your_movie.mp4 -ss 00:00:00 -t 00:05:00 -c copy output.mp4
`

I got this:


Metadata:
        title           : The Story of Home
  Stream #0:0[0x1](eng): Video: hevc (hev1 / 0x31766568), none(tv, bt2020nc/bt2020/smpte2084), 3840x2160, 23379 kb/s, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 24k tbn (default)
    Metadata:
      handler_name    : encode 4K HDR Dolby Vision x265 BL+RPU FrIeNdS - Source UHD BD PRECELL (Thx)
      vendor_id       : [0][0][0][0]
      encoder         : DOVI Coding



the source has this metadata:       DOVI configuration record: version: 1.0, profile: 5, level: 6, rpu flag: 1, el flag: 0, bl flag: 1, compatibility id: 0

however the downloaded video does not have that additional metadata. is that normal?

**Comment by kingslay** [comment]
那是不对的 应该要有dovi信息才可以

**Comment by cdguy** [comment]
@kingslay is the ffmpeg command correct to extract non-transcoded video?

`ffmpeg -i http://example.com/your_movie.mp4 -ss 00:00:00 -t 00:05:00 -c copy output.mp4 `

**Comment by kingslay** [comment]
这个命令是对。那你可以试下把视频下载本地，然后在进行裁剪。看行不行

**Comment by cdguy** [comment]
@kingslay when I extract the movie using ffmpeg the dovi properties are gone.
I will send you a download link for a file that has the same properties

**Comment by kingslay** [comment]
@cdguy 目前播放dolby vision 除了颜色会有问题，还有其他的问题吗？

**Comment by cdguy** [comment]
@kingslay the player always buffers at the same minutes. I sent you a torrent link that has the same video properties

**Comment by JeremTM93** [comment]
> @cdguy 目前播放dolby vision 除了颜色会有问题，还有其他的问题吗？

Hi, no color issues. The stream hangs as shown in the Vimeo link above. Except that 8 months later, the problem worsened, the stream does not play despite Dolby Vision detected.

**Comment by JeremTM93** [comment]
This has now been fixed, certainly since the ffmpeg update 👌
