### ISSUE TITLE
Colometry problem on Dolby Vision file (green and pink)

### ISSUE THREAD

**Issue by JeremTM93** [kingslay/KSPlayer#348]
Tested on AppleTV4k 2021 & 2022, iPad and iPhone.

Stream type :

Format/protocol : MKV or mov,mp4,m4a,3gp,3g2,mj2
Vidéo : HEVC
Profil DV : dvhe.05.06, BL+RPU
Pixel format : nv12
Primaries : bt.709 or bt.601-525
Colormatrix : bt.709 or bt.601
Levels : limited or full
Gamma : bt.1886

![problème colométrie](https://user-images.githubusercontent.com/121438307/209830488-c7278c32-63c5-442e-9d13-287c49acb360.jpg)

**Comment by Alanko5** [comment]
https://github.com/kingslay/KSPlayer/issues/190

**Comment by Alanko5** [comment]
https://github.com/kingslay/KSPlayer/issues/335

**Comment by Alanko5** [comment]
so far, only DV profile 8 has been developed

**Comment by JeremTM93** [comment]
> jusqu'à présent, seul le profil DV 8 a été développé

There have been improvements.
In MKV, profile 5 works all the time when the video is in bt.2020.
No problem with profile 8, like profile 7 for that matter.

**Comment by JeremTM93** [comment]
Hi @kingslay, this problem still exists on tvOS

https://github.com/kingslay/KSPlayer/issues/348#issue-1512874271

**Comment by kingslay** [comment]
@JeremTM93 你是用我的testflight 包试的吗？目前我的testflight的审核遇到问题了。所以最近几周都没有发不出去新的testflight。所以目前最新的testflight包可能还没包含这个修复。

**Comment by cdguy** [comment]
> @JeremTM93 你是用我的testflight 包试的吗？目前我的testflight的审核遇到问题了。所以最近几周都没有发不出去新的testflight。所以目前最新的testflight包可能还没包含这个修复。

the best thing to do is, when apple solves the issue, update the tracyplayer with the latest commit and let's wait for @JeremTM93 to test

**Comment by kingslay** [comment]
@JeremTM93 或者你发给我url。我这边来进行测试下。也是可以的。

**Comment by cdguy** [comment]
@kingslay please check your mailbox

I will send you now 3 different movie clips that have the same properties. the playback has to be fluid and with the correct colours :)

**Comment by JeremTM93** [comment]
> @JeremTM93 或者你发给我url。我这边来进行测试下。也是可以的。

@cdguy will take care of everything, thank you both.

**Comment by kingslay** [comment]
@JeremTM93  @cdguy 你发给我的三个链接我在tvos试了。颜色不会有问题了。所以剩下的事情就等待苹果审核通过最新的testflight包就可以了。

**Comment by FaiChou** [comment]
@kingslay  最新的代码在 tvOS 模拟器上测试了下，颜色仍然发绿。测试视频已经发你邮箱。

**Comment by kingslay** [comment]
需要自己配置filter

**Comment by cdguy** [comment]
> @kingslay 最新的代码在 tvOS 模拟器上测试了下，颜色仍然发绿。测试视频已经发你邮箱。

How?
