### ISSUE TITLE
Video slows down and jerks above a some bitrate (~ <10mbit/s).

### ISSUE THREAD

**Issue by JeremTM93** [kingslay/KSPlayer#349]
Tested on AppleTV4k 2021 & 2022

There are jerks (slowdowns) at regular intervals on videos above a some bitrate.
I would say that from 10mbit/s the problem occurs, 4k SDR, HDR or DV, it doesn't matter.
I jointly compared these videos with MPV and I don't have this problem of "jumping" images.

[Demonstration video](https://vimeo.com/784787105)

**Comment by UnknownCoder807** [comment]
I just posted about a dropped frame issue that causes slowdowns, lag and stuttering.

https://github.com/kingslay/KSPlayer/issues/369

I wonder if this is the same or related issue.

**Comment by JeremTM93** [comment]
@kingslay you can delete this ticket.

With the new version, we can see that ticket #375 is more accurate.

Still jerks with 50i interlaced TV streams (25fps), it's not smooth.

For 23.976fps streams there is some improvement but still some micro jerks unfortunately.
