### ISSUE TITLE
在swiftui，系统tvOS当中， @State resource/url 属性数值发生改变, 不会切换直播

### ISSUE THREAD

**Issue by jackiossy** [kingslay/KSPlayer#350]
在swiftui，系统tvOS当中， @State resource/url 属性数值发生改变, 不会切换直播 依然会播放默第一次加载的url 

代码中使用的是KSVideoPlayView 的swiftui demo
KSVideoPlayView(resource: resources[self.c1])

SwiftUI中如何实现按遥控器上下 切换URL 换台？
我在遥控器   .focusable()
                    .onMoveCommand 方法中修改了self.c1的下标数值， 但是KSVideoPlayView并没有切换画面。

**Comment by kingslay** [comment]
你可以用 KSVideoPlayerView.openURL()

**Comment by jackiossy** [comment]
> 你可以用 KSVideoPlayerView.openURL()

首先， 感谢您的回复。

KSVideoPlayerView.openURL() 的返回对象并不是SwiftUI中 someview类型， 会报错， 我尝试用了以下代码，但是依然无法切换播放频道
                
let definition = resources[c1].definitions.first!
KSVideoPlayerView(url: definition.url, options: definition.options)

**Comment by kingslay** [comment]
openURL这个方法是专门用来更新url的。初始化方法还是要用KSVideoPlayerView(url: definition.url, options: definition.options)

**Comment by jackiossy** [comment]
> openURL这个方法是专门用来更新url的。初始化方法还是要用KSVideoPlayerView(url: definition.url, options: definition.options)

 Xcode报错 Instance member 'openURL' cannot be used on type 'KSVideoPlayerView'; did you mean to use a value of this type instead?

我不能在.onMoveCommand  方法中调用 openURL

**Comment by jackiossy** [comment]
> openURL这个方法是专门用来更新url的。初始化方法还是要用KSVideoPlayerView(url: definition.url, options: definition.options)

KSVideoPlayerView(url: definition.url, options: definition.options) 初始化， 我可以写在 some view 之中， 但是我要怎么在 遥控器上下方法 .onMoveCommand 方法中写  KSVideoPlayerView.openURL方法？

**Comment by kingslay** [comment]
.onMoveCommand { direction in
                    isMaskShow = true
                    openURL(URL(fileReferenceLiteralResourceName: ""))
                    #if os(macOS)
                    switch direction {
                    case .left:
                        playerCoordinator.skip(interval: -15)
                    case .right:
                        playerCoordinator.skip(interval: 15)
                    case .up:
                        playerCoordinator.playerLayer?.player.playbackVolume += 1
                    case .down:
                        playerCoordinator.playerLayer?.player.playbackVolume -= 1
                    @unknown default:
                        break
                    }
                    #endif
                }

**Comment by kingslay** [comment]
KSVideoPlayerView的url是一个@State。所以外部可以随便更改他的值。
