### ISSUE TITLE
Swift Package Manager can't resolve KSPlayer

### ISSUE THREAD

**Issue by Stengo** [kingslay/KSPlayer#351]
Hey!
Adding KSPlayer as a dependency to a completely fresh project on Xcode 14.2 leads to the error shown below. Using cocoapods works just fine, but it would be nice to be able to use the more modern package management style 🙂 

EDIT: I just tried again by pointing it to the `develop` branch and that worked fine, but specifying a version range seems to cause issues 🤔 

![Screenshot 2023-01-01 at 12 39 22](https://user-images.githubusercontent.com/12018882/210169470-b4e2236e-b446-4de2-832d-0077783e6359.png)

**Comment by kingslay** [comment]
你之前报错的spm配置是怎么样写的呢？

**Comment by Stengo** [comment]
I simply used the Xcode UI (in project -> package dependencies) and configured it like this:

![Screenshot 2023-01-01 at 14 18 54](https://user-images.githubusercontent.com/12018882/210171924-d3539206-781d-4234-8486-edb3137b65d8.png)

**Comment by kingslay** [comment]
fix by a9e032470eb7cfa8686249af11e1325c532d3cf1

**Comment by neckaros** [comment]
I'm still having the issue
我仍然有问题
![Capture d’écran 2023-06-08 à 13 21 21](https://github.com/kingslay/KSPlayer/assets/7789770/c5427745-ca67-43c7-8700-c95b76fcb34a)

i think #377 is related
我认为#377 是相关的

**Comment by kingslay** [comment]
> I'm still having the issue 我仍然有问题 ![Capture d’écran 2023-06-08 à 13 21 21](https://user-images.githubusercontent.com/7789770/244367287-c5427745-ca67-43c7-8700-c95b76fcb34a.jpg)
> 
> i think #377 is related 我认为#377 是相关的

你在试下，我打了tag了

**Comment by neckaros** [comment]
> > I'm still having the issue 我仍然有问题 ![Capture d’écran 2023-06-08 à 13 21 21](https://user-images.githubusercontent.com/7789770/244367287-c5427745-ca67-43c7-8700-c95b76fcb34a.jpg)
> > i think #377 is related 我认为#377 是相关的
> 
> 你在试下，我打了tag了

Sorry i don't understand (Google translate failed me)

**Comment by kingslay** [comment]
I had fixed. I can try again

**Comment by nevzatbozkurt** [comment]
unfortunately it doesn't seem to be working again.
