### ISSUE TITLE
Crash when initializing secodary player

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#352]
Set secondary player `KSOptions.secondPlayerType = KSMEPlayer.self` and trying loading a stream URL, would crash:

`KSPlayer_MEPlayerItem_open (51): EXC_BAD_ACCESS (code=1, address=0x0)`

This is where it crashes:

<img width="1303" alt="Screenshot 2023-01-03 at 7 09 07 PM" src="https://user-images.githubusercontent.com/1998171/210477093-d8a83bc2-96a9-4a33-a73d-72222b326647.png">

**Comment by matteogobbi** [comment]
With the demo it doesn't crash apparently, although `ogg` format is stuck in buffering.

I use a Custom implementation. I followed your initialization example.

**Comment by kingslay** [comment]
@matteogobbi 你是否方便把url发给我呢？ 我这边试下
