### ISSUE TITLE
Fatal error: can not find AudioChannelLayoutTag for AVChannelLayout

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#356]
I'm getting the following crash

<img width="1673" alt="Screenshot 2023-01-10 at 21 03 36" src="https://user-images.githubusercontent.com/56231066/211662436-d9576e05-fa7c-4a07-97d5-5036cafbb104.png">

**Comment by kingslay** [comment]
@UnknownCoder807 你试下，把这行代码注释掉。看下播放的声音是否正常

**Comment by UnknownCoder807** [comment]
I will try this when it happens again.  I can't remember how I made it happen, it's a very specific thing to make it crash.  I'll get back and give further info when/if I come across it again.

**Comment by kingslay** [comment]
这个应该是特定的某个音频格式才会这样的。所以你只要找到那个url就可以了

**Comment by UnknownCoder807** [comment]
I have now had this error repeatedly.

If comment out the assertionFailure line, the video does play, but no centre speaker sound.

here is the details

 
<img width="1667" alt="Screenshot 2023-01-13 at 04 02 27" src="https://user-images.githubusercontent.com/56231066/212234907-fd3d6c6d-ec57-498a-8839-9a1e4bf9e854.png">
