### ISSUE TITLE
KSPlayer 视频的上下黑边不是纯黑

### ISSUE THREAD

**Issue by FaiChou** [kingslay/KSPlayer#358]
<img width="878" alt="Xnip2023-01-12_23-08-02" src="https://user-images.githubusercontent.com/18500846/212103673-0e9bdb1f-5800-4c57-94e5-167241a4f3b4.png">

使用 AVPlayer 播放时候是正常的纯黑, 但 KSPlayer 的上下黑边并不是纯黑.

哪里能够设置视频的背景颜色?

**Comment by FaiChou** [comment]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/18500846/212228277-765b6d1f-d79a-4035-9124-8048fa40df85.png">
甚至会这样.

**Comment by kingslay** [comment]
需要我这边sdk改什么东西吗

**Comment by FaiChou** [comment]
> 需要我这边sdk改什么东西吗

应该可以优化下的，有些尺寸的视频会有这问题。如果不处理，应用层可以用一个黑色view做背景，也能解决。

**Comment by kingslay** [comment]
这边MediaPlayerProtocol.view的背景色是nil。 都没有做过特殊的处理。所以应用层设置了背景色才会生效
