### ISSUE TITLE
MKV media playing with subtitles automatically

### ISSUE THREAD

**Issue by snappycode1** [kingslay/KSPlayer#36]
When I select an MKV file which has internal subtitles, the subtitles are automatically displayed

I have selected the media using both :

```
        let res0 = KSPlayerResourceDefinition(url: mediaURL, definition: "HD")
        let asset = KSPlayerResource(name: "Test Video", definitions: [res0], cover: coverImageURL)
        playerView.set(resource: asset)

```
and
        
`        playerView.set(resource: KSPlayerResource(url: mediaURL, name: "Test Video", cover: coverImageURL, subtitleURL: nil))
`

and in both instances, the internal subtitles are displayed by default.  I would like there to be no subtitles displayed by default.

thanks.

**Comment by kingslay** [comment]
you can set KSPlayerManager.autoSelectEmbedSubtitle = false

**Comment by snappycode1** [comment]
Thanks, the new option you added works well.
