### ISSUE TITLE
有些音轨没有对白声音

### ISSUE THREAD

**Issue by FaiChou** [kingslay/KSPlayer#360]
有些客户遇到这问题, 有些视频文件, 是正常的, 使用 AVPlayer 播放是正常的, 分享给我, 我用 KSPlayer 也是正常的.
但在这些客户设备上(电视)使用 KSPlayer 播放, 会出现人物说话没有声音, 或许有声音, 特别小, 完全被背景声音给覆盖掉.

不知道播放器这边能不能解决, 或者是他们有什么电视上的设置问题?

**Comment by kingslay** [comment]
他们的系统是16的吗

**Comment by FaiChou** [comment]
我收集一下他们的设备信息.

**Comment by FaiChou** [comment]
问了几个 都是 16 系统，我也是 16 的系统是没问题的。

**Comment by kingslay** [comment]
这些视频是多音轨的吗

**Comment by kingslay** [comment]
我这周解决了多音轨播放的问题了。他们的代码是最新的吗？

**Comment by FaiChou** [comment]
我更新到最新版本, 已经解决了.

因为我自己也维护了一份 forked 代码, 所以没更新及时.
