### ISSUE TITLE
闪退 Fatal error: can not find AudioChannelLayoutTag for 2 channels

### ISSUE THREAD

**Issue by FaiChou** [kingslay/KSPlayer#361]
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/18500846/212473867-07088013-caf1-43c8-9823-13b57c54b589.png">

视频:
破坏之王 (1994)
https://www.aliyundrive.com/s/woJdRPoCDa7
提取码: r1a2
点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。

**Comment by kingslay** [comment]
这个视频太大了。你是否可以用ffmepg的命令把他变短一点。只要前面几分钟就可以了

**Comment by kingslay** [comment]
你也可以试下把这一行注释掉。播放的声音是否正常

**Comment by FaiChou** [comment]
注释掉是可以正常播放的, 所以要注释掉吗?

**Comment by kingslay** [comment]
这个是debug才会触发的。正式环境不会有问题

**Comment by kingslay** [comment]
所以可以不用注释掉

**Comment by FaiChou** [comment]
OK
