### ISSUE TITLE
List all subtitles from player (ios)

### ISSUE THREAD

**Issue by ridhabnj** [kingslay/KSPlayer#363]
Hello,

How to list all subtitles from the player and put it in array to set subtitle programmatically form app.

Regards.

**Comment by kingslay** [comment]
extension KSMEPlayer: SubtitleDataSouce {
    public var infos: [SubtitleInfo]? {
        tracks(mediaType: .subtitle) as? [FFmpegAssetTrack]
    }

**Comment by ridhabnj** [comment]
Thanks.
