### ISSUE TITLE
Problem with Picture in Picture

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#366]
Using SwiftUI and untouched SwiftUI player view.

When using PiP on a real iPhone there is a problem when you press the icon in the PiP window to return full screen.  It closes the video.

To replicate, have ContentView() have a button to play a video.  Press the button then and press the PiP button.  When the PiP window is displayed, click on the X in the top left to return to the previous view (ie, contentView) and then in the PiP window, click the return to full screen button in the top right.  The PiP window just closes.

(click X in top left)
![IMG_0112](https://user-images.githubusercontent.com/56231066/212857030-6a08092f-fe1e-48a8-9779-0688e82ad70d.PNG)

(returned to ContentView, press return to full screen button in top right of PiP window)
![IMG_0114](https://user-images.githubusercontent.com/56231066/212857116-c29db0e2-43e9-4e2a-a860-407389c720fc.PNG)

**Comment by kingslay** [comment]
我用demo是不是有这个问题。你是直接用demo的吗？

**Comment by UnknownCoder807** [comment]
Hi,

Using your demo app tracyplayer, PiP does not work on Mac.

thanks.

**Comment by kingslay** [comment]
是的，PIP只能在iOS和tvOS使用。不能在macOS使用PIP是apple的bug。需要等他们修复

> 2023年1月20日 11:31，UnknownCoder807 ***@***.***> 写道：
> 
> 
> Hi,
> 
> Using your demo app tracyplayer, PiP does not work on Mac.
> 
> thanks.
> 
>

**Comment by UnknownCoder807** [comment]
Hi,

Thanks.

**Comment by UnknownCoder807** [comment]
I'm not sure what's happened in this thread, but the macOS issue is a separate thing.

My original issue in post 1 above stands.  Picture in Picture on iOS works but exits when you go back a screen in the app and then press the icon to restore the PiP to full screen.

**Comment by UnknownCoder807** [comment]
Thanks for the fix today.  There is a problem with the X button in the PiP window.  When I press it, it returns to full screen.  It should close the PiP window instead.

**Comment by kingslay** [comment]
是的 会有这个问题 但是我找不到方式来区分x按钮和全屏按钮。
