### ISSUE TITLE
rtsp?

### ISSUE THREAD

**Issue by duhrich** [kingslay/KSPlayer#367]
I've got an old app that was built around kxmovie, that I'd like to replace. One key feature was ability to play `rtsp` streams. When I try build a sample app with KSPlayer, I get an "unsupported URL" error when trying to open `rtsp://` URLs... is this expected? ffmpeg handles these I believe. Is the problem with the Swift `URL` class?

**Comment by kingslay** [comment]
rtsp的连接是支持的。你可以看下demo的rtsp的例子。

    if let url = URL(string: "rtsp://rtsp.stream/pattern") {
        let options = MEOptions()
        objects.append(KSPlayerResource(url: url, options: options, name: "rtsp video"))
    }

**Comment by duhrich** [comment]
Huh... Thank you...
you're right, my `rtsp` stream works fine with the bundled SwiftUI demo app, but not with my very simple one.

I'll have to see why, but this is very helpful.

Incidentally, my non-functional app is this:
```
import SwiftUI
import KSPlayer

struct ContentView: View {
    let rtspVideo = URL(string: "rtsp://path-to-rtsp-stream")!
    let httpVideo = URL(string: "http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8")!
    var body: some View {
        VStack {
            KSVideoPlayerView(url: rtspVideo, options: KSOptions())
        }
    }
}
```

It works fine if you replace the url with `httpVideo` but does _not_ work if you use `rtspVideo`.

If I add the exact same `rtsp` stream to the SwiftUI demo app, it plays fine.

**Comment by duhrich** [comment]
I discovered the issue. If I set the first player type to `KSMEPlayer` when my app initializes, it plays the `rtsp` stream as expected.

Thank you for your help!

```
        KSOptions.firstPlayerType = KSMEPlayer.self
```
