### ISSUE TITLE
Seek Programmatically

### ISSUE THREAD

**Issue by ridhabnj** [kingslay/KSPlayer#368]
Hello,

How to seek to time programmatically.

I was using this code before  but now not working :

 self.LivePlayer.seek(time: seektime ?? 0)

I get an error :

'async' call in a function that does not support concurrency

Thanks for help.

**Comment by kingslay** [comment]
private func seek(time: TimeInterval) {
        Task {
            await self.seek(time: time, autoPlay: self.options.isSeekedAutoPlay)
        }
    }
