### ISSUE TITLE
4:3 16:9 Aspect Ratio

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#37]
Is it possible to change the actual video aspect ratio?

If a video is in 4:3 format, I would like the option to stretch it to 16:9 (for example) - removing/reducing the black bars down the left and right sides.

I know about contentMode = .scaleAspectRatio etc but that doesn't do what I expected.

is this possible on KSPlayer ? and if so, how please?

**Comment by kingslay** [comment]
You can get the size of the video and update the layout yourself
` MediaPlayerProtocol.naturalSize `

**Comment by snappycode1** [comment]
Thanks

**Comment by wertpoiu** [comment]
i am having same issue no code anywhere to fill phone screen .scaletofill dont work at all

**Comment by wertpoiu** [comment]
please update demo

**Comment by UnknownCoder807** [comment]
Is it possible to add this feature please?  It's the one major thing missing for me.  thanks

**Comment by kingslay** [comment]
What effect do you hope to achieve? Can you draw a schematic diagram for me to see

**Comment by UnknownCoder807** [comment]
Basically, for example, some video's are in 4:3 format and when they are displayed they look like the first image below

If I can set the aspect ratio to 4:3 then the video will look like the 2nd image below.  Both images are captured from VLC.

<img width="1053" alt="Screenshot 2021-02-27 at 15 04 28" src="https://user-images.githubusercontent.com/56231066/109391131-7df9f100-790d-11eb-93a9-1896fb1964bc.png">

<img width="1053" alt="Screenshot 2021-02-27 at 15 04 40" src="https://user-images.githubusercontent.com/56231066/109391139-83efd200-790d-11eb-86cf-46c7b4a60d9b.png">

**Comment by kingslay** [comment]
@UnknownCoder807 can you provide the video to me？ I will test it.

**Comment by UnknownCoder807** [comment]
Normally I would but these videos links aren’t mine to share.  they are paid for links.

**Comment by kingslay** [comment]
Can you download it, and then take a small part of it through ffmepg and send it to me separately by email? I won't leak out

**Comment by kingslay** [comment]
```
class MeOptions: KSOptions {
    override func drawableSize(par: CGSize, sar: CGSize) -> CGSize {
        return CGSize(width: par.width, height: par.width*3/4)
    }
}
```

**Comment by UnknownCoder807** [comment]
Hi I'm not getting this to work.  can you provide a more detailed example or update the demo please?

**Comment by UnknownCoder807** [comment]
Thank I got this to work.  I have a question though.  How do I read the original aspect ratio so I can have a return to default option for the user?  Default, 4:3, 5:4, 16:9 etc

the user selects default and it reverts back to the original aspect ratio?

**Comment by kingslay** [comment]
`let original =  super.drawableSize(par: CGSize, sar: CGSize)`

**Comment by UnknownCoder807** [comment]
Thanks, that works.
