### ISSUE TITLE
Frame Skipping, drops

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#375]
I'm not sure what has happened in recent updates, but KSPlayer seems lot more unstable these days.

Interlaced, 23.9fps and some other videos are experiencing frame drops, frame skipping, audio sync issues (possibly because of the video frame issues).  Some streams also speed up and slow down. (sports for example).

I will try and collate a list of streams/videos with issues.  None of these issues happen with VLCKit so I'm hopeful @kingslay you can solve them.

**Comment by UnknownCoder807** [comment]
A previous version of my app (from mid-december) has none of these issues, so it's got to be something committed since.

**Comment by JeremTM93** [comment]
I confirm, there is an improvement but still a smoothness problem on 50i interlaced TV channels (25fps).
The 23.976fps streams still suffer from micro jerks but less frequent.
I asked to close ticket #349.

**Comment by kingslay** [comment]
好的。麻烦你们提供给你下对应的url。然后我修复下这个问题

**Comment by fedalcode** [comment]
> 好的。麻烦你们提供给你下对应的url。然后我修复下这个问题

@kingslay please check your inbox I will send you 2 links.
One is an interlaced stream, the other is a video file encoded in 23.9 fps

**Comment by UnknownCoder807** [comment]
@kingslay have you had chance to look into these issues?

**Comment by kingslay** [comment]
> @kingslay have you had chance to look into these issues?

可以的，你发下有问题的url给我

**Comment by fedalcode** [comment]
> > @kingslay have you had chance to look into these issues?
> 
> 可以的，你发下有问题的url给我

@kingslay I sent you via e-mail a small list of .ts live interlaced streams

**Comment by fedalcode** [comment]
@kingslay have you received me e-mail with the links?
I doubt that my e-mail got in your spam folder because of the high number of links that I sent to you

**Comment by UnknownCoder807** [comment]
I am seeing this issue on livw video streams that are 59.9 frames per second and also on movies that are 23.9 frames per second.  

Seems KSPlayer doesn't like non-integer frames per second.

**Comment by JeremTM93** [comment]
If it helps, on a 2k or 4k video at 23.976fps, the image jumps at regular intervals (every 15 or 20 seconds) but I have the impression that after a certain time on the video there is no more jerking or jumping of the image, I have observed this on the last two movies I watched in full.

**Comment by UnknownCoder807** [comment]
I wonder if it's something as simple as a rounding up issue.  by rounding up the FPS to a whole number, every 20-30 seconds there is now a whole extra second of frames to display.

**Comment by fedalcode** [comment]
> @UnknownCoder807 @fedalcode
> Do you see an improvement?
> I still see frame jumps on 23.876 FPS streams.

Yes there are still frame jumps in streams/video files that are encoded on non-integer FPS value

That’s why I opened a ticket regarding this (#387) @kingslay
