### ISSUE TITLE
项目的git记录怎么没有了?

### ISSUE THREAD

**Issue by FaiChou** [kingslay/KSPlayer#378]
能否再恢复一下? 或者创建个新的 branch 将旧的提交记录存档下.

**Comment by kingslay** [comment]
为什么要恢复呢。是有什么问题呢。你还是可以在在上面直接改代码然后push 过来

**Comment by kingslay** [comment]
有人说clone太慢了 拉不下来。所以就清空了

**Comment by FaiChou** [comment]
@kingslay 因为我维护了两份 remote, 你更新时候我会去 cherry-pick, 有段时间没有更新了, 今天想去看下有什么变动, 打算合并代码, 没想到记录没有了.

**Comment by FaiChou** [comment]
我维护的一份是 tvOS 定制的, 很多其他端代码都删掉了, 所以不能 pr 到这个库.

**Comment by FaiChou** [comment]
"clone太慢了 拉不下来":

```bash
~ git clone --depth=1 https://...
```

**Comment by FaiChou** [comment]
"clone太慢了 拉不下来":

```bash
~ git clone --depth=1 https://...
```

**Comment by kingslay** [comment]
我加了 backup 这个分支了。你看下

**Comment by kingslay** [comment]
但是那个分支也不全，只到了一月一号。中间缺少了部份代码。

**Comment by FaiChou** [comment]
这次提交是最新的提交吗?

2月14号

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/18500846/219936233-e2f82f9f-ef1d-43d4-9e3a-151e30082905.png">

**Comment by kingslay** [comment]
2月14号是比较新的。我在昨天又更新了一些

**Comment by kingslay** [comment]
![image](https://user-images.githubusercontent.com/3964055/219936332-f4040d9f-d634-402a-8d84-fb98830796e0.png)

**Comment by FaiChou** [comment]
@kingslay  能否将 2b4bbba 之后的 commit 弄出来呢? 或者导出 patch?

**Comment by FaiChou** [comment]
@kingslay 我发现打上 commit id, github 会自动连接到这次提交.  可以将后面的 commit id 发出来吗? 这样我自己 merge

**Comment by kingslay** [comment]
你可以直接把现在develop分支的最新代码提交上去，就可以了。变动不大。就昨天改了一些代码

**Comment by kingslay** [comment]
https://github.com/kingslay/KSPlayer/commit/1ce09ff1faa63cdd14a83085da94504bb33b0333
https://github.com/kingslay/KSPlayer/commit/c6d1c9d86f8a59bdae54b1c3f337b719262feb2a
https://github.com/kingslay/KSPlayer/commit/d68127ec8a9c8bffa2f8ba0a2e6f07c6c08038d5
https://github.com/kingslay/KSPlayer/commit/1a12408fff7031d654406843d454251b66d24f58

**Comment by FaiChou** [comment]
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/18500846/219938195-5ef2cef0-185b-4e53-8d27-325fb9ce1bb1.png">

**Comment by kingslay** [comment]
swift package reset

**Comment by FaiChou** [comment]
我 reset package cache 没有效果, 是我添加的方式不对吗?



<img width="340" alt="image" src="https://user-images.githubusercontent.com/18500846/219939133-a5f97d92-d004-4c76-81da-24811fbced92.png">

**Comment by kingslay** [comment]
那你在同级目录自己git clone 下FFmpegKit
