### ISSUE TITLE
在 tvOS 端播放视频, 手机上并没有出现 remote control

### ISSUE THREAD

**Issue by FaiChou** [kingslay/KSPlayer#381]
我看项目代码中都有添加 `MPRemoteCommandCenter ` 和 `MPNowPlayingInfoCenter`.
但是电视端运行起来后, 手机控制中心并不会有相应的信息, 也不能控制电视上暂停播放快进快退等.

**Comment by Kimentanm** [comment]
KSPlayerLayerView.swift的490行，有定义MPRemoteCommandCenter，你那没生效吗？

**Comment by FaiChou** [comment]
@Kimentanm 是的没有生效(registerRemoteControllEvent)
