### ISSUE TITLE
Picture in Picture and tvOS

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#384]
Using the SwiftUI Demo Tracy Player on a real Apple TV device, I play some media and press the PiP button.

The audiio continues but the video screen disappears and there is no small PiP video window.

**Comment by UnknownCoder807** [comment]
Also, is it possible when PiP is active, to swap the video around in the full screen and the PiP window?

**Comment by kingslay** [comment]
其他app在tvOS上可以pip吗？

**Comment by UnknownCoder807** [comment]
Not for all content there isn't.  but ksplayer manages to do it for iOS for all media, so I figured it would be possible on tvOS too.

**Comment by kingslay** [comment]
这个是调用系统的方法。目前pip不支持tvos和macos。只有iOS可以用

**Comment by UnknownCoder807** [comment]
ok, thanks.
