### ISSUE TITLE
Deinterlacing filters

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#39]
Is it possible to access deinterlace filters?  

VLCKit for example has linear, discard, x, mean, yadif, yadif2x etc

is there an equivalent for KSPlayer please?

**Comment by kingslay** [comment]
Have not added this feature.  you can use FFmpeg Filters

**Comment by UnknownCoder807** [comment]
Is there any chance this can be considered for implementing thanks?
