### ISSUE TITLE
central voice absent are 5.1 headphones

### ISSUE THREAD

**Issue by Zayatoshi** [kingslay/KSPlayer#392]
Hello.

There was a problem with ksplayer on the central voices, which could not be heard with on the soundbars, when the sound played was in 5.1.

You solved this problem a big thank you great job.

However, this problem still seems to be present when playing with headphones (Bluetooth...)

The problem disappears if we restart the played content.

**Comment by kingslay** [comment]
是视频在播放的过程中，切换成用蓝牙音箱。然后导致没有声音有问题吗？

**Comment by Zayatoshi** [comment]
No problem on the sound with the video on the speakers on the 5.1 sound. You have solved the problem. The missing sound on the central comes randomly when you continue playing the video with a headset. The video must be restarted for the sound to work properly.

**Comment by kingslay** [comment]
那用mpv或vlc会有这个问题吗？

**Comment by Zayatoshi** [comment]
No problem only with ks. No problem with mpv and vlc

**Comment by kingslay** [comment]
你可以试下改下代码。看能不能解决这个问题。
 把
        engine.connect(nodes: [sourceNode, dynamicsProcessor, timePitch, engine.mainMixerNode, engine.outputNode], format: options.audioFormat)

改成是
engine.connect(nodes: [sourceNode, dynamicsProcessor, timePitch, engine.mainMixerNode], format: options.audioFormat)

**Comment by kingslay** [comment]
@Zayatoshi 你用的耳机是 AirPods吗？

**Comment by Zayatoshi** [comment]
Yes, mainly.

**Comment by Zayatoshi** [comment]
Tvos

**Comment by kingslay** [comment]
你可以试下最新代码，然后设置 KSOptions.isUseAudioRenderer=true。看会不会有这个问题。因为我没有5.1的音响。所以无法测试。
