### ISSUE TITLE
请问一个页面中能否有多个KSPlayer同时加载？

### ISSUE THREAD

**Issue by biruhamachi** [kingslay/KSPlayer#393]
请问一个页面中能否有多个KSPlayer同时加载？比如每个UICollectionViewCell里面都有一个IOSVideoPlayerView，然后在func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) 里面对每个cell加载不同的IOSVideoPlayerView的视频。我试了一下，所有的视频都不能成功加载。但如果页面中只有一个IOSVideoPlayerView，视频加载是没有问题的。向您请教一下，请问有什么解决办法没有？非常感谢您的帮助！

**Comment by kingslay** [comment]
是可以的啊。我刚才用swiftui试了下。是ok的
        WindowGroup {
            HStack {
                KSVideoPlayerView(resource: testObjects[0])
                KSVideoPlayerView(resource: testObjects[1])
            }
}
