### ISSUE TITLE
Crash: 播放器播放时出错

### ISSUE THREAD

**Issue by hippiefox** [kingslay/KSPlayer#396]
<img width="1514" alt="截屏2023-04-03 19 42 14" src="https://user-images.githubusercontent.com/47681432/229499478-e22e8392-5b17-4a49-991e-dbb01839ea9a.png">

在播放某些线上文件时，总是在此处Crash掉，如图所示。求解答。

**Comment by kingslay** [comment]
有具体的url吗？如果把这个url下载到本地。进行播放还会crash吗？

**Comment by hippiefox** [comment]
> 有具体的url吗？如果把这个url下载到本地。进行播放还会crash吗？

将URL直接放入demo项目中，可以正常播放出来，并不会Crash。
项目中某些线上Url可以正常播放，剩下的一些线上的Url，播放时，则发生上图所示的Crash。

**Comment by kingslay** [comment]
是不是你的app没有开启http的支持。现在目前是不允许http的。一定要https

**Comment by hippiefox** [comment]
> 有具体的url吗？如果把这个url下载到本地。进行播放还会crash吗？

需要添加的Headers:
Cookie:FTN5K=b8181cfa
地址：
http://tjc-download.weiyun.com/ftn_handler/fa4a4f5158f9cba384554a31bfa66a24e9d6b8c608dbd4d555c81e1b51db2d4d/m.mp4

**Comment by hippiefox** [comment]
> 你自己的工程用https可以吗？

不可以...

**Comment by hippiefox** [comment]
> 你自己的工程用https可以吗？

项目设置：Allow Arbitrary Loads：YES

Q：
场景1:
        KSOptions.firstPlayerType = KSMEPlayer.self
        KSOptions.secondPlayerType = KSMEPlayer.self
        KSOptions.firstPlayerType = KSMEPlayer.self
        KSOptions.secondPlayerType = KSMEPlayer.self

**Comment by kingslay** [comment]
firstPlayerType 默认是走avplayer

**Comment by hippiefox** [comment]
还有一个问题，为什么视频播放时 画面 总是上下颠倒？

**Comment by hippiefox** [comment]
> 那是因为配置了filter。

好的 谢谢。
