### ISSUE TITLE
Question: how do I inject an external subtitle?

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#397]
`let ksSubtitle = KSURLSubtitle(url: subtitleURL)`

how do I add it to the stream?

Thank you for the player!

**Comment by kingslay** [comment]
public func openURL(_ url: URL) {
        if url.isAudio || url.isMovie {
            self.url = url
            try? FileManager.default.contentsOfDirectory(at: url.deletingLastPathComponent(), includingPropertiesForKeys: nil).forEach {
                if $0.isSubtitle {
                    subtitleModel.addSubtitle(info: URLSubtitleInfo(url: url))
                }
            }
            subtitleModel.selectedSubtitleInfo = subtitleModel.subtitleInfos.first
        } else {
            let info = URLSubtitleInfo(url: url)
            subtitleModel.selectedSubtitleInfo = info
            subtitleModel.addSubtitle(info: info)
        }
    }

**Comment by matteogobbi** [comment]
what's the contest of this method? it's into a player extension?

**Comment by matteogobbi** [comment]
So..it's unclear how to call this method.

It looks like it should live in an extension of `KSVideoPlayerView`, but my `playerView` is a custom `IOSVideoPlayerView` which inherits from `VideoPlayerView`. So how can I arrive to get a `KSVideoPlayerView` instance and call the `openURL` method?

**Comment by kingslay** [comment]
```
public class KSPlayerResource: Hashable {
    public static func == (lhs: KSPlayerResource, rhs: KSPlayerResource) -> Bool {
        lhs.definitions == rhs.definitions
    }

    public let name: String
    public let cover: URL?
    public let definitions: [KSPlayerResourceDefinition]
    public var subtitle: KSSubtitleProtocol?
    public var nowPlayingInfo: KSNowPlayableMetadata?
    /**
     Player recource item with url, used to play single difinition video

     - parameter name:      video name
     - parameter url:       video url
     - parameter cover:     video cover, will show before playing, and hide when play
     - parameter subtitleURL: video subtitle
     */
    public convenience init(url: URL, options: KSOptions = KSOptions(), name: String = "", cover: URL? = nil, subtitleURL: URL? = nil) {
        let definition = KSPlayerResourceDefinition(url: url, definition: "", options: options)
        var subtitle: KSSubtitleProtocol?
        if let subtitleURL {
            subtitle = KSURLSubtitle(url: subtitleURL)
        }
        self.init(name: name, definitions: [definition], cover: cover, subtitle: subtitle)
    }

```

**Comment by matteogobbi** [comment]
Thank you.

This seems to create a resource with video + subtitles.

In my case, I'm playing a video, and want to add a subtitle of which I have a subtitle URL (which I have locally downloaded).
Is there a way to ask the player to start using that subtitle?

**Comment by kingslay** [comment]
你只要改下KSPlayerResource的subtitle就可以了

**Comment by matteogobbi** [comment]
Ok, I was able to make it work thank you.

However although I can see the subtitles going, when I do:

`let tracks = player.tracks(mediaType: .subtitle)`

The subtitle isn't there.
Is there a way to add the subtitles to the stream while the video is playing, and be able to retrieve it in the list of tracks like VLC does?

Thank you.

**Comment by kingslay** [comment]
不行的 目前外挂字幕和内嵌字幕是分开的。你可以自己聚合下

**Comment by matteogobbi** [comment]
Ok thank you, I'll manage it manually.
