### ISSUE TITLE
Crash: new OpenSSL 3.1.0 crash at startup

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#398]
I just updated the pod, and there's consistently a OpenSSL crash at startup. Tested on my real iPad device.
Going back to the previous version (3.0.7) no problems.

**Comment by kingslay** [comment]
我更新了ffmpegkit了。你重新试下

**Comment by UnknownCoder807** [comment]
@kingslay  I'm not sure if this is the same crash. but since the latest commit I get the following crash on startup.

<img width="2560" alt="Screenshot 2023-04-05 at 11 31 02" src="https://user-images.githubusercontent.com/56231066/230055768-7f4d962d-75a2-41bb-bf3e-8d677d1c0992.png">

**Comment by kingslay** [comment]
你是用pod还是用swiftpm来引入ksplayer的呢

**Comment by UnknownCoder807** [comment]
I use cocoapods.

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test ksplayer playback ui ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test ksplayer playback ui ios
pod 'KSPlayer',:git => 'https://github.com/kingslay/KSPlayer.git', :branch => 'develop'
    pod 'FFmpegKit',:git => 'https://github.com/kingslay/FFmpegKit.git', :branch => 'main'
    pod 'OpenSSL',:git => 'https://github.com/kingslay/FFmpegKit.git', :branch => 'main'
end
```

**Comment by kingslay** [comment]
我今天有更新了FFmpegKi。你是用最新的FFmpegKi吗

**Comment by UnknownCoder807** [comment]
This is a brand new project I just created, it's as up to date as the latest commits for all pods.

**Comment by kingslay** [comment]
我看了下是openssl的最新版本的问题。我先把openssl还原一下。改成用久的版本

**Comment by kingslay** [comment]
修复好了。换成用3.0.7的openssl

**Comment by matteogobbi** [comment]
Yeah it was the same crash. I pointed to the commit with the 3.0.7 to fix it.
