### ISSUE TITLE
Image freezes and audio keeps going

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#399]
Hello,

I have had an app that for 4 years uses VLC and AVPlayer under the hood without problems.

I'm now implementing this amazing player, but it constantly freezes the image while the audio keeps playing.
Sometimes it recovers after 1  or 2 minutes. Otherwise, it never recovers and the only way is to reload the stream from scratch or move the seek bar.

What it could depend on? Any settings that could help?

Tested on iPad Air 2 and tvOS 4K.

**Comment by kingslay** [comment]
你是用KSMEPlayer 这个播放器内核吗？你可以看下日志
```
  KSLog("video delay time: \(videoClockDelay), audio time:\(desire). seek video track ")
                    videoTrack.outputRenderQueue.flush()
                    videoTrack.seekTime = desire
```

看是否有这个日志。这个url在demo里面播放是否也会有问题，是否可以分享出来。

**Comment by matteogobbi** [comment]
I can't share the URL but I'm playing for 20 mins without problems when I play MKV which uses Metal under the hood.
I think the problem happens when I play mp4 with KSAVPlayer.

**Comment by kingslay** [comment]
用KSAVPlayer的话，就比较难解决这个问题了。因为KSAVPlayer只是调用了AVPlayer来进行播放。你可以试下，用KSMEPlayer会不会有问题。

**Comment by matteogobbi** [comment]
The weird think is that if I use AVPlayer, it doesn't freeze. I'll so some more test, however MKV with KSME play without issues.
