### ISSUE TITLE
KSAVPlayer always shutdown

### ISSUE THREAD

**Issue by byMohamedali** [kingslay/KSPlayer#4]
<img width="746" alt="image" src="https://user-images.githubusercontent.com/6490189/79013455-d0a5af80-7b79-11ea-8ada-d11502b8e203.png">

Avplayer seems to not work anymore only KSMEPlayer is working, I want to use AVplayer because I want use the airplay functionality

I will send you the iptv link like this you can test.

Thank you

**Comment by kingslay** [comment]
the url Report an error Error Domain=CoreMediaErrorDomain Code=-12939 "byte range and no content length - error code is 200"。
And the url can't play use QuickTime Player. If  QuickTime Player can play the url  , then KSAVPlayer will do too

**Comment by byMohamedali** [comment]
Ok thank you :)
