### ISSUE TITLE
Player states / rate is inconsistent

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#400]
**Tested on Live Streams (m3u8)**

When I call `player.pause()` I receive 2 state changes:

`.paused`
`.bufferFinished`

However, I also get a call to:

`func playerController(currentTime: TimeInterval, totalTime: TimeInterval)`

In this method I check if the player `isPlaying` and it returns `true`.

So I cross-checked and I see that `player.playbackRate == 1.0` which is wrong as it should be `0`.

A weird thing I see here:

```
public enum KSPlayerState: CustomStringConvertible {
    case prepareToPlay
    case readyToPlay
    case buffering
    case bufferFinished
    case paused
    case playedToTheEnd
    case error
    public var description: String {
        [....]
    }

    public var isPlaying: Bool { self == .buffering || self == .bufferFinished }
}
```

is that `isPlaying` is determined by:

`self == .buffering || self == .bufferFinished`

This is also inconsistent because `bufferFinished` apparently is called when I call a pause, afeter the `.paused` state has been estabilshed.

**Comment by matteogobbi** [comment]
I think one important thing is that:

`playerView.playerLayer?.player.play()`
and
`playerView.play()`

have 2 different effects. The first one doesn't trigger the state change.
If it is meant to be kept as private, I think it'd be good to update the pod.

**Comment by kingslay** [comment]
嗯。需要用playerView.play()。playerView.playerLayer?.player.play()是很底层的方法。这个还不能设置为private，不然有些人的代码可能就编译不通过了。
