### ISSUE TITLE
Value of type 'UnsafeMutablePointer<Float>' has no member 'update'

### ISSUE THREAD

**Issue by lowking** [kingslay/KSPlayer#401]
tvos使用报错
![image](https://user-images.githubusercontent.com/33308659/230546963-65d0a367-c39c-4e46-8a88-008abbf83a51.png)
```
  pod 'KSPlayer',:git => 'https://github.com/kingslay/KSPlayer.git', :branch => 'develop'
  pod 'FFmpegKit',:git => 'https://github.com/kingslay/FFmpegKit.git', :branch => 'main'
  pod 'OpenSSL',:git => 'https://github.com/kingslay/FFmpegKit.git', :branch => 'main'
```

**Comment by kingslay** [comment]
你需要用Xcode Version 14.3

**Comment by hippiefox** [comment]
> 你需要用Xcode Version 14.3

这个问题在Xcode14.2可以解决吗？ Xc
![281681724828_ pic](https://user-images.githubusercontent.com/47681432/232669602-655cb7d0-49b0-4e66-87ae-98ab49589515.jpg)
ode14.3 打出的包存在官方bug。 求解答。

**Comment by kingslay** [comment]
@hippiefox已经修复了。最新的代码在xcode14.2也可以运行了

**Comment by hippiefox** [comment]
> @hippiefox已经修复了。最新的代码在xcode14.2也可以运行了

Many Thanks!!!
