### ISSUE TITLE
Subtitles work oddly - inconsistencies, UI problems, and long waiting time to display

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#404]
Hello,

I deeply tested subtitles and found these problems:

1. If I `track.setEnabled(true)` for a subtitle track, it takes 40 seconds to start displaying the subtitles;
2. I have also to select all the other tracks to `false` or it won't change;
3. When I want to disable the subtitles, for each track I `track.setEnabled(false)`, but it still takes ~40 seconds to stop displaying them.
4. Even after settings all tracks to false, and waiting for the player to stop displaying the subtitles, printing `playerView.resource?.subtitle` would still return the last subtitle (or the one that was forced at opening automatically).
5. If I do `playerView.resource?.subtitle = nil` instead, it will top updating subtitles immediately, however, it would keep the last subtitle's text displayed on the screen.

It's unclear to me how to make this work. I think it's a set of problems that should be resolved at the core.

Thank you!

**Comment by matteogobbi** [comment]
Thank you. 
Your PR only fixes point number **5**, but not the other points.

The major issue is that, after I disable the subtitles doing `playerView.resource?.subtitle = nil`, when then I set another subtitle enabled it doesn't work. And `playerView.resource?.subtitle` is still `nil`.

**Comment by kingslay** [comment]
你可以看下我demo里面的方案。你激活字幕的话，是要自己设置到resource?.subtitle才行。还有内嵌字幕激活之后，是无法马上生效的，因为视频流是有缓存的。所以你可以看到我默认是把所有的内嵌文字字幕在一开始都激活了。只有图片字幕没有激活。因为图片字幕占用的资源会比较大。

**Comment by matteogobbi** [comment]
oooh so when I `enable` a subtitle I'm not showing them up? I thought that was the case. Instead seems like that enabling is one thing, but to show them I still need to do it manually some how. Right?

**Comment by kingslay** [comment]
是的，如果是图片字幕的话，那建议用select(track: MediaPlayerTrack)。它会帮你进行seek。这样的话，视频和图片字幕就能同时显示出来。但是就会导致视频会卡顿一下。各有优缺点。

**Comment by matteogobbi** [comment]
Thank you.
I need to study a little bit how it works..I have no idea if the user has a subtitle that is an image or not. I need to find a universal way to manage them.

**Comment by kingslay** [comment]
有isImageSubtitle 这个属性可以判断

**Comment by matteogobbi** [comment]
so let's say I show a subtitle like this now:

```
            // Try internal subtitle.
            let subtitles = playerView.srtControl.filterInfos { _ in true }
            for subtitle in subtitles {
                if Int(subtitle.subtitleID) == newValue {
                    subtitle.enableSubtitle { [weak self] result in
                        self?.playerView.resource?.subtitle = try? result.get()
                        return
                    }
                }
            }
```

however `subtitle` is of kind `SubtitleInfo` and doesn't contain the `isImageSubtitle` property. The `MediaPlayerTrack` does, but what should I do then? Should I first go through all tracks and use `select(track:)` if it's an image subtitle, without the need of settign `self?.playerView.resource?.subtitle`, or should I also do this step even if I called `select` (I checked `select` and I see what it does is disabling eventual other image subtitles)?

**Comment by matteogobbi** [comment]
Furthermore, only `FFmpegAssetTrack` has this `isImageSubtitle` parameter.

**Comment by matteogobbi** [comment]
Also:

given a `playerView.resource?.subtitle`, is there a way to retrieve the subtitle ID?

**Comment by kingslay** [comment]
> Also:
> 
> given a `playerView.resource?.subtitle`, is there a way to retrieve the subtitle ID?

SubtitleInfo 有subtitle ID

**Comment by matteogobbi** [comment]
thank you.
