### ISSUE TITLE
商用AVSampleBufferDisplayLayer播放杜比的HDR内容需要杜比授权吗

### ISSUE THREAD

**Issue by FantasyKingdom** [kingslay/KSPlayer#409]
iPhone自带相机拍摄的就是杜比的HDR，自己开发的商用软件使用AVSampleBufferDisplayLayer正确显示HDR画面会涉及到版权问题吗，想简单讨论一下。

**Comment by FantasyKingdom** [comment]
有没有办法禁用AVSampleBufferDisplayLayer的HDR效果，使用metal可以不显示HDR，但是没法画中画

**Comment by FantasyKingdom** [comment]
> 
把解码后的数据放入AVSampleBufferDisplayLayer，就直接以HDR的模式显示了，有没有办法在AVSampleBufferDisplayLayer上面以SDR的方式显示HDR内容

**Comment by kingslay** [comment]
可以试下destinationDynamicRange 不知道有没有效果

**Comment by FantasyKingdom** [comment]
> 可以试下destinationDynamicRange 不知道有没有效果

我试了并没有任何效果

**Comment by FantasyKingdom** [comment]
已经解决了，通过判断流的类型，杜比的流使用metal渲染，其它使用AVSampleBufferDisplayLayer渲染
