### ISSUE TITLE
你好。请问能否像VLC一样提供tvOS下的基础界面

### ISSUE THREAD

**Issue by aningxu** [kingslay/KSPlayer#41]
经过几天的测试，KSPlayer的解码能力非常好，但是在tvOS下，我几乎找不到定制界面的相关文档。

请问能否像VLC一样，做一下tvOS下的基础界面呢？

其中2个操作：
1、遥控器触控板往下滑动 ，显示视频元数据，切换音轨、字幕轨道
2、按触控板可暂停，并显示进度条，可左右滑动更改播放时间，再按触控板确定，从选择的时间开始播放。

这2个在tvOS上属于最基础的功能，请问能否实现呢？

**Comment by kingslay** [comment]
目前没有时间做这个支持。你可以发起个 pull requests
