### ISSUE TITLE
AVSampleBufferDisplayLayer切后台再切回来会黑屏，及画中画异常

### ISSUE THREAD

**Issue by FantasyKingdom** [kingslay/KSPlayer#410]
1.使用AVSampleBufferDisplayLayer，暂停播放，切后台再切回来，画面直接黑屏，继续播放才能恢复
2.使用AVSampleBufferDisplayLayer，竖屏播放视频，并设置为裁剪模式，这时候启动画中画，画面显示不完全了，一部分画面直接黑屏。我个人的猜测是：启动画中画时系统直接以当前裁剪的画面进行展示的，但实际画中画里面的内容是按照原比例进行展示。

**Comment by kingslay** [comment]
第一个问题是AVSampleBufferDisplayLayer本身存在的问题，其他的人的解决方案是退后台的时候做了下屏幕截图，然后插入一个imageview。这样回来就不会黑屏了。

**Comment by FantasyKingdom** [comment]
> 第一个问题是AVSampleBufferDisplayLayer本身存在的问题，其他的人的解决方案是退后台的时候做了下屏幕截图，然后插入一个imageview。这样回来就不会黑屏了。

谢谢，这个方案可行

**Comment by kingslay** [comment]
第二个问题，你是设置为scaleAspectFit吗？

**Comment by FantasyKingdom** [comment]
> 第二个问题，你是设置为scaleAspectFit吗？

是设置为isScaleAspectFill出现这个问题，使用提供的Demo就能复现这个问题

![2721682087931_ pic](https://user-images.githubusercontent.com/43386949/233664256-92ca875c-4ec2-4125-9ced-4e88de15d524.jpg)
![2711682087855_ pic](https://user-images.githubusercontent.com/43386949/233664280-ea821707-8f6a-4a03-a46f-2a96a00d3dea.jpg)

**Comment by kingslay** [comment]
看了下，感觉是画中画没有设置contentMode导致的。但是系统也没有开放设置contentMode的地方
