### ISSUE TITLE
What exactly isUseAudioRenderer used for?

### ISSUE THREAD

**Issue by talshr** [kingslay/KSPlayer#412]
My app is only playing audio. Is that the right way to go?

**Comment by UnknownCoder807** [comment]
From my understanding it allows Spatial Audio to be enabled.

However, if this setting is enabled, the video is jerky and the audio is out of sync.  Repeated attempts to get it fixed have had no success so far sadly.

**Comment by kingslay** [comment]
启用isUseAudioRenderer 目前是会有一些问题。目前isUseAudioRenderer只适用于纯音频的播放的。对于视频的话，建议不要开启。

**Comment by talshr** [comment]
Thanks! Is there any other benefits with it except for Spacial Audio?
