### ISSUE TITLE
Fast backward doesn't work

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#414]
`KSMEPlayer`

1. Try to play at a negative `rate` (ie. `-2`);

**Expected:**
- like for rate 2 or higher, the player should play at speed but backward;

**Current:**
- Stream continues forward lagging.

**Comment by kingslay** [comment]
无法后退的

**Comment by matteogobbi** [comment]
I'm not sure to understand your answer

**Comment by kingslay** [comment]
不支持这个功能

**Comment by matteogobbi** [comment]
You can add it. It's supported by default from AVPlayer.
