### ISSUE TITLE
add by spm failed for thousands of time，help me my brother

### ISSUE THREAD

**Issue by swanfly** [kingslay/KSPlayer#417]
<img width="595" alt="image" src="https://user-images.githubusercontent.com/5317370/234633664-a22bd9da-2a10-4aed-83a6-c69a6ca43275.png">
<img width="481" alt="image" src="https://user-images.githubusercontent.com/5317370/234633778-895f89b9-e67d-412e-9b0e-c1e9534b4b91.png">

**Comment by kingslay** [comment]
2c3eb15dbeb9fccc632546d37d7c98f2d4b9631e
