### ISSUE TITLE
[!] No podspec found for `FFmpegKit` in `../../FFmpegKit`

### ISSUE THREAD

**Issue by swanfly** [kingslay/KSPlayer#418]
<img width="437" alt="image" src="https://user-images.githubusercontent.com/5317370/234746794-dc263466-97af-4c23-ada2-09a640c3947a.png">

**Comment by kingslay** [comment]
你可以看下readme 
 pod 'FFmpegKit',:git => 'https://github.com/kingslay/FFmpegKit.git', :branch => 'main'
  pod 'OpenSSL',:git => 'https://github.com/kingslay/FFmpegKit.git', :branch => 'main'
