### ISSUE TITLE
macOS刚开始播放时，整个窗口会变得很卡

### ISSUE THREAD

**Issue by Kimentanm** [kingslay/KSPlayer#419]
Intel macOS 13.3.1
复现步骤：使用 macOS demo 刚开始播放m3u8，拖动窗口整个窗口都在掉帧

**Comment by Kimentanm** [comment]
#382 修复该issue后才出现的问题，在这之前没问题

**Comment by Kimentanm** [comment]
在这个 [use CAMEtalLayer](https://github.com/kingslay/KSPlayer/commit/f3ce8a1940d2bf1bd820b41ceadd41314b5cfb9b) commit之后，macOS播放视频时整个窗口会掉帧，电脑也会变得很卡

**Comment by kingslay** [comment]
这个是因为vision os 不支持用MTKView。所以我就换成用CAMetalLayer。那看来MTKView内部是有做了一些优化。那我们一起看下是不是因为我少设置CAMetalLayer的一些属性导致变卡。

**Comment by kingslay** [comment]
@Kimentanm 你是用AVSampleBufferDisplayLayer来进行渲染视频的吧

**Comment by Kimentanm** [comment]
> @Kimentanm 你是用AVSampleBufferDisplayLayer来进行渲染视频的吧

是的呢
