### ISSUE TITLE
How can I get the frames per second?

### ISSUE THREAD

**Issue by snappycode1** [kingslay/KSPlayer#42]
as per the subject, how do I get the frames per second (FPS) of a playing media?

some demo code would be welcome, thanks

**Comment by snappycode1** [comment]
Can you please help kingslay?

**Comment by kingslay** [comment]
use nominalFrameRate  b1ce32184229b7acf3a0aa1fb3d4a36007990e98

**Comment by snappycode1** [comment]
Thanks.
