### ISSUE TITLE
String encoding for stream metadata

### ISSUE THREAD

**Issue by talshr** [kingslay/KSPlayer#420]
Hi,

I'm streaming the radio stream: https://radio.streamgates.net/stream/90fm
and in the log I can see metadata title received is "M√°lteigurin". This is incorrect, the correct encoding is "Málteigurin".
I tried various encoding on this line `var log = String(cString: format)`  in `MEPlayerItem.swift` but no change. 
Maybe the log is not the correct place to follow metadata? maybe it's already distorted?

Thank you...

**Comment by kingslay** [comment]
你说的metadata是从那边取的呢？我这边看到的Metadata是这样的。不像是你描述的那样。

Input #0, mp3, from 'https://radio.streamgates.net/stream/90fm':
  Metadata:
    icy-br          : 128
    icy-description : Powered By Multix
    icy-genre       : Pop
    icy-name        : Radio 90FM
    icy-pub         : 0
    icy-url         : www.90fm.co.il
    StreamTitle     : CDN - Powered By Multix Technologies
  Duration: N/A, start: 0.000000, bitrate: 128 kb/s
  Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 128 kb/s

**Comment by talshr** [comment]
Hi,
So the data I'm referring to is not this, rather what's coming after:

```
KSPlayer: MEPlayerItem.swift:130 init(url:options:) | Metadata update for StreamTitle: F√≥tb√≥ltspr√°t
```

**Comment by talshr** [comment]
It seems the encoding problem is coming from the arguments. 
```
log = NSString(format: log, arguments: arguments) as String
```

**Comment by kingslay** [comment]
我这边打印出来的是，不会有你的这个问题
Metadata update for StreamTitle: CDN - Powered By Multix Technologies

**Comment by talshr** [comment]
Oops, the stream is `http://netvarp.kringvarp.fo:443/uvhm`. Still, bear in mind it changes every few minutes so you might see different text that what I've pasted. Right now it's supposed to be (if encoded correctly - "Norðurljóð"). I've using VLC to know that.

**Comment by kingslay** [comment]
你从metadata里面就可以能取到这个值了。不需要通过log了

**Comment by talshr** [comment]
Interesting.. can you direct me to how to access it?

**Comment by talshr** [comment]
OK, may I ask where can I access this metadata? all I get is what comes in the log:
```
KSPlayer: MEPlayerItem.swift:130 init(url:options:) | request: GET /stream/90fm HTTP/1.1
User-Agent: ksplayer
Accept: */*
Range: bytes=0-
Connection: close
Host: radio.streamgates.net
Icy-MetaData: 1
```

**Comment by talshr** [comment]
(I think you're getting it from command line FFMpeg, but I don't know how to retrieve this information from KSPlayer)

**Comment by talshr** [comment]
I just did this `ffmpeg -stats -report -I` for the problematic stream (`http://netvarp.kringvarp.fo:443/uvhm`) and the encoding is correct. So the question remains how to retrieve this metadata in KSPlayer.

**Comment by kingslay** [comment]
9941a5a21b62ec9ad59babb6aac82852854a94ce
public extension KSMEPlayer {
    var metadata: [String: String] {
        playerItem.metadata
    }

**Comment by talshr** [comment]
It seems the array is empty. I've tried to query it after metadata has been received in the log.

**Comment by kingslay** [comment]
那过几秒之后再去取。可以看到值吗？

**Comment by talshr** [comment]
Ha. I put a delay of 5 seconds and now it exists. Is there any accurate trigger I can latch on to when this data updates?

**Comment by kingslay** [comment]
public func readyToPlay(player: some MediaPlayerProtocol) {

**Comment by talshr** [comment]
But if the stream title changes, will this be called again?

**Comment by kingslay** [comment]
不会的。那你只能先监听log。然后推迟个3秒再去读metadata

**Comment by talshr** [comment]
OK Thank you very much!
