### ISSUE TITLE
random crash

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#422]
I have the following crash that has been happening for some time to some of my users of my app, and finally tonight it has happened for me to get a proper crash report.  This is completely random and very intermittent so doesn't alway happen.

All I did was try to open a .ts stream and it appeared to be waiting to play for around 20 seconds then crashed.

<img width="2547" alt="Screenshot 2023-05-01 at 21 02 00" src="https://user-images.githubusercontent.com/56231066/235522206-912797ec-65f1-4064-b7ff-4212def6630f.png">

**Comment by kingslay** [comment]
可以把这个ts下载下来 然后在本地重现吗

**Comment by UnknownCoder807** [comment]
It turned out this was happening for all video formats.  I can't replicate it now.

**Comment by kingslay** [comment]
有日志吗？
