### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by talshr** [kingslay/KSPlayer#423]
Hi,

So I noticed playing a random audio stream (`https://yes2dayradio.radioca.st/stream`) that CPU on iPhone Pro 14 (simulator) takes 7%-8% in comparison tp 2%-3% when using some other AudioToolbox http player. The question is anything can be done to improve the CPU usage. This is audio only. (maybe hwaccel?)

**Comment by kingslay** [comment]
if let path = Bundle.main.path(forResource: "mjpeg", ofType: "flac") {
        let options = MEOptions()
        options.videoDisable = true
        options.syncDecodeAudio = true
        objects.append(KSPlayerResource(url: URL(fileURLWithPath: path), options: options, name: "本地音频"))
    }

**Comment by talshr** [comment]
No change in CPU

**Comment by talshr** [comment]
I was able to decrease to 4%-5% by commenting
```
//        engine.attach(dynamicsProcessor)
//        engine.attach(timePitch)
```
and consequently removing them from here:
```
engine.connect(nodes: [sourceNode, engine.mainMixerNode, engine.outputNode], format: options.audioFormat)
```

Are they critical? 
any other ideas?

**Comment by kingslay** [comment]
timePitch 是用来控制播放速度的。2x或是0.5x。
