### ISSUE TITLE
Rewind a livestream

### ISSUE THREAD

**Issue by talshr** [kingslay/KSPlayer#424]
Hi,
Is it possible to rewind a livestream? right now when playing a livestream on the demo the slider is at the end and cannot really be moved back. If moved the stream simply continues the live stream.

**Comment by kingslay** [comment]
直播流无法往回退。只能对直播流进行录制，把它变成一个本地视频。然后你在进行播放。目前有提供了录制能力
  let moviesDirectory = try? FileManager.default.url(for: .moviesDirectory, in: .userDomainMask, appropriateFor: nil, create: false)
        options.outputURL = moviesDirectory?.appendingPathComponent("recording.mp4")
