### ISSUE TITLE
老哥,swiftUI上开关字幕的最佳方式是什么呀?

### ISSUE THREAD

**Issue by birdmichael** [kingslay/KSPlayer#425]
我理解的是SubtitleModel直接
selectedSubtitleInfo = nil 就行了.
SubtitleModel.selectedSubtitleInfo.disableSubtitle()也没效果
但是好像没效果

**Comment by kingslay** [comment]
你可以在加一下subtitleModel.selectedSubtitle = nil。 这个我后续也会修复下。

**Comment by birdmichael** [comment]
我现在偷了个懒,直接clear color 哈哈哈...
还缺少一个removeAll
