### ISSUE TITLE
KSAVPlayer: Audio Delay doesn't work

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#428]
The audio delay is never applied. Whereas the same code works and delay is applied when using KSMEPlayer.
```
// playerView is IOSVideoPlayerView
playerView.playerLayer?.options.audioDelay = 4.0
```

**Comment by kingslay** [comment]
options里面的大部份属性是针对KSMEPlayer的。 我这边主要是维护KSMEPlayer。KSMEPlayer的功能会更强大。KSAVPlayer是系统的播放器。能够做的事情很少

**Comment by matteogobbi** [comment]
Understood.
However KSME has less features at the moment, like for example doesn't Airplay right?
If you choose to implement both players, is because AVPlayer has something more than MEPlayer. Can you explain what are the difference at this time?

ie. Airplay works only on AV

Thank you!

**Comment by Alanko5** [comment]
https://github.com/kingslay/KSPlayer/issues/157#issuecomment-1456987877
