### ISSUE TITLE
Not getting resolution of video

### ISSUE THREAD

**Issue by wertpoiu** [kingslay/KSPlayer#43]
print("Size = \(String(describing: playerView.playerLayer.player?.naturalSize))")

this gives me 

Size = Optional((0.0, 0.0))

I am not getting resolution can you help please @kingslay ?

**Comment by kingslay** [comment]
```

    override open func player(layer: KSPlayerLayer, state: KSPlayerState) {
        super.player(layer: layer, state: state)
        if state == .readyToPlay, let player = layer.player {
            print(player.naturalSize)
            // list the all subtitles
            let subtitleInfos = srtControl.filterInfos { _ in true }
            subtitleInfos.forEach {
                print($0.name)
            }
            subtitleInfos.first?.makeSubtitle { result in
                self.resource?.subtitle = try? result.get()
            }
            for track in player.tracks(mediaType: .audio) {
                print("audio name: \(track.name) language: \(track.language ?? "")")
            }
        }
    }
```

**Comment by wertpoiu** [comment]
> ```
> 
>     override open func player(layer: KSPlayerLayer, state: KSPlayerState) {
>         super.player(layer: layer, state: state)
>         if state == .readyToPlay, let player = layer.player {
>             print(player.naturalSize)
>             // list the all subtitles
>             let subtitleInfos = srtControl.filterInfos { _ in true }
>             subtitleInfos.forEach {
>                 print($0.name)
>             }
>             subtitleInfos.first?.makeSubtitle { result in
>                 self.resource?.subtitle = try? result.get()
>             }
>             for track in player.tracks(mediaType: .audio) {
>                 print("audio name: \(track.name) language: \(track.language ?? "")")
>             }
>         }
>     }
> ```

Player has issue getting resolution of video it always returns 0 , 0

**Comment by kingslay** [comment]
please provide the playback url
