### ISSUE TITLE
HLG returned as Dolby Vision

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#432]
This stream has 10 bits per component, but `KSMEPlayer` returns it is a Dolby Vision, when is instead `HLG`.
After trying with my custom code for `AVPlayer`, indeed, `HLG` is returned.

It's easy to see it's not a Dolby Vision, as this has 10 bits per component, whereas Dolby Vision wants 12.

```
    AmbientViewingEnvironment = {length = 8, bytes = 0x002fe9a03d134042};
    BitsPerComponent = 10;
    CVFieldCount = 1;
    CVImageBufferChromaLocationBottomField = Left;
    CVImageBufferChromaLocationTopField = Left;
    CVImageBufferColorPrimaries = "ITU_R_2020";
    CVImageBufferTransferFunction = "ITU_R_2100_HLG";
    CVImageBufferYCbCrMatrix = "ITU_R_2020";
    Depth = 24;
    FormatName = HEVC;
    FullRangeVideo = 0;
    RevisionLevel = 0;
    SampleDescriptionExtensionAtoms =     {
        dvvC = {length = 24, bytes = 0x010010554000000000000000000000000000000000000000};
        hvcC = {length = 129, bytes = 0x01222000 0000b000 00000000 99f000fc ... 2fe9a03d 13404280 };
    };
    SpatialQuality = 512;
    TemporalQuality = 512;
    VerbatimSampleDescription = {length = 293, bytes = 0x00000125 68766331 00000000 00000001 ... 3d134042 00000000 };
    Version = 0;
 ```

**Comment by Alanko5** [comment]
DV use 10 and 12 bit colors.
Please send your example stream?
I want to see the display criteria

**Comment by matteogobbi** [comment]
from https://kodi.wiki/view/Samples

[Dolby Vision w/embedded HLG HEVC 60fps](https://img.photographyblog.com/reviews/apple_iphone_13_pro/sample_images/4K60p.mov) (in mov, Photography Blog's iPhone 13 Pro raw 4K footage)

**Comment by matteogobbi** [comment]
anything?

**Comment by kingslay** [comment]
我用QuickTime Player 查看视频信息。里面现实的是杜比视界 啊
![image](https://github.com/kingslay/KSPlayer/assets/3964055/b827b536-237b-43eb-a4e1-df619645f046)

**Comment by matteogobbi** [comment]
Interesting
