### ISSUE TITLE
请问下画中画 pictureInPictureControllerTimeRangeForPlayback 这个代理方法 timeRange是如何计算的？

### ISSUE THREAD

**Issue by 12207480** [kingslay/KSPlayer#433]
请问下画中画 pictureInPictureControllerTimeRangeForPlayback 这个代理方法 timeRange是如何计算的？
现在这个timeRange感觉不对 不是当前的进度，而是从头开始

**Comment by kingslay** [comment]
timeRange的开始时间是当前的播放进度，结束时间是 当前的播放进度 + 当前缓冲时间

**Comment by matteogobbi** [comment]
If you check your implementation, it is wrong. First of all it doesn't handle live streaming, second thing it's incorrect for VODs. You already add the playable time. You end up adding it twice. Regardless, it's wrong. Indeed it will either PIP a gray layer or will have a wrong progress bar. I'm talking with Apple spending one of my DTS to understand how to implement it, but I think there's an Apple bug here.

**Comment by matteogobbi** [comment]
This still doesn't work sir.
You can test yourself. The progress bar would quickly load till the end.

Correct behavior:
The progress bar should be set to the current progress and should proceed a peace considering the full duration of the movie. I think there's an Apple bug here.
