### ISSUE TITLE
image base 的字幕切换会卡很久的字幕

### ISSUE THREAD

**Issue by birdmichael** [kingslay/KSPlayer#435]
image base 的字幕切换会卡很久的字幕
但是如果快进在快退一次,就瞬间出现字幕了...
有可能是什么问题呀?

**Comment by kingslay** [comment]
image字幕切换的话。是无法马上出现新的字幕。需要进行seek才能马上出字幕。因为默认是不会解码图片字幕的，图片字幕的内存占用会比较大。

**Comment by birdmichael** [comment]
ok~加一个Subtitle的type在KSSubtitleProtocol 比较好
如果是图片字幕.就手动seek下

**Comment by kingslay** [comment]
MediaPlayerTrack 有isImageSubtitle 这个属性了

**Comment by birdmichael** [comment]
啊? 
我知道MediaPlayerTrack里面有..
但是切换字幕不是只关心SubtitleModel么..他里面现在没有办法查看是否是isImageSubtitle..
所谓我感觉在SubtitleInfo 加一个参数比较好

**Comment by kingslay** [comment]
他们都是FFmpegAssetTrack
extension FFmpegAssetTrack: SubtitleInfo {
