### ISSUE TITLE
PIPing from KSMEPlayer shows a gray layer with a loading spinner.

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#436]
`player.pipController?.playerLayer` (`AVPlayerLayer`) has size `0,0`.

**Comment by matteogobbi** [comment]
![IMG_55866AA66840-1](https://github.com/kingslay/KSPlayer/assets/1998171/20b22a70-3cfb-45fb-926a-7ee0bd42ddb9)
it used to work before

**Comment by matteogobbi** [comment]
now it worked. Sometime works sometime doesn't. Ideas?

**Comment by matteogobbi** [comment]
There's also a further problem:

1. PIP a stream
2. unpip (restore) stream fullscreen
3. change stream url on the same player
4. PIP isn't longer possible

The same code works perfectly when I use AVPlayer underneath instead of KSME.

**Comment by matteogobbi** [comment]
I'm using a custom view, I grab your KSPipController which ineriths from the AVPIPController and I use it to call the AV methods startPIP and stopPIP. What's the correct way to use a custom view and use your start/stop pip?

**Comment by matteogobbi** [comment]
I found the problem:

the KSMEPlayer changes (aka a new one is allocated) every time I change URL.
A new KSPlayerLayer is allocated, and the KSMEPlayer has a different address.

**Comment by matteogobbi** [comment]
https://github.com/kingslay/KSPlayer/assets/1998171/ea491c4f-4492-4af8-9762-126ed1f8efb0

Is it normal that `KSME` player layer changes continuously?
`AVPlayerLayer` doesn't change

**Comment by matteogobbi** [comment]
please this is something I need to understand.

**Comment by matteogobbi** [comment]
Please this is something we need to understand.

**Comment by matteogobbi** [comment]
Anything here?

**Comment by kingslay** [comment]
KSMEplayer 里面的pipController?.playerLayer是没有意义的。他不是通过playerLayer来实现pip的，他是通过contentSource

**Comment by matteogobbi** [comment]
The question is why it keeps changing/being allocated?Also there’s still a pip problem. I have my pip delegate and I use your pip controller. But most of the time is a gray layer. Sent from my iPhoneOn May 23, 2023, at 8:08 AM, kingslay ***@***.***> wrote:﻿
KSMEplayer 里面的pipController?.playerLayer是没有意义的。他不是通过playerLayer来实现pip的，他是通过contentSource

**Comment by matteogobbi** [comment]
trust me, you have a problem on KSME
