### ISSUE TITLE
Airplay video with KSME?

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#437]

**Comment by kingslay** [comment]
不行，苹果只允许AVPlay进行Airplay video。但是也可以破解Airplay，把它用于KSME。但是这个工作量很多。而且apple可能会拒绝应用上架。

**Comment by matteogobbi** [comment]
Yeah but it shouldn't be a problem given that you use Metal and AVSampleBufferDisplayLayer. Worth to ask them as KSME would never replace AVPlayer entirely if it doesn't support Airplay. I think KSME has great potential to beat AVPlayer, assuming it doesn't miss features from AVPlayer. Thanks.
