### ISSUE TITLE
KSME hdr10 grayed out picture

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#439]
The problem can’t be shown as if I take a screenshot the picture is clear.

**Comment by kingslay** [comment]
那是不是你的视频上面增加了一个grayed的view呢？例如字幕之类的。在demo会有这个问题吗？

**Comment by matteogobbi** [comment]
I didn’t try the demo and I think it’s limited to just a few streams. When you start to test more streams you might have more cases to cover. Their effect is like a gray layer above the video and it comes 100% from the metal rendering / system. When i take a screenshot the system doesn’t capture the gray overlay. When I move the app like if I want to put it in background , the gray layer disappears.It is something generates from Metal on iOS and tvOS. Avplayer and vlc do not have any problem. This is a big blocker. Please let’s focus on it. Thank you. Sent from my iPhoneOn May 16, 2023, at 4:40 AM, kingslay ***@***.***> wrote:﻿
那是不是你的视频上面增加了一个grayed的view呢？例如字幕之类的。在demo会有这个问题吗？

**Comment by kingslay** [comment]
你可以提供给你下这个视频的某个片段吗？我下载到本地进行复现下。

**Comment by matteogobbi** [comment]
I don't know how to share with you the original file, but this is what I meant:

[https://we.tl/t-2JNR1xMFaw](https://we.tl/t-2JNR1xMFaw?utm_campaign=TRN_TDL_05&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_05)

**Comment by kingslay** [comment]
你可以直接给我那个原视频的URL吗？不行的话，那你可以试下用vlc进行视频录制。然后你看下录制之后的视频会不会有问题

**Comment by matteogobbi** [comment]
If I record or take screenshots, the gray layer isn't shown in the captured media.
I can't share the link publicly, I can send you the video somehow if you tell me. Or just tell me what to check in your code and I will.

**Comment by matteogobbi** [comment]
sir, anything here? This is a big one for this awesome player.

**Comment by kingslay** [comment]
我这边需要能够复现这个问题，才能帮忙解决这个问题。所以需要有对应的url才可以。

**Comment by matteogobbi** [comment]
there's a way to write to you privately?

**Comment by matteogobbi** [comment]
I see that all HDR10 (4K) return a black overlay.
The primary color and transfer function, first return `kCVImageBufferColorPrimaries_ITU_R_2020` abd `kCVImageBufferTransferFunction_ITU_R_2020`, but then return UNSPECIFIED cases and so:

`return CVColorPrimariesGetStringForIntegerCodePoint(Int32(rawValue))?.takeUnretainedValue()`

**Comment by matteogobbi** [comment]
Devices testes:

- iPad Pro simulator: WORKS WELL
- iPhone 14 Pro Max real device: WORKS WELL
- AppleTV 4K simulator: WORKS WELL
- iPad Air real device: DOESN'T WORK WELL
- AppleTV 4K 2022: DOESN'T WORK WELL

**Comment by kingslay** [comment]
> there's a way to write to you privately?

kingslay@icloud.com

**Comment by matteogobbi** [comment]
I sent you a video HDR 10, please use KSMEPlayer and try it on a real iPad Air and on AppleTV 4Ks

**Comment by matteogobbi** [comment]
pls let me know your thouhgts

**Comment by kingslay** [comment]
我用我的设备试了下，不会有这个问题  Apple TV 4K (3rd generation)。 我没有iPad air。所以无法尝试
