### ISSUE TITLE
Set subtitle fail because all subtitles are enabled. 

### ISSUE THREAD

**Issue by loicleser** [kingslay/KSPlayer#440]
Hi, 
I'm implementing KSPlayer in my app. 

All is working fine but I've a bug when I select subtitle from custom UI. 

here is my code: 

                let index = Int(newValue)
                let allTracks = KSplayerView.playerLayer?.player.tracks(mediaType: .subtitle) ?? []
                var selectedTrack = allTracks[index]
                KSplayerView.playerLayer?.player.select(track: selectedTrack)
                
I verified and the selected track is the correct one (the one I selected on the app)

I noticed that all tracks on allTracks have 'isEnabled = true'... and on the function below from KSPlayer I return at the 'track.isEnabled'

 func select(track: MediaPlayerTrack) {
        if track.isEnabled {
            return
        }
        assetTracks.filter { $0.mediaType == track.mediaType }.forEach {
            if $0.mediaType == .subtitle, !$0.isImageSubtitle {
                return
            }
            $0.isEnabled = false
        }
        track.setIsEnabled(true)
        guard let assetTrack = track as? FFmpegAssetTrack else {
            return
        }
        if assetTrack.mediaType == .video {
            findBestAudio(videoTrack: assetTrack)
        } else if assetTrack.mediaType == .subtitle {
            if assetTrack.isImageSubtitle {
                if !options.isSeekImageSubtitle {
                    return
                }
            } else {
                return
            }
        }
        seek(time: currentPlaybackTime) { _ in
        }
    }
    
Do you have an idea how I can fix that?

**Comment by kingslay** [comment]
你可以看下我的demo。你可以用 subtitleModel.selectedSubtitleInfo 这个方法

**Comment by loicleser** [comment]
Thanks. It works.
