### ISSUE TITLE
Question: how to detect if a video has Dolby Atmos?

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#444]
We have a way to detect Dolby Vision vs HDR10 vs HLG vs SDR, but what about detecting if has Dolby Atmos?

**Comment by kingslay** [comment]
Dolby Atmos 应该是指音频方面的。Dolby Vision vs HDR10 vs HLG vs SDR是视频方面。所以你要判断是否 atmos的话，那应该是要判断音频的格式。我不知道我的理解对不对。我从网上看的资料是这样说的

**Comment by matteogobbi** [comment]
Yes I know it's the audio aspect. That's why I'm saying that we have a way to detect the video quality but not the audio quality. Thx

**Comment by Alanko5** [comment]
If detected codec truehd or dolby mat, then is dolby atmos audio.

**Comment by kingslay** [comment]
@matteogobbi 那你可以用mediaSubType 或是MediaPlayerTrack.descriptioncodecType 来判断音频的格式
