### ISSUE TITLE
Your UI changes isn't thread safe. 

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#447]
Calls to play/pause etc. will make the app crash because they trigger UI changes that aren't main thread safe.

**Comment by kingslay** [comment]
我用KSVideoPlayerView 不会有问题。你的ui是不是自己写的。

**Comment by matteogobbi** [comment]
No no, the problem is on `KSVideoPlayerView` etc.
Try to call `player.pause()` (for example) from a **background thread**.
You will see that the app at some point irregularly will crash. This is because there's no main thread protection in the points there you manipulate the UI (ie setting a button hidden etc).

Consider that I use 3 players, and I had to rebuild my logic only for this player, because it would invoke piece of its inner UI not in the main thread.

This is just a hint to cover your UI parts with an additional `runInMainQueue`.

Thank you.
