### ISSUE TITLE
Crash in MEPlayerItem

### ISSUE THREAD

**Issue by nihalahmed** [kingslay/KSPlayer#449]
I am getting crash reports in MEPlayerItem at the following line:
```
formatContext.options.io(log: log)
```
https://github.com/kingslay/KSPlayer/blob/develop/Sources/KSPlayer/MEPlayer/MEPlayerItem.swift#L111

Please take a look.

**Comment by kingslay** [comment]
这个crash能够复现吗？可以的话，那给下URL

**Comment by nihalahmed** [comment]
Will try to find one

**Comment by nihalahmed** [comment]
Crash is happening because `av_log_set_callback` is not cleared so when another library calls av_log, your callback gets called, causing the crash.

**Comment by kingslay** [comment]
是因为formatContext = nil 导致的吗？

**Comment by nihalahmed** [comment]
Am not sure, could be. The error is ` EXC_BAD_ACCESS (KERN_INVALID_ADDRESS) `.
I think you should set the callback to nil in `deinit` of `MEPlayerItem` so that it doesn't get called.

**Comment by kingslay** [comment]
av_log_set_callback 是一个全局的函数。如果进行清空的话。那可能会导致无法输出日志了。因为在切换视频的时候。有可能先走MEPlayerItem的init方法，然后再走MEPlayerItem的deinit方法。
