### ISSUE TITLE
Playback Error

### ISSUE THREAD

**Issue by snappycode1** [kingslay/KSPlayer#45]
When seeking through an MKV multiple times, sometimes the video freezes.  the sound is still playing and there is a spinning activity spinner at the centre of the screen.  This is the output in the xcode debugger

```
KSPlayer: KSMEPlayer.swift:259 play() | play KSPlayer.KSMEPlayer
KSPlayer: KSPlayerLayer.swift:100 state | playerStateDidChange - bufferFinished
2020-07-22 17:20:14.405145+0800 Snappy IPTV[4270:4990322] [CAMetalLayerDrawable texture] should not be called after already presenting this drawable. Get a nextDrawable instead.
```

then after a short while the app will crash and outputs :

```
2020-07-22 17:22:43.357929+0800 Snappy IPTV[4270:4990457] Execution of the command buffer was aborted due to an error during execution. Discarded (victim of GPU error/recovery) (IOAF code 5)
2020-07-22 17:22:43.358099+0800 Snappy IPTV[4270:4990457] Execution of the command buffer was aborted due to an error during execution. Discarded (victim of GPU error/recovery) (IOAF code 5)
KSPlayer: KSMEPlayer.swift:264 pause() | pause KSPlayer.KSMEPlayer
KSPlayer: KSPlayerLayer.swift:100 state | playerStateDidChange - paused
```

This happens regardless of the MKV being viewed.

**Comment by kingslay** [comment]
can you provide the mkv url

**Comment by kingslay** [comment]
can you provide the mkv url?

**Comment by snappycode1** [comment]
Seems to have corrected itself.  I will reopen if needed.

**Comment by snappycode1** [comment]
ok, I have narrowed this down.

If media is playing and you want to start playing a new media, when the new media starts playing the UI hangs and there is a spinning activity spinner in the middle of the screen.  The audio plays fine.

```
KSPlayer: KSPlayerLayer.swift:100 state | playerStateDidChange - bufferFinished
2020-07-24 03:02:10.584339+0800 Snappy IPTV[321:35008] [CAMetalLayerDrawable texture] should not be called after already presenting this drawable. Get a nextDrawable instead.

```
It doesn't matter what media format is used, as long as you play one media straight after another.

In my example, when a tv series episode is near the end, a button is displayed that prompts the user to start watching the next episode.  This is where the issue arises.

It's possible I am doing something wrong.

```
if let newURL = URL(string: currentEpisodeArray!.fullUrl) {

                playerView.resetPlayer()
                
                asset = nil
                
                let res0 = KSPlayerResourceDefinition(url: newURL, definition: "HD")
                    asset = KSPlayerResource(name: programmeName, definitions: [res0], cover: nil)

                playerView.set(resource: asset!)

                playerView.play()

```

**Comment by kingslay** [comment]
you is use  `player.replace(url: url, options: options)` ?

**Comment by snappycode1** [comment]
I wasn't using that option.  I am using KSPlayerResource so I can access the subtitles in 

`override open func player(layer: KSPlayerLayer, state: KSPlayerState) {
`

using player.replace, the media just stops and displays this :

```
KSPlayer: KSMEPlayer.swift:207 replace(url:options:) | replaceUrl KSPlayer.KSMEPlayer
KSPlayer: KSMEPlayer.swift:273 shutdown() | shutdown KSPlayer.KSMEPlayer
KSPlayer: KSPlayerLayer.swift:100 state | playerStateDidChange - bufferFinished
KSPlayer: KSPlayerLayer.swift:100 state | playerStateDidChange - buffering
KSPlayer: MEPlayerItem.swift:389 shutdown() | 清空formatCtx
```

So if I am using KSPlayerResource like in your example :

```
let res0 = KSPlayerResourceDefinition(url: URL(string: "http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4")!,
                                      definition: "高清")
let res1 = KSPlayerResourceDefinition(url: URL(string: "http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4")!,
                                      definition: "标清")
   
let asset = KSPlayerResource(name: "Big Buck Bunny",
                             definitions: [res0, res1],
                             cover: URL(string: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Big_buck_bunny_poster_big.jpg/848px-Big_buck_bunny_poster_big.jpg"))
playerView.set(resource: asset)

```
How can I play a new media straight after another media?

**Comment by snappycode1** [comment]
Got any feedback on this issue kingslay?

**Comment by snappycode1** [comment]
On further investigation I think this is an issue that arises if you seek the video using

```
    @IBAction func sliderChanged(_ sender: UISlider) {
        playerView.seek(time: Double(sender.value))
    }
```

I have channel zapping on live tv and it doesn't have an issue with quickly changing media url.

It only happens if I seek a video then try and play another media file without leaving the screen (viewcontroller)

Dunno if that helps to narrow the issue down or not.

**Comment by snappycode1** [comment]
On further investigation I think this is an issue that arises if you seek the video using

```
    @IBAction func sliderChanged(_ sender: UISlider) {
        playerView.seek(time: Double(sender.value))
    }
```
I have channel zapping on live tv and it doesn't have an issue with quickly changing media url.

It only happens if I seek a video then try and play another media file without leaving the screen (viewcontroller)

Dunno if that helps to narrow the issue down or not.

You can use any video files.

**Comment by kingslay** [comment]
i had update the code. you can try again

**Comment by snappycode1** [comment]
I tried that code earlier as I noticed you made changes.  It fixes it slightly bit its still an issue.

**Comment by snappycode1** [comment]
I am almost certain it is related to playerView.seek(time: )

If I watch a tv episode and don't use seek, the play next episode button plays the next episode ok.  If I use seek, it doesn't work.

Sometimes when using the slider and playerView.seek(time : ) the video freezes and the audio continues to play.  I'm sure this is the same issue.

**Comment by kingslay** [comment]
Can you reproduce it on the demo

**Comment by snappycode1** [comment]
I can't update the demo because the code involved is massive.  i dont use the built in gestures, I've implemented seek myself.

When the slider is moved I simply call

```
@IBAction func sliderChanged(_ sender: UISlider) {
        playerView.seek(time: Double(sender.value))
    }
```

**Comment by snappycode1** [comment]
Here is the output in debugger :
```
SPlayer: KSMEPlayer.swift:263 play() | play KSPlayer.KSMEPlayer
KSPlayer: KSPlayerLayer.swift:267 changeLoadState(player:) | ["prepareTime": 0.0006280833331402391, "findTime": 1.110171291671577, "readVideoTime": 1.1592579999996815, "readAudioTime": 1.1607740833278513, "firstTime": 2.4884292083297623, "decodeAudioTime": 1.1664960000052815, "openTime": 1.0537572916655336, "decodeVideoTime": 1.1865029583277646]
KSPlayer: KSPlayerLayer.swift:100 state | playerStateDidChange - bufferFinished
2020-07-27 18:42:12.046894+0800 Snappy IPTV[1035:389359] [CAMetalLayerDrawable texture] should not be called after already presenting this drawable. Get a nextDrawable instead.
2020-07-27 18:42:12.049168+0800 Snappy IPTV[1035:389653] [CAMetalLayerDrawable present] should not be called after already presenting this drawable. Get a nextDrawable instead.
2020-07-27 18:42:18.890673+0800 Snappy IPTV[1035:389665] Execution of the command buffer was aborted due to an error during execution. Caused GPU Timeout Error (IOAF code 2)
2020-07-27 18:42:18.890840+0800 Snappy IPTV[1035:389665] Execution of the command buffer was aborted due to an error during execution. Caused GPU Timeout Error (IOAF code 2)
2020-07-27 18:42:18.891097+0800 Snappy IPTV[1035:389665] Execution of the command buffer was aborted due to an error during execution. Discarded (victim of GPU error/recovery) (IOAF code 5)
2020-07-27 18:42:18.891201+0800 Snappy IPTV[1035:389665] Execution of the command buffer was aborted due to an error during execution. Discarded (victim of GPU error/recovery) (IOAF code 5)
....
2020-07-27 18:42:18.891201+0800 Snappy IPTV[1035:389665] Execution of the command buffer was aborted due to an error during execution. Discarded (victim of GPU error/recovery) (IOAF code 5)
repeats for ever
...
```
seek works sometimes but others it just displays the above logging

**Comment by kingslay** [comment]
You can see if you call seek frequently.

**Comment by snappycode1** [comment]
If I call seek frequently on the same video, the same freezing issues arises.  The only difference is that the frame is paused and sound plays - instead of a black screen and sound playing.

**Comment by snappycode1** [comment]
Is this likely to be looked into or fixed?  seek is definitely the issue.  if it can't be fixed, then I will have to find another media player option sadly, I like KSplayer.

**Comment by kingslay** [comment]
Mainly because I don't have a demo here, I can't reproduce this problem. You need to update the demo.

**Comment by kingslay** [comment]
You can't  call seek Very frequently

**Comment by snappycode1** [comment]
Course you can.  use a slider to seek to seek to a position then use it again to seek further on, then keep repeating.
The first seeked position might not be what the user wants, so they seek further.

Updating the demo is no point, as it's of no value to other people.

I understand you can't replicate the issue so I'll call it quits here.  thanks for the all the help so far.
