### ISSUE TITLE
Failing live stream cause call to `playerController(finish error: Error?)` with a nil error

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#451]
A live stream cannot play to the end. When it stop, it's because there's an error. Ie. if the server interrupts a live stream, it should be considered an error. Therefore, `playerController(finish error: Error?)` should get a non-nil error.

**Comment by kingslay** [comment]
这个是因为ffmpeg返回的错误是eof。

**Comment by matteogobbi** [comment]
Well, the problem remains.

**Comment by kingslay** [comment]
服务端断开一段时间的话，那可能就会被认为是eof了。这个是ffmpeg里面的逻辑。我这边是无法控制的。
