### ISSUE TITLE
[URGENT] PIP doesn't work on Demo tvOS app

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#459]
Why is `pictureInPictureControllerTimeRangeForPlayback` not called from tvOS?

My KSME PIP isn't working ONLY on tvOS. I realized that ONLY on tvOS, the PIP delegate methods including`pictureInPictureControllerTimeRangeForPlayback` don't get called.

Therefore, while on iOS PIP works properly, on tvOS doesn't work.

Into the Demo app also doesn't work.

**Comment by UnknownCoder807** [comment]
@kingslay is PiP possible on tvOS?  The Apple TV+ App has it.

Can you work your magic and make it work?

**Comment by matteogobbi** [comment]
PIP is possible in tvOS. With AVPlayer it works properly. With KSME it used to work too during my tests, not it no longer does. Not even in the demo.

**Comment by matteogobbi** [comment]
Hello, has PIP been disable on tvOS?

**Comment by matteogobbi** [comment]
@kingslay ?

**Comment by kingslay** [comment]
这个应该的是tvos不支持非avplayer的pip。

**Comment by matteogobbi** [comment]
Actually not true: I was able to PIP with KSME, until when it started to not work anymore. But I swear it was possible.
You should put it back and try to understand what's changed in the last month that broke it.

**Comment by kingslay** [comment]
最新没有改pip 是不是升级了新的版本tvOS导致pip失效了。你还能找到老的可以pip的me代码
