### ISSUE TITLE
希望可以支持8K视频解码

### ISSUE THREAD

**Issue by FantasyKingdom** [kingslay/KSPlayer#460]
当前的SDK已经很好用了，但是无法解码8k视频。做影视剪辑这块经常会用到8k视频素材，目前ksplayer无法解码，软解硬解都不支持。以目前的mac和新款ipad，iPhone来说，性能是完全足够的。希望能支持一下，毕竟8K是发展趋势。

**Comment by kingslay** [comment]
你用到的视频格式是什么呢？你可以用ffmpeg -i url 来查看对应的视频信息。然后我加一下对应的解码器

**Comment by FantasyKingdom** [comment]
升级到ffmpeg6.0可以解码了，谢谢
