### ISSUE TITLE
`KSME` + live `.ts` format would crash after 2 mins

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#463]
You might have a memory problem or something else:

Using `KSMEPlayer` and playing `.ts` format, would make the app crash after 2 minutes.
This is reproducible at 100% at least on iOS real devices.

Multiple users reported this problem and I also verified it.

**Comment by kingslay** [comment]
能够提供那个url吗？

**Comment by matteogobbi** [comment]
No but you can use any .ts format stream url

**Comment by kingslay** [comment]
我在网上找不到 .ts format stream url.  如果你有找到的话，麻烦发给我下。我才能解决这个问题

**Comment by matteogobbi** [comment]
I'll look for that. In the meantime someone said is also crashing with m3u8 live stream after a couple of minutes of streaming.

**Comment by matteogobbi** [comment]
I noticed this btw - after deallocating the KSPlayer, I see these remains allocated:

<img width="763" alt="Screenshot 2023-06-09 at 6 11 51 PM" src="https://github.com/kingslay/KSPlayer/assets/1998171/66df9da0-f949-4188-96e4-a7262e42fe3d">
