### ISSUE TITLE
OpenSSL still crashing on latest version. See logs

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#467]
<img width="561" alt="Screenshot 2023-06-11 at 6 31 05 PM" src="https://github.com/kingslay/KSPlayer/assets/1998171/7f077c46-33a5-4706-9d46-ce0758b0e9fd">

**Comment by kingslay** [comment]
你的openssl用的是那个版本？不能用最新的openssl。他们最近的版本有太多的bug了，不要用。目前只有3.0.7版本是比较稳当的。如果你发下3.0.7版本也有crash的。那就要用低于3.0.7版本的openssl。你可以到论坛问下那个版本的openssl是最稳定的。

**Comment by matteogobbi** [comment]
I'm using your OpenSSL main branch.

**Comment by matteogobbi** [comment]
We'll see if this is solved now (I updated to your branch yesterday). But the other one I opened is still happening.

**Comment by matteogobbi** [comment]
Hello @kingslay, can you please help me understand this?
I'm using your OpenSSL lib, but we still see several crashes with OpenSSL. Which is the best repo to report this problem directly to them?

**Comment by kingslay** [comment]
https://github.com/openssl/openssl

**Comment by matteogobbi** [comment]
thank you.

**Comment by matteogobbi** [comment]
BTW what is OpenSSL used for in the context of Metal?

**Comment by kingslay** [comment]
metal不会用到openssl。是网络请求会用到openssl。例如https，srt
