### ISSUE TITLE
Frame rate 25fps going slow-motion for live streams

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#468]

**Comment by matteogobbi** [comment]
This is still happening although the recent FPS fix.

**Comment by pexavc** [comment]
@matteogobbi have you tried setting this value to `-1`? https://github.com/kingslay/KSPlayer/blob/dd5297153c8d116162cfcfb6b827ae6b98a9cd5d/Sources/KSPlayer/AVPlayer/KSOptions.swift#L92

**Comment by matteogobbi** [comment]
nice thanks I'll try!

**Comment by chillout23** [comment]
Any update on this? KSLib is playing all 50/60FPS streams smoothly but 25/30fps streams are stuttering more than they should. It is unwatchable. @matteogobbi, did that fix suggested here work?

**Comment by matteogobbi** [comment]
I didn't try it because the users that originally reported the problem, seem no longer complaining. However I noticed some shuttering in some high quality movies using KSME that with other players work well. But I'm not sure what the fps was.

**Comment by pexavc** [comment]
@chillout23 I played around with monitoring HLS streams over the weekend. Especially ones where frame rate changes mid-stream. Such as an 60fps stream that leads into a 24FPS ad in between.

> This is assuming you are using Metal/MEPlayer for Stream viewing. 

I noticed this may be the case if FPS was not being properly updated on CVDisplayLink on macOS. The preferred frame rate variable is not functional on macOS as it is on iOS. I also made my own version of MEPlayer that uses the draw callback from MTKView instead as the render loop. While having a SwiftUI representable of MTKView installed in my main view. Then I properly update the fps of the MTKView when changes are detected via a .environment extension.

I had also encountered another issue where if 24FPS ads are interlaced with the 60FPS stream the entire stream would break/become out of sync etc. to resolve this I setup a restart flow for KSPlayerItem and created a timer object that would probe the codec of the stream every 3~ seconds to detect FPS differences with the current live stream, on a background thread (the resource usage is not high at all). If there’s a change all codecs get updated and the MTKView’s FPS updates as well. This made watching a stream really reliable so far. Although I feel it’s still not perfect yet as there’s still a bit of stuttering but it’s still watchable on <=30fps streams. 

Hope it gives an idea or this helps out in some way. I am away from my computer currently. But, if you need some more insight code wise I can provide some examples for specific clarifications. If they truly are valid I can make a PR. And see what the owner thinks.

**Comment by kingslay** [comment]
@pexavc 我之前也有用过MTKView的draw(in:)。但是这个会卡顿 。但我忘了是在什么情况下会卡顿。可能是4k或是mac屏幕最小化一会儿然后回到前台。还有一个不行的消息是MTKView在visionOS不能用。所以MTKView的方案不行。还是需要找到根本的原因。看下为什么fps交错的流在mac下会卡顿。

**Comment by pexavc** [comment]
@kingslay oh interesting, thanks for the note about visionOS. I will do more digging around the root cause

**Comment by matteogobbi** [comment]
This isn’t just about macOS. The best use case is tvOS. Sent from my iPhoneOn Jul 7, 2023, at 3:47 PM, PEXAVC ***@***.***> wrote:﻿
@kingslay oh interesting, thanks for the note about visionOS. I will do more digging around the root cause

**Comment by chillout23** [comment]
Basically every 25 fps stream is not playing correct with this player. But I am talking about Live TV now. Movies at 24 fps they also work great!

I will make some examples in this thread https://github.com/kingslay/KSPlayer/issues/493
I will be comparing to VLC and make some videos when I have some time later :)

**Comment by chillout23** [comment]
So I made some videos to show what I mean. @matteogobbi this is with your IPTVX app :-)

https://github.com/kingslay/KSPlayer/issues/493#issuecomment-1626031012

**Comment by pexavc** [comment]
@kingslay could this possibly be CVDisplayLink is unable to sync with certain refresh rates and CAMetalLayers?

https://stackoverflow.com/questions/76598416/mtkview-or-cametallayer-cvdisplaylink-stuttering-in-fullscreen

**Comment by chillout23** [comment]
@pexavc, what could be the reason 50/60 fps streams work great without stuttering do you think? Technically those streams could also be stuttering.

**Comment by pexavc** [comment]
@chillout23 

If `currentRenderPassDescriptor/currentDrawable calls are all stalls` is the culprit. I'll have to profile the CPU/GPU again to confirm that it is in-fact stalling only on 30FPS and not on 60FPS for my 60Hz monitor. Since it doesn't make sense for a lower FPS to stall on a higher refresh rate.

If it is, the source of the issue might be somewhere here? 

When the draw is invoked:
https://github.com/kingslay/KSPlayer/blob/552f8e2e52deafcdf85cae0c49100656ff35a9fd/Sources/KSPlayer/MEPlayer/MetalPlayView.swift#L185

Into MetalRender:
https://github.com/kingslay/KSPlayer/blob/552f8e2e52deafcdf85cae0c49100656ff35a9fd/Sources/KSPlayer/Metal/MetalRender.swift#L77-L98

Maybe how textures are rendered from the buffer prior to insertion:
https://github.com/kingslay/KSPlayer/blob/dcb83d6c1a540fab093ab7e93c7b340cdad448e8/Sources/KSPlayer/Metal/MetalRender.swift#L140-L162

Or something with how the Shaders are sampling?
https://github.com/kingslay/KSPlayer/blob/dcb83d6c1a540fab093ab7e93c7b340cdad448e8/Sources/KSPlayer/Metal/Shaders.metal

**Comment by chillout23** [comment]
Thanks for your reply. 50 / 60 FPS streams does not stutter at all, they are silky smooth. But nice if more people can test with preferably different Apple TVs and post some results. For now my conclusion is that there is a huge bug in KSPlayer as this does not happen with VLC / MPV and other players. I have also tried Lilly Player, iPlay TV and different apps which has KSPlayer as engine and they behave the same, so I think it should be something in the code.

**Comment by chillout23** [comment]
@matteogobbi https://github.com/kingslay/KSPlayer/issues/493#issuecomment-1627400841
Something you should look into :)

**Comment by matteogobbi** [comment]
#493 is a dupe of this

**Comment by chillout23** [comment]
Is this also fixed as https://github.com/kingslay/KSPlayer/issues/493 is closed now?

**Comment by kingslay** [comment]
@matteogobbi 可以麻烦你看下这个问题是否还会存在吗？#493这个问题是视频帧的间隔不均匀，一会儿快，一会儿慢。但是这个问题是不是指视频一直播放很慢。

**Comment by matteogobbi** [comment]
If for @chillout23 works, is good with me.
