### ISSUE TITLE
[URGENT] [Crash] from `KSPlayer_MEPlayerItem_open` with `srt::FileCC::onRTO(srt::ETransmissionEvent, srt::EventVariant)`

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#469]
`KSPlayer_MEPlayerItem_open` for several people would crash with `srt::FileCC::onRTO(srt::ETransmissionEvent, srt::EventVariant)`

https://en.wikipedia.org/wiki/Secure_Reliable_Transport

**Comment by kingslay** [comment]
这个应该也是openssl导致的。srt依赖openssl

**Comment by matteogobbi** [comment]
still happens in the last version of OpenSSL

**Comment by matteogobbi** [comment]
Which version of OpenSSL you use? I use yours. Are you sure you shouldn't update that?

**Comment by kingslay** [comment]
我是用3.0.7版本（就是FFmpegKit的main分支），不会有问题。你可以给下会导致crash的url吗？我这边看下能不能复现

**Comment by kingslay** [comment]
那你本地用srt的url进行播放，会crash吗？

**Comment by matteogobbi** [comment]
I don’t have idea what’s a srt url. I thought that was a .ts format url. Do you know?

**Comment by matteogobbi** [comment]
should I point to 3.0.7? I use your pod, as in your demo. But I see OpenSSL 3.1.0 gets installed.

**Comment by kingslay** [comment]
只是pod上的版本号没有更新。真正的版本号是3.0.7

**Comment by matteogobbi** [comment]
Ok. Anyway this is the version I have and it crashes. Sent from my iPhoneOn Jun 16, 2023, at 3:28 AM, kingslay ***@***.***> wrote:﻿
只是pod上的版本号没有更新。真正的版本号是3.0.7

**Comment by matteogobbi** [comment]
@kingslay we should reopen this please.
I contacted OpenSSL guys and this seems to come from something related to Live Streaming most probably.
Does your player support well live streaming. Can you help looking into this?

For more info:

https://github.com/Haivision/srt
