### ISSUE TITLE
关于画中画的进度条

### ISSUE THREAD

**Issue by FantasyKingdom** [kingslay/KSPlayer#471]
视频播到50%左右，开启画中画，但是画中画的进度条是从0开始的。这个画中画的进度要如何正确设置。

**Comment by FantasyKingdom** [comment]
在AVPictureInPictureSampleBufferPlaybackDelegate中也就 
public func pictureInPictureControllerTimeRangeForPlayback(_: AVPictureInPictureController) -> CMTimeRange 
这个方法会给系统返回一个可播放的时间范围。但是没找到其它有关返回当前时间以及总时间的的方法。是要通过其它途径进行设置吗？

**Comment by matteogobbi** [comment]
I reported this too in a different thread. I also spent my token talking with apple devs, but they told me obvious solutions had already tried and then disappeared. I'm 100% sure that there's an Apple bug, as usual.

**Comment by FantasyKingdom** [comment]
问题解决了，需要这样改

1.在pictureInPictureControllerTimeRangeForPlayback返回总时间
public func pictureInPictureControllerTimeRangeForPlayback(_: AVPictureInPictureController) -> CMTimeRange {
        // CMTimeRange为总时间范围duration
}

2. 进度发生改变实时设置displayLayer的controlTimebase为当前时间。如果要节省性能可以只在每次seek时设置一次
 CMTimebaseSetTime(controlTimebase, time: CMTimeMake(value: Int64(curentTime), timescale: 1))
 CMTimebaseSetRate(controlTimebase, rate: 1.0)

**Comment by kingslay** [comment]
> 问题解决了，需要这样改
> 
> 1.在pictureInPictureControllerTimeRangeForPlayback返回总时间 public func pictureInPictureControllerTimeRangeForPlayback(_: AVPictureInPictureController) -> CMTimeRange { // CMTimeRange为总时间范围duration }
> 
> 2. 进度发生改变实时设置displayLayer的controlTimebase为当前时间。如果要节省性能可以只在每次seek时设置一次
>    CMTimebaseSetTime(controlTimebase, time: CMTimeMake(value: Int64(curentTime), timescale: 1))
>    CMTimebaseSetRate(controlTimebase, rate: 1.0)

谢谢你帮忙找到解决办法。

**Comment by matteogobbi** [comment]
@kingslay you need to apply the same changes for the `startTime` > 0 case (which currently doesn't trigger it).

**Comment by kingslay** [comment]
@matteogobbi  duration已经有减去startTime了。所以这个进度条应该是正常的。
```
 duration = TimeInterval(max(formatCtx.pointee.duration, 0) / Int64(AV_TIME_BASE))
        if duration > startTime {
            duration -= startTime
        }
```

**Comment by matteogobbi** [comment]
I'll check. I tested it and when I set startTime, and then PIP, the progress bar isn't correct, until when I seekTo.

**Comment by kingslay** [comment]
> I'll check. I tested it and when I set startTime, and then PIP, the progress bar isn't correct, until when I seekTo.

@matteogobbi  你是指KSOptions的startPlayTime，还是MEPlayerItem的startTime

**Comment by matteogobbi** [comment]
KSOptions

**Comment by Kimentanm** [comment]
这个issue fix后，画中画完全失效了，触发画中画之后一直在灰屏loading

**Comment by kingslay** [comment]
是不是直播的视频会一直灰屏loading。有结束时间的视频应该不会吧

**Comment by Kimentanm** [comment]
@kingslay 嗯嗯，只有直播会灰屏loading

**Comment by FantasyKingdom** [comment]
对于直播这类没有长度的视频，需要将以下方法CMTimeRange的值返回为
CMTimeRange(start: Double.leastNormalMagnitude , end: Double.infinity)

public func pictureInPictureControllerTimeRangeForPlayback(_: AVPictureInPictureController) -> CMTimeRange {
      if (xxx){  
        return yyy
        }else{   //直播视频
        return CMTimeRange(start: Double.leastNormalMagnitude , end: Double.infinity)
      }
}
