### ISSUE TITLE
Using formatContext in MEPlayerItem

### ISSUE THREAD

**Issue by nightfall708** [kingslay/KSPlayer#472]
Hi,

I am trying to access a property of MEPlayerItem while in the log context `av_log_set_callback { ptr, level, format, args) ...` but apparently I can't use "self" because it's a c callback. 
So I tried using formatContext which is basically `MEPlayerItem`. But when I try to access a property (e.g. metadata) I crash on "Simultaneous accesses to 0x11af48810, but modification requires exclusive access." 
Any idea how I can access this property while in the log callback?

Thanks!

**Comment by kingslay** [comment]
目前只有URLContext才能获取到MEPlayerItem。你可以参考我的代码。你的那个日志的 ptr的类型是什么呢？
   let avclass = ptr.assumingMemoryBound(to: UnsafePointer<AVClass>.self).pointee
                if avclass.pointee.category == AV_CLASS_CATEGORY_NA, avclass == &ffurl_context_class {
                    let context = ptr.assumingMemoryBound(to: URLContext.self).pointee
                    if let opaque = context.interrupt_callback.opaque {
                        let playerItem = Unmanaged<MEPlayerItem>.fromOpaque(opaque).takeUnretainedValue()
                        playerItem.options.io(log: log)
                        if log.starts(with: "Will reconnect at") {
                            playerItem.videoTrack?.seekTime = playerItem.currentPlaybackTime
                            playerItem.audioTrack?.seekTime = playerItem.currentPlaybackTime
                        }
                    }
                }

**Comment by nightfall708** [comment]
My log is StreamTitle update. I need to call a delegate of MEPlayerItem to call it when it's updated. So I need to access self.metadata from this block

**Comment by kingslay** [comment]
那你可以发现StreamTitle update之后。就发一个kvo。然后重新获取下MEPlayerItem的metadata就可以了。StreamTitle update的
```
extension MEPlayerItem {
    var metadata: [String: String] {
        toDictionary(formatCtx?.pointee.metadata)
    }
```
你可以把那个日志的内容发出下吗？
