### ISSUE TITLE
是否支持多线程请求？

### ISSUE THREAD

**Issue by FaiChou** [kingslay/KSPlayer#473]
有些视频限制下载速度，导致缓冲很慢，使用多线程可以加快一下缓冲。
比如夸克网盘的视频。

**Comment by kingslay** [comment]
那这个就要看下ffmpeg是否支持多线程加载视频了。

**Comment by FaiChou** [comment]
哦我理解错了，网盘文件是可以多线程下载，最终将下载完的 part 合并。但视频缓冲只能从开头往前缓冲，多线程缓冲的部分不一定是要播放的，所以慢的话没法解决。

请问 preferredForwardBufferDuration 和 maxBufferDuration 是否是请求时候对视频文件的 range 字段？
@kingslay

**Comment by FaiChou** [comment]
看到 alist 针对夸克网盘的文件是进行了 10MB 的切片，可能会提升视频缓冲效律（未验证）
https://github.com/alist-org/alist/blob/main/drivers/quark_uc/driver.go#L91

**Comment by kingslay** [comment]
那这个就是要自己实现一个下载协议了。进行多线程下载了。ffmepg是支持自定义下载协议的

**Comment by kingslay** [comment]
可以试下改下   decoderOptions["threads"] = "auto" 这个值。看下有没有效果。改成那个4之类的
