### ISSUE TITLE
问题请教，如何使用本库或者 FFmpegKit 将苹果系统不支持的 mkv 格式视频解码给系统播放器？

### ISSUE THREAD

**Issue by FaiChou** [kingslay/KSPlayer#475]
端午节安康。

如题，由于苹果系统本身不支持 mkv 的视频格式。所以选择了本库，但是在 tvOS 端定制播放器会有一些问题，代码越来越难维护。

所以想，如何将 mkv 等不支持的视频格式，通过本库或者 FFmpegKit 解码给系统播放器。

能否给个例子？（SwiftUI）

**Comment by kingslay** [comment]
这个能力今天的wwdc有推出这个能力。但是这个能力只是macos有。其他都没有
