### ISSUE TITLE
Metal Airplay Video only cast audio

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#478]
Hello @kingslay, I see you have support for `CAMetalLayer` and AirplayView, however, when I try to airplay, it only casts audio (not video). I'm not using your interface, I have a Custom interface. Is airplay video supported?

**Comment by kingslay** [comment]
不支持的，AirplayView只有avplayer才能进行视频播放

**Comment by matteogobbi** [comment]
gotcha. Thx
