### ISSUE TITLE
截图Function失败

### ISSUE THREAD

**Issue by hippiefox** [kingslay/KSPlayer#479]
KSMEPlayer

    public func thumbnailImageAtCurrentTime() async -> UIImage? {
        await videoOutput?.pixelBuffer?.cgImage()?.image()
    }

每次调用这个功能 都无法获取到当前帧的截图呢？求解

**Comment by kingslay** [comment]
我在macOS下试了，是可以的
```
 if timemodel.currentTime == 2 {
            Task {
                let image = await layer.player.thumbnailImageAtCurrentTime()
                if let imageRep = NSBitmapImageRep(data: image!.tiffRepresentation!) {
                    if let data = imageRep.representation(using: .png, properties: [:]) {
                        let moviesDirectory = try? FileManager.default.url(for: .moviesDirectory, in: .userDomainMask, appropriateFor: nil, create: false)
                        let url = moviesDirectory?.appendingPathComponent("copy.png")
                        do {
                            try data.write(to: url!)

                        } catch {
                            print(error)
                        }
                    }
                }
            }
        }
```

**Comment by hippiefox** [comment]
Task {
                    if let p = playerView.playerLayer?.player {
                        if let img = await p.thumbnailImageAtCurrentTime() {
                            let resultImage = UIImage(cgImage: img)
                            coverImageView.image = resultImage
                        }
                    }
                }
在iOS平台下， 当播放器是KSMEPlayer时，直接从内存里读结果，显示的是一张透明图呢

**Comment by kingslay** [comment]
我用iOS模拟器是不会透明图的。是不是那个时候还没画面。
