### ISSUE TITLE
如何使用内部字幕呢？

### ISSUE THREAD

**Issue by aningxu** [kingslay/KSPlayer#48]
我成功打印出了字幕信息
            let tracks = player.tracks(mediaType: .audio)
            let track = tracks[1]
            let subtitle = player.tracks(mediaType: .subtitle)
            print(subtitle)

            player.select(track: track)

如何像使用音轨一样使用他呢？

**Comment by kingslay** [comment]
```
   override open func player(layer: KSPlayerLayer, state: KSPlayerState) {
        super.player(layer: layer, state: state)
        if state == .readyToPlay, let player = layer.player {
            print(player.naturalSize)
            // list the all subtitles
            let subtitleInfos = srtControl.filterInfos { _ in true }
            subtitleInfos.forEach {
                print($0.name)
            }
            subtitleInfos.first?.makeSubtitle { result in
                self.resource?.subtitle = try? result.get()
            }
            for track in player.tracks(mediaType: .audio) {
                print("audio name: \(track.name) language: \(track.language ?? "")")
            }
        }
    }
```

**Comment by aningxu** [comment]
此代码提示：Value of type 'SubtitleInfo' has no member 'makeSubtitle'

**Comment by kingslay** [comment]
更新下最新的代码

**Comment by aningxu** [comment]
tvOS上没有这个方法。
我昨天更新的

**Comment by aningxu** [comment]
pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `KSPlayer` from `https://github.com/kingslay/KSPlayer.git`, branch `master`
Pre-downloading: `Openssl` from `https://github.com/kingslay/KSPlayer.git`, branch `master`
Downloading dependencies
Installing KSPlayer 1.0
Installing Openssl 1.1.1
Generating Pods project
Integrating client project
Pod installation complete! There are 2 dependencies from the Podfile and 2 total pods installed.

[!] Automatically assigning platform `tvOS` with version `14.0` on target `XXX` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

更新显示版本还是1.0呢。

**Comment by kingslay** [comment]
用最新的 develop分支

**Comment by aningxu** [comment]
![WX20200731-172402](https://user-images.githubusercontent.com/68496559/89021269-d1de3080-d352-11ea-9070-19db27938b2a.png)

上面的方法，不能显示webvtt字幕。


let subtitle = player.tracks(mediaType: .subtitle)
print(subtitle)
这样可以打印出webvtt字幕的信息，但是如何使用他呢。

![WX20200731-172746](https://user-images.githubusercontent.com/68496559/89021493-33060400-d353-11ea-8280-499792dc1f0b.png)

**Comment by kingslay** [comment]
如果是用avplayer的话，那直接用    
`player.select(track: track)
`就可以了。avplayer你需要在设备上开启字幕功能。才能显示。

**Comment by aningxu** [comment]
该视频使用  KSMEPlayer 才能播放

**Comment by kingslay** [comment]
麻烦你提供下视频的url。我试下

**Comment by aningxu** [comment]
请查看您的邮箱，我前几天发了邮件给您。
现在的情况是，在真机测试，webvtt的字幕能正常显示，另外一种基于图形的字幕能显示字幕轨道信息，但是不能在屏幕显示。

我用的代码如下：
            let audio = player.tracks(mediaType: .audio)
            let subtitle = player.tracks(mediaType: .subtitle)
            
            print(audio)
            print(subtitle)

            player.select(track: audio[0])
            player.select(track: subtitle[0])

**Comment by kingslay** [comment]
基于图形的字幕现在还不支持。现在只支持这几种格式的字幕
CONFIGURE_FLAGS="$CONFIGURE_FLAGS --enable-decoder=ass"
CONFIGURE_FLAGS="$CONFIGURE_FLAGS --enable-decoder=srt"
CONFIGURE_FLAGS="$CONFIGURE_FLAGS --enable-decoder=ssa"
CONFIGURE_FLAGS="$CONFIGURE_FLAGS --enable-decoder=movtext"
CONFIGURE_FLAGS="$CONFIGURE_FLAGS --enable-decoder=subrip"
CONFIGURE_FLAGS="$CONFIGURE_FLAGS --enable-decoder=dvdsub"
CONFIGURE_FLAGS="$CONFIGURE_FLAGS --enable-decoder=webvtt"

**Comment by aningxu** [comment]
能否看下邮件，确认下我是否对那条流携带的字幕轨道认识错误？

**Comment by aningxu** [comment]
希望能尽快支持，基于图形的字幕在国外的使用场景非常多。

**Comment by aningxu** [comment]
-filter_complex [0:s:0]scale=1920*1080,setpts=PTS-STARTPTS-0/TB,tblend=all_mode=linearlight,select='isnan(prev_selected_t)+gte(t-prev_selected_t,0.1)'[s0];[0:v][s0]overlay[v] 

ffmpeg 是可以使用以上命令来选择字幕轨道的。

**Comment by kingslay** [comment]
基于图形的那个字幕是什么格式的呢

**Comment by aningxu** [comment]
dvb subtitles
![IMG10](https://user-images.githubusercontent.com/68496559/89119143-6923bf00-d4de-11ea-9a92-0a292718bf72.jpeg)

**Comment by kingslay** [comment]
你能提供下有dvb字幕的视频让我测试下吗？

**Comment by aningxu** [comment]
我发了邮件到您的邮箱：kingslay@icloud.com，麻烦查收一下。

**Comment by kingslay** [comment]
收到了。谢谢

**Comment by aningxu** [comment]
我看你添加了 dvbs字幕支持，但是我更新了代码，还不能使用呢

**Comment by kingslay** [comment]
是的，只是增加了dvbs格式的识别。但是这个解码还需要做特殊的处理，因为他是图片字幕跟之前的文字字幕不大一样。需要把流程改下。改动比较大。图片字幕的内存占用太高了。

**Comment by aningxu** [comment]
可以借鉴下 VLC 播放器，辛苦。

**Comment by aningxu** [comment]
字幕问题能解决吗？

**Comment by kingslay** [comment]
这个问题还在改
