### ISSUE TITLE
Pod update fail.

### ISSUE THREAD

**Issue by loicleser** [kingslay/KSPlayer#481]
Hello, 
I did a pod update yesterday and I get errors on Xcode when all was working well before. 

<img width="713" alt="image" src="https://github.com/kingslay/KSPlayer/assets/1853830/9aad8da2-462c-45e6-9f33-90b1e4f7ee0d">

It's not the first time I've trouble with KSPlayer  when updating pods... 
Do I integrate this correctly into my podfile? 

pod 'KSPlayer',:git => 'https://github.com/kingslay/KSPlayer.git', :branch => 'main'
pod 'FFmpegKit',:git => 'https://github.com/kingslay/FFmpegKit.git', :branch => 'main'
pod 'OpenSSL',:git => 'https://github.com/kingslay/FFmpegKit.git', :branch => 'main'

Thanks

**Comment by loicleser** [comment]
And if I try with the develop branch I get this error: 

<img width="1703" alt="image" src="https://github.com/kingslay/KSPlayer/assets/1853830/a65ed9df-e227-4720-97b7-694bccc677ef">

**Comment by kingslay** [comment]
你可以用spm来引入ksplayer。

**Comment by loicleser** [comment]
All my project use cocoapod :-/ Do you think you can fix it ? 
I don't really want to use 2 dependency manager :-/

**Comment by kingslay** [comment]
我可以修复这个问题，但是我平时开发主要是用spm，所以没有去验证pod会不会有问题。所以pod会比较不稳定。

**Comment by loicleser** [comment]
I'll let you know if I run into any problems, if that's ok with you. 
Can you let me know once it's fixed? 

Thanks

**Comment by kingslay** [comment]
> I'll let you know if I run into any problems, if that's ok with you. Can you let me know once it's fixed?
> 
> Thanks

OK

**Comment by loicleser** [comment]
Hello, I still have one error when launching my app: 

<img width="433" alt="image" src="https://github.com/kingslay/KSPlayer/assets/1853830/65c56f2f-351d-4d06-b53f-85ce0428a419">

<img width="1256" alt="image" src="https://github.com/kingslay/KSPlayer/assets/1853830/5c1369d8-9959-4b02-a955-b8e80d929638">

for the history when I first used KS player I had no problem, then I had this error 2 weeks ago on the develop branch and now I have it on the main and develop branch. last week I had no problem on the main branch. 

I hope you'll be able to fix it because I'm stuck in my development until it's fixed :-/ 

Thanks

**Comment by kingslay** [comment]
我这边不会有这个问题。我看这个文件的行数只到689。你可以在这个文件的最后一行加空行 看行不行

**Comment by kingslay** [comment]
如果可以的话 那你就发起一个代码变更。我合入下
