### ISSUE TITLE
Picture In Picture broken

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#483]
PiP is broken.  You can select the icon to make the media shrink to a small window.  But if you then press the restore button the top right of the pip video window, you get a black/blank screen.  The PiP window disappears, the sound stops but the full screen video is not resumed/displayed.

This happens in my app AND in your tracy demo app.

**Comment by kingslay** [comment]
是iOS 还是tvos呢

**Comment by UnknownCoder807** [comment]
iOS on a real device.

**Comment by kingslay** [comment]
我用我的iOS real device试了。pip是不会有这个问题。 iOS version 16.5.1

**Comment by UnknownCoder807** [comment]
I have sent you a link to a short video of the problem via email.

**Comment by UnknownCoder807** [comment]
Also, .ts streams don't work with the latest develop branch.  The window just shows a gray screen with a spinning icon, but the audio plays.  I can't test in TracyPlayer because the latest version doesn't run, can't find KSPlayer package error when compiling.

![IMG_0002](https://github.com/kingslay/KSPlayer/assets/56231066/65b00e5b-67e1-4304-a634-e9418dfbf7e8)
