### ISSUE TITLE
Live TV subtitles have some horrible green background

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#486]
Here are 2 screenshots, live tv stream,  subtitles have a green background

![Simulator Screenshot - iPhone 14 Pro Max - 2023-06-29 at 15 56 28](https://github.com/kingslay/KSPlayer/assets/56231066/9d75ce0c-1ce9-4268-a452-2f6562bb4593)

![Simulator Screenshot - iPhone 14 Pro Max - 2023-06-29 at 15 56 30](https://github.com/kingslay/KSPlayer/assets/56231066/9b9c516c-bf8f-4545-bcb9-1a86d184efd4)

**Comment by Kimentanm** [comment]
I have the same issue when use image subtitle
![photo_2023-06-29_23-13-49](https://github.com/kingslay/KSPlayer/assets/25970284/277d94ca-1719-4d1b-b9f7-972a5b16330e)

**Comment by kingslay** [comment]
@Kimentanm 有这个视频的url吗？

**Comment by Kimentanm** [comment]
> @Kimentanm 有这个视频的url吗？

今天比较晚了，明天找个test url发你

**Comment by Kimentanm** [comment]
> @Kimentanm 有这个视频的url吗？

我的这是个private url，所以只能通过邮箱发你测试
但是没有找到你的邮箱，如果可以的话，请通过邮件联系我一下：Kimentanm@gmail.com

**Comment by Kimentanm** [comment]
有个频道会出现黑色的背景，具体的频道地址我通过邮件发送你了
![image](https://github.com/kingslay/KSPlayer/assets/25970284/3ad51e43-5636-4aab-a7a1-02b85662f89e)

**Comment by kingslay** [comment]
@Kimentanm 用vlc或iina会有黑色背景吗？

**Comment by Kimentanm** [comment]
黑色背景貌似是都有，应该是视频自带的，但是字母的长宽比不太正常，而且偏大，下面是iina的截图
<img width="1028" alt="image" src="https://github.com/kingslay/KSPlayer/assets/25970284/ba22a9aa-e58d-417d-baeb-03062fc9db55">

**Comment by Kimentanm** [comment]
同时，KSPlayer在mac上的字幕非常的小
<img width="1032" alt="image" src="https://github.com/kingslay/KSPlayer/assets/25970284/f1b2bea1-daea-4fa7-9ddb-455d9d4e7e7d">

**Comment by kingslay** [comment]
这个截图是tvos的吗？还是iOS的

> 有个频道会出现黑色的背景，具体的频道地址我通过邮件发送你了
> ![image](https://user-images.githubusercontent.com/25970284/250441616-3ad51e43-5636-4aab-a7a1-02b85662f89e.png)

**Comment by Kimentanm** [comment]
@kingslay iOS的

**Comment by kingslay** [comment]
@Kimentanm 你可以把.scaledToFit() 给去掉
 ```
           if let image = model.part?.image {
                Spacer()
                GeometryReader { geometry in
                    let fitRect = image.fitRect(geometry.size)
                    imageView(image)
                        .offset(CGSize(width: fitRect.origin.x, height: fitRect.origin.y))
                        .frame(width: fitRect.size.width, height: fitRect.size.height)
                }
//                .scaledToFit()
                .padding()
            }
```

**Comment by Kimentanm** [comment]
我没用SwiftUI呢

**Comment by kingslay** [comment]
那你是怎么用这个图片字幕的呢？是不是对图片的宽高设置的有问题。我刚看了这个图片字幕的图片需要很大。图片宽度是1920，高度848

**Comment by Kimentanm** [comment]
@kingslay 没有显示定义字幕的高度，默认就是用的是VideoPlayerView中的subtitleBackView
我设置了一下subtitleBackView的contentMode，貌似可以了，目前这个bbc的频道播放的节目没有字幕，等会有字幕了我再试试

**Comment by Kimentanm** [comment]
@kingslay 测试过了，增加subtitleBackView.contentMode = .scaleAspectFit后，图片字幕的比例正常了

![image](https://github.com/kingslay/KSPlayer/assets/25970284/7cf58a5e-193b-4edc-b5be-32abab19775d)
