### ISSUE TITLE
No podspec found for `FFmpegKit` in `../FFmpegKit`

### ISSUE THREAD

**Issue by kevinpp** [kingslay/KSPlayer#487]
pod  failed. No podspec found for `FFmpegKit` in `../FFmpegKit`

**Comment by kingslay** [comment]
pod 'FFmpegKit',:git => 'https://github.com/kingslay/FFmpegKit.git', :branch => 'main'
 pod 'OpenSSL',:git => 'https://github.com/kingslay/FFmpegKit.git', :branch => 'main'
