### ISSUE TITLE
更新到最新版本后，打包时报错

### ISSUE THREAD

**Issue by hippiefox** [kingslay/KSPlayer#489]
<img width="735" alt="截屏2023-07-06 13 30 52" src="https://github.com/kingslay/KSPlayer/assets/47681432/b271a8fa-c8a9-4072-aacc-e4a6b70537d6">
求解，KSPlayer有没有版本回退的概念啊

**Comment by kingslay** [comment]
CMTimebaseCreateWithSourceClock 这个方法很早就有在调用了啊。而且这个方法是public的。那是打包iOS还是打包Macos呢？

**Comment by Kimentanm** [comment]
是不是用的Xcode15？

**Comment by Kimentanm** [comment]
是不是用的Xcode15？

**Comment by LeeJH0827** [comment]
> 是不是用的Xcode15？

Xcode 14.3.1

**Comment by hippiefox** [comment]
> CMTimebaseCreateWithSourceClock 这个方法很早就有在调用了啊。而且这个方法是public的。那是打包iOS还是打包Macos呢？

iOS版本，_CMTimebaseCreateWithMasterClock, 注意是MasterClock不是SourceClock

同样的问题：
https://github.com/aws-samples/amazon-ivs-player-ios-sample/issues/51

**Comment by hippiefox** [comment]
如何破解。 
我尝试了一下，去除Pods中 去除KSPlayer 然后upload一个build版本，是可以通过的。

**Comment by Kimentanm** [comment]
我这边打包是可以的，在upload的时候显示了同样的错误，但感觉像是苹果的server问题
<img width="857" alt="image" src="https://github.com/kingslay/KSPlayer/assets/25970284/a11db3d2-4c7e-4f27-bc50-03f3eee34d16">

**Comment by Kimentanm** [comment]
export之后使用Transporter上传ipa，可以上传成功，你可以试试

**Comment by hippiefox** [comment]
transporter的方式 依然会被拒绝。

**Comment by kingslay** [comment]
@hippiefox 可以帮忙确认下是那个commit引起的吗？

**Comment by hippiefox** [comment]
<img width="1308" alt="截屏2023-07-06 15 43 25" src="https://github.com/kingslay/KSPlayer/assets/47681432/5f17cabd-ab97-415c-a4b6-3bcb7b486d7e">
盲猜是昨天的这些提交吧。
我07.05日 17:00前还做了一次发版，那时候没问题。

**Comment by kingslay** [comment]
那你帮忙确认下是不是2c80ec0 这个commit引起的。

**Comment by Kimentanm** [comment]
目测还是Apple Server的问题，我目前是基于7月4号的版本upload的，还是会有问题

**Comment by hippiefox** [comment]
> 那你帮忙确认下是不是2c80ec0 这个commit引起的。

试了几个很早的版本 也不行。 暂定为Server端的问题了。

**Comment by chuyeonhak** [comment]
Do you use pip in the app?

**Comment by hhfssg** [comment]
通遇到这个问题，不知道是苹果改规则了，还是苹果server出问题了。

**Comment by UnknownCoder807** [comment]
I am getting this issue.  Seems its an apple problem.

ITMS-90338: Non-public API usage-_CMTimebaseCreateWithMasterClock - https://developer.apple.com/forums/thread/733322?answerId=758347022#758347022

https://developer.apple.com/system-status/

**Comment by UnknownCoder807** [comment]
> I am getting this issue. Seems Apple may have changed the binary validation rules.
> 
> ITMS-90338: Non-public API usage-_CMTimebaseCreateWithMasterClock - https://developer.apple.com/forums/thread/733322?answerId=758347022#758347022
> 
> https://developer.apple.com/system-status/

This issue is now resolved on Apple's servers.

**Comment by hippiefox** [comment]
> > I am getting this issue. Seems Apple may have changed the binary validation rules.
> > ITMS-90338: Non-public API usage-_CMTimebaseCreateWithMasterClock - https://developer.apple.com/forums/thread/733322?answerId=758347022#758347022
> > https://developer.apple.com/system-status/
> 
> This issue is now resolved on Apple's servers.

Many THX!

**Comment by hippiefox** [comment]
> I am getting this issue. Seems Apple may have changed the binary validation rules.
> 
> ITMS-90338: Non-public API usage-_CMTimebaseCreateWithMasterClock - https://developer.apple.com/forums/thread/733322?answerId=758347022#758347022
> 
> https://developer.apple.com/system-status/

Done
