### ISSUE TITLE
Demo App

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#492]
Whenever I download the .zip of KSPlayer from the homepage, and follow the instructions in the Readme

```
cd Demo
pod install
```

I get the following error :

```
Analyzing dependencies
[!] No podspec found for `FFmpegKit` in `../FFmpegKit`
```

**Comment by kingslay** [comment]
ffmpegkit是一个git submodule。所以下载zip的话 是不会有这个的。你需要指定ffmpegkit地址

**Comment by Kimentanm** [comment]
You can use `git clone --recurse-submodules` to clone project or use `git submodule update --init` when the project has been cloned

**Comment by UnknownCoder807** [comment]
Thanks.  Yes but I am pointing out that your instructions don't work in the readme don't work.

I added ffmpegkit and openssl in the Podfile and installed them ok, but the Demo workspace says ksplayer is not found.

**Comment by UnknownCoder807** [comment]
> You can use `git clone --recurse-submodules` to clone project or use `git submodule update --init` when the project has been cloned

Thanks, this works.
