### ISSUE TITLE
某些视频播放时会崩溃

### ISSUE THREAD

**Issue by Kimentanm** [kingslay/KSPlayer#494]
video url: 
http://211.54.77.15:9981/stream/channelid/78?ticket=D581F8887EE7ABB5FD5919057156E3B9E0C3EA11

**Comment by kingslay** [comment]
这个直播结束了。无法播放了

**Comment by Kimentanm** [comment]
我再找找新的url

**Comment by Kimentanm** [comment]
暂时找不到新的URL了，先关闭吧
