### ISSUE TITLE
OpenSSL and KSME Crash on tvOS

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#496]
How OpenSSL is correlated to KSMEPlayer?

The most happening crash in my app **ONLY on tvOS** (not iOS):

```
Crashed: KSPlayer_MEPlayerItem_open
SIGSEGV 0x0000000000000000
0
App
OPENSSL_strcasecmp + 4374882516
1
App
obj_name_cmp + 4375024240
2
App
getrn + 4374837844
3
App
OPENSSL_LH_insert + 4374836756
4
App
lh_OBJ_NAME_insert + 4375022316
5
App
OBJ_NAME_add + 4375022012
6
App
openssl_add_all_ciphers_int + 4374543332
7
App
ossl_init_add_all_ciphers + 4374867156
8
App
ossl_init_add_all_ciphers_ossl_ + 4374866392
9
libsystem_pthread.dylib
<redacted> + 76
10
libsystem_platform.dylib
<redacted> + 32
11
libsystem_pthread.dylib
pthread_once + 100
12
App
CRYPTO_THREAD_run_once + 4374945460
13
App
OPENSSL_init_crypto + 4374865212
14
App
OPENSSL_init_ssl + 97016
15
App
SSL_CTX_new_ex + 114816
16
App
SSL_CTX_new + 117008
17
App
tls_open + 4373226628
18
App
closure #1 in MEPlayerItem.read() + 4367619492
19
App
<compiler-generated> - Line 4367629188
partial apply for closure #1 in MEPlayerItem.prepareToPlay() + 4367629188
20
App
<compiler-generated> - Line 4365519328
thunk for @escaping @callee_guaranteed () -> () + 4365519328
```

I'm using your package with your OpenSSL library and I can't understand how to resolve this problem that seems to happen to random users with any operative system (stable or beta).

**Comment by kingslay** [comment]
如果openssl他们无法解决这个问题。那就需要把openssl的的版本给回退了。你可以试着改下openssl的版本。然后重新打包下。看下那个版本openssl是没有问题的。你可以改下改FFmpegKit这个工程的main.swift 这个文件。

**Comment by matteogobbi** [comment]
I'm trying to talk with them but it's weird. 

1. Why avplayer doesn't crash playing https and srt, whereas ksme systematically crashes when it tries to open a https or srt stream?

2. Can you try to update the version of OpenSSL? Maybe new versions are more stable. 

3. What does avplayer uses to open https / srt? Are you sure OpenSSL is needed and can't be replaced by anything else?

**Comment by kingslay** [comment]
avplayer应该不可以使用srt链接吧？你可以看下是不是只要是srt链接，就一定会crash。而不是https的问题。

**Comment by matteogobbi** [comment]
I don’t have srt url to try but what about https? Ksme will crash due OpenSSL error with https streams whereas avplayer no right?Sent from my iPhoneOn Jul 17, 2023, at 12:37 PM, kingslay ***@***.***> wrote:﻿
avplayer应该不可以使用srt链接吧？你可以看下是不是只要是srt链接，就一定会crash。而不是https的问题。

**Comment by kingslay** [comment]
协议是https的应该不会crash，我的demo里面就有https的url，不会crash的。你有引起crash的链接吗？有的话发给我。我来调试下。

**Comment by matteogobbi** [comment]
Also from OpenSSL team:

"This sounds like some problem with the application - i.e., some race condition when initializing OpenSSL. As a workaround I'd recommend calling OPENSSL_init_ssl() on application startup instead of relying on implicit initialization."

https://github.com/openssl/openssl/issues/21449#issuecomment-1637999713

**Comment by kingslay** [comment]
@matteogobbi 你的app允许同时播放多个url吗？

**Comment by matteogobbi** [comment]
Yes but in this case the app crashes as soon as one stream starts, either live or vod.

**Comment by matteogobbi** [comment]
Also do you do this at startup time like suggested?

"OPENSSL_init_ssl()"

**Comment by kingslay** [comment]
> Also do you do this at startup time like suggested?
> 
> "OPENSSL_init_ssl()"

可以的，我会试着这样改下。
