### ISSUE TITLE
Slider and SwiftUI

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#497]
I am using your slider.swift file for my tvOS app and have a slight issue.

When the user starts to swipe right, the red progress bar skips backwards before starting to scroll right.  It's like it is over sensitive to the start position of their finger.  On the simulator it works perfectly but not on a real device.

**Comment by kingslay** [comment]
我在闭源版本里面优化了下进度条的交互。你更新下。看下效果怎么样。
