### ISSUE TITLE
在播放一个广播音频时，会一直在buffering

### ISSUE THREAD

**Issue by Kimentanm** [kingslay/KSPlayer#498]
test url: http://hls.nntv.cn/nnradio/FM895.m3u8
用VLC和IINA试过可以播放，单独取出来里面的ts链接也可以播放

**Comment by kingslay** [comment]
可以先把KSOptions.videoDisable 设置为true。来解决这个问题。这个是因为没有视频帧，但是有视频轨道导致的。

**Comment by Kimentanm** [comment]
那如何知道这个频道没有视频帧，从而动态的去将KSOptions.videoDisable设置成false

**Comment by kingslay** [comment]
这个目前还无法知道。我想下要怎么解决这个问题。让你不用设置videoDisable。

**Comment by Kimentanm** [comment]
感谢，辛苦了~
