### ISSUE TITLE
请问有什么方式可以设置一个默认的播放速度  类似默认的播放开始位置一样  谢谢

### ISSUE THREAD

**Issue by nicknull** [kingslay/KSPlayer#499]

**Comment by kingslay** [comment]
你可以在播放之后 就设置下速度 可以直接就生效了

**Comment by nicknull** [comment]
> 你可以在播放之后 就设置下速度 可以直接就生效了

但是仍然建议给流出这个设置项 谢谢

**Comment by kingslay** [comment]
@nicknull 你可以发起个pull requests。然后我合入下。

**Comment by nicknull** [comment]
> @nicknull 你可以发起个pull requests。然后我合入下。

好的 ，稍微晚些时候我会发起pull requests的
