### ISSUE TITLE
Cannot get the name of subtitle

### ISSUE THREAD

**Issue by byMohamedali** [kingslay/KSPlayer#5]
Hi,

I am trying to get the name of the subtitle but by default you put a default name "内置字幕", how can I get the real name of the subtitle ?

Thank you

**Comment by kingslay** [comment]
Can you provide that play URL?

**Comment by byMohamedali** [comment]
http://portal.geniptv.com:8080/movie/moha.by/FqdjPofH8E/19780.mkv

**Comment by kingslay** [comment]
There's no title in Metadata, so I can't get the name of the subtitle.

 Stream #0:2(eng): Subtitle: subrip (default)
    Metadata:
      BPS-eng         : 42
      DURATION-eng    : 02:14:07.946000000
      NUMBER_OF_FRAMES-eng: 1586
      NUMBER_OF_BYTES-eng: 42386
      _STATISTICS_WRITING_APP-eng: mkvmerge v21.0.0 ('Tardigrades Will Inherit The Earth') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-05-02 12:48:38
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:3(eng): Subtitle: subrip
    Metadata:
      BPS-eng         : 1
      DURATION-eng    : 02:10:25.193000000
      NUMBER_OF_FRAMES-eng: 68
      NUMBER_OF_BYTES-eng: 1173
      _STATISTICS_WRITING_APP-eng: mkvmerge v21.0.0 ('Tardigrades Will Inherit The Earth') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-05-02 12:48:38
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:4(spa): Subtitle: subrip
    Metadata:
      BPS-eng         : 43
      DURATION-eng    : 02:14:16.603000000
      NUMBER_OF_FRAMES-eng: 1450
      NUMBER_OF_BYTES-eng: 43425
      _STATISTICS_WRITING_APP-eng: mkvmerge v21.0.0 ('Tardigrades Will Inherit The Earth') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-05-02 12:48:38
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:5(fre): Subtitle: subrip
    Metadata:
      BPS-eng         : 45
      DURATION-eng    : 02:14:16.465000000
      NUMBER_OF_FRAMES-eng: 1473
      NUMBER_OF_BYTES-eng: 45715
      _STATISTICS_WRITING_APP-eng: mkvmerge v21.0.0 ('Tardigrades Will Inherit The Earth') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-05-02 12:48:38
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:6(gre): Subtitle: subrip
    Metadata:
      BPS-eng         : 164
      DURATION-eng    : 02:06:18.223000000
      NUMBER_OF_FRAMES-eng: 1418
      NUMBER_OF_BYTES-eng: 155779
      _STATISTICS_WRITING_APP-eng: mkvmerge v21.0.0 ('Tardigrades Will Inherit The Earth') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-05-02 12:48:38
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:7(lat): Subtitle: subrip
    Metadata:
      BPS-eng         : 43
      DURATION-eng    : 02:06:33.185000000
      NUMBER_OF_FRAMES-eng: 1364
      NUMBER_OF_BYTES-eng: 41110
      _STATISTICS_WRITING_APP-eng: mkvmerge v21.0.0 ('Tardigrades Will Inherit The Earth') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-05-02 12:48:38
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:8(dut): Subtitle: subrip
    Metadata:
      BPS-eng         : 40
      DURATION-eng    : 02:14:17.479000000
      NUMBER_OF_FRAMES-eng: 997
      NUMBER_OF_BYTES-eng: 40700
      _STATISTICS_WRITING_APP-eng: mkvmerge v21.0.0 ('Tardigrades Will Inherit The Earth') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-05-02 12:48:38
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:9(rum): Subtitle: subrip
    Metadata:
      BPS-eng         : 43
      DURATION-eng    : 02:01:47.732000000
      NUMBER_OF_FRAMES-eng: 1199
      NUMBER_OF_BYTES-eng: 39331
      _STATISTICS_WRITING_APP-eng: mkvmerge v21.0.0 ('Tardigrades Will Inherit The Earth') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-05-02 12:48:38
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:10(srp): Subtitle: subrip
    Metadata:
      BPS-eng         : 39
      DURATION-eng    : 02:14:22.203000000
      NUMBER_OF_FRAMES-eng: 1040
      NUMBER_OF_BYTES-eng: 39916
      _STATISTICS_WRITING_APP-eng: mkvmerge v21.0.0 ('Tardigrades Will Inherit The Earth') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-05-02 12:48:38
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:11(tur): Subtitle: subrip
    Metadata:
      BPS-eng         : 46
      DURATION-eng    : 02:06:11.333000000
      NUMBER_OF_FRAMES-eng: 1352
      NUMBER_OF_BYTES-eng: 44135
      _STATISTICS_WRITING_APP-eng: mkvmerge v21.0.0 ('Tardigrades Will Inherit The Earth') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-05-02 12:48:38
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:12(ara): Subtitle: subrip
    Metadata:
      BPS-eng         : 62
      DURATION-eng    : 02:15:12.659000000
      NUMBER_OF_FRAMES-eng: 1453
      NUMBER_OF_BYTES-eng: 63234
      _STATISTICS_WRITING_APP-eng: mkvmerge v21.0.0 ('Tardigrades Will Inherit The Earth') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-05-02 12:48:38
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:13(hrv): Subtitle: subrip
    Metadata:
      BPS-eng         : 40
      DURATION-eng    : 02:04:15.225000000
      NUMBER_OF_FRAMES-eng: 981
      NUMBER_OF_BYTES-eng: 37575
      _STATISTICS_WRITING_APP-eng: mkvmerge v21.0.0 ('Tardigrades Will Inherit The Earth') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-05-02 12:48:38
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:14(cze): Subtitle: subrip
    Metadata:
      BPS-eng         : 39
      DURATION-eng    : 01:43:34.080000000
      NUMBER_OF_FRAMES-eng: 835
      NUMBER_OF_BYTES-eng: 30672
      _STATISTICS_WRITING_APP-eng: mkvmerge v21.0.0 ('Tardigrades Will Inherit The Earth') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-05-02 12:48:38
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:15(dan): Subtitle: subrip
    Metadata:
      BPS-eng         : 38
      DURATION-eng    : 02:14:33.618000000
      NUMBER_OF_FRAMES-eng: 1104
      NUMBER_OF_BYTES-eng: 38533
      _STATISTICS_WRITING_APP-eng: mkvmerge v21.0.0 ('Tardigrades Will Inherit The Earth') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-05-02 12:48:38
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

**Comment by byMohamedali** [comment]
When I'm trying on VLC, they get the name. Do you know how they get it ?

**Comment by kingslay** [comment]
The latest code solves that problem. Could you please update the code?

**Comment by byMohamedali** [comment]
Thank you so much 👍
