### ISSUE TITLE
音频是使用native原生解码吗？

### ISSUE THREAD

**Issue by FantasyKingdom** [kingslay/KSPlayer#500]
比如ac3这种音频格式，是支持系统原生解码播放的。
此SDK目前使用的是原生解码方式还是FFMPEG软解？

**Comment by kingslay** [comment]
是用ffmpeg。但是ffmpeg 里面是用硬解的

**Comment by FantasyKingdom** [comment]
> 是用ffmpeg。但是ffmpeg 里面如果是系统支持的格式 是用原生解码
1.请问下这个是ffmpeg官方文档有说明吗，另外是否有方法可以进行判断是软解还是硬解吗

2.目前视频的硬件解码是在sdk应用层的，视频是否也能像音频那样，使用ffmpeg解码，里面如果是系统支持的格式使用原生解码。因为编译ffmpeg的时候毕竟用到了videotoolbox相关参数。

以上问题仅仅是想探讨一下，对这块有点疑惑。

**Comment by kingslay** [comment]
视频是可以判断是不是硬解，但是音频这块要如何判断，我还不知道。
