### ISSUE TITLE
Potentially Incorrect Uses of "available"

### ISSUE THREAD

**Issue by VaslD** [kingslay/KSPlayer#503]
First, thank you for this awesome project. It's a great learning material and provides many insights to writing FFmpeg decodings in Swift.

Not trying to point fingers or anything, but as a somewhat experienced iOS developer, I do find many `available` annotations look suspicious.

1. In `if #available` checks, `*` does not implicitly cross platforms. Which means something like `if #available(macOS 11, *)` evaluates to `false` (and runs the `else` branch) on all iOS versions. I can't be sure if these are intentional:

https://github.com/kingslay/KSPlayer/blob/2766c83222915befb0f84eac9d10bf933de55a30/Sources/KSPlayer/Video/VideoPlayerView.swift#L964-L968

https://github.com/kingslay/KSPlayer/blob/2766c83222915befb0f84eac9d10bf933de55a30/Sources/KSPlayer/Video/SeekView.swift#L29-L31

2. `@available` also does not cross platform. Which means something like `@available(tvOS 14, *)` means the annotated class/property will **only** be available on tvOS 14+, thus **unavailable** on all macOS/iOS versions. These don't make sense:

https://github.com/kingslay/KSPlayer/blob/2766c83222915befb0f84eac9d10bf933de55a30/Sources/KSPlayer/AVPlayer/KSPictureInPictureController.swift#L9-L10

https://github.com/kingslay/KSPlayer/blob/2766c83222915befb0f84eac9d10bf933de55a30/Sources/KSPlayer/AVPlayer/KSAVPlayer.swift#L98-L110

**Comment by kingslay** [comment]
你的理解是有误的，available 的* 是包含其他所有操作系统的，所以如果 #available(macOS 11, *) 那iOS 是会返回true的。你运行下项目。就知道对不对了

**Comment by VaslD** [comment]
不好意思，感谢指正。我一直以为是 Mac Catalyst 导致它生效的，但我原生运行模拟器也的确可以。
