### ISSUE TITLE
SOS，播放器播放过程中，视频流自己创建了新的控件

### ISSUE THREAD

**Issue by hippiefox** [kingslay/KSPlayer#505]
![IMG_0128](https://github.com/kingslay/KSPlayer/assets/47681432/8d2803e0-5009-483b-9644-b4b1ab093c63)
<img width="1604" alt="截屏2023-07-27 11 41 08" src="https://github.com/kingslay/KSPlayer/assets/47681432/f302a657-f58c-4fef-9ea7-003e8afb8e69">

如图所示，某些视频源在一开始播放时，会自动爆出上述信息。且对应的控件(一个imageView, 一个label)是自动生成的。
请问 这种情况是如何产生的呢？

**Comment by kingslay** [comment]
这个是字幕，你可以把autoSelectEmbedSubtitle 设置为false。那就不会自动选择字幕了。

**Comment by hippiefox** [comment]
> 这个是字幕，你可以把autoSelectEmbedSubtitle 设置为false。那就不会自动选择字幕了。

明白，视频源外挂了字幕。 蟹蟹

**Comment by hippiefox** [comment]
外挂字幕（subtitle）
