### ISSUE TITLE
Pauses when playing m3u8

### ISSUE THREAD

**Issue by nightfall708** [kingslay/KSPlayer#506]
Hi,

I'm trying to play this stream https://admdn7ta.cdn.mangomolo.com/adfmrdo/adfmrdo.stream_aac/chunklist.m3u8 but apparently there is a slight pause when the player switches from chunk to chunk. Any way to resolve that?

Thank you...

**Comment by kingslay** [comment]
用mpv或vlc播放，会有这个问题吗？
