### ISSUE TITLE
SPM无法添加

### ISSUE THREAD

**Issue by chenfengfeng** [kingslay/KSPlayer#507]
![WX20230728-012456@2x](https://github.com/kingslay/KSPlayer/assets/6957977/75a4d260-ac78-45d3-a4a4-f83c1f97960c)

如图，使用Up to Next Major Version模式，或者使用指定develop分支也一样无法安装。

麻烦检查下～非常感谢

**Comment by kingslay** [comment]
你可以先直接点Add Anyway。就可以添加了。我研究下要怎么解决这个问题

**Comment by kingslay** [comment]
排查了下是因为spm不支持#file。导致解析报错了。但是如果不用#file，就无法判断本地的开发环境了。如果要修复这个问题的话，就要牺牲本地的开发体验了。
