### ISSUE TITLE
How to set `subtitleDelay` now?

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#508]
`options.subtitleDelay = -newValue`

was the old approach. 
Now from my custom view, I don't know how to access the `subtitleModel` where this property has been moved to.

I have access to `player` which is a `MediaPlayerProtocol` which can only access to `subtitleDataSource`.

**Comment by kingslay** [comment]
你有用KSVideoPlayer或是PlayerView吗？里面就有subtitleModel了。没有的话，你也可以自己new一下SubtitleModel。你可以看下我的demo是怎么实现的
