### ISSUE TITLE
Tvos Seek Speed

### ISSUE THREAD

**Issue by wertpoiu** [kingslay/KSPlayer#51]
It seeks very fast, seek speed should be slow or give us code to slow it down.

**Comment by kingslay** [comment]
is you  set isLoopPlay = true ?

**Comment by wertpoiu** [comment]
> is you set isLoopPlay = true ?

yes its true

**Comment by kingslay** [comment]
i fixed it. please update the code

**Comment by wertpoiu** [comment]
> i fixed it. please update the code

seek bar or toolbar stopped showing after update

**Comment by kingslay** [comment]
Yes someone asked to hide it. So I hide it by default. You can show it. Or custom ui

**Comment by wertpoiu** [comment]
> Yes someone asked to hide it. So I hide it by default. You can show it. Or custom ui

It was me can you please show it by default?

**Comment by wertpoiu** [comment]
> > Yes someone asked to hide it. So I hide it by default. You can show it. Or custom ui
> 
> It was me can you please show it by default?

I tried to show it manually its not working.

**Comment by kingslay** [comment]
ok .i had rollback

**Comment by wertpoiu** [comment]
> ok .i had rollback

thats ok i am able to bring it back

**Comment by wertpoiu** [comment]
Please give us code to control slider seek speed with apple tv remote.

**Comment by kingslay** [comment]
i had update the code.  you can override 
```
 open func panValue(velocity point: CGPoint, direction: KSPanDirection, currentTime _: Float, totalTime: Float) -> Float {
        if direction == .horizontal {
            return max(min(Float(point.x) / 0x40000, 0.01), -0.01) * totalTime
        } else {
            return -Float(point.y) / 0x2800
        }
    }
```

**Comment by wertpoiu** [comment]
> i had update the code. you can override
> 
> ```
>  open func panValue(velocity point: CGPoint, direction: KSPanDirection, currentTime _: Float, totalTime: Float) -> Float {
>         if direction == .horizontal {
>             return max(min(Float(point.x) / 0x40000, 0.01), -0.01) * totalTime
>         } else {
>             return -Float(point.y) / 0x2800
>         }
>     }
> ```

Thank you very much
