### ISSUE TITLE
能否删掉默认的 User-Agent: ksplayer？

### ISSUE THREAD

**Issue by FaiChou** [kingslay/KSPlayer#512]
代码中已经设置了 `options.appendHeader(["User-Agent": "Custom HTTP User Agent"])` 了，
但是看到最终请求是：

```
KSPlayer: MEPlayerItem.swift:130 init(url:options:) | request: GET /xxxxx/wwdc2023-10117_hd.mp4?t=1691230387&u=101248331&s=x&d=x-x-0&c=2&f=1&k=xxxxx&us=52428800&uc=10&v=1 HTTP/1.1
User-Agent: ksplayer
Accept: */*
Range: bytes=0-
Connection: close
Host: cdn.somehost.com
Icy-MetaData: 1
Cookie:COOKIE
User-Agent:Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36 
```

这样后台会收到两个 User-Agent，由于后台判断的比较严格， User-Agent 有 ksplayer 会 403.
这是我在 Xcode console 中看到的日志。

我通过抓包工具并不能看到实际的请求，应该如何正确设置代理？是不是代码中设置了 bypass 系统代理？所以抓包抓不到？那应该如何设置 http 代理？

**Comment by kingslay** [comment]
我的的develop分支已经去掉这个了。换成自己设置了。 你可以直接用userAgent 这个字段，或是appendHeader(["User-Agent": "Custom HTTP User Agent"])。在1628ea7fbb86ca82a12ecc257ce1a0b0dc6b64ff 这个commit改的
