### ISSUE TITLE
5.1 (and above) rear speakers not working via tvOS

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#514]
I am not sure when this has happened, but I am getting reports that 5.1 (and above) rear speakers aren't working anymore.

It's like everything is being forced to stereo.

Has there been a change in how audio is setup in ksplayer?  

I created a small test app that has 1 button that plays a local dolby 5.1 mkv file and this too has the problem.

**Comment by kingslay** [comment]
可以让用户发一下日志吗？

**Comment by UnknownCoder807** [comment]
```
info KSPlayer: KSPlayerLayer.swift:141 state | playerStateDidChange - buffering
info KSPlayer: AVFFmpegExtension.swift:397 layoutTag | FFmepg channelLayout: 7.1 order: AVChannelOrder(rawValue: 1)
info KSPlayer: AudioEnginePlayer.swift:141 prepare(audioFormat:) | outputFormat channelLayout AudioFormat: <AVAudioFormat 0x28223fc00:  8 ch,  48000 Hz, Float32, deinterleaved>
info KSPlayer: AudioEnginePlayer.swift:143 prepare(audioFormat:) | outputFormat channelLayout tag: 8388616
info KSPlayer: AVFoundationExtension.swift:140 channelLayout() | KSOptions channelLayout: AudioChannelLayoutTag: 8388616, mNumberChannelDescriptions: 0
info KSPlayer: AVFoundationExtension.swift:166 channelLayout() | out channelLayout mask: 1599 nb_channels: 8
info KSPlayer: Resample.swift:192 init(audioDescriptor:audioFormat:) | out channelLayout: 7.1
info KSPlayer: AudioEnginePlayer.swift:144 prepare(audioFormat:) | outputFormat channelLayout channelDescriptions: []
info KSPlayer: KSPlayerLayer.swift:141 state | playerStateDidChange - readyToPlay
```

**Comment by kingslay** [comment]
看这个日志，所有的属性设置都是对的。这个是7.1的视频。

**Comment by UnknownCoder807** [comment]
i can send you the video links to try yourself.

**Comment by kingslay** [comment]
但是我没有7.1的音响设备，无法测试。你本地测试了结果是怎么样呢？

**Comment by kingslay** [comment]
> I can send you the video links to try yourself.
> 
> Sound for rears is coming out the fronts.

是只有后面的声音会有问题吗？其他的声音不会有问题吗？

**Comment by UnknownCoder807** [comment]
I simply play https://www.demolandia.net/downloads.html?id=30191483

My test app is a single button that calls

`
let path = Bundle.main.path(forResource: "71", ofType:"mkv")
KSVideoPlayerView(url: URL(fileURLWithPath: path!), options: myOptions)
`

My soundbar is dolby atmos with surround speakers and was working previously (except when there was the issue with no centre speaker).

**Comment by UnknownCoder807** [comment]
Only the rears are not working correctly.

**Comment by kingslay** [comment]
@UnknownCoder807 我试着修复下，也增加了一些日志来帮忙排查。日志可以通过[audio] 来进行过滤。你本地试下

**Comment by UnknownCoder807** [comment]
Still not working.

```
info KSPlayer: KSPlayerLayer.swift:138 state | playerStateDidChange - buffering
info KSPlayer: KSOptions.swift:316 setAudioSession(audioDescriptor:) | [audio] maximumOutputNumberOfChannels: 32
info KSPlayer: KSOptions.swift:326 setAudioSession(audioDescriptor:) | [audio] isSpatialAudioEnabled: false
info KSPlayer: KSOptions.swift:337 setAudioSession(audioDescriptor:) | [audio] preferredOutputNumberOfChannels: 6
info KSPlayer: AVFFmpegExtension.swift:398 layoutTag | FFmepg channelLayout: 5.1(side) order: AVChannelOrder(rawValue: 1)
info KSPlayer: AudioEnginePlayer.swift:141 prepare(audioFormat:) | [audio] outputFormat AudioFormat: <AVAudioFormat 0x283629e00:  6 ch,  48000 Hz, Float32, deinterleaved>
info KSPlayer: AudioEnginePlayer.swift:143 prepare(audioFormat:) | [audio] outputFormat tag: 7929862
info KSPlayer: AudioEnginePlayer.swift:144 prepare(audioFormat:) | [audio] outputFormat channelDescriptions: []
info KSPlayer: AVFoundationExtension.swift:140 channelLayout() | [audio] channelLayout: AudioChannelLayoutTag: 7929862, mNumberChannelDescriptions: 0
info KSPlayer: AVFoundationExtension.swift:166 channelLayout() | [audio] out mask: 1551 nb_channels: 6
info KSPlayer: Resample.swift:192 init(audioDescriptor:audioFormat:) | out channelLayout: 5.1(side)
info KSPlayer: KSPlayerLayer.swift:138 state | playerStateDidChange - readyToPlay

```

**Comment by kingslay** [comment]
@UnknownCoder807 你可以试下是不是2f9f7115a42d8dc382c07c484358c53810895633 这个bugfix 引起的。最近音频的改动点就是这个了

**Comment by kingslay** [comment]
如果不是这个引起的话，那就在试下 b6e172de68eee7ee2f9ec63239ce5c3e1fbee5aa @UnknownCoder807 麻烦你了。谢谢

**Comment by UnknownCoder807** [comment]
> @UnknownCoder807 你可以试下是不是 [2f9f711](https://github.com/kingslay/KSPlayer/commit/2f9f7115a42d8dc382c07c484358c53810895633) 这个bugfix 引起的。最近音频的改动点就是这个了

I tried the 2 commits you mentioned and the issue is in both of them.

So I then installed the previous commit dated 2nd May (https://github.com/kingslay/KSPlayer/commit/06093169f0893126964745f1aa0615ec5e4a4a17) and the issue was not there.

So it appears https://github.com/kingslay/KSPlayer/commit/b6e172de68eee7ee2f9ec63239ce5c3e1fbee5aa is root of the problem.

**Comment by kingslay** [comment]
@UnknownCoder807 麻烦确认下最新的代码是否修复了这个问题了。谢谢

**Comment by UnknownCoder807** [comment]
working fine using latest code.

**Comment by kingslay** [comment]
#523
