### ISSUE TITLE
PIP Stoped working on demo app (on Simulator)

### ISSUE THREAD

**Issue by AalokParikh** [kingslay/KSPlayer#515]
I have tried to install the demo app with Xcode 14.3.1 & on all simulators with iOS 16.4. 
On all simulators, the PIP functionality is now working.

**Comment by kingslay** [comment]
这个只是iPhone会有问题吧，用ipad是可以的吧。只是用ipad的话，pip的画面是黑色的，无法显示视频内容。

**Comment by AalokParikh** [comment]
It is only an issue with the simulator. It works perfectly with the actual device (even on iPhone).
