### ISSUE TITLE
Recording Record Live Stream!

### ISSUE THREAD

**Issue by ParthAlliancetek** [kingslay/KSPlayer#517]
You have added **Recording feature** in Your feature list but i cant find it any where!
![image](https://github.com/kingslay/KSPlayer/assets/136800803/a58a5278-b9df-4e5f-9cbe-afc4623e1e5f)
@kingslay Please add this feature

**Comment by ParthAlliancetek** [comment]
But how to start and stop it ?

**Comment by kingslay** [comment]
开始播放就可以自动开始，等停止播放了，就会自动结束。

**Comment by ParthAlliancetek** [comment]
Thanks man👍🏽

**Comment by ParthAlliancetek** [comment]
can you Provide a sample code please i am streaming from a

**Comment by kingslay** [comment]
我的demo里面就有了。你可以看下demo

**Comment by ParthAlliancetek** [comment]
sorry but i didn't get it 
some how can you help me

**Comment by ParthAlliancetek** [comment]
I'm trying on IOS device

**Comment by kingslay** [comment]
你可以自己直接在demo里面搜索outputURL这个关键字。这样就知道要怎么用了。只要设置了outputURL就可以。不用在做什么事。

**Comment by ParthAlliancetek** [comment]
it is showing me 
![image](https://github.com/kingslay/KSPlayer/assets/136800803/0d6acba5-ee67-4f6c-9db6-2a515344b7fe)

**Comment by ParthAlliancetek** [comment]
![image](https://github.com/kingslay/KSPlayer/assets/136800803/6ad172e5-d569-431f-8a3a-78dfe81f48b1)
