### ISSUE TITLE
[SwiftUI] PIP not working when put app to background first time

### ISSUE THREAD

**Issue by sega4revenge** [kingslay/KSPlayer#518]
I was faced issue about KSPlayerView in SwiftUI about PIP
- Open PlayerView
- Put app to background
- PIP not show 
- Open app again and we will see PlayerView was paused
- Tap to play continue
- Put app to background again
- PIP now working
Beside, how can I update MPnowplayinginfocenter. I saw in VideoPlayerView for UIKit, we have parameter KSPlayerResource but not have in SwiftUI

**Comment by kingslay** [comment]
你有点击PIP按钮吗？需要点击过pip按钮才能在推到后台的时候，自动pip

**Comment by sega4revenge** [comment]
If I tap to PIP button, it will work. But I'm curious can we have automatic PIP without tap this button when put app to background?

You can see this video:
The second times will working without tap PIP button but not first
https://drive.google.com/file/d/1km1Xhjhg_ZQvdZIDxu-HRZrZwGBGNjjV/view?usp=drivesdk

**Comment by sega4revenge** [comment]
Thank you! I really like this player and used in my project with SwiftUI.
Hope we will have function for set media information with KSMPlayerResource (MPNowPlayingInfoCenter) in KMSPlayerView

**Comment by kingslay** [comment]
> Thank you! I really like this player and used in my project with SwiftUI.
> Hope we will have function for set media information with KSMPlayerResource (MPNowPlayingInfoCenter) in KMSPlayerView

我不知很明白这个是什么意思。 
目前KSPlayerLayer 会设置MPNowPlayingInfoCenter 了啊。你可以搜索下MPNowPlayingInfoCenter这个关键字

**Comment by sega4revenge** [comment]
I know, but only time and duration for player. I mean we can set artCover and name for MPNowPlayingInfoCenter
Like this

```swift
let asset = KSPlayerResource(name: "Big Buck Bunny",
                             definitions: [res0, res1],
                             cover: URL(string: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Big_buck_bunny_poster_big.jpg/848px-Big_buck_bunny_poster_big.jpg"))

playerView.set(resource: asset)
```

But it only if we using VideoPlayerView in UIKit
In KSVideoPlayer for SwiftUI we only have constructor with URL
```swift

public struct KSVideoPlayer {
    public let coordinator: Coordinator
    public let url: URL
    public let options: KSOptions
    public init(coordinator: Coordinator, url: URL, options: KSOptions) {
        self.coordinator = coordinator
        self.url = url
        self.options = options
    }
}
```
and only have duration and something information but not have name and cover
```swift
private func updateNowPlayingInfo() {
        if MPNowPlayingInfoCenter.default().nowPlayingInfo == nil {
            MPNowPlayingInfoCenter.default().nowPlayingInfo = [MPMediaItemPropertyPlaybackDuration: player.duration]
        } else {
            MPNowPlayingInfoCenter.default().nowPlayingInfo?[MPMediaItemPropertyPlaybackDuration] = player.duration
        }
        var current: [MPNowPlayingInfoLanguageOption] = []
        var langs: [MPNowPlayingInfoLanguageOptionGroup] = []
        for track in player.tracks(mediaType: .audio) {
            if let lang = track.language {
                let audioLang = MPNowPlayingInfoLanguageOption(type: .audible, languageTag: lang, characteristics: nil, displayName: track.name, identifier: track.name)
                let audioGroup = MPNowPlayingInfoLanguageOptionGroup(languageOptions: [audioLang], defaultLanguageOption: nil, allowEmptySelection: false)
                langs.append(audioGroup)
                if track.isEnabled {
                    current.append(audioLang)
                }
            }
        }
        if !langs.isEmpty {
            MPRemoteCommandCenter.shared().enableLanguageOptionCommand.isEnabled = true
        }
        MPNowPlayingInfoCenter.default().nowPlayingInfo?[MPNowPlayingInfoPropertyAvailableLanguageOptions] = langs
        MPNowPlayingInfoCenter.default().nowPlayingInfo?[MPNowPlayingInfoPropertyCurrentLanguageOptions] = current
    }
```

**Comment by kingslay** [comment]
那我理解，你可以直接MPNowPlayingInfoCenter.default().nowPlayingInfo = ？  这样就可以了。
