### ISSUE TITLE
avformat can't open input

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#519]
A user, said that since a few days, `KSMEPlayer` isn't able to play his stream anymore. I tried his streams and indeed there's this error. @kingslay ideas on what you could have changed recently that could have brought this error in?

```
warning KSPlayer: KSPlayerLayer.swift:402 finish(player:error:) | Error Domain=KSPlayerErrorDomain Code=2 "avformat can't open input" UserInfo={NSUnderlyingError=0x600005c61ec0 {Error Domain=KSPlayer.AVError Code=1 "(null)"}, NSLocalizedDescription=avformat can't open input}
```

**Comment by kingslay** [comment]
我这个只是支持大部份格式 还有少部分格式没有支持。你需要把url发给我 我查下格式 或是你自己用ffmpeg查下视频的格式。然后我增加下这个格式

**Comment by matteogobbi** [comment]
The outside format is mkv. 
He said it used to play and now suddenly not. 
I’m asking him if we can send you the url.

**Comment by matteogobbi** [comment]
@kingslay here one of the video that don't work with this error [https://wetransfer.com/downloads/b40a333312560e04544940e7417ab63e20230812173505/9e5ed54b3ca63a1541ad892f8472bbba20230812173505/ee0ded](https://wetransfer.com/downloads/b40a333312560e04544940e7417ab63e20230812173505/9e5ed54b3ca63a1541ad892f8472bbba20230812173505/ee0ded?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid)

please let me know.

**Comment by kingslay** [comment]
我下载到本地，用demo是可以进行播放的。

**Comment by kingslay** [comment]
我感觉这个可能是网络协议的问题。所以需要用户给到原始的url。看下是不是走的是smb或是其他不支持的网络协议。

**Comment by matteogobbi** [comment]
What’s your email again? I will send it privately. Sent from my iPhoneOn Aug 13, 2023, at 6:45 AM, kingslay ***@***.***> wrote:﻿
我感觉这个可能是网络协议的问题。所以需要用户给到原始的url。看下是不是走的是smb或是其他不支持的网络协议。

**Comment by kingslay** [comment]
kingslay@icloud.com

**Comment by matteogobbi** [comment]
Sent, please let me know here. Thx

**Comment by kingslay** [comment]
收到了

**Comment by kingslay** [comment]
你发的这个链接我用vlc或iina都无法打开。这个好像是一个失效的链接。你本地用iina或vlc可以打开吗？

**Comment by matteogobbi** [comment]
Yeah it seems not working atm. I’ll let you know Sent from my iPhoneOn Aug 13, 2023, at 11:59 AM, kingslay ***@***.***> wrote:﻿
你发的这个链接我用vlc或iina都无法打开。这个好像是一个失效的链接。你本地用iina或vlc可以打开吗？

**Comment by matteogobbi** [comment]
@kingslay now the URL seems to work, can you test it now?

**Comment by kingslay** [comment]
@matteogobbi 我看现在又不行了。你用vlc可以播放吗？

**Comment by kingslay** [comment]
报错 HTTP error 461 . ffplay不能播放这个url。

**Comment by bgoncal** [comment]
@matteogobbi did you endup finding a solution?
