### ISSUE TITLE
AudioRendererPlayer 播放交错格式的音频时没声音

### ISSUE THREAD

**Issue by strangeliu** [kingslay/KSPlayer#521]
比如s32, s16 都没声音，平面的就没问题，比如s16p

**Comment by kingslay** [comment]
可以给个测试视频吗？我这边调试下。

**Comment by strangeliu** [comment]
https://github.com/qiudaomao/MPVColorIssue/blob/master/MPVColorIssue/resources/captain.marvel.2019.2160p.uhd.bluray.x265-terminal.sample.mkv?raw=true

这个视频，第一个音频s32没声音，第二个fltp没问题，我在macOS上测试的。

**Comment by strangeliu** [comment]
最新的代码使用 AudioRendererPlayer 会闪退

**Comment by strangeliu** [comment]
使用 AudioRendererPlayer 播放这个视频的第一个s32音轨还是没声音 macOS

https://github.com/qiudaomao/MPVColorIssue/blob/master/MPVColorIssue/resources/captain.marvel.2019.2160p.uhd.bluray.x265-terminal.sample.mkv?raw=true

**Comment by kingslay** [comment]
嗯。这个还是没有找到解决办法。我是先解决了crash的问题

**Comment by kingslay** [comment]
还有其他的s32格式的视频吗？你现在提供的测试视频，每个音频帧的长度太短了，我怀疑是这个导致的，所以想要找另一个视频试下。

**Comment by strangeliu** [comment]
我找一下有没有小点的，完整版的文件太大了

**Comment by strangeliu** [comment]
应该不是长度的问题，我播放完整版的也没有声音，上面那个测试视频用IINA播放是有声音的

**Comment by kingslay** [comment]
我指的不是视频的长度，是解码之后的每个音频长度。现在用AudioEnginePlayer播放这个视频也是会有声音的，只是用AVSampleBufferAudioRenderer才会有问题。视频长度还是跟之前的一样，1分钟以内就可以了。

**Comment by strangeliu** [comment]
https://github.com/strangeliu/VideoTestFile/raw/main/Reminiscence-s32.mkv
试下这个

**Comment by strangeliu** [comment]
https://github.com/strangeliu/VideoTestFile/raw/main/AIWar-s32.mkv
这个片段有3个音频
* s32 (没声音)
* fltp (正常)
* s16p (正常)
