### ISSUE TITLE
No 5.1 rear speaker sound with latest IPTVX Update and Metal Player

### ISSUE THREAD

**Issue by AJ150916** [kingslay/KSPlayer#523]
Hello,
I've installed the latest IPTVX yesterday which should have the announced 5.1 rear channel audio fix. But it's not working, still no sound on my rear speakers when choosing 5.1 surround audio. For an example that it's not related to my setup, it's working fine with the Intune App.

**Comment by cdguy** [comment]
> Hello, I've installed the latest IPTVX yesterday which should have the announced 5.1 rear channel audio fix. But it's not working, still no sound on my rear speakers when choosing 5.1 surround audio. For an example that it's not related to my setup, it's working fine with the Intune App.

@kingslay  is not the developer of iptvX, you should ask @matteogobbi what is wrong.

**Comment by AJ150916** [comment]
Ho, OK that's correct but as far as I know you are the developer of the Metal Player used in IPTVX. So any idea why, after the fix for the rear speakers, it doesn't work? Thanks.

**Comment by kingslay** [comment]
#514

**Comment by kingslay** [comment]
#514

**Comment by kingslay** [comment]
@matteogobbi 这个问题已经在#514 解决了。你需要更新最新的代码

**Comment by matteogobbi** [comment]
The guy tested the latest app version. But I have another person saying that it works well.
@AJ150916 are you sure you tried the last version and the Metal player on IPTVX?

**Comment by AJ150916** [comment]
Hi, yes I'm on the latest version installed last Sunday night. I'm using an Apple TV 4K 2nd Gen. and 5.1 is working fine with all other Apps, especially for Infuse. The Audio Settings in Apple TV are also set to Dolby Digital 5.1 and my AV Receiver is showing that 5.1 Audio is activated. I have only Front L/R and Center working and the Rear R/L are totally silent. I've switched to the Metal Player in IPTVX for live and VOD. When switching to Infuse and playing the same file it's working as expected. So any recommendations in the Audio Setup?@matteogobbi @cdguy

**Comment by matteogobbi** [comment]
Can you provide a url to play to Kingslay so he can look into?Sent from my iPhoneOn Aug 15, 2023, at 10:59 AM, AJ150916 ***@***.***> wrote:﻿
Hi, yes I'm on the latest version installed last Sunday night. I'm using an Apple TV 4K 2nd Gen. and 5.1 is working fine with all other Apps, especially for Infuse. The Audio Settings in Apple TV are also set to Dolby Digital 5.1 and my AV Receiver is showing that 5.1 Audio is activated. I have only Front L/R and Center working and the Rear R/L are totally silent. I've switched to the Metal Player in IPTVX for live and VOD. When switching to Infuse and playing the same file it's working as expected. So any recommendations in the Audio ***@***.*** @cdguy

**Comment by kingslay** [comment]
> Can you provide a url to play to Kingslay so he can look into?Sent from my iPhoneOn Aug 15, 2023, at 10:59 AM, AJ150916 ***@***.***> wrote:﻿ Hi, yes I'm on the latest version installed last Sunday night. I'm using an Apple TV 4K 2nd Gen. and 5.1 is working fine with all other Apps, especially for Infuse. The Audio Settings in Apple TV are also set to Dolby Digital 5.1 and my AV Receiver is showing that 5.1 Audio is activated. I have only Front L/R and Center working and the Rear R/L are totally silent. I've switched to the Metal Player in IPTVX for live and VOD. When switching to Infuse and playing the same file it's working as expected. So any recommendations in the Audio ***@***.*** @cdguy —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

我这边没有5.1的声响。所以我这边也无法进行测试。

**Comment by AJ150916** [comment]
Just asked my IPTV provider and URL contains my login credential and is only working out of Germany. The other Option is to provide a file from my local NAS drive which contains 5.1 audio - can this be an option?

**Comment by matteogobbi** [comment]
I think @kingslay doesn't have the Dolby surround so he cannot test.
However, based on #514 this has been fixed and tested.
Also, another user from IPTVX told me that is working correctly.
So I'm wondering if it's your content. Can you try grabbing a test video file with Dolby 5.1 from the web and test that from your NAS? You can connect it to IPTVX through the SMB protocol playlist type.

**Comment by AJ150916** [comment]
I've did some tests now and no 5.1 file is working of IPTVX as it should be. Here are the 5.1 files I've used https://drive.google.com/drive/folders/1JxmeedtAtgmoafXv9rroiDOS2vEX7N4b

The rear channels are coming from the front surround speakers or, really strange, out of the center.

When using the Infuse App, everything is fine. I'm just wondering how 5.1 will work or how to bring it to work? I'm not switching anything on my AV Receiver or Apple TV, it simply just work with the Infuse App and not out of IPTVX.

I did also a test on the setup of a friend of mine with one of my files, different AV Receiver but same Apple TV Version.
It's working via the Infuse App and some other Apps like the VLC Player and it's not working out of IPTVX as well.

I will not switch to another App, IPTVX is by far the best App I've seen and used so far, but I'm highly interested to get this 5.1 issue solved.

**Comment by matteogobbi** [comment]
Notice that VLC doesn't have Dolby digital surround, so what you hear from the rear speakers is just general stereo audio.
Make sure the track is dolby digital (to see this in IPTVX, while playing enter in the player and check what the audio track selected says.

**Comment by AJ150916** [comment]
Hi, OK so then we ignore the VLC output then. For a better idea, I took a picture so that you can see that 5.1 audio is available and playing correctly with Infuse App and with IPTVX choosing Metal Player I have only FR, LR and Center.
![IMG_1771](https://github.com/kingslay/KSPlayer/assets/142207044/b664cbbb-7426-476a-95e9-cd2eca9bed41)

**Comment by matteogobbi** [comment]
This doesn’t seem metal to me. are you sure you are forcing metal?Sent from my iPadOn Aug 17, 2023, at 10:28 PM, AJ150916 ***@***.***> wrote:﻿
Hi, OK so then we ignore the VLC output then. For a better idea, I took a picture so that you can see that 5.1 audio is available and playing correctly with Infuse App and with IPTVX choosing Metal Player I have only FR, LR and Center.

**Comment by AJ150916** [comment]
Hi, so please find two photos attached. One, where you can see it's forced to metal when using IPTV list and the second one when using my NAS drive. Here you can't choose any player.
![IP-TV](https://github.com/kingslay/KSPlayer/assets/142207044/1adf17c7-953d-4ce4-b977-9ec8ce1b7095)
![local_nas](https://github.com/kingslay/KSPlayer/assets/142207044/cfc6811d-c4d5-44d4-8122-db344da465b0)

**Comment by matteogobbi** [comment]
So are you sure that the screenshot you attached before is the player coming from the first playlist? NAS can’t use Metal player in our app.

**Comment by AJ150916** [comment]
The Screenshot with the playlist called "IP-TV" is set to the Metal Player and 5.1 is not working, sound is only 2 Ch. When switching to Automatic (Beta) then I have real 5.1 sound. So it must be something related to the Metal Player

**Comment by matteogobbi** [comment]
@AJ150916 I try to repeat:

1. Go into your playlist IP-TV and make sure Metal player is forced on VODs;
2. Go into a movie that you think has dolby digital sorround 5.1;
3. In the player, open the audio settings and send a screenshot.

**Comment by cdguy** [comment]
I am wondering why you two do not exchange your thoughts via e-mail.  @AJ150916 @matteogobbi this github is not the iptvX support page. And no other devs talk, or is troubleshooting about their apps here.

@kingslay please delete this thread. I don’t thing devs are interested about an app issue here. The only app that should be discussed here is the KSplayer Demo App.

thanks.

**Comment by matteogobbi** [comment]
FYI if I thought was an app issue, I wouldn't have continued talking here. @AJ150916 opened a bug here, and he is using this app to test KSLib. We are trying to understand if it's a track problem or if KSLib is missing handling some cases, given that he isn't familiar with the demo app. 

If you aren't interested, you could simply avoid checking this thread, as I think the only outcome of it can be positive, regardless of the app. 

However, never mind.

**Comment by AJ150916** [comment]
Thanks Matteo, so I've checked everything again and it's definitely set to the Metal Player for Live and VOD. But still not working for VOD. When playing files from my NAS I have only Front L/R + Center and Sub but no audio from Rear L/R. When using the Infuse App it's woking as it should and nothings is mixed up or so, it's clear 5.1 Audio. With live TV there is no issue when using the Metal Player, which indeed is strange. Please find the two requested screenshots. Thanks
![IMG_1785](https://github.com/kingslay/KSPlayer/assets/142207044/ea1365a1-9dd8-4d41-91bb-29b4a3168fa0)
![IMG_1786](https://github.com/kingslay/KSPlayer/assets/142207044/17adf641-b5f5-4d19-8a7e-f44775adde27)

**Comment by matteogobbi** [comment]
I believe your audio track is not 5.1. The reason why Infuse might play is because they set it to stereo on all speakers. If it was 5.1 it should say 5.1 next to it, retrieved directly from the audio track. 
Other users reported 5.1 is working well for them on the same app.

Anyway please let’s close this here.

Thank you.

**Comment by AJ150916** [comment]
nope, here's a screenshot out of Infuse and you can clearly here the different and i't not mixing stereo to 5.1. If there are some effects they are coming from the rear where the normal radio is coming from the front.
![IMG_1787](https://github.com/kingslay/KSPlayer/assets/142207044/ff60b470-e2fa-415e-ad03-a562b541fa46)
