### ISSUE TITLE
Current deinterlacer method is not smooth (Yadif Mode 1 does not work properly)

### ISSUE THREAD

**Issue by chillout23** [kingslay/KSPlayer#525]
Current deinterlacing option in KSLib is not producing smooth TV-like motion. Please try to implement something like VLC's **Yadif x2** or MPV's deinterlacer. They are very smooth and looks very good. Can you take this challenge @kingslay ?

**Comment by nakiostudio** [comment]
I believe this is how you would setup Yadif x2 in ffmpeg `ffmpeg -i input.mp4 -vf "yadif=mode=1" output.mp4`

**Comment by cdguy** [comment]
@nakiostudio @chillout23
In earlier versions of the demo app, when I used the function “yadif=mode=1” the live streams played in slow motion.

1- normally the yadif documentation says "yadif=1 takes true interlaced 50i footage and turns it into astonishingly high-quality 50p output"

however, the live streams played in slow motion.

@kingslay when I check the bitratea of interlaced streams with a player like Qmplay2 I see that interlaced streams never output 50i consistently.

The bitrate varies between 45i-50i.
Besides, when I open an interlaced stream with the demo app, the demo app says that the FPS value is 25p (nothing wrong here, 50i=25p)

As you can imagine if you divide 46i to 2, it is equal to 23p

perhaps if you can find a way to double the frames per second before the stream starts (meaning that the demo app displays the FPS value as 50p) this “might” solve the issue

**Comment by cdguy** [comment]
https://stackoverflow.com/questions/45462731/using-ffmpeg-to-change-framerate?ssp=1&darkschemeovr=1&setlang=tr-TR&safesearch=moderate

@kingslay maybe this might help

**Comment by chillout23** [comment]
Do you guys know what kind of deinterlacer MPVLib uses? The motion is very smooth and performance is good on Apple TV. With Yadif x2 on VLC the performance is not very good on Apple TV. It is not optimized for ARM CPUs. So stuttering happens after 5 minutes as Apple TV cannot keep up with high load. However, MPV provides some similar deinterlacer which works well, but I do not know what kind of method is being used. So if possible the logic from MPV is what is needed to solve this - as it works well on ATV.

**Comment by cdguy** [comment]
> Do you guys know what kind of deinterlacer MPVLib uses? The motion is very smooth and performance is good on Apple TV. With Yadif x2 on VLC the performance is not very good on Apple TV. It is not optimized for ARM CPUs. So stuttering happens after 5 minutes as Apple TV cannot keep up with high load. However, MPV provides some similar deinterlacer which works well, but I do not know what kind of method is being used.
> 
> So if possible the logic from MPV (which is also based on ffmpeg) is what is needed to solve this - as it works well on ATV.

@chillout23 mpv uses yadif x1

In my opinion, doubling the frames (converting the 50i stream to 50p) “might” solve the issue. Let’s wait and see

**Comment by chillout23** [comment]
I see. Technically we are talking about 25i don't we? I see that 25i is also known as 50i.

**Comment by cdguy** [comment]
> I see. Technically we are talking about 25i don't we? I see that 25i is also known as 50i.
> 
> Anyways, sounds like a good suggestion :)

No, interlaced streams are only encoded in 50i/60i which is also equal to 25p/30p.
Let’s wait for @kingslay what he has to say, no need to speculate :)

**Comment by kingslay** [comment]
> https://stackoverflow.com/questions/45462731/using-ffmpeg-to-change-framerate?ssp=1&darkschemeovr=1&setlang=tr-TR&safesearch=moderate
> 
> @kingslay maybe this might help

目前ksplayer是支持fps 这个filter。你可以加一下fps，看下视频播放会不会更流畅点。

**Comment by kingslay** [comment]
> > Do you guys know what kind of deinterlacer MPVLib uses? The motion is very smooth and performance is good on Apple TV. With Yadif x2 on VLC the performance is not very good on Apple TV. It is not optimized for ARM CPUs. So stuttering happens after 5 minutes as Apple TV cannot keep up with high load. However, MPV provides some similar deinterlacer which works well, but I do not know what kind of method is being used.
> > So if possible the logic from MPV (which is also based on ffmpeg) is what is needed to solve this - as it works well on ATV.
> 
> @chillout23 mpv uses yadif x1
> 
> In my opinion, doubling the frames (converting the 50i stream to 50p) “might” solve the issue. Let’s wait and see

@cdguy 
我看yadif的mode 参数值如下

mode = 0 : temporal and spatial interlacing check (default).

= 1 : double framerate (bob), temporal and spatial interlacing check.

= 2 : skips spatial interlacing check.

= 3 : double framerate (bob), skips spatial interlacing check.

你的意思是mpv用的是 mode=1 这个参数值吗？

**Comment by cdguy** [comment]
> > https://stackoverflow.com/questions/45462731/using-ffmpeg-to-change-framerate?ssp=1&darkschemeovr=1&setlang=tr-TR&safesearch=moderate
> > @kingslay maybe this might help
> 
> @cdguy 目前ksplayer是支持fps 这个filter。你可以加一下fps，看下视频播放会不会更流畅点。

@kingslay can you please write the code regarding how to double the fps value for interlaced streams?
I mean if the stream is 50i, to make it 50p; and if the stream is 60i, how to make it 60p

**Comment by kingslay** [comment]
你可以先试下用这个。
class MEOptions: KSOptions {
    override func process(assetTrack: some MediaPlayerTrack) {
        if assetTrack.mediaType == .video {
            if [FFmpegFieldOrder.bb, .bt, .tt, .tb].contains(assetTrack.fieldOrder) {
                videoFilters.append("yadif=mode=1:parity=-1:deint=1")
                hardwareDecode = false
            }
        }
    }
}

如果不够顺畅的话，那可以试下
class MEOptions: KSOptions {
    override func process(assetTrack: some MediaPlayerTrack) {
        if assetTrack.mediaType == .video {
            if [FFmpegFieldOrder.bb, .bt, .tt, .tb].contains(assetTrack.fieldOrder) {
                videoFilters.append("yadif=mode=1:parity=-1:deint=1")
                videoFilters.append("fps=fps=\(Int(assetTrack.nominalFrameRate*2))")
                hardwareDecode = false
            }
        }
    }

**Comment by cdguy** [comment]
> > > Do you guys know what kind of deinterlacer MPVLib uses? The motion is very smooth and performance is good on Apple TV. With Yadif x2 on VLC the performance is not very good on Apple TV. It is not optimized for ARM CPUs. So stuttering happens after 5 minutes as Apple TV cannot keep up with high load. However, MPV provides some similar deinterlacer which works well, but I do not know what kind of method is being used.
> > > So if possible the logic from MPV (which is also based on ffmpeg) is what is needed to solve this - as it works well on ATV.
> > 
> > 
> > @chillout23 mpv uses yadif x1
> > In my opinion, doubling the frames (converting the 50i stream to 50p) “might” solve the issue. Let’s wait and see
> 
> @cdguy 我看yadif的mode 参数值如下
> 
> mode = 0 : temporal and spatial interlacing check (default).
> 
> = 1 : double framerate (bob), temporal and spatial interlacing check.
> 
> = 2 : skips spatial interlacing check.
> 
> = 3 : double framerate (bob), skips spatial interlacing check.
> 
> 你的意思是mpv用的是 mode=1 这个参数值吗？

@kingslay I mean, mpv uses the default yadif parameter (=0) 

I just installed the desktop version of MPV. the stream I opened is an interlaced stream (50i),
the media info says that the stream is 25p. 
My computer refresh rate is at 59.9 hz; because of that, you can see that the "displayed FPS" value is 59.977 FPS

![image](https://github.com/kingslay/KSPlayer/assets/123307657/d0db2837-29bf-40e0-8951-ebea405d3dcc)

**Comment by kingslay** [comment]
@cdguy 那你换下用videoFilters.append("yadif=mode=0:parity=-1:deint=1")，看下效果怎么样。用mode=1的话，会导致cpu占用比较高。不知道是不是因为这个原因所以视频不够流畅。

**Comment by cdguy** [comment]
@kingslay 

Let me express my findings:

1- Unfortunately, the last commit did not solve the "non-smooth" issue
2- if the audio codec of the interlaced stream is MP2, the sound sounds very strange
3a- when you open the same interlaced stream with MPV and KSPLAYER, without the YADIF filter, the smoothness is the same
3b- I suspect the "non smooth" issue happens when you apply the YADIF filter to KSplayer because with MPV it is smooth
4- when I used this code, the FPS value was still 25p, and the YADIF filter did not work:

```
class MEOptions: KSOptions {
override func process(assetTrack: some MediaPlayerTrack) {
if assetTrack.mediaType == .video {
if [FFmpegFieldOrder.bb, .bt, .tt, .tb].contains(assetTrack.fieldOrder) {
videoFilters.append("yadif=mode=1:parity=-1:deint=1")
videoFilters.append("fps=fps=(Int(assetTrack.nominalFrameRate*2))")
hardwareDecode = false
```

I will send you in a few minutes some links

**Comment by cdguy** [comment]
@kingslay the audio tracks encoded in MP2 still have the issue I mentioned.
You can try with the stream link I sent to you via e-mail (the one that ends with 32487)

**Comment by chillout23** [comment]
Is this fixed now? @cdguy

**Comment by kingslay** [comment]
@cdguy 可以不用加videoFilters.append("fps=fps=(Int(assetTrack.nominalFrameRate*2))")。
只要videoFilters.append("yadif=mode=0:parity=-1:deint=1") 。

**Comment by cdguy** [comment]
> Is this fixed now? @cdguy

@chillout23 Yes it is (almost) fixed.
It works perfectly on tvos, and on ios it needs a fine tuning.

I sent an e-mail to Kingslay about it

**Comment by kingslay** [comment]
> > Is this fixed now? @cdguy
> 
> @chillout23 Yes it is (almost) fixed. It works perfectly on tvos, and on ios it needs a fine tuning.
> 
> I sent an e-mail to Kingslay about it

@cdguy  我看了下是因为在iOS preferredFramesPerSecond 不起作用，在tvOS是起作用的。还是会以60hz来刷新，但是视频是25hz。这就会导致不流畅。mpv在iOS也是流畅的吗？

**Comment by cdguy** [comment]
@kingslay I suspect this “might be” because of the refresh rate of ios devices; as some models have a refresh rate up to 120hz, whereas other ios devices have a “static” screen refresh rate of 60/90 hz

**Comment by cdguy** [comment]
> 我看了下是因为在iOS preferredFramesPerSecond 不起作用，在tvOS是起作用的。还是会以60hz来刷新，但是视频是25hz。这就会导致不流畅。mpv在iOS也是流畅的吗？

Yes, just check the link I sent you yesterday (that ends with 6cc3a) you will see that the video with MPV is smooth
@kingslay

**Comment by kingslay** [comment]
是的，我在最新的代码增加了高刷的支持，有设备的人可以尝试下。但是我看了apple的文档 https://developer.apple.com/documentation/quartzcore/optimizing_promotion_refresh_rates_for_iphone_13_pro_and_ipad_pro 。里面没有支持25hz或50hz。所以我猜测还是会有问题。但是如果刷新率高一点的话，不流畅就不会那么明显了。

**Comment by cdguy** [comment]
> > > Is this fixed now? @cdguy
> > 
> > 
> > @chillout23 Yes it is (almost) fixed. It works perfectly on tvos, and on ios it needs a fine tuning.
> > I sent an e-mail to Kingslay about it
> 
> @cdguy 我看了下是因为在iOS preferredFramesPerSecond 不起作用，在tvOS是起作用的。还是会以60hz来刷新，但是视频是25hz。这就会导致不流畅。mpv在iOS也是流畅的吗？

@kingslay I know it is easy to say, but if you could log and monitor the behaviour of the refresh rate in MPV lib when using an iphone (X-11-12) that has a refresh rate of 60hz; you might find something

**Comment by kingslay** [comment]
我对mpv的了解很少，你知道mpv是怎么来实现视频的渲染的吗？我搜索下了下mpv的代码。里面没有用NSTimer和CADisplayLink。 我很好奇他它怎么样来实现定时渲染视频的。

**Comment by cdguy** [comment]
I have sent you via e-mail a few screenshots that might help you. @kingslay

**Comment by chillout23** [comment]
Personally I dont think its that critical on iOS as the screen size is too small to notice this, but its good if it can be fixed of course. Let's aim for perfection :)

**Comment by chillout23** [comment]
@cdguy is the motion smooth as MPV now in this KSPlayer?

**Comment by chillout23** [comment]
Tested in latest version of Tracy Player, the motion is better than before but still not perfect like MPV or VLCs Linear deinterlacer.

**Comment by cdguy** [comment]
> 是的，我在最新的代码增加了高刷的支持，有设备的人可以尝试下。但是我看了apple的文档 https://developer.apple.com/documentation/quartzcore/optimizing_promotion_refresh_rates_for_iphone_13_pro_and_ipad_pro 。里面没有支持25hz或50hz。所以我猜测还是会有问题。但是如果刷新率高一点的话，不流畅就不会那么明显了。

There is nothing to reopen @chillout23; on tvos the image is very smooth, @kingslay will definitely publish a “fix” for ios/ipados devices that does not  have ProMotion screens.

**Comment by chillout23** [comment]
There is. Have you seen MPVs deinterlacer? Or VLCs Linear deinterlacer? The motion is silky smooth. I am not talking about iOS/iPadOS. I am testing on TV and comparing different player engines. Download VLC, enable deinterlacing and try a interlaced stream and compare with KSPlayer. Can you do that?

**Comment by cdguy** [comment]
@kingslay the “fix” you can apply might be the following:

1- identify the ios/ipadOS devices that does have promotion display: 
- iphone: 13pro-14pro-15pro (and pro max models)
- Ipad: all pro models from 2021 model to the most recent

2- if the device used is not the device mentioned above do the following:

a- for 25 fps streams (I mean 25p streams); multiply the number of frames by 2,4 so the stream would be “upgraded” to 60p and match the refresh rate of the device’s screen which is 60hz
b- for a stream that is 50fps (both 50i or 50p) multiply the number of frames by 1,2 so the stream would be “upgraded” to 60p and match the refresh rate of the device’s screen which is 60hz.

**Comment by chillout23** [comment]
@cdguy, let me know when you have tested. you will see what I mean.

**Comment by cdguy** [comment]
> There is. Have you seen MPVs deinterlacer? Or VLCs Linear deinterlacer? The motion is silky smooth. I am not talking about iOS/iPadOS. I am testing on TV and comparing different player engines. Download iPlayTV on tvOS for example and compare VLC/MPV engines with KSPlayer with an interlaced stream.
> 
> https://testflight.apple.com/join/irMsXGg0
> 
> VLCs deinterlacer flickers, but the motion is silky smooth. MPVs deinterlacer does not flicker and is also perfect. This is what KSPlayer should aim for. If using MPV on iPlay TV you have to enable deinterlacing manually. Auto does not work.
> 
> Try it and see for yourself :)

The iplayTV beta app does not use the latest ksplayer code, and the stream is still jerky in IplayTV. You should ask to Andre to update first the ksplayer and let him know that the player is called Ksplayer and not “ffmpeg” as he names it. A bit of respect to @kingslay would be cool.
Second, please check that in your appleTV settings that dynamic range and content matching settings are ON.

**Comment by chillout23** [comment]
@cdguy, I know he is not using the latest version of KSPlayer at the moment yes. But check out VLC and MPV as I told you in my post and see for yourself how interlacing works. 

"Second, please check that in your appleTV settings that dynamic range and content matching settings are ON."
Nothing to do with this. I have full control over these settings.

Let us stay within the topic. If you have a proper interlaced stream, try it out with VLC and MPV in iPlayTV Beta.

**Comment by Kimentanm** [comment]
In the previous version, I added "yadif=mode=0:parity=auto:deint=0" to options.videoFilters, and the deinterlacing runned well.
But now it's not working.

**Comment by kingslay** [comment]
@Kimentanm 你有把hardwareDecode 设置为false吗？你设置了yadif之后。代码有走到 
return outputFrame ?? inputFrame 这一行吗？

**Comment by UnknownCoder807** [comment]
I use the following in my app and people report it works ok for interlaced

`videoFilters = ["yadif=mode=0:parity=-1:deint=1"]
`

**Comment by cdguy** [comment]
> In the previous version, I added "yadif=mode=0:parity=auto:deint=0" to options.videoFilters, and the deinterlacing runned well.
> But now it's not working.

Check the path  Demo/demo-iOS/demo-iOS/AppDelegate.swift and at line 101 you will see the correct deintrrlace settings: https://github.com/kingslay/KSPlayer/blob/114da4bb06de62dc868d09def5593d1bde6b91dc/Demo/demo-iOS/demo-iOS/AppDelegate.swift#L101
@Kimentanm

**Comment by cdguy** [comment]
And for the memo, here is the dfference between yadif=0 and yadif=1

-> In FFmpeg, the `yadif` filter is used for deinterlacing video content. It stands for "yet another deinterlacing filter." When specifying `yadif=0` or `yadif=1`, you are setting the filter mode:

1. `yadif=0`: This mode is called "auto." In this mode, FFmpeg automatically determines whether to apply deinterlacing or not based on the input video's field order and motion analysis. It will apply deinterlacing when needed.

2. `yadif=1`: This mode is called "bob." In this mode, the filter will always perform deinterlacing by using a basic "bob" deinterlacing algorithm, which creates a frame for each field, effectively doubling the frame rate.

The choice between these modes depends on your specific video content and requirements. If you're unsure, using the default "auto" mode (`yadif=0`) is generally a safe choice as it allows FFmpeg to decide whether deinterlacing is necessary. However, if you want to force deinterlacing, you can use `yadif=1`.

**Comment by chillout23** [comment]
@kingslay can you add all the different options for deinterlacing in Tracy Player so we can change in GUI the different options?

**Comment by chillout23** [comment]
> vf=yadif=mode=1:deint=1
 is the correct way to deinterlace and the only option which provides smooth motion. You can test this in MPV on the computer putting this into mpv.conf

**Comment by cdguy** [comment]
> @kingslay can you add all the different options for deinterlacing in Tracy Player so we can change in GUI the different options?

@chillout23 
don't get me wrong but as YADIF is the best deinterlacer mode in terms of image blending and image quality (I mean it is the one that has the less image degradation), why someone would want to use Bob or Linear?

**Comment by chillout23** [comment]
@cdguy **vf=yadif=mode=1:deint=1** is the correct option for having smooth motion, I tested this on PC with mpv and there is night and day difference between yadif-mode=0 and 1.

**Comment by cdguy** [comment]
> @nakiostudio @chillout23 In earlier versions of the demo app, when I used the function “yadif=mode=1” the live streams played in slow motion.
> 
> 1- normally the yadif documentation says "yadif=1 takes true interlaced 50i footage and turns it into astonishingly high-quality 50p output"
> 
> however, the live streams are played in slow motion.
> 
> @kingslay when I check the bitratea of interlaced streams with a player like Qmplay2 I see that interlaced streams never output 50i consistently.
> 
> The bitrate varies between 45i-50i. Besides, when I open an interlaced stream with the demo app, the demo app says that the FPS value is 25p (nothing wrong here, 50i=25p)
> 
> As you can imagine if you divide 46i to 2, it is equal to 23p
> 
> perhaps if you can find a way to double the frames per second before the stream starts (meaning that the demo app displays the FPS value as 50p) this “might” solve the issue

@chillout23 as mentioned above on the 16th of August, with `yadif mode =1` the video playback is in slow motion; and @kingslay also mentions here https://github.com/kingslay/KSPlayer/issues/525#issuecomment-1681949322 that the CPU usage is higher with yadif=1

I agree that yadif=1 should be used for a smoother playback but I guess this needs a "better memory" management from ksplayer, I do not know if Kingslay can find a way to improve the performance with the `yadif mode =1` filter

**Comment by chillout23** [comment]
Yes this is exactly what "we" should try to work on. MPV can do this on tvOS. CPU usage is high but I left the stream for 3 hours and I had no lag whatsoever. The box gets hot though and I monitored 170% CPU usage in average.

So lets experiment @kingslay , please add the options to toggle between yadif-mode=0 and 1 :)

**Comment by chillout23** [comment]
Maybe we need to enable Yadif-mode:1 and exclude hardware decoding, so it is only done in software - maybe the reason for the "slow motion" playback @cdguy

**Comment by chillout23** [comment]
@kingslay I also suggest you reopen this thread. A smooth interlacer is really important in a player like this, there are still so much interlaced content being broadcasted in the world. Let's try to get this `yadif-mode:1` working.

**Comment by kingslay** [comment]
我可以在demo里面增加这个开关。并且现在yadif也支持硬解码了。你们可以试下在yadif_videotoolbox=mode=1的场景下。视频播放的效果怎么样。

**Comment by cdguy** [comment]
> 我可以在demo里面增加这个开关。并且现在yadif也支持硬解码了。你们可以试下在yadif_videotoolbox=mode=1的场景下。视频播放的效果怎么样。

@chillout23 is not a developper; he can only try the tracyplayer testflight app
if you want, add the switch and update the tracyplayer testflight app

**Comment by kingslay** [comment]
好的，可以

**Comment by cdguy** [comment]
@kingslay please do not forget to update the testflight app :)

**Comment by chillout23** [comment]
Just tested, but unfortunately nothing works.
Tracy Player does not deinterlace at all.

I tried all settings:
send_frame
send_field
send_frame_nospatial
send_field_nospatial

@kingslay

**Comment by cdguy** [comment]
> Just tested, but unfortunately nothing works. Tracy Player does not deinterlace at all.
> 
> I tried all settings: send_frame send_field send_frame_nospatial send_field_nospatial
> 
> @kingslay



@kingslay I confirm the issue too, de-interlace does not work

**Comment by kingslay** [comment]
可以提供下url吗

**Comment by cdguy** [comment]
I sent you a few URLs @kingslay 

Please use a VPN with a Europe Location (Germany is preferred)

**Comment by edge261** [comment]
I gave it a look after the last commit and even when the text looks smooth, the motion is still very stuttery. 

in fact, looking at it gave me a headache lol

i still wonder what the lillyplayer dev did to achieve that smoothness...

**Comment by matteogobbi** [comment]
ask @JeremTM93 , maybe they know.

**Comment by chillout23** [comment]
Lillyplayer enabled yadif mode = 1 but it is based on MPV.

**Comment by chillout23** [comment]
After the last commit, can anyone get this to work? For me these new settings don't do anything...

**Comment by cdguy** [comment]
> I gave it a look after the last commit and even when the text looks smooth, the motion is still very stuttery.
> 
> in fact, looking at it gave me a headache lol
> 
> i still wonder what the lillyplayer dev did to achieve that smoothness...

Guys be patient a bit, in the changelog @kingslay mentions  that `videotoolbox` creates a bug; 

Once he founds the issue, the interlaced streams playback will be awesome.

**Comment by cdguy** [comment]
> After the last commit, can anyone get this to work? For me these new settings don't do anything...

If you use `send_frame` aka yadif=0 it is how it was before the commit.

@kingslay in my opinion you should repoen the thread and close it until you find the fix for `videotoolbox` usage

**Comment by chillout23** [comment]
I think Tracy Player has no functionality to actually **enable** deinterlacing right now. There are just options to choose different types: `0, send_frame
Output one frame for each frame.

1, send_field
Output one frame for each field.

2, send_frame_nospatial
Like send_frame, but it skips the spatial interlacing check.

3, send_field_nospatial
Like send_field, but it skips the spatial interlacing check.

The default value is send_frame.`

**Comment by chillout23** [comment]
Ok. I got it to work. I had a stream set to .m3u8 (hls) where it did not work. With .ts it works, but yes, it is slow motion like @cdguy  said. So there are some stuff missing here, let's wait and see if kingslay can fix it.

**Comment by chillout23** [comment]
@kingslay this issue is not fixed you need to open it.

**Comment by cdguy** [comment]
@kingslay I might have found a temporary fix for a smooth playback of interlaced streams.
Please note that I have tried with this last commit: https://github.com/kingslay/KSPlayer/commit/247d8c9105be6e0d9dd8d1e340b5586f596c0893

My temp fix:

use `yadif=1` (yadif_field)
As you know, whith yadif=1 the video is played at half speed and the sound is heard at “normal speed”

if you play the stream at x2 speed (via playback speed) you can see that the video playback is very good. The only thing you would need to do codewise is this:
If yadif=1 is used
make playback speed x2 (for video)
Make audio track playback x0,5

I am uploading a video record and you will see what I mean.
You will receive the videos via “collect”

I hope that is helps

**Comment by cdguy** [comment]
Also using the “method” I mentioned above, made the stream very smooth on ios device that does not support 120hz display @kingslay

**Comment by chillout23** [comment]
> @kingslay I might have found a temporary fix for a smooth playback of interlaced streams. Please note that I have tried with this last commit: [247d8c9](https://github.com/kingslay/KSPlayer/commit/247d8c9105be6e0d9dd8d1e340b5586f596c0893)
> 
> My temp fix:
> 
> use `yadif=1` (yadif_field) As you know, whith yadif=1 the video is played at half speed and the sound is heard at “normal speed”
> 
> if you play the stream at x2 speed (via playback speed) you can see that the video playback is very good. The only thing you would need to do codewise is this: If yadif=1 is used make playback speed x2 (for video) Make audio track playback x0,5
> 
> I am uploading a video record and you will see what I mean. You will receive the videos via “collect”
> 
> I hope that is helps

@cdguy i had to disable the audio renderer in tracy player to playback deinterlaced smoothly with 2x, with audio renderer on the playback started to jump. But interesting idea, if this could be implemented in a way that works :)

**Comment by cdguy** [comment]
@kingslay don’t forget to update the testflight app, @chillout23 would like to test the fix

**Comment by cdguy** [comment]
@kingslay it looks like you fixed the issue!! Waiting for @chillout23 and @JeremTM93 confirmation :)

on the other hand,

can you please rename the filters in your code like this (novice users would not understand what send_frame means):

yadif = yadif=0
yadif_2x = yadif=1
yadif_spatial_skip = yadif=2
yadif_2x_spatial_skip = yadif=3

besides, I haven’t checked your code, but please make `yadif=1` (yadif_2x in my naming suggestion) the default yadif filter.

those who want to use other yadif filters would change it according to their taste

thanks!!

**Comment by cdguy** [comment]
@kingslay i mean this


`yadif=mode=1:parity=-1:deint=1`

**Comment by kingslay** [comment]
好的 可以 我改下

**Comment by chillout23** [comment]
Just tested, it's unfortunately jerky. It's smooth for 2 seconds, then it jumps a little, then the player eventually crashes after 20-30 seconds. This should be easy for @kingslay to reproduce if he has a interlaced stream to work with, preferably some video with scrolling text... @cdguy how come it works for you, do you have your own app? Did you try TracyPlayer? Which ATV device you using?

**Comment by cdguy** [comment]
> Just tested, it's unfortunately jerky. It's smooth for 2 seconds, then it jumps a little, then the player eventually crashes after 20-30 seconds. This should be easy for @kingslay to reproduce if he has a interlaced stream to work with, preferably some video with scrolling text... @cdguy how come it works for you, do you have your own app? Did you try TracyPlayer? Which ATV device you using?

I spoke a bit early this morning @chillout23 I provided a few interlaced streams to @kingslay he is working on it

**Comment by chillout23** [comment]
No problem, thank you for your contribution to this issue :)

**Comment by cdguy** [comment]
@chillout23 new fix just updated, try it when the new testflight beta is uploaded

**Comment by JeremTM93** [comment]
Hi Kingslay, can you update TracyPlayer with your latest changes please?

**Comment by kingslay** [comment]
这个问题还没修复好。我

**Comment by kingslay** [comment]
@JeremTM93 这个问题我修复了。也更新test flight

**Comment by JeremTM93** [comment]
![1000006768.jpg](https://github.com/kingslay/KSPlayer/assets/121438307/2db464c7-c124-472b-a619-7ce5df3d1415)

**Comment by JeremTM93** [comment]
At the beginning of the video, it's really in time-lapse, image and sound. After a minute it's almost perfect, it's very slightly accelerated. It's very fluid, no jerks noted.

And by staying longer on the live stream, it cuts (buffering)... and the sound becomes out of sync with the image.

**Comment by cdguy** [comment]
@kingslay @JeremTM93 

I could only try on ios:
1- I noticed that the playback speed button does not work.
2- the yadif x2 filter works very well, however the playback speed is around 1.5x speed. And the sound is synced with the video. Perhaps fixing the playback speed button/feature might solve the issue

i will write here after I try on tvos

**Comment by chillout23** [comment]
On my end the playback is jerky... it "jumps". I watch a interlaced stream with a rolling text bar...

**Comment by cdguy** [comment]
> On my end the playback is jerky... it "jumps". I watch an interlaced stream with a rolling text bar...

Please specify your device. The stream details, etc.
This kind of comment does not help.

**Comment by chillout23** [comment]
@cdguy  Apple TV 4K 2022. I tried several streams I have access to through my provider. If you have a public link please send me so we can do tests on same channel/stream :)

**Comment by kingslay** [comment]
> At the beginning of the video, it's really in time-lapse, image and sound. After a minute it's almost perfect, it's very slightly accelerated. It's very fluid, no jerks noted.
> 
> And by staying longer on the live stream, it cuts (buffering)... and the sound becomes out of sync with the image.

这个是因为我做了一个直播降低 时延的功能。缓存很小的话，那就以0.8倍数来播放，如果缓存很大的话，那就以1.2倍数来播放。我优化下这个倍数播放的策略。所以目前在直播场景的话，外部是无法控制倍数播放的。

**Comment by cdguy** [comment]
@kingslay I sent you a 5 minutes interlaced stream via e-mail
You can easily check if the playback speed is x1; there is a time counter

![Ekran görüntüsü 2023-10-30 090014](https://github.com/kingslay/KSPlayer/assets/123307657/0a9e3a9b-5c36-477d-af19-0053e93749bc)

In my opinion, for buffer settings and being "the closest possible to a live stream" (meaning watching without buffering) you can use the settings of Qmplay2 which uses only ffmpeg library (https://github.com/zaps166/QMPlay2)

some providers add incremental buffering; because of this, even if you set the "live stream buffer length" to 5 seconds and then fast-forward to be "ahead" you will see that a buffer size will again be added.

how to replicate:

1- open a stream with qmplay2; set the settings as seen in the screenshot.
2- open a stream
3- press the right arrow key on your keyboard
4- look at the buffer value (the field where it is written "4.0 s")
5- you should see that even if you reduced the buffer size by hitting the right arrow key on your keyboard, buffer has been added.

what can be implemented and done:

1- as I suggested, add the playback settings (the first 7; starting with "short seeking" and ending with "start internet playback internet stream if...")

2- for the fast forward feature (short seeking as per qmplay2) one of the 2 things can be used:

use the "fast forward" buttons like the one used in the native player
![WhatsApp Görsel 2023-10-30 saat 09 23 04_6c78ea93](https://github.com/kingslay/KSPlayer/assets/123307657/7e88118c-d735-469e-9e8c-b0864380ac97)

or use tap gestures:
in VLC you can seek forward by double-tapping on the screen:

https://github.com/kingslay/KSPlayer/assets/123307657/9bfc31a4-e13f-4f65-a983-28420008508f


on TVOS, a double press on the right arrow on the remote can do the "fast forward"/forward seek

**Comment by kingslay** [comment]
我看了，音视频不同步是因为内存占用太高了。软解来不及，导致没有解码后的视频帧。这个时候暂停一会儿，情况就好转了。但是这个是直播，这样就会导致时延很大。还有一个可以做的事情就是，就是丢弃一些解码之前的视频包，这样解码压力就不会那么大了。这样改动就会大一点。

**Comment by cdguy** [comment]
> 我看了，音视频不同步是因为内存占用太高了。软解来不及，导致没有解码后的视频帧。这个时候暂停一会儿，情况就好转了。但是这个是直播，这样就会导致时延很大。还有一个可以做的事情就是，就是丢弃一些解码之前的视频包，这样解码压力就不会那么大了。这样改动就会大一点。

I am going to send you a screen video  record via e-mail that supports your idea

**Comment by chillout23** [comment]
@kingslay why you keep closing this issue without checking with users first if it is fixed or not?

**Comment by cdguy** [comment]
> @kingslay why you keep closing this issue without checking with users first if it is fixed or not?

@chillout23 mate, calm down :) I guess you don't know how @kingslay works. as he wrote above, he is aware of the issue and will push a new commit when the issue is fixed

**Comment by chillout23** [comment]
> > @kingslay why you keep closing this issue without checking with users first if it is fixed or not?
> 
> @chillout23 mate, calm down :) I guess you don't know how @kingslay works. as he wrote above, he is aware of the issue and will push a new commit when the issue is fixed

I did see what he wrote. And I am very calm actually, it was just a friendly question :) @kingslay take your time, and I hope for a proper fix without any workarounds.

**Comment by matteogobbi** [comment]
@chillout23 then 

> > > @kingslay why you keep closing this issue without checking with users first if it is fixed or not?
> > 
> > 
> > @chillout23 mate, calm down :) I guess you don't know how @kingslay works. as he wrote above, he is aware of the issue and will push a new commit when the issue is fixed
> 
> I did see what he wrote. And I am very calm actually, it was just a friendly question :) @kingslay take your time, and I hope for a proper fix without any workarounds.

Then you should rephrase, because that isn't a friendly question.

This said, I agree with you that he closes issues too superficially, but is also true that this is his library and it is a free library, hence he can do wtf he wants 🤣

**Comment by cdguy** [comment]
can you please update the tracy player testflight app? @JeremTM93 will try when he can
thanks

**Comment by kingslay** [comment]
现在已经在打包了

**Comment by chillout23** [comment]
It seems to work perfectly for me right now. But lets verify with @JeremTM93 :)

**Comment by kingslay** [comment]
> Only thing I noticed is perhaps a slight lip sync issue? But I am not 100% sure it might be my stream, something others can test and report back on maybe?

是指音频和视频会有轻微的不同步吗？如果是音视频同步的问题，可以看下日志里面是否有 [video] video delay 这个信息

**Comment by JeremTM93** [comment]
I am currently testing with yadif 2 and a 25 FPS stream. It's fluid and the image is much more beautiful! Well done @kingslay! 
I let the flow run to check stability.

**Comment by JeremTM93** [comment]
We should also test on streams in 30 and 60 FPS, right?  Shouldn't there be any change for 24 and 50 FPS streams?

**Comment by chillout23** [comment]
**Update**: When I select "Audio Renderer = Off" I have no problems with the audiosync!👍 

@kingslay what does exactly "Audio Renderer = On" do? And do you know why it causes the audio to not be in sync?

**Comment by JeremTM93** [comment]
We will continue to test different streams. But it's now very fluid, the image is beautiful, it's stable and there's no audio delay.
Well done @kingslay, and thank you @cdguy for your involvement 👏

**Comment by cdguy** [comment]
> **Update**: When I select "Audio Renderer = Off" I have no problems with the audiosync!👍
> 
> @kingslay what does exactly "Audio Renderer = On" do? And do you know why it causes the audio to not be in sync?

`Audiorenderer` is used for spatial audio. @kingslay himself says that this feature should only be used for audio only features. Spatial audio is only beneficial if you have compatible airpods @chillout23

**Comment by chillout23** [comment]
All right, thanks @cdguy . It works perfectly now, thanks to everyone involved!
