### ISSUE TITLE
Crash on `var result = avformat_open_input(&self.formatCtx, urlString, nil, &avOptions)`

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#526]
This keeps crashing for certain streams, although all MKV and playable with other players.

`var result = avformat_open_input(&self.formatCtx, urlString, nil, &avOptions)`

I can't understand what's the problem but it seems a memory issue. @kingslay do you have any idea on how to approach this problem?

Notice that the issue is on tvOS.

**Comment by kingslay** [comment]
这个需要有对应的url让我调试。我才能解决这个问题。不然我无能为力。

**Comment by matteogobbi** [comment]
@kingslay  Sent you an email.

**Comment by kingslay** [comment]
@matteogobbi 我没有收到邮件

**Comment by matteogobbi** [comment]
Wrong mail sorry. Sent again. Sent from my iPhoneOn Aug 20, 2023, at 4:07 PM, kingslay ***@***.***> wrote:﻿
@matteogobbi 我没有收到邮件

**Comment by kingslay** [comment]
那这个应该是因为你的应用引入的其他sdk导致的，你可以看下那个sdk有SSL_CTX_new 这个符号。

**Comment by matteogobbi** [comment]
What do you mean?

**Comment by kingslay** [comment]
你要检查下你的代码里面是不是有其他的openssl,或是openssl的变体 例如 libtls之类的

**Comment by matteogobbi** [comment]
I found that there was indeed a set of old OpenSSL/Crypto headers that was making it crash.

Thank you for your help and support.
