### ISSUE TITLE
Best way to get media informations.

### ISSUE THREAD

**Issue by loicleser** [kingslay/KSPlayer#529]
Hello
I start again to integrate KSPlayer in my application.

What is the best way to retrieve movie information to create a custom interface?

I need to retrieve the following information:
Total time
Remaining time
Current Time / Position

I don't see an easy way to retrieve this information so I guess I'm missing the solution.

Currently I seated a customPlayer that works when I set a ressource. 

THANKS

**Comment by kingslay** [comment]
currentTime
totalTime
```
public protocol KSPlayerLayerDelegate: AnyObject {
    func player(layer: KSPlayerLayer, state: KSPlayerState)
    func player(layer: KSPlayerLayer, currentTime: TimeInterval, totalTime: TimeInterval)
    func player(layer: KSPlayerLayer, finish error: Error?)
    func player(layer: KSPlayerLayer, bufferedCount: Int, consumeTime: TimeInterval)
}
```

**Comment by loicleser** [comment]
No way to do it like on VLC? : 

func totalTimeFormatted() -> String {
        if currentPlayerEngine == .FFMPEG {
            // Need KSTotalTime here
            return ksPlayerView...
        } else {
            return VLCplayer.media?.length.stringValue ?? "00:00"
        }
    }

**Comment by kingslay** [comment]
duration  Total time
currentPlaybackTime 
```

public protocol MediaPlayback: AnyObject {
    var duration: TimeInterval { get }
    var naturalSize: CGSize { get }
    var currentPlaybackTime: TimeInterval { get }
    func prepareToPlay()
    func shutdown()
    func seek(time: TimeInterval, completion: @escaping ((Bool) -> Void))
}
```

**Comment by loicleser** [comment]
Sorry but I don't know how I can use it from the ksPlayerView var I've :-D

**Comment by kingslay** [comment]
你可以看我的demo
也可以搜索下currentPlaybackTime 这个关键字。看下要怎么用。
