### ISSUE TITLE
Tracy player (testflight version) - Audio Renderer issue

### ISSUE THREAD

**Issue by cdguy** [kingslay/KSPlayer#531]
It looks like the audio renderer in your testflight test app (tracy player - ios) does not output the sound in multichannel audio.
![IMG_5266](https://github.com/kingslay/KSPlayer/assets/123307657/ca14c8bb-f5f1-48ae-82a4-30d0594a1a0d)
![IMG_5267](https://github.com/kingslay/KSPlayer/assets/123307657/ff31ff87-d138-4020-8fad-97241ae28be0)
![IMG_5268](https://github.com/kingslay/KSPlayer/assets/123307657/3a8a7eae-f811-4fca-98f0-f2c9d2136ce0)

**Comment by cdguy** [comment]
I sent you an e-mail with the link

the issue is the same with the testflight app updated today.

The stream has sound. the issue is that the audio "properties" is displayed as stereo, but the tag has to be "multichannel"

**Comment by kingslay** [comment]
![image](https://github.com/kingslay/KSPlayer/assets/3964055/b297f2c9-20af-4975-84f7-478a64f2a4b7)

**Comment by kingslay** [comment]
我试了 是可以的啊

**Comment by cdguy** [comment]
@kingslay I found an easier way to help you debug the spatial audio issue.

1- put your airpods and after open tracy app; then open the link I sent you. even if audio renderer= true; the audio is displayed as Stereo.

2- open tracy player; open the link I sent you, start the playback (here audio renderer is also = true), THEN put your airpods. when you force touch the volume control it says multi channel. However, you will also notice that when you start the stream and after put your airpods pro, the sound is audible for 1 second and after there is no audio. the issue is "fixed" if you hit the +/- 15 seconds button.

**Comment by cdguy** [comment]
@kingslay do you have any automation process to update the testflight tracy player? For users who are not dev but willing to provide feedback, it would be great to update automatically tracy player after each commit

**Comment by kingslay** [comment]
有的，我有配置了Xcode cloud，代码合并到master的时候会自动发布testflight。 每次提交都自动发布的话，那会非常的频繁，而且xcode cloud 超过使用时间的话，也要收费。

**Comment by cdguy** [comment]
> @kingslay I found an easier way to help you debug the spatial audio issue.
> 
> 1- put your airpods and after open tracy app; then open the link I sent you. even if audio renderer= true; the audio is displayed as Stereo.
> 
> 2- open tracy player; open the link I sent you, start the playback (here audio renderer is also = true), THEN put your airpods. when you force touch the volume control it says multi channel. However, you will also notice that when you start the stream and after put your airpods pro, the sound is audible for 1 second and after there is no audio. the issue is "fixed" if you hit the +/- 15 seconds button.

@kingslay unfortunately, this time "multichannel audio" does not work at all when I enable audio renderer =true on the testflight tracy player

**Comment by kingslay** [comment]
你是用iPhone 还是 tvos呢

**Comment by cdguy** [comment]
> 你是用iPhone 还是 tvos呢

I had the issue on iphone;

I have not yet tried on tvos. I will try
@kingslay

**Comment by cdguy** [comment]
@kingslay on tvos audio renderer works fine. The issue is on IOS. Also, can you please check the audio delay issue, after a few seconds of playback, there is a slight audio delay with the video.

![IMG_5312](https://github.com/kingslay/KSPlayer/assets/123307657/79fd8455-fd96-4ae0-87f7-410ced1c773d)
