### ISSUE TITLE
KSPlayer keeps trying though it should probably fail

### ISSUE THREAD

**Issue by nightfall708** [kingslay/KSPlayer#533]
Hi,
Trying to play this stream: `http://eno.emit.com:8000/5uv_live_64.mp3` I would expect the player to fail as the host cannot be resolved, but it keeps trying.. 
VLC Fails.

**Comment by kingslay** [comment]
你可以设置下这个代码

formatContextOptions["reconnect_on_network_error"] = 0

**Comment by nightfall708** [comment]
Thanks... hmm, the question is what is contained in "network error". If the user is on cellular and lost signal, will it reconnect?

**Comment by kingslay** [comment]
这个就不清楚了。因为这个是ffmpeg那边的开关。是根据错误来区分的。你可以在ffmpeg里面搜索reconnect_on_network_error 这个关键字。就可以看到代码逻辑了。

**Comment by kingslay** [comment]
你可以试下，如果把reconnect_on_network_error设置为0.会不会影响到一些网络差的情况。如果不会影响的话，那我会默认把reconnect_on_network_error 设置为0.
