### ISSUE TITLE
totalTime与实际不符

### ISSUE THREAD

**Issue by Kimentanm** [kingslay/KSPlayer#534]
test url：http://[2409:8087:2001:20:2800:0:df6e:eb26]/ott.mobaibox.com/PLTV/1/224/3221228277/index.m3u8?playseek=20230829070000-20230829120000

实际时间是18000s，但检测出来的时间是6275.614933000001

**Comment by kingslay** [comment]
这个连接我打不开。你可以用ffmpeg的命令。看下读取出来的totalTime是多少。
ffmpeg -i http://\[2409:8087:2001:20:2800:0:df6e:eb26\]/ott.mobaibox.com/PLTV/1/224/3221228277/index.m3u8\?playseek\=20230829070000-20230829120000

**Comment by Kimentanm** [comment]
ffmpeg log:
Input #0, hls, from 'http://[2409:8087:2001:20:2800:0:df6e:eb26]/ott.mobaibox.com/PLTV/1/224/3221228277/index.m3u8?playseek=20230829070000-20230829120000':
  Duration: 05:00:00.00, start: 11724.385067, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
  Stream #0:0: Video: hevc (Main) ([36][0][0][0] / 0x0024), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn
    Metadata:
      variant_bitrate : 0
  Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 32000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
      
这是ipv6的地址，一般wifi是没有ipv6的，但是手机流量是肯定有ipv6的，所以想访问这个链接可以用手机给电脑开热点就可以访问了。

**Comment by kingslay** [comment]
按照ffmpeg 的结果来算的 
5*3600- 11724.385067 =  6275.614933000001
我的totalTime就是通过这个方式来算的。你是用vlc，然后他们算出来的totalTime是18000s吗？

**Comment by Kimentanm** [comment]
我是用iina看的，进度条显示的是05:00:00.00，这个startTime很奇怪，这是一段视频，startTime应该是0才对
![image](https://github.com/kingslay/KSPlayer/assets/25970284/a22aee33-0140-4856-ab8d-f60fd90d73bb)

**Comment by kingslay** [comment]
视频的startTime 不是会一直都是0的。 ffmpeg里面的startTime是start: 11724.385067。 有些视频是录制其中的一小部份，所以startTime就会不为0了。

**Comment by kingslay** [comment]
iina是错误的 ，他没有减去startTime这个值。

**Comment by Kimentanm** [comment]
从download下来的m3u8文件上看，是有完整的5个小时的ts切片的
[index.m3u8](https://github.com/kingslay/KSPlayer/files/12471406/index.txt)

**Comment by kingslay** [comment]
对于这种视频有两个思路。
一个是iina这样的。totalTime  显示18000s，但是播放的时候，开始时间是用start: 11724.385067 。
另一种是我的方式，totalTime显示 18000 - 11724.385067。播放的开始时间是0。
我是觉得第二种的方式比较好。因为我这种方式就比较好进行seek。 
例如下面的一个极端情况，Duration: 05:00:00.00, start: 179950 。这样的话iina就很难进行进度条的调整。

**Comment by kingslay** [comment]
> 从download下来的m3u8文件上看，是有完整的5个小时的ts切片的
> [index.m3u8](https://github.com/kingslay/KSPlayer/files/12471406/index.txt)

那是不是因为你加了playseek=20230829070000-20230829120000 。所以导致有start: 11724.385067 。你可以把playseek去掉试试看

**Comment by Kimentanm** [comment]
> 

playseek是必须要加的，加了就是一段视频，不加就是live stream

**Comment by Kimentanm** [comment]
> 对于这种视频有两个思路。 一个是iina这样的。totalTime 显示18000s，但是播放的时候，开始时间是用start: 11724.385067 。 另一种是我的方式，totalTime显示 18000 - 11724.385067。播放的开始时间是0。 我是觉得第二种的方式比较好。因为我这种方式就比较好进行seek。 例如下面的一个极端情况，Duration: 05:00:00.00, start: 179950 。这样的话iina就很难进行进度条的调整。

iina的方式可以在5个小时内seek，KSPlayer的方式只能在1个半小时内seek，无法seek到startTime以前的时间点

**Comment by kingslay** [comment]
那iina播放的开始位置应该是11724.385067吧。 那这个应该要看下ffmpeg会返回start  11724.385067。应该返回start 0

**Comment by kingslay** [comment]
这个问题解决了。你再试下。
