### ISSUE TITLE
所有直播源都无法硬解码

### ISSUE THREAD

**Issue by FantasyKingdom** [kingslay/KSPlayer#537]
今天看直播发现设备发烫，然后日志看了下，发现是无法硬解码。
试了下任何直播源，都是无法硬解的。非直播源硬解正常。
希望k神能支持下。

**Comment by kingslay** [comment]
我刚试了下 http://[2409:8087:2001:20:2800:0:df6e:eb13]:80/ott.mobaibox.com/PLTV/3/224/3221228228/index.m3u8 这个直播是可以硬解的。只是这个硬解不是用我自己写的，而是ffmpeg的硬解。你可以看下代码是不是走到这个分支了。有的话，那就是走了ffmpeg的硬解了。
```
if avframe.pointee.format == AV_PIX_FMT_VIDEOTOOLBOX.rawValue {
            frame.corePixelBuffer = unsafeBitCast(avframe.pointee.data.3, to: CVPixelBuffer.self)
        }
```

**Comment by FantasyKingdom** [comment]
确实是走到ffmpeg的硬解码了。
请问下ffmpeg的硬解和自己写的VideoToolboxDecode硬解各自的优缺点是啥。我把默认的硬解码改成ffmpeg的硬解会不会有问题。

**Comment by kingslay** [comment]
自己写的多了异步解码的能力，在一些4k的场景下，比较不会卡顿。但是系统支持的硬解场景会更多。默认解码不行的话，代码是会自动切换到ffmpeg的硬解的。所以理论上你不用改。

**Comment by FantasyKingdom** [comment]
感谢大神的解答！
