### ISSUE TITLE
Some TV runs black when switching between streams

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#539]
Some TV runs black for 1-2 seconds when switching between different streams.
This could depend on the High Dynamic range switch or on frame rate matching.

Do you have any idea?

Also:
there's a way to force a HDR10 or better to play in SDR instead?

**Comment by kingslay** [comment]
destinationDynamicRange 这个属性可以强制把HDR10转为SDR

**Comment by kingslay** [comment]
你可以把isClearVideoWhereReplace这个值设置为false

**Comment by kingslay** [comment]
是的

**Comment by matteogobbi** [comment]
How this should be related? What I means is that is the TV to turn black, not the player. The entire TV, the entire app, not only the player portion. Therefore has nothing to do with this.

**Comment by cdguy** [comment]
> How this should be related? What I means is that is the TV to turn black, not the player. The entire TV, the entire app, not only the player portion. Therefore has nothing to do with this.

@matteogobbi 
Don’t you think it is normal? only selected devices such as newer iphones, ipad pros, etc have dynamic screen refresh rate. As all TVs on the market support 1 refresh rate at the same time; when the source signal (the media played) is different than the output device (hence, the TV) and if the appleTV settings is set to match frame rate and/or dynamic range, the appleTV cuts the signal for a second or two, and changes the video signal to make sure that the source signal matches the TV’s refresh rate…

**Comment by matteogobbi** [comment]
Yes I think is normal for some tv, not all tvs. But I need to understand what’s the exact reason, if it’s the frame rate or the high dynamic range, such that I can act accordingly in certain scenarios to avoid it. Sent from my iPhoneOn Sep 5, 2023, at 12:21 AM, cdguy ***@***.***> wrote:﻿

How this should be related? What I means is that is the TV to turn black, not the player. The entire TV, the entire app, not only the player portion. Therefore has nothing to do with this.

@matteogobbi
Don’t you think it is normal? only selected devices such as newer iphones, ipad pros, etc have dynamic screen refresh rate. As all TVs on the market support 1 refresh rate at the same time; when the source signal (the media played) is different than the output device (hence, the TV) and if the appleTV settings is set to match frame rate and/or dynamic range, the appleTV cuts the signal for a second or two, and changes the video signal to make sure that the source signal matches the TV’s refresh rate…

**Comment by djpirra** [comment]
So this should be kept as-is?? Its the whole screen black and colors seem more vivid. Is this supposed to be controlled by the app or this is a TV feature that we should leave?? Shouldnt this be then detected in the app right from the start to avoid this bad user experience?
