### ISSUE TITLE
 Black video Seek Issue

### ISSUE THREAD

**Issue by wertpoiu** [kingslay/KSPlayer#54]
(tvOS Only) Start Seeking right after video starts lets say after 1 or 2 seconds video will go all black had to restart video. 
and wait few seconds to seek. Please fix @kingslay

**Comment by snappycode1** [comment]
This sounds like its related to the issue I have.

https://github.com/kingslay/KSPlayer/issues/45

**Comment by prikshitgupta** [comment]
Its same

**Comment by snappycode1** [comment]
ok after speaking to @wertpoiu wertpoiu this is definitely the same issue as I was having.

Please @kingslay try and replicate this yourself.  its dead simple

```
    @IBAction func sliderChanged(_ sender: UISlider) {
        print("Slider has been changed")
        playerView.seek(time: Double(sender.value))
    }

```

then seek through a media and you will sometimes see this issue.  It is very intermittent for me.

If you want a video link (although any video will have the issue) then I can send you one via email?

This issue alone is stopping me from shipping your fabulous player with my iptv app.

**Comment by wertpoiu** [comment]
yes its a issue with playerView.seek

**Comment by kingslay** [comment]
you must use  touchUpInside not valueChanged
```
    open func slider(value: Double, event: ControlEvents) {
        if event == .valueChanged {
            toolBar.currentTime = value
        } else if event == .touchUpInside {
            seek(time: value)
        }
    }
```

**Comment by snappycode1** [comment]
I’m not using the built in slider.  I am using my own slider.

**Comment by kingslay** [comment]
yes i know. But when was your method called? is on valueChanged?

**Comment by snappycode1** [comment]
I don't know what you are asking me.  I have a UISlider which has an action of 

```
 @IBAction func sliderChanged(_ sender: UISlider) {
        playerView.seek(time: Double(sender.value))
    }
```

this is how I detect the slider has been dragged (slided? changed?) by the end user

**Comment by wertpoiu** [comment]
Do you actual apple tv to test? @kingslay

**Comment by kingslay** [comment]
no. i only have the simulator

**Comment by snappycode1** [comment]
The same issue arises on a real ipad or iphone.  Please try and replicate it as its a major deal-breaker for using your player.

**Comment by kingslay** [comment]
> The same issue arises on a real ipad or iphone. Please try and replicate it as its a major deal-breaker for using your player.

I feel like this is a problem with your code. You should only seek when the user's finger leaves the progress bar. not just seek while dragging.

**Comment by snappycode1** [comment]
ok, I will change my code to only do seek when the user stops dragging.  see if this helps.

**Comment by wertpoiu** [comment]
this is issue is with KSMEPlayer and seek method while using avplayer as a first player i dont find this issue, If i use playerView.seek method manually then this issue arises as well.

**Comment by wertpoiu** [comment]
Can i email you video?

**Comment by kingslay** [comment]
It can be. Can you reproduce the problem in the demo now?

**Comment by wertpoiu** [comment]
> It can be. Can you reproduce the problem in the demo now?

it happens in real device only

**Comment by kingslay** [comment]
can it happens in real iPhone device？ i only have a real iPhone device

**Comment by wertpoiu** [comment]
> can it happens in real iPhone device？ i only have a real iPhone device

No its not happening in iphone, but if you will implement playerView.seek method manually then it can happen

**Comment by snappycode1** [comment]
@kingslay I've sent you an email with a very basic demo showing the issue.  this demo is for iPhone or iPad.  Please run on a real device because on the simulator it works ok.

**Comment by wertpoiu** [comment]
seek issue is so bad on tvos that if video starts and (i seek with my manual seek method) i start seeking right away, audio dont pause and after that i play other video there is 2,3 sounds coming out of tv of same video.

**Comment by kingslay** [comment]
> @kingslay I've sent you an email with a very basic demo showing the issue. this demo is for iPhone or iPad. Please run on a real device because on the simulator it works ok.

OK . i will try it

**Comment by wertpoiu** [comment]
> you must use touchUpInside not valueChanged
> 
> ```
>     open func slider(value: Double, event: ControlEvents) {
>         if event == .valueChanged {
>             toolBar.currentTime = value
>         } else if event == .touchUpInside {
>             seek(time: value)
>         }
>     }
> ```

i tried this it didnt work

**Comment by kingslay** [comment]
@snappycode1 @wertpoiu i have update the code 5b88b7fbe7c146047ee303dab374e60a11964ff8. please try again.

**Comment by wertpoiu** [comment]
> @snappycode1 @wertpoiu i have update the code [5b88b7f](https://github.com/kingslay/KSPlayer/commit/5b88b7fbe7c146047ee303dab374e60a11964ff8). please try again.

it seems fixed black video issue and 2 3 sounds were playing issue. But if seek forward and backward sometimes video stucks and keep loading and dont play.

**Comment by snappycode1** [comment]
> @snappycode1 @wertpoiu i have update the code [5b88b7f](https://github.com/kingslay/KSPlayer/commit/5b88b7fbe7c146047ee303dab374e60a11964ff8). please try again.

I still have the seek issue.  The frame is frozen and the following is logged

```
KSPlayer: KSPlayerLayer.swift:100 state | playerStateDidChange - bufferFinished
2020-08-04 17:20:33.187684+0100 Test Seek[33429:1526278] [CAMetalLayerDrawable texture] should not be called after already presenting this drawable. Get a nextDrawable instead.
2020-08-04 17:20:33.190915+0100 Test Seek[33429:1526311] Each CAMetalLayerDrawable can only be presented once!
IOSurfaceCompressionFootprint of 0 used 
IOSurfaceCompressionFootprint of 0 used 
IOSurfaceCompressionFootprint of 0 used 
IOSurfaceCompressionFootprint of 0 used 
2020-08-04 17:20:38.193815+0100 Test Seek[33429:1526315] Execution of the command buffer was aborted due to an error during execution. Caused GPU Timeout Error (IOAF code 2)
2020-08-04 17:20:38.194161+0100 Test Seek[33429:1526315] Execution of the command buffer was aborted due to an error during execution. Caused GPU Timeout Error (IOAF code 2)
```

the last line of this log is repeated loads of times a second.

This is using the same demo I sent to you via email.

**Comment by kingslay** [comment]
> > @snappycode1 @wertpoiu i have update the code [5b88b7f](https://github.com/kingslay/KSPlayer/commit/5b88b7fbe7c146047ee303dab374e60a11964ff8). please try again.
> 
> I still have the seek issue. The frame is frozen and the following is logged
> 
> ```
> KSPlayer: KSPlayerLayer.swift:100 state | playerStateDidChange - bufferFinished
> 2020-08-04 17:20:33.187684+0100 Test Seek[33429:1526278] [CAMetalLayerDrawable texture] should not be called after already presenting this drawable. Get a nextDrawable instead.
> 2020-08-04 17:20:33.190915+0100 Test Seek[33429:1526311] Each CAMetalLayerDrawable can only be presented once!
> IOSurfaceCompressionFootprint of 0 used 
> IOSurfaceCompressionFootprint of 0 used 
> IOSurfaceCompressionFootprint of 0 used 
> IOSurfaceCompressionFootprint of 0 used 
> 2020-08-04 17:20:38.193815+0100 Test Seek[33429:1526315] Execution of the command buffer was aborted due to an error during execution. Caused GPU Timeout Error (IOAF code 2)
> 2020-08-04 17:20:38.194161+0100 Test Seek[33429:1526315] Execution of the command buffer was aborted due to an error during execution. Caused GPU Timeout Error (IOAF code 2)
> ```
> 
> the last line of this log is repeated loads of times a second.
> 
> This is using the same demo I sent to you via email.

do you had clean Build Folder?

**Comment by kingslay** [comment]
You can see if you have access to this method.
`clear(drawable: CAMetalDrawable, renderPassDescriptor: MTLRenderPassDescriptor)`
Normal doesn't go into this method.

**Comment by snappycode1** [comment]
I cleaned the build folder, built the project again and same.  As soon as I seek the video it freezes and displays the above logging.  

I checked the source code for KSPlayer to make sure the changes you made are definitely there and they are so I'm using the latest public code.

**Comment by kingslay** [comment]
> I cleaned the build folder, built the project again and same. As soon as I seek the video it freezes and displays the above logging. On a real ipad using the demo I sent.
> 
> I checked the source code for KSPlayer to make sure the changes you made are definitely there and they are so I'm using the latest public code.

You can see if you have access to this method？
clear(drawable: CAMetalDrawable, renderPassDescriptor: MTLRenderPassDescriptor)

**Comment by snappycode1** [comment]
Forgive my ignorance and not knowing, but how do I check for that function? thanks.

**Comment by kingslay** [comment]
i had update the code b7f4a55b2c710822bf98ad42827b34527ff68d46 . please try again

**Comment by snappycode1** [comment]
> i had update the code [b7f4a55](https://github.com/kingslay/KSPlayer/commit/b7f4a55b2c710822bf98ad42827b34527ff68d46) . please try again

Sadly still the same on the real iPad.

**Comment by wertpoiu** [comment]
I am sorry Black video issue is still there and multiple audio's are playing for same video even the video is paused and multiple audios are palying

**Comment by wertpoiu** [comment]
Its happening with manual seek only, and one more issue with internal seek i have to press play pause 2,3 times to play video after seeking.

**Comment by kingslay** [comment]
My side of the viewing is very stuck and cannot be reproduced. So I download 131956.mkv to local and play it. Still can't reproduce. You can replace the url in my demo to play it, and then use my own seek to see if it can reproduce the problem.
```

   if let url = URL(string: "http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8") {
            objects.append(KSPlayerResource(url: url, options: KSOptions(), name: "m3u8视频"))
        }

```

**Comment by kingslay** [comment]
Or you can download that video and play it locally. See if it works.

**Comment by kingslay** [comment]
@snappycode1 What is the system version of your iOS device?

**Comment by snappycode1** [comment]
> @snappycode1 What is the system version of your iOS device?

I have 2 iPads.  one is on iOS 13 and the other on iOS 14 beta 4

Both devices have the same issue.

**Comment by snappycode1** [comment]
> My side of the viewing is very stuck and cannot be reproduced. So I download 131956.mkv to local and play it. Still can't reproduce. You can replace the url in my demo to play it, and then use my own seek to see if it can reproduce the problem.
> 
> ```
> 
>    if let url = URL(string: "http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8") {
>             objects.append(KSPlayerResource(url: url, options: KSOptions(), name: "m3u8视频"))
>         }
> ```

Using your internal seek, the issue is black screen and audio still playing.

**Comment by kingslay** [comment]
you can download 131956.mkv to local and play it. So that you can check if it's a network problem

**Comment by snappycode1** [comment]
> you can download 131956.mkv to local and play it. So that you can check if it's a network problem

I downloaded 131956.mkv and loaded it locally.  The manual seek seems to work ok.

**Comment by snappycode1** [comment]
After more extensive testing I found that playing the file locally is generally working, but sometimes the video will freeze (audio still plays) but it recovers after a few seconds.

**Comment by snappycode1** [comment]
@kingslay any more thoughts on how we can resolve this issue please?

**Comment by kingslay** [comment]
@snappycode1 i update the code e0fc6272df369063587a8a4af3e5b10aa0a87c3d. please try again. thank you

**Comment by snappycode1** [comment]
> @snappycode1 i update the code [e0fc627](https://github.com/kingslay/KSPlayer/commit/e0fc6272df369063587a8a4af3e5b10aa0a87c3d). please try again. thank you

Thanks.  I have tested a load of videos on ipad and apple tv and they are all so far, playing perfectly.  I'll keep testing and report back if I have any issues with seek still.

**Comment by snappycode1** [comment]
It's been a few days since the last code update for this issue and so far I have not had 1 problem.  so for me at least, this issue is resolved.
