### ISSUE TITLE
有没有计划支持libass字幕

### ISSUE THREAD

**Issue by FantasyKingdom** [kingslay/KSPlayer#540]
目前的ass字幕只能按照纯文本显示，效果有点不大好。
不必在乎libass带来的性能影响，现在的设备性能都非常强。
希望k神能支持这个功能。

**Comment by kingslay** [comment]
可以，那你是否可以找个有内嵌ass字幕的视频，上传到github。然后我来调试下。

**Comment by FantasyKingdom** [comment]
> 可以，那你是否可以找个有内嵌ass字幕的视频，上传到github。然后我来调试下。
可以的，下班后我给你发一下。大神可以先调试下外挂类型的ASS字幕。

**Comment by FantasyKingdom** [comment]
@kingslay 这个视频内含两条ass字幕。在片头和片尾时，视频底部和顶部都会显示字幕。
https://web.ugreen.cloud/web/#/share/EC-VMOO554JJ4223Mvx-201468 提取码：45A6

**Comment by kingslay** [comment]
支持了一部份的ass字幕的样式了

**Comment by FantasyKingdom** [comment]
太强了，居然自己写了一套解析ass的方法
