### ISSUE TITLE
Subtitles have been broken in this repo

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#544]
**Describe the bug**
One of the commit after
```
FFmpegKit:
    :commit: 8eae8c2f8854e34e1441c2d33072568d83785f2a
    :git: https://github.com/kingslay/FFmpegKit.git, 
```
or 
After commit https://github.com/kingslay/KSPlayer/commit/e8f616179cb932b3f7155a96c942e61839f69172,

subtitles are broken. See screenshots.
If I go back to that commit, the subtitles aren't broken.

**To Reproduce**
1. Open a movie;
2. Select subtitles.
Actual: At least some subtitles type (those I tested, but maybe all) that use to work before, now are broken.

**Expected behavior**
ALL types of subtitles should still be showing correctly, like before.

**Screenshots**
In the first screenshot observe letters appearing in the middle of the screen.
In the second screenshot observe the subtitle squeezed.

![sub](https://github.com/kingslay/KSPlayer/assets/1998171/02e56c31-3066-416a-8896-732bae7d2813)
![sub2](https://github.com/kingslay/KSPlayer/assets/1998171/737c17fb-44bf-4b75-a85a-349d4220dd00)

**Platform (please complete the following information):**
 - Device: AppleTV
 - OS: tvOS
 - Version: 16 and 17 (and any version in between)

**Comment by kingslay** [comment]
你能提供下这个url吗？我用最新的代码，然后用播放https://github.com/kingslay/KSPlayer/raw/develop/Tests/KSPlayerTests/Resources/dvd_subtitle.mkv是不会有问题的。这个也是图片字幕

**Comment by kingslay** [comment]
你的意思是commit https://github.com/kingslay/KSPlayer/commit/e8f616179cb932b3f7155a96c942e61839f69172, 导致图片字幕出现问题吗？

**Comment by kingslay** [comment]
你这个是文字字幕还是图片字幕呢？我最近是有改了文字字幕（ass格式的）

**Comment by matteogobbi** [comment]
These are text subtitles. If I go back to my commits before I updated your pod, everything is back working well. But after that pod update it stopped working properly. Sent from my iPhoneOn Sep 11, 2023, at 5:20 PM, kingslay ***@***.***> wrote:你的意思是commit e8f6161, 导致图片字幕出现问题吗？

**Comment by matteogobbi** [comment]
Recently they not even longer appear. Or if they do in the previous commits they appear in a bad format like you see in the screenshot. Sent from my iPhoneOn Sep 11, 2023, at 6:58 PM, kingslay ***@***.***> wrote:﻿
O 你这个是文字字幕还是图片字幕呢？我最近是有改了文字字幕（ass格式的）

**Comment by kingslay** [comment]
你用最新的代码试下。我周末的时候有修复了这个问题。如果还是不行的话 你把URL发给我下 我debug下

**Comment by matteogobbi** [comment]
With the most recent code, the subtitles don't appear at all.

To recap:

- If I go back to the version before those pod updates -> everything works well;
- If I go after, subtitles show broken;
- If I go to the latest, subtitles don't work anymore (don't appear).

I can't share URLs unfortunately.

**Comment by kingslay** [comment]
你是否可以只截取一分钟的视频，然后上传到github。

**Comment by kingslay** [comment]
或者你可以把ass字幕从视频剥离出来。然后单独发给我ass字幕文件

**Comment by matteogobbi** [comment]
I confirm that is a problem with your updates. Atm the only thing I could do is to go way back and force push a different commit on my fork (because `:commit` in the podfile doesn't work, it always take the latest).

**Comment by kingslay** [comment]
我有网上找了几个ass字幕来进行测试，是可以显示字幕的。所以你这边需要提供给我有问题的字幕。我才能排查是什么问题导致。

**Comment by matteogobbi** [comment]
Now looks like you fixed one problem, but it came back with another problem.

Observe how tiny and almost not visible are the subtitle now:

![Simulator Screenshot - Apple TV 4K (3rd generation) - 2023-09-12 at 22 52 32](https://github.com/kingslay/KSPlayer/assets/1998171/bbbaada1-6295-41ab-8c49-ecdc8678c1e2)


And how were, when I use the same app code, but I go back to past versions with KSPlayer pod:


![Simulator Screenshot - Apple TV 4K (3rd generation) - 2023-09-12 at 11 58 16](https://github.com/kingslay/KSPlayer/assets/1998171/d45e333f-d62b-4e54-9252-1535fad1d8ca)

**Comment by matteogobbi** [comment]
Noticed that after selecting a subtitle, the subtitleLabel gets the font set to 16 instead fo keeping the font size.
Also the color is totally bad.

**Comment by matteogobbi** [comment]
@kingslay this needs to be reopened. Please see my latest comments. Thx.

**Comment by matteogobbi** [comment]
Thank you. @kingslay  Now the style is back to normal, but not the size. I have a large subtitles set, but instead of showing the old size like the picture in the comment above, it is super small.

![Simulator Screenshot - Apple TV 4K (3rd generation) - 2023-09-17 at 01 20 34](https://github.com/kingslay/KSPlayer/assets/1998171/fffbf0f4-d4d4-4d21-928b-de68a2614316)

**Comment by UnknownCoder807** [comment]
I can confirm that on iOS/iPadOS the subtitles colour and size no longer change.  Used to work fine.  Works on tvOS.

**Comment by kingslay** [comment]
因为你这个是ass字幕。ass字幕指定了字体大小和颜色。所以就无法修改字体大小和颜色

**Comment by matteogobbi** [comment]
Sorry but if until few days ago it used to work well and the dimension was right, how can you say this now?
I posted a picture of the same movie before and after and you can see the dimension is different although the code is the same. 

@UnknownCoder807 for me doesn't work not even on tvOS. 

I'm using an older version of this library for now because this problem.

**Comment by UnknownCoder807** [comment]
> Because yours is an ass subtitle. ass subtitles specify the font size and color. So you can’t change the font size and color

I just tried an older testflight build of my app and subtitle colour and size for live tv could be changed.

I then opened the latest testflight version (with all ksplayer commits so far) and the exact same stream as before and the subtitle colour and size cannot be changed.

This is the same issue as the OP is having I am sure.

**Comment by kingslay** [comment]
是的，因为之前不支持解析ass的样式，最近的代码才支持的。所以才有这个问题。你可以直接从NSAttributedString取出string，而不用NSAttributedString。这样就可以自定义样式呢

**Comment by UnknownCoder807** [comment]
> > Because yours is an ass subtitle. ass subtitles specify the font size and color. So you can’t change the font size and color
> 
> I just tried an older testflight build of my app and subtitle colour and size for live tv could be changed.
> 
> I then opened the latest testflight version (with all ksplayer commits so far) and the exact same stream as before and the subtitle colour and size cannot be changed.
> 
> This is the same issue as the OP is having I am sure.

edit to add :

It's movies/tv series as well that won't allow colour change.  and also, I was mistaken, it is broken on tvOS too.

I am not sure what you've done @kingslay but customised subtitles no longer work.

**Comment by kingslay** [comment]
因为NSAttributedString带有字体大小和颜色。你们可以不用NSAttributedString。用String就可以了

**Comment by UnknownCoder807** [comment]
> 因为NSAttributedString带有字体大小和颜色。你们可以不用NSAttributedString。用String就可以了


I don't even know what this means.

I will roll back to an earlier commit and just use ksplayer only for then.  But whatever you have changed has broken a major feature of ksplayer and sadly it seems you can't see this.

**Comment by UnknownCoder807** [comment]
even forcing the colour to .red it is still white

<img width="1121" alt="Screenshot 2023-09-17 at 11 15 41" src="https://github.com/kingslay/KSPlayer/assets/56231066/8e8e082c-7348-452a-86c1-25ba17aa5772">

![Simulator Screenshot - Apple TV 4K (3rd generation) - 2023-09-17 at 11 14 59](https://github.com/kingslay/KSPlayer/assets/56231066/17375a72-f8c7-4984-af54-6c3652ba7b73)

**Comment by kingslay** [comment]
把Text(AttributedString(text)) 改成Text(AttributedString(text.stinrg)) 字体大小和颜色就可以生效了

**Comment by kingslay** [comment]
然后也把.if(self.textPosition == nil) {  去掉就可以

**Comment by kingslay** [comment]
把代码改成
```
   Text(AttributedString(text.string))
                    .font(Font(SubtitleModel.textFont))
                    .shadow(color: .black.opacity(0.9), radius: 1, x: 1, y: 1)
                    .foregroundColor(SubtitleModel.textColor)
                    .italic(SubtitleModel.textItalic)
                    .background(SubtitleModel.textBackgroundColor)
                    .multilineTextAlignment(.center)
                    .alignmentGuide(textPosition.horizontalAlign) {
                        $0[.leading]
                    }
                    .padding(textPosition.edgeInsets)
```

**Comment by UnknownCoder807** [comment]
Thanks, this has fixed it!

![Simulator Screenshot - Apple TV 4K (3rd generation) - 2023-09-17 at 11 22 07](https://github.com/kingslay/KSPlayer/assets/56231066/b5745a85-9af3-4678-97de-30c0695e0c17)

**Comment by matteogobbi** [comment]
so in a non swift ui environment with custom view, what I do is only selecting the subtitle. Do you have an example of how to change the code to make it work?
Currently I can only change the properties of the subtitle label, such as the size, but it's ignored.

**Comment by matteogobbi** [comment]
@kingslay how can I reach the same result using `playerView.srtControl.selectedSubtitleInfo` in my custom player wrapper / view?

**Comment by matteogobbi** [comment]
@kingslay would you help me understanding this?

**Comment by matteogobbi** [comment]
I think you referenced the wrong issue?
