### ISSUE TITLE
This stream won't play, but works in VLC

### ISSUE THREAD

**Issue by nightfall708** [kingslay/KSPlayer#545]
Hi,

Apparently this stream `http://soloradiofm.redirectme.net:4700/` won't play in the demo ("Failed to resolve hostname") but works in VLC. (MPV crashes 🤷‍♂️)

**Comment by kingslay** [comment]
这个链接是不是要用vpn才能打开呢？我刚用vlc也是无法打开。

**Comment by nightfall708** [comment]
My bad. It's not working for me either..
