### ISSUE TITLE
Observe the `(Embed)` string attached straight away at the end of the subtitle's name.

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#546]
**Previously:**

Subtitle name -> _"English Forced"_

**Now:**

Subtitle name -> _"English Forced(Embed)"_

Observe the `(Embed)` attached straight away at the end.

I see it coming from here:

```
        if mediaType == .subtitle {
            name += "(Embed)"
        }
```

**Comment by matteogobbi** [comment]
Proposed https://github.com/kingslay/KSPlayer/pull/547

**Comment by kingslay** [comment]
这个是专门改的，为的是在选择字幕的时候，可以一眼就看出那些是视频的内嵌字幕

**Comment by matteogobbi** [comment]
This is something you should manage elsewhere in your UI. Given that these subtitles name are also provided to custom views, in this way you are impacting UIs that don’t need this and have different mechanisms to handle the thing. Moreover the “(embed)” is attached to the name of the subtitles without a space. Sent from my iPhoneOn Sep 13, 2023, at 6:32 AM, kingslay ***@***.***> wrote:﻿
这个是专门改的，为的是在选择字幕的时候，可以一眼就看出那些是视频的内嵌字幕

**Comment by kingslay** [comment]
你是在什么场景下用这个name的

**Comment by matteogobbi** [comment]
This is first of all a principle: `FFmpegAssetTrack.swift` shouldn't care about the UI. 
It should provide the name of the track (as it is) and eventually, in a separate parameter, provide the information if it's an internal (embedded) subtitle (ie. `track.isEmbedded`).
On the player side, the developer can choose to show this info as needed. For example:

**Embedded subtitles**

sub1
sub2

**External subtitles**

sub3
sub4
