### ISSUE TITLE
tvos VideoSettingView 显示不正常

### ISSUE THREAD

**Issue by wangliangliang2** [kingslay/KSPlayer#549]
使用demo也就是TracyPlayer这个项目。在tvOS16， KSVideoPlayerVIew 中的 VideoSettingView 
使用了 Form {
}
会导致选项不能选择【选项内容弹不出】。
该问题develop和main 都有。
[使用的视频](http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4)
【模拟器 tvOS 版本16.4】
建议：
[这是改完后的文件](http://qupfile.cloudvdn.com/KSVideoPlayerView.swift)
主要内容是：
```swift
struct PlatformView<Content: View>: View {
    let content: () -> Content

    var body: some View {
        #if os(tvOS)
        ScrollView {
            content()
        }
        #else
        Form {
            content()
        }
        #endif
        
    }

    init(@ViewBuilder content: @escaping () -> Content) {
        self.content = content
    }
}
PlatformView{
Group{
原内容
}
            #if os(tvOS)
            .padding()
            .pickerStyle(.navigationLink)
            #endif
}

@available(iOS 15, tvOS 16, macOS 12, *) <- 此处需要 tvOS 16
struct VideoSettingView: View
```
@kingslay

**Comment by kingslay** [comment]
好的，谢谢。我改下

**Comment by wangliangliang2** [comment]
另外
ffmpegkit 的这个warning也顺带给解决下怎么样😂 prohibited flag(s): -D_THREAD_SAFE

**Comment by wangliangliang2** [comment]
<img width="746" alt="image" src="https://github.com/kingslay/KSPlayer/assets/20638550/c3c1e6e0-512d-491c-ae30-93eefb7f68b4">
感觉是编译时加入的

**Comment by kingslay** [comment]
但是我搜索了ffmpeg的代码也没有找到D_THREAD_SAFE

**Comment by kingslay** [comment]
查了下是sdl2 引入的。把sdl2 注释掉就不会了。但是ffplay需要用到sdl。

**Comment by kingslay** [comment]
我升级到最新版本的sdl2就不会有这个警告了。你可以用brew升级下。

**Comment by wangliangliang2** [comment]
好的，谢啦。
