### ISSUE TITLE
Application hang when changing url too quickly

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#552]
**Describe the bug**
In my app I allow the user to swipe left and right to change live tv channels.  If they swipe too quickly, ksplayer is locking up the UI.  The phone appears to be hung,

**Expected behavior**
For ksplayer not to hang.

**Platform (please complete the following information):**
 - Device: [e.g. iPhone6]. iPhone All Models
 - OS: [e.g. iOS8.1]. iOS 16 and 17

**Additional context**
The only logs I get are :

`AURemoteIO.cpp:1,747 AURemoteIO::Stop: error 268,451,843 calling TerminateOwnIOThread (port 127,151)`

I am not sure how you can replicate this other than have a test app that allows you to swipe and change the active URL instantly.

**Comment by kingslay** [comment]
这个问题我应该解决了。你可以更新下最新的代码，试下

**Comment by UnknownCoder807** [comment]
looks like this is still happening frequently.

```
warning KSPlayer: KSMEPlayer.swift:355 pause() | pause <KSPlayer.KSMEPlayer: 0x600003792a00>
AURemoteIO.cpp:1,747 AURemoteIO::Stop: error 268,451,843 calling TerminateOwnIOThread (port 173,347)
```

**Comment by kingslay** [comment]
#555
