### ISSUE TITLE
macOS Somona issue

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#554]
I have upgraded to the macOS Somona release candidate and ksplayer is not working at all.

No matter what file I tried to play, I see the first video frame and then my app hangs.

all I have in the logs is

```
cannot open file at line 46973 of [554764a6e7]
os_unix.c:46973: (2) open(/private/var/db/DetachedSignatures) - No such file or directory
AQMEIO_HAL.cpp:777 kAudioDevicePropertyMute returned err 2,003,332,927
```

Does this mean anything to fix?

**Comment by kingslay** [comment]
我也升级到Somona了。但是我的demo在mac上是可以进行播放的。你的操作路径是怎么样的呢？

**Comment by UnknownCoder807** [comment]
> 我也升级到Somona了。但是我的demo在mac上是可以进行播放的。你的操作路径是怎么样的呢？

What is an operation path?

**Comment by kingslay** [comment]
你是用我的demo吗？要怎么样才会出现你说的这个错误呢？

**Comment by UnknownCoder807** [comment]
It's not just sonama, its any macos version with Apple Silicon.  I tried a popular iptv app and it also has the same issue as my app.

When trying to play any media, only the first video frame is shown, the cpu then goes to 100% and the UI locks.  can't do anything other than a force close.

Only on Apple Silicon.  It used to work until recently.

**Comment by kingslay** [comment]
你可以帮忙看下是最近那个提交导致出问题吗？因为我的macbook是intel。所以无法测试。

**Comment by UnknownCoder807** [comment]
This commit is the one that breaks it

https://github.com/kingslay/KSPlayer/commit/32ed56dbca95a8f3a497169ca96f598755cb9a40

**Comment by UnknownCoder807** [comment]
thanks, working now.
