### ISSUE TITLE
Constat crash

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#559]
I am seeing the following crash in my logs quite often.  It is happening to my users so I do not have a URL.

<img width="1153" alt="Screenshot 2023-09-23 at 22 23 27" src="https://github.com/kingslay/KSPlayer/assets/56231066/cf9d2c01-d9c9-4c36-aea3-0c6c9f09fd86">

<img width="1153" alt="Screenshot 2023-09-23 at 22 23 12" src="https://github.com/kingslay/KSPlayer/assets/56231066/39b695d8-1eb0-4d2a-ac03-cc7abc2b5b66">

**Comment by matteogobbi** [comment]
Same.

**Comment by kingslay** [comment]
这个你们可以找到复现的路径吗？

**Comment by UnknownCoder807** [comment]
i can't find a way.  It's a report via Crashlytics.  I don't know any anything other than what those 2 screenshots show.
