### ISSUE TITLE
4K Video screen is slow motion

### ISSUE THREAD

**Issue by aningxu** [kingslay/KSPlayer#56]
Play 4K Video the sound is normal,  screen is slow motion.

**Comment by kingslay** [comment]
Are you using tvos or ios?

**Comment by aningxu** [comment]
tvos

**Comment by wertpoiu** [comment]
its plays slow in ios and tvos both

**Comment by wertpoiu** [comment]
@kingslay this is big issue

**Comment by kingslay** [comment]
目前4k视频是解码是比较耗时的，所以会导致视频卡断。这个需要机器的性能比较好才不会卡断。目前我还没找到优化解码性能的手段

**Comment by wertpoiu** [comment]
> 目前4k视频是解码是比较耗时的，所以会导致视频卡断。这个需要机器的性能比较好才不会卡断。目前我还没找到优化解码性能的手段

please reply in english

**Comment by aningxu** [comment]
> > 目前4k视频是解码是比较耗时的，所以会导致视频卡断。这个需要机器的性能比较好才不会卡断。目前我还没找到优化解码性能的手段
> 
> please reply in english

google translation, haha.

**Comment by wertpoiu** [comment]
> > > 目前4k视频是解码是比较耗时的，所以会导致视频卡断。这个需要机器的性能比较好才不会卡断。目前我还没找到优化解码性能的手段
> > 
> > 
> > please reply in english
> 
> google translate, haha.

i did that :)

**Comment by kingslay** [comment]
@aningxu @wertpoiu  I fixed it
