### ISSUE TITLE
Question: Updating film while it's playing

### ISSUE THREAD

**Issue by Gamec** [kingslay/KSPlayer#562]
Hi, I have a server that's appending live video to fragmented mp4 file. I can play it fine with KSPlayer but it will only show me duration of this file from the moment I started to play it. New frames are added to that file every second. Is it possible to watch it and refresh KSPlayer, so I can rewind to new frames?

My end goal would be to have iOS app that downloads this file continuously and plays it like a live stream (but local to device).

Is it possible to achieve using KSPlayer?

I implemented this feature using AVMutableComposition from AVKit, but it requires me to replace playerItem every time composition updates. It works but it's not perfect.

Thank you for your work!

**Comment by kingslay** [comment]
这个要看下ffmpeg是否支持这种方式，因为我的这个项目是基于ffmpeg来的。

**Comment by kingslay** [comment]
你可以试着把这个播放文件封装成直播。这样是否就可以了。

**Comment by Gamec** [comment]
How can I encapsulate file into live broadcast? I also need to be able to rewind this file.

**Comment by kingslay** [comment]
如果你需要倒带播放的话，那就只能用avplayer了。目前KSMEPlayer 不支持倒带播放

**Comment by Gamec** [comment]
I don't mean rewind playback, as in playing backwards. I just need to be able to seek to previous frames of this file.

Maybe better explanation would be this. I need it look like live hls player (so I can seek to previous frames, new frames appear automatically at end of video), but file (or files) are local to device.

Do you think it's possible to achieve using KSPlayer?

**Comment by kingslay** [comment]
那你可以试着把视频的长度设置为一个比较大的值。例如是24小时。看下行不行

**Comment by Gamec** [comment]
Ok, thanks. I'll check it.
