### ISSUE TITLE
Crashes in iOS 17.0

### ISSUE THREAD

**Issue by nightfall708** [kingslay/KSPlayer#564]
Hi,

So apparently I'm having these crashes on iOS 17.0. No clue yet on how to reproduce. It happens to users only once. So it's pretty random. 

Crashed: KSPlayer_soun
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000845976f00
0
libobjc.A.dylib
objc_retain_x8 + 16
1
AudioToolboxCore
auoop::RenderPipeUser::~RenderPipeUser() + 112
2
AudioToolboxCore
-[AUAudioUnit_XPC internalDeallocateRenderResources] + 92
3
AVFAudio
AUInterfaceBaseV3::Uninitialize() + 60
4
AVFAudio
AVAudioEngineGraph::PerformCommand(AUGraphNodeBaseV3&, AVAudioEngineGraph::ENodeCommand, void*, unsigned int) const + 772
5
AVFAudio
AVAudioEngineGraph::_Uninitialize(NSError**) + 132
6
AVFAudio
AVAudioEngineImpl::Stop(NSError**) + 396
7
AVFAudio
-[AVAudioEngine stop] + 48
8
TextToSpeech
TTSSpeechLanguageCanonicalFormToGeneralLanguage + 9136
9
libdispatch.dylib
_dispatch_call_block_and_release + 32
10
libdispatch.dylib
_dispatch_client_callout + 20
11
libdispatch.dylib
_dispatch_lane_serial_drain + 748
12
libdispatch.dylib
_dispatch_lane_invoke + 432
13
libdispatch.dylib
_dispatch_root_queue_drain_deferred_wlh + 288
14
libdispatch.dylib
_dispatch_workloop_worker_thread + 404
15
libsystem_pthread.dylib
_pthread_wqthread + 288
16
libsystem_pthread.dylib
start_wqthread + 8

**Comment by kingslay** [comment]
这是用最新的代码吗？之前是会有一个audio的并发crash的问题，在b07d96d2f9aa07e54303d072c3f861677c79f332 这个commit解决了

**Comment by nightfall708** [comment]
I am using an older version. Maybe that's the issue. I'll check it out. Thank you.
