### ISSUE TITLE
AirPlay not working

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#565]
**Describe the bug**
Using airplay to listen to audio on a different device produces no audio.

**To Reproduce**
Simple enable airplay.

**Expected behavior**
Sound to play.

**Platform (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone/iPad
 - OS: [e.g. iOS8.1] 17

**Additional context**
This used to work.  I don’t know when it was broken as it has only been reported to me on the 20th September.

**Comment by UnknownCoder807** [comment]
any ideas on this @kingslay  ?

**Comment by kingslay** [comment]
这个还没找到原因，我的手机在最新的系统，目前无法debug调试，我正在等我十月底的新手机。估计要等到十月底才可以解决。

**Comment by UnknownCoder807** [comment]
Fair enough, thanks.

**Comment by kingslay** [comment]
是不是tvos 17 才会有这个问题呢？  #588

**Comment by UnknownCoder807** [comment]
> 是不是tvos 17 才会有这个问题呢？ #588

yes.

**Comment by kingslay** [comment]
这个是tvos17的bug。解决办法是 需要吧Apple TV用wifi来链接，不要用以太网。
