### ISSUE TITLE
Forced subtitles stop working when switching stream

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#566]
**Describe the bug**
Subtitles stop working after changing stream on the same player.

**To Reproduce**
1. Open a stream;
2. Without creating a new playerView/player, change the stream (`playerView.set(url: value, options: options)`)

** Actual** 
Forced subtitles are theoretically enforced, but they don't show up.

**Actual2**
Forced subtitles will never show even disabling and reenabling subtitles.
Only creating a new player would solve the problem.

**Expected behavior**
The player, when receive a new stream request, should make sure to set the forced subtitles as it does when opening a stream on a player the first time.

**Platform (please complete the following information):**
- iOS and Android

**Other**
Other players like VLC work with the same content in the same app.

**Comment by kingslay** [comment]
你可以提供这个demo吗？或是直接把我项目里面的demo-tvOS 改下。我现在的demo是一个url就会创建一个PlayerView。需要改成你现在的场景。我比较少维护UIKit，大部份都是维护SwiftUI。所以需要你来提供下UIKit的demo。然后我基于你的demo来修改bug。

**Comment by kingslay** [comment]
你用的是VideoPlayerView 还是PlayerView呢？只有VideoPlayerView才会自动帮忙选择字幕。
