### ISSUE TITLE
HDR/SDR and Frame rate matching being forced on all the time

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#567]
I have just updated my test app to the latest ksplayer code and migrated to the new

`override open func preferredDisplayCriteria(track: some MediaPlayerTrack) -> AVDisplayCriteria?
`

However, regardless if this override function is included or not, HDR/SDR & FRM is always forced.   Even setting this to return nil (like the previous version of this function) has no effect.

The previous version of preferredDisplayCriteria worked perfectly, so why change?

**Comment by kingslay** [comment]
你是tvOS 17吗？这个是用到了tvos17的一个新的功能。目前可以在播放的时候自动进行适配
    #if os(tvOS) || os(xrOS)
    private func setDisplayCriteria(formatDescription: CMFormatDescription) {
        guard let displayManager = UIApplication.shared.windows.first?.avDisplayManager,
              displayManager.isDisplayCriteriaMatchingEnabled,
              !displayManager.isDisplayModeSwitchInProgress
        else {
            return
        }
        if #available(tvOS 17.0, *) {
            let criteria = AVDisplayCriteria(refreshRate: fps, formatDescription: formatDescription)
            displayManager.preferredDisplayCriteria = criteria
        }
    }
    #endif

你是在什么场景下想要把HDR/SDR and Frame rate matching关了呢？我是读取系统的配置来决定要不要开启这个功能的

**Comment by kingslay** [comment]
你是想把这个功能做成是可配置的吗？例如付费用户才能开启吗？如果是的话，那我就加一个开关。还是有开启了这个自动适配会有什么问题呢？

**Comment by UnknownCoder807** [comment]
I have an option in my app to override the system settings.

So if the ATV is set to On for Content and Frame Rate Matching, my app can override this setting and turn it off in certain scenario's.

One such scenario is the small live tv preview window i have which shows a preview of the focused channel.  If the channel is an SDR one, then I get a black screen whilst the TV switches modes.  This black screen is normal, but not when you want to quickly scroll through live tv channels and see a preview of each one.  In the previous version of the preferredDisplayCriteria function I could turn off the dynamic range and frame rate matching temporarily.

**Comment by UnknownCoder807** [comment]
> 你是想把这个功能做成是可配置的吗？例如付费用户才能开启吗？如果是的话，那我就加一个开关。还是有开启了这个自动适配会有什么问题呢？

if you could make it like before, where I can turn it off when I want it would be perfect.  A lot of IPTV apps on apple tv have a preview window and this current version will affect them all.

**Comment by UnknownCoder807** [comment]
Thanks @kingslay this switch works nicely.

I have a question.  I don't know if it's down to ksplayer or my code.

If the ATV is set to HDR and I play an SDR channel, ksplayer rightly switches to SDR mode.  In my app when watching a channel, you can swipe right to play the next channel.  If this next channel is also SDR, shouldn't ksplayer not switch anything?  At the moment, when I swipe right, the new channel triggers a new switch of hdr/sdr.

**Comment by kingslay** [comment]
我在播放之后做了这个处理
UIApplication.shared.windows.first?.avDisplayManager.preferredDisplayCriteria = nil

你先试着把这个代码注释掉。看下是不是因为这行代码造成的。

**Comment by UnknownCoder807** [comment]
> @UnknownCoder807 我在播放结束之后做了这个处理 UIApplication.shared.windows.first?.avDisplayManager.preferredDisplayCriteria = nil
> 
> 你先试着把这个代码注释掉。看下是不是因为这行代码造成的。

I did this and although it stops the switching when changing channels (url) it doesn't switch back when I exit playback completely.   which is expected since I commented it out of the resetPlayer() function.

<img width="960" alt="Screenshot 2023-10-03 at 05 03 48" src="https://github.com/kingslay/KSPlayer/assets/56231066/47652304-fa99-4b24-a277-15b471cc4806">

**Comment by kingslay** [comment]
那是不是我把这两行代码去掉就可以符合你的需求呢

**Comment by UnknownCoder807** [comment]
if you remove them, then even after just watching 1 channel, ksplayer will not switch back to HDR or SDR when exiting playback which is not the correct thing.

The users ATV is in HDR Mode.  They select an SDR channel to watch.  KSPlayer switches the display to SDR mode.  Whilst watching that channel, they decide to change channels via an onscreen UI.  KSPlayer now stops the playback and plays the newly selected channel.  At the moment, KSPlayer is switching back to HDR then back to SDR between the current channel ending and the new one playing. 

What should happen is, when the current channel ends playback and the new channel starts to play, KSPlayer should check if the new channel is also SDR and if it is, stay in SDR mode.  don't switch.  When the user exits playback completely, KSPlayer should then switch back to HDR.

So if the user watches 4 different channels in succession, it stays in SDR (or HDR) mode for the duration of the session.

Hope that makes sense.

**Comment by UnknownCoder807** [comment]
I play media using

`KSVideoPlayer(coordinator: playerCoordinator, url: url, options: options)`

and I change the live tv channel currently playing by changing thr value of url

How can I do what you suggest with ksplaylayer?

**Comment by kingslay** [comment]
你要一直持有playerCoordinator。然后让playerCoordinator不会运行到resetPlayer 函数。resetPlayer这个函数是在swiftui的view消失的时候才会调用
   public static func dismantleUIView(_: UIViewType, coordinator: Coordinator) {
        coordinator.resetPlayer()
    }
你可以用最新的代码试下，我更新代码了
