### ISSUE TITLE
iOS Subtitle Issue

### ISSUE THREAD

**Issue by wertpoiu** [kingslay/KSPlayer#57]
iOS subtitle selection tableview rows are not selectable. Its hit and miss.

**Comment by wertpoiu** [comment]
please look into it @kingslay

**Comment by wertpoiu** [comment]
?

**Comment by ridhabnj** [comment]
Up

**Comment by kingslay** [comment]
Selecting subtitles will automatically hide the tableview.
` 
view.selectedInfo.observer = { [weak self] _, info in
            guard let self = self, let selectWithFilePath = self.selectWithFilePath else { return }
            DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 0.2) { [weak self] in
                guard let self = self else { return }
                self.view.isHidden = true
            }
            info.makeSubtitle(completion: selectWithFilePath)
        }
`

you can check the code 

` 
private func setupSrtControl() {
        subtitleLabel.numberOfLines = 0
        subtitleLabel.textAlignment = .center
        subtitleLabel.textColor = .white
        subtitleLabel.font = .systemFont(ofSize: 16)
        subtitleBackView.cornerRadius = 2
        subtitleBackView.backgroundColor = UIColor.black.withAlphaComponent(0.4)
        subtitleBackView.addSubview(subtitleLabel)
        subtitleBackView.isHidden = true
        addSubview(subtitleBackView)
        addSubview(srtControl.view)
        srtControl.view.isHidden = true
        srtControl.selectWithFilePath = { [weak self] result in
            guard let self = self else { return }
            self.resource?.subtitle = try? result.get()
        }
    }
`
