### ISSUE TITLE
Search in OpenSubtitle

### ISSUE THREAD

**Issue by Alanko5** [kingslay/KSPlayer#574]
I would like to be able to search using the name of the movie or the number of the episode and the series of TV show. 
Or using IMDB id.

https://github.com/kingslay/KSPlayer/commit/4b41ee45a7d629b0d269d81e0e6a177ae2310bf6

Very nice work!
Thx

**Comment by cdguy** [comment]
the "best" solution would be something like this:

 when you search for a content name (Search Querry ), all results from opensubtitles would be displayed:

iOS example: you hit "Get More" and after you type the name of the content (https://apps.apple.com/us/app/iplaytv-aio/id1517121326)

![E77F713B-E579-4264-A308-638E84566157](https://github.com/kingslay/KSPlayer/assets/123307657/025cb20e-45a3-4b51-8cd2-d85c85469235)
 

![44076FE9-5C2A-4708-8CEB-68E683E617B7](https://github.com/kingslay/KSPlayer/assets/123307657/3cbb7026-ef29-42bc-bb12-3fe72b627520)

TVOS: (iplayTV - https://apps.apple.com/us/app/iplaytv-iptv-m3u-player/id1072226801)

![5AE8C1DA-60B1-413A-AFCC-B3D3E3B3BB93](https://github.com/kingslay/KSPlayer/assets/123307657/bc776656-8395-48be-8b12-930d964127c6)

![49CDE917-EF4F-436D-917D-3B1D3F0CE282](https://github.com/kingslay/KSPlayer/assets/123307657/4de0c228-a207-4510-93ba-fb124b30ab7d)

![724F02F1-A2BD-462B-879B-E024A5DE4E0C](https://github.com/kingslay/KSPlayer/assets/123307657/b2aadea8-3114-4bc9-b078-5f160b05ce91)

**Comment by cdguy** [comment]
here is a video screen recording.

You can see at the end that I can search for the content I want; which is a great feature because some video files are named wrongly

https://github.com/kingslay/KSPlayer/assets/123307657/ece1812c-60a8-4e8f-9a43-53f3e95aad7b

**Comment by Alanko5** [comment]
just add calls to this api to do it
