### ISSUE TITLE
`private func registerRemoteControllEvent()` shouldn't be mandatory. This player can be encapsulated as custom player.

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#578]
From a design perspective, you shouldn't `registerRemoteControllEvent` in the `KSMEPlayerLayer`.
Your player can be used as a custom player like `AVPlayer`. Only the controller should `registerRemoteControllEvent`, like`AVPlayerController` does. 

In this way, the player is breaking the custom logic of those that have a custom player controller.

Therefore this part should be moved elsewhere.

PS. I understand there's an option for it, but from a design perspective should be in the controller, not in the layer.
PPS. There's a type `controll` -> `control`

**Comment by kingslay** [comment]
07ed04974537917137fd07a5f570a8ef510872e8
