### ISSUE TITLE
开启屏幕锁定后观看横屏视频，点击倍速画面会转回竖屏

### ISSUE THREAD

**Issue by sunzongzheng** [kingslay/KSPlayer#580]
Demo项目中可以复现，如果不锁定屏幕&横屏观看就没有问题

https://github.com/kingslay/KSPlayer/assets/12635613/cebef77e-0c42-406b-97d8-b0d59d0250d0

**Comment by kingslay** [comment]
这个应该是用了UIMenu 才会有这个问题。你可以换成不用UIMenu，

**Comment by sunzongzheng** [comment]
> 这个应该是用了UIMenu 才会有这个问题。你可以换成不用UIMenu，

试了下用`UIAlertController`也会，能提供一个示例吗


https://github.com/kingslay/KSPlayer/assets/12635613/9c9b24f5-58b6-4264-8185-2c8a70768c10

**Comment by charsdavy** [comment]
可以关闭自动旋转的支持吗？

**Comment by kingslay** [comment]
你手机的锁定屏幕应该是打开的吧。所以这个走的应该是强制旋转，而不是自动旋转。

**Comment by charsdavy** [comment]
> 你手机的锁定屏幕应该是打开的吧。所以这个走的应该是强制旋转，而不是自动旋转。

可以在我手机屏幕锁定开关未开启的状态下，关闭KSPlayer的自动旋转吗？即我手动旋转手机，KSPlayer不自动响应旋转。

**Comment by kingslay** [comment]
这个应该是可以的。

**Comment by charsdavy** [comment]
看你的文档说了支持自动旋转，但是代码中没看到哪个配置可以控制这个能力。

**Comment by Kimentanm** [comment]
> 看你的文档说了支持自动旋转，但是代码中没看到哪个配置可以控制这个能力。

KSOptions.supportedInterfaceOrientations
用这个可以控制

**Comment by charsdavy** [comment]
那需要实时动态调整吗？不然如果只给了portrait，那不是不能手动旋转了？
