### ISSUE TITLE
KSPlayerLayer set display criteria although `displayCriteriaFormatDescriptionEnabled` is `false`

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#581]
The following method set the display criteria despite `displayCriteriaFormatDescriptionEnabled` is set to `false`.

```
    private func setDisplayCriteria(track: some MediaPlayerTrack) {
        guard let displayManager = UIApplication.shared.windows.first?.avDisplayManager,
              displayManager.isDisplayCriteriaMatchingEnabled,
              !displayManager.isDisplayModeSwitchInProgress
        else {
            return
        }
        if let criteria = options.preferredDisplayCriteria(track: track) {
            displayManager.preferredDisplayCriteria = criteria
            print("[AVDisplayCriteria] DISPLAY CRITERIA SET ON KSPlayerLayer")
        }
    }
```

**Comment by kingslay** [comment]
AVDisplayCriteria 有两个初始化方法，一个是tvOS17 才有的 AVDisplayCriteria(refreshRate: refreshRate, formatDescription: formatDescription)。 displayCriteriaFormatDescriptionEnabled这个开关就是用来控制这个初始化方法的。 另一个是AVDisplayCriteria(refreshRate: refreshRate, videoDynamicRange: videoDynamicRange)。 你应该是有重载了preferredDisplayCriteria，然后走了AVDisplayCriteria(refreshRate: refreshRate, videoDynamicRange: videoDynamicRange) 这个方法吧。

**Comment by matteogobbi** [comment]
I understand that, and I already have the logic to do so. The problem is infrastructural. I don't want the player to automatically set the display criteria. There should be an option to decide this.

Also, when setting the criteria on live streams with KSMEPlayer, the stream goes bad.

**Comment by matteogobbi** [comment]
So imagine I have my custom player, which use your engine under the hood.

I want to be able to enable and disable content matching whenever I want, with my logic.
Therefore I need:

1. Get informed when MetalView generated the format description, which is the only one working well enough for lives;
2. Have access to MetalView generated format description;
3. Be able to disable the KS inner logic to set display criteria.

One big step for this project is to well separate the concept of "Player" and "Controller". I use the Player, but I have my Controller. So things can't be mixed up.

To help, take in consideration "AVPlayer" and "AVPlayerController".

**Comment by UnknownCoder807** [comment]
The commit you posted for this has broken 4K 50fps playback.  it's losing loads of frames and is now jerky/stuttering playback - totally unwatchable.

**Comment by kingslay** [comment]
> The commit you posted for this has broken 4K 50fps playback. it's losing loads of frames and is now jerky/stuttering playback - totally unwatchable.

displayCriteriaFormatDescriptionEnabled 这个值是为false吗？

**Comment by UnknownCoder807** [comment]
> > The commit you posted for this has broken 4K 50fps playback. it's losing loads of frames and is now jerky/stuttering playback - totally unwatchable.
> 
> displayCriteriaFormatDescriptionEnabled 这个值是为false吗？

It was set to true.  tried with false and now it's ok.

**Comment by matteogobbi** [comment]
@kingslay you missed this 

        `UIApplication.shared.windows.first?.avDisplayManager.preferredDisplayCriteria = nil`

It should also be covered by the flag.

<img width="951" alt="Screenshot 2023-10-15 at 01 38 55" src="https://github.com/kingslay/KSPlayer/assets/1998171/f5d45b22-d96f-4c16-a46e-feb2229b9b89">
