### ISSUE TITLE
    public var formatDescription: CMFormatDescription? not always set when changing stream

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#582]
```
    private var formatDescription: CMFormatDescription? {
        didSet {
             // .....
        }
   }
```

this method is called only when the player is started. When changing stream in the same player, this is never updated again.

**Comment by matteogobbi** [comment]
Now I can reproduce it again.
It seems random. Sometimes it works sometimes it doesn't.
Would you help to understand this logic?

**Comment by kingslay** [comment]
这个方法是会判断下，视频的宽高和mediaSubType 之类的信息，如果一样的话，就不用更新。 
通过CMVideoFormatDescriptionMatchesImageBuffer(formatDescription!, imageBuffer: pixelBuffer) 这个方法来判断的。
