### ISSUE TITLE
User interacions not responding (tvOS)

### ISSUE THREAD

**Issue by Alanko5** [kingslay/KSPlayer#584]
**Describe the bug**
If playing 4k HDR video with (5.1, 7.1, matt, trheHD) multichanel audio
Then player not responding to swipe or click on remote controller (tvOS)

**To Reproduce**
1. Play video 4k
2. select audio track with multichannel audio
3. User interface not responding

**Platform (please complete the following information):**
 - Device: appleTV 4k 3.gen
 - OS: tvOS 17

**Comment by Alanko5** [comment]
check email

**Comment by Alanko5** [comment]
debug KSPlayer: MEPlayerItem.swift:455 readThread() | seek to 18.412 spend Time: 0.19463770830770954
debug KSPlayer: KSPlayerLayer.swift:138 state | playerStateDidChange - buffering
debug KSPlayer: KSOptions.swift:432 outputNumberOfChannels(channels:isUseAudioRenderer:) | [audio] maximumOutputNumberOfChannels: 2
debug KSPlayer: KSOptions.swift:433 outputNumberOfChannels(channels:isUseAudioRenderer:) | [audio] preferredOutputNumberOfChannels: 2
debug KSPlayer: KSOptions.swift:436 outputNumberOfChannels(channels:isUseAudioRenderer:) | [audio] isSpatialAudioEnabled: false
debug KSPlayer: KSOptions.swift:437 outputNumberOfChannels(channels:isUseAudioRenderer:) | [audio] isUseAudioRenderer: false
debug KSPlayer: KSOptions.swift:449 outputNumberOfChannels(channels:isUseAudioRenderer:) | [audio] currentRoute max channels: 2
debug KSPlayer: KSOptions.swift:455 outputNumberOfChannels(channels:isUseAudioRenderer:) | [audio] outputNumberOfChannels: 2
debug KSPlayer: AVFFmpegExtension.swift:398 layoutTag | [audio] FFmepg AVChannelLayout: stereo order: AVChannelOrder(rawValue: 1) mask: 3
debug KSPlayer: Resample.swift:293 audioFormat(channels:isUseAudioRenderer:) | [audio] out channelLayout: stereo
debug KSPlayer: MEPlayerItem.swift:125 MEPlayerItem | Using fltp internally between filters
debug KSPlayer: MEPlayerItem.swift:125 MEPlayerItem | Matrix coefficients:
debug KSPlayer: MEPlayerItem.swift:125 MEPlayerItem | FL:
debug KSPlayer: MEPlayerItem.swift:125 MEPlayerItem | FL:1.000000
debug KSPlayer: MEPlayerItem.swift:125 MEPlayerItem | FR:0.000000
debug KSPlayer: MEPlayerItem.swift:125 MEPlayerItem | FC:0.707107
debug KSPlayer: MEPlayerItem.swift:125 MEPlayerItem | LFE:0.000000
debug KSPlayer: MEPlayerItem.swift:125 MEPlayerItem | BL:0.707107
debug KSPlayer: MEPlayerItem.swift:125 MEPlayerItem | BR:0.000000
debug KSPlayer: MEPlayerItem.swift:125 MEPlayerItem | SL:0.707107
debug KSPlayer: MEPlayerItem.swift:125 MEPlayerItem | SR:0.000000
debug KSPlayer: MEPlayerItem.swift:125 MEPlayerItem |
debug KSPlayer: MEPlayerItem.swift:125 MEPlayerItem | FR:
debug KSPlayer: MEPlayerItem.swift:125 MEPlayerItem | FL:0.000000
debug KSPlayer: MEPlayerItem.swift:125 MEPlayerItem | FR:1.000000
debug KSPlayer: MEPlayerItem.swift:125 MEPlayerItem | FC:0.707107
debug KSPlayer: MEPlayerItem.swift:125 MEPlayerItem | LFE:0.000000
debug KSPlayer: MEPlayerItem.swift:125 MEPlayerItem | BL:0.000000
debug KSPlayer: MEPlayerItem.swift:125 MEPlayerItem | BR:0.707107
debug KSPlayer: MEPlayerItem.swift:125 MEPlayerItem | SL:0.000000
debug KSPlayer: MEPlayerItem.swift:125 MEPlayerItem | SR:0.707107
debug KSPlayer: MEPlayerItem.swift:125 MEPlayerItem |
debug KSPlayer: KSPlayerLayer.swift:138 state | playerStateDidChange - bufferFinished

**Comment by Alanko5** [comment]
<img width="928" alt="Thread activity" src="https://github.com/kingslay/KSPlayer/assets/71501260/87b70343-c127-4d29-865c-5d750e9cf510">

TrueHD audio decoding in 10 sec:
<img width="1076" alt="TrueHD source" src="https://github.com/kingslay/KSPlayer/assets/71501260/2e58f8a6-ca6d-4d98-803b-37de72ff9276">

AC stereo audio in 10 sec:
<img width="1086" alt="Snímka obrazovky 2023-11-13 o 17 29 42" src="https://github.com/kingslay/KSPlayer/assets/71501260/0049d79b-5ef2-48af-b313-db1b79b65895">

**Comment by Alanko5** [comment]
Audio mixer creating too match threads
<img width="1013" alt="Audio mixer" src="https://github.com/kingslay/KSPlayer/assets/71501260/ddc757cc-0906-4bde-b06e-a5fae122f34c">

**Comment by kingslay** [comment]
你把audioPlayerType 改成是AudioUnitPlayer 试试看。

**Comment by Alanko5** [comment]
> 你把audioPlayerType 改成是AudioUnitPlayer 试试看。

the image cuts and the sound pops

**Comment by kingslay** [comment]
你把视频裁剪出一个几分钟的片段，上传到github。我测试下。

**Comment by kingslay** [comment]
还会有这个问题吗？
