### ISSUE TITLE
How to change subtitle size?

### ISSUE THREAD

**Issue by loicleser** [kingslay/KSPlayer#585]
Hello I'm looking how I can set subtitle size? 
Thanks

**Comment by kingslay** [comment]
SubtitleModel.textFontSize

**Comment by loicleser** [comment]
Can you help me a bit more :-) 
Where i find that ?

**Comment by kingslay** [comment]
你可以看我的demo

**Comment by loicleser** [comment]
Thanks it's ok :-)
