### ISSUE TITLE
Video not fluid when 25fps video output format description criteria

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#586]
Every time I switch to 25fps video output format description, the video is not fluid..it's jerk.
These are a couple of logs I have:

```
🟢: [AVDisplayCriteria] Video has been updated - refreshRate: 25.0, formatDescription: Optional(<CMVideoFormatDescription 0x2888dfea0 [0x21d7a20e8]> {
	mediaType:'vide' 
	mediaSubType:'420v' 
	mediaSpecific: {
		codecType: '420v'		dimensions: 1280 x 720 
	} 
	extensions: {{
    CVBytesPerRow = 1924;
    CVImageBufferChromaLocationTopField = Left;
    CVImageBufferColorPrimaries = "ITU_R_709_2";
    CVImageBufferTransferFunction = "ITU_R_709_2";
    CVImageBufferYCbCrMatrix = "ITU_R_709_2";
    CVPixelAspectRatio =     {
        HorizontalSpacing = 1;
        VerticalSpacing = 1;
    };
    Version = 2;
}}
}).
🟢: [AVDisplayCriteria] Criteria was switched to video output refreshRate: 25.0 and DR: SDR
```

**Comment by kingslay** [comment]
是在播放同一个视频的时候，会一直发生Video has been updated  吗？这个是不合理的

**Comment by matteogobbi** [comment]
I didn’t get the question. This in response to the video output change. I set the criteria, but the quality is bad. If I disable the content matching, the stream goes fluid. Sent from my iPhoneOn Oct 15, 2023, at 12:42 PM, kingslay ***@***.***> wrote:﻿
是在播放同一个视频的时候，会一直发生Video has been updated  吗？这个是不合理的

**Comment by kingslay** [comment]
你是重载updateVideo(refreshRate: Float, formatDescription: CMFormatDescription?) 这个方法吗？

**Comment by kingslay** [comment]
试着用AVDisplayCriteria(refreshRate: refreshRate, videoDynamicRange: videoDynamicRange.rawValue) 这给初始化方法，不要用 AVDisplayCriteria(refreshRate: refreshRate, formatDescription: formatDescription) 这个初始化方法

**Comment by matteogobbi** [comment]
a week ago I tried track format description but it wasn’t good either. That’s why I always set the video output when is ready. Yes I overridden it.

**Comment by kingslay** [comment]
你试着这样重载。看行不行
```

    override func updateVideo(refreshRate: Float, formatDescription: CMFormatDescription?) {
        #if os(tvOS) || os(xrOS)
        guard let displayManager = UIApplication.shared.windows.first?.avDisplayManager,
              displayManager.isDisplayCriteriaMatchingEnabled,
              !displayManager.isDisplayModeSwitchInProgress
        else {
            return
        }
        if let formatDescription {
            displayManager.preferredDisplayCriteria = AVDisplayCriteria(refreshRate: refreshRate, videoDynamicRange: formatDescription.dynamicRange.rawValue)
        }
        #endif
    }

```

**Comment by matteogobbi** [comment]
That’s what I do but then I select the video output format description when is ready. I’ll try only with that then but it seems video output is more accurate in theory

**Comment by matteogobbi** [comment]
I tried even using
```  
displayManager.preferredDisplayCriteria = AVDisplayCriteria(refreshRate: refreshRate, videoDynamicRange: formatDescription.dynamicRange.rawValue)
```
with the video output, with no success.

**Comment by matteogobbi** [comment]
I have the impression that live refresh rate less than 50, works with:

`AVDisplayCriteria(refreshRate: track.nominalFrameRate, videoDynamicRange: videoDynamicRange)`

and that for 50 or more, works with the new tvOS17 API.

**Comment by matteogobbi** [comment]
So for 50 fps I use this:

`displayManager.preferredDisplayCriteria = AVDisplayCriteria(refreshRate: videoOutputRefreshRate, formatDescription: videoOutputFormatDescription)` 

and it works.

For 25 fps most of the time doesn't work well with any approach.
