### ISSUE TITLE
Dolby Atmos support

### ISSUE THREAD

**Issue by chillout23** [kingslay/KSPlayer#590]
I have media that has Dolby Atmos track but Tracy Player is outputting them 5.1 only without the additional metadata for Atmos. Would be nice to see this getting implemented in KSPlayer :)

**Comment by cdguy** [comment]
This is almost impossible.
Only apple native player supports it, because pays for the licensing 
Open libraries like FFMPEG do not support dolby atmos (yet)

**Comment by chillout23** [comment]
Thanks for the info!
