### ISSUE TITLE
Error "unsupported URL" when play RTSP url from new iOS Swift project

### ISSUE THREAD

**Issue by huytbt** [kingslay/KSPlayer#592]
**Describe the bug**
Hi there, I have an issue when play RTSP.  This is error message:
```
warning KSPlayer: KSPlayerLayer.swift:409 finish(player:error:) | Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL, NSUnderlyingError=0x280ec1080 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "unsupported URL" UserInfo={NSDescription=unsupported URL}}}
```
Issue only occurs for my new project. When I put the code into your Demo Project, this issue does not occur.
This is my code
```
import Foundation
import SwiftUI
import KSPlayer

struct PlayerView: View {
    var body: some View {
        KSVideoPlayerView(
            url: URL(string: "rtsp://user:password@192.168.1.9:554")!
        )
    }
}
```

**To Reproduce**
1. Create new iOS Swift Project
2. Add new file PlayerView.swift (Code content above)
3. Add PlayerView() for render in MainApp View
4. Build app and run

**Expected behavior**
Play RTSP streaming video

**Platform (please complete the following information):**
 - Device: [e.g. iPhoneX]
 - OS: [e.g. iOS16.7]

Thank you very much

**Comment by kingslay** [comment]
KSOptions.firstPlayerType = KSMEPlayer.self

**Comment by huytbt** [comment]
@kingslay thank you very much. Issue has been resolved
Best Regards
