### ISSUE TITLE
[SwiftUI] : .onBufferChanged view modifier doesn't print buffer value

### ISSUE THREAD

**Issue by nazar-41** [kingslay/KSPlayer#594]
I'm attempting to print the buffer value whenever it changes:

`.onBufferChanged { int, interval in
    print("\n • int: \(int), interval: \(interval)")
}
`

However, it doesn't print every time it changes.

**Comment by kingslay** [comment]
我的demo是可以的，你可以看下我刚才的提交。然后用我的demo试下
