### ISSUE TITLE
[VisionOS] 关闭窗口后，音频还在播放

### ISSUE THREAD

**Issue by yc2014d** [kingslay/KSPlayer#596]
你好：
在vision pro模拟器上，关闭窗口后，音频还在播放。
  KSVideoPlayerView(url: voiceURL).frame(width: 10.0,height: 10.0)
  KSVideoPlayerView(url: videoURL)

需要调用什么方法，可以通知播放器销毁。

**Comment by kingslay** [comment]
public static func dismantleUIView(_: UIViewType, coordinator: Coordinator) {
        coordinator.resetPlayer()
    }
看下有没有走到这里。销毁的时候应该是要调用resetPlayer()的

**Comment by yc2014d** [comment]
> public static func dismantleUIView(_: UIViewType, coordinator: Coordinator) { coordinator.resetPlayer() } 看下有没有走到这里。销毁的时候应该是要调用resetPlayer()的
关闭窗口调用这个方法：
dismissWindow(id: "contentView")
dismantleUIView方法没有执行

**Comment by kingslay** [comment]
那你要找下原因为什么dismantleUIView 没有调用。目前我的电脑不是m芯片。所以无法跑vision 模拟器了
