### ISSUE TITLE
Buffer Settings for being "the closest possible to a live stream"

### ISSUE THREAD

**Issue by cdguy** [kingslay/KSPlayer#598]
I found it worth sharing my comment regarding buffer settings in another post. It might be easier for your to track it via this tread:

https://github.com/kingslay/KSPlayer/issues/525#issuecomment-1784557156

**Comment by kingslay** [comment]
@cdguy  直播流的话，应该是无法进行seek的。

**Comment by cdguy** [comment]
> @cdguy 直播流的话，应该是无法进行seek的。

So the “easiest” thing to do (for the user) is to increase the playback stream to be able to watch a live stream with the least buffer possible
