### ISSUE TITLE
播放部分虎牙直播会跳帧，并且控制台会输出很多警告

### ISSUE THREAD

**Issue by pcccccc** [kingslay/KSPlayer#599]
同一个直播间抓出的直播源，使用KSPlayer播放会跳帧，并且控制台会输出下面的错误：

平台：tvOS模拟器
播放器内核：KSMEPlayer
版本 tvOS 17.0

warning KSPlayer: KSOptions.swift:361 videoClockSync(main:nextVideoTime:fps:) | [video] video delay=-0.940158875004272, clock=41636.339158875, delay count=11030
warning KSPlayer: KSOptions.swift:361 videoClockSync(main:nextVideoTime:fps:) | [video] video delay=-0.9478529166735825, clock=41636.36385291667, delay count=11031
warning KSPlayer: KSOptions.swift:361 videoClockSync(main:nextVideoTime:fps:) | [video] video delay=-0.9498434583438211, clock=41636.39984345834, delay count=11032
warning KSPlayer: KSOptions.swift:361 videoClockSync(main:nextVideoTime:fps:) | [video] video delay=-0.9702557083292049, clock=41636.43625570833, delay count=11033

iina并没有类似问题，这是iina的视频轨道简介。
<img width="359" alt="截屏2023-10-31 22 32 34" src="https://github.com/kingslay/KSPlayer/assets/13974510/14d27a5f-151e-468d-a7fd-fc8486a10735">

**Comment by kingslay** [comment]
你用最新的代码在试下，我晚上刚提交了一个优化版本。这个是音视频不同步，所以才进行跳帧了。

**Comment by pcccccc** [comment]
> 你用最新的代码在试下，我晚上刚提交了一个优化版本。这个是音视频不同步，所以才进行跳帧了。

拉了一份最新的代码，问题还在，log变成了：

`warning KSPlayer: KSOptions.swift:379 videoClockSync(main:nextVideoTime:fps:frameCount:) | [video] video delay=-0.97491529166291, clock=43190.257915291666, delay count=530, frameCount=15 drop next frame
warning KSPlayer: KSOptions.swift:379 videoClockSync(main:nextVideoTime:fps:frameCount:) | [video] video delay=-0.98553441666445, clock=43190.31853441666, delay count=532, frameCount=12 drop next frame
warning KSPlayer: KSOptions.swift:379 videoClockSync(main:nextVideoTime:fps:frameCount:) | [video] video delay=-1.0082272083309363, clock=43190.39122720833, delay count=534, frameCount=9 drop next frame
warning KSPlayer: KSOptions.swift:379 videoClockSync(main:nextVideoTime:fps:frameCount:) | [video] video delay=-1.0188793749985052, clock=43190.451879374996, delay count=536, frameCount=15 drop next frame`

**Comment by kingslay** [comment]
看这个是信息是 视频渲染来不急。是一直都是输出这个信息吗？还是间隔性的。你可以把isUseDisplayLayer 改成是false。看下还会不会有这个问题。

**Comment by pcccccc** [comment]
> 看这个是信息是 视频渲染来不急。是一直都是输出这个信息吗？还是间隔性的。你可以把isUseDisplayLayer 改成是false。看下还会不会有这个问题。

输出非常频繁，不是间隔性的，如果您什么时候方便我可以提供一条播放链接，但是连接失效的比较快

**Comment by pcccccc** [comment]
我尝试将display设置成vr 让isUseDisplayLayer=false
但是控制台依旧会产生警告，并且能看出画面依旧有卡顿的问题。

**Comment by Kimentanm** [comment]
是虎牙的m3u8还是flv链接？

**Comment by kingslay** [comment]
不能用vr。这个会让资源占用更高。你就把这个方法的返回值改成返回false就可以了

**Comment by pcccccc** [comment]
> 是虎牙的m3u8还是flv链接？

flv

**Comment by pcccccc** [comment]
> 不能用vr。这个会让资源占用更高。你就把这个方法的返回值改成返回false就可以了

感觉是和这个虎牙的15fps的flv直播源有关系

<img width="449" alt="image" src="https://github.com/kingslay/KSPlayer/assets/13974510/e6987049-b883-4918-aad8-72bee815da9a">

这是iina的检查器。

当我使用一个60fps的直播源时，就不会产生这个问题。

**Comment by kingslay** [comment]
我怀疑是flv返回的fps不对，不是15。你试着把 let preferredFramesPerSecond = Int(ceil(fps)) 这个代码改成是 preferredFramesPerSecond = 24 @pcccccc

**Comment by pcccccc** [comment]
> 我怀疑是flv返回的fps不对，不是15。你试着把 let preferredFramesPerSecond = Int(ceil(fps)) 这个代码改成是 preferredFramesPerSecond = 24 @pcccccc

经过测试，手动设置成24确实是可以。但是我本身不是做视频相关的，不太理解这其中的道理，望指教。

另外根据虎牙的接口判断，iMobilePriorityRate这个字段会返回15， 25， 65 三个字段，使用IINA的检查器来看确实也可以对应上帧数。

**Comment by kingslay** [comment]
那可以返回25的flv吗

**Comment by pcccccc** [comment]
> 那可以返回25的flv吗

比较大的主播会同时返回三种： 15， 25 ，60，两种格式flv和m3u8。
我目前是把15的直接跳过了。
