### ISSUE TITLE
Hls adaptive bitrate

### ISSUE THREAD

**Issue by minhtoantm** [kingslay/KSPlayer#6]
Hi.
Thanks for great player.
But can you implemnt function: hls adaptive bitrate when playing m3u8 master playlist? 
Example: https://mnmedias.api.telequebec.tv/m3u8/29880.m3u8

When I play master m3u8, always play the first playlist, not by bandwidth.
Thank you again.

**Comment by kingslay** [comment]
The latest develop branch is now support  hls adaptive bitrate 

KSOptions.adaptable(state: )

**Comment by minhtoantm** [comment]
> The latest develop branch is now support hls adaptive bitrate
> 
> KSOptions.adaptable(state: )

Great!!!.
Can you let me know: this function is only develop in swift? Not modifed in ffmpeg?
Thank.

**Comment by kingslay** [comment]
this function is only develop in swift
