### ISSUE TITLE
possible to record stream?

### ISSUE THREAD

**Issue by snappycode1** [kingslay/KSPlayer#60]
Is there a way to record a video stream that is playing?

in vlckit you can use mediaPlayer.startRecording() and it will record whatever video is being played.

is this possible in KSPlayer?

**Comment by kingslay** [comment]
It's not supported yet.

**Comment by ParthAlliancetek** [comment]
> It's not supported yet.

can you please add this features Because you already mentioned it in your feature list.

**Comment by kingslay** [comment]
这个能力目前已经支持了。你只要设置下outputURL 就可以了
```
   let moviesDirectory = try? FileManager.default.url(for: .moviesDirectory, in: .userDomainMask, appropriateFor: nil, create: false)
                options.outputURL = moviesDirectory?.appendingPathComponent("recording.mov")
```
