### ISSUE TITLE
[Question] Set default video track

### ISSUE THREAD

**Issue by nazar-41** [kingslay/KSPlayer#601]
Hello everyone, I'm currently working with an HLS file that contains four video tracks of varying qualities. I'm wondering how to set the default track quality. My HLS file looks like:

```
#EXTM3U

#EXT-X-INDEPENDENT-SEGMENTS

#EXT-X-MEDIA:TYPE=AUDIO,URI="audio/audio.m3u8",GROUP-ID="audio",LANGUAGE="en",NAME="ENGLISH",AUTOSELECT=YES,CHANNELS="2"

#EXT-X-STREAM-INF:BANDWIDTH=950376,AVERAGE-BANDWIDTH=728275,CODECS="avc1.4d401e,mp4a.40.2",RESOLUTION=640x360,FRAME-RATE=29.970,VIDEO-RANGE=SDR,AUDIO="audio",CLOSED-CAPTIONS=NONE
	360p/playlist.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=4813550,AVERAGE-BANDWIDTH=3158741,CODECS="avc1.640020,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=59.960,VIDEO-RANGE=SDR,AUDIO="audio",CLOSED-CAPTIONS=NONE
	720p/playlist.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=6968449,AVERAGE-BANDWIDTH=5007913,CODECS="avc1.64002a,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=59.960,VIDEO-RANGE=SDR,AUDIO="audio",CLOSED-CAPTIONS=NONE
	1080p/playlist.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1609228,AVERAGE-BANDWIDTH=1232391,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=854x480,FRAME-RATE=29.970,VIDEO-RANGE=SDR,AUDIO="audio",CLOSED-CAPTIONS=NONE
	480p/playlist.m3u8
```

**Comment by chillout23** [comment]
Ideally KSPlayer should select the best quality based on your connection, automatically. In Tracy Player I have to explicitly select which video track when I have a HLS stream with multiple tracks. Both for audio and video.

**Comment by kingslay** [comment]
///  wanted video stream index, or nil for automatic selection
    /// - Parameter : video bitRate
    /// - Returns: The index of the bitRates
    open func wantedVideo(bitRates _: [Int64]) -> Int? {
        nil
    }

**Comment by nazar-41** [comment]
could you please give code example how i can set it as default. Here how i get list of bitrates

`guard let bitrates = config.playerLayer?.player.tracks(mediaType: .video).map(\.bitRate) else{return}`

**Comment by kingslay** [comment]
我的上一个评论已经说了解决的方法了 
`open func wantedVideo(bitRates _: [Int64]) -> Int? {
`
