### ISSUE TITLE
Teletext appearing as subtitles?

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#603]
With updates up to yesterdays, people see the teletext as subtitles on lives. 

![IMG_7564](https://github.com/kingslay/KSPlayer/assets/1998171/979e7b1b-c0ac-4c48-b3f7-d2f4e475ac6d)

**Comment by djokt** [comment]
I wish to express my frustration with how often you request improvements for your (paid) application while showing no support for the player's development. It is important to recognize Kingslay's work and effort. Not even mentioning their name demonstrates a blatant lack of consideration. 
I encourage you to reflect on the value this player brings to your daily use, and consider supporting the developer, even if just by crediting them and showing some appreciation for their work by becoming a sponsor, at the minimum. By providing financial support to the developer, you would contribute more to the development and improvement of the player for all users, including your own.

**Comment by matteogobbi** [comment]
@djokt 

1. I report and help with improvement for this player, not for my paid app; I even have a couple of PR into this project, that you also use; the fact that this player might or might not be part of my paid app is irrelevant (also my paid app had success without this player, it's out since April 2019, and we introduced this player only in the last 3-4 months);
2. You are not putting out your name and your app. I'm totally transparent with my name and everybody know which app I have. So if you want to talk, come out first, otherwise you are just an avatar and a nickname;
3. What I do or not do, is none of your business. My position here is to report bugs and help test/fix them, with the goal of improving this project. And that's all you should (or shouldn't) care about.
4. Thanks to the many users I had when I introduced this player in my app, I was able to report several bugs, and to help fix/test them. The project, and the people using it (including you) benefited from that.
5. Kingslay have all my respect. The reason why I don't always ping his name, is to not put pressure on him and leave his time to review. I worked in big companies as Google and Twitter (and many other companies) therefore my approach is based on the experiences I got with many other devs. But again, you did your deductions, thinking that they are the only truth;
6. My plans and decisions are private, and the fact that you imagine something, thinking to have considered all aspects, is superficial. Therefore I discourage you to open this off topic discussions in future;
7. In encourage you to reflect.

Thank you.
