### ISSUE TITLE
Teletext appearing as subtitles (?)

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#604]
With the updates up to yesterday, people see the teletext as subtitles on lives. Do you have any clue with this?

![IMG_7564](https://github.com/kingslay/KSPlayer/assets/1998171/979e7b1b-c0ac-4c48-b3f7-d2f4e475ac6d)

**Comment by djokt** [comment]
No problem I can repost here.
I wish to express my frustration with how often you request improvements for your (paid) application while showing no support for the player's development. It is important to recognize Kingslay's work and effort. Not even mentioning their name demonstrates a blatant lack of consideration. 
I encourage you to reflect on the value this player brings to your daily use, and consider supporting the developer, even if just by crediting them and showing some appreciation for their work by becoming a sponsor, at the minimum. By providing financial support to the developer, you would contribute more to the development and improvement of the player for all users, including your own.

**Comment by matteogobbi** [comment]
Well, the problem is you not caring about the fact that this is a bug, and you are not respecting the topic. And this is the only reason why I recreated the bug. But if it makes you feel better..

**Comment by cdguy** [comment]
@matteogobbi 

https://github.com/kingslay/KSPlayer/issues/603#issuecomment-1791427781

My intention is not to escalate things, but please let me add some comments on your response:

1- it is true that even before KSplayer your app was on the appstore, but on the other hand you felt very happy to inform all your users that iptvX "now supports dolby vision" which is thanks to KSplayer which is the only media player using the Metal architecture, and most importantly SwiftUI

2- that is correct that you do now need to specify the name of the APIs you are using, but in the opensource world, it is a "gentlemanhood" to mention all the libraries you are using. you, where you say that you worked for the biggest tech companies, in the world of coding it "the manner" to credit the open sources, which is a source of motivation for the deveopper to work hard. on the contrary, not mentioning Ksplayer is cheep.


3- of course you do not have any obligation to pay for any donation to this player, but as you are the "greatest app" in terms of revenue (you say it yourself), giving a "small" contribution would also be a very kind gesture to the dev of this media player.

**Comment by matteogobbi** [comment]
Given the out of topic, I give a last reply to clarify:

1. We have AVPlayer since several years, and always supported Dolby Vision, so we didn't introduce it with this player. But yes, it was good to see that this player would support it on other video formats too. We don't use KSAVPlayer indeed, only KSME as fallback player.

2. At my company we respect all the licenses of the projects we introduce, and we make attributions on AppStore and websites (and I always talked publicly with users about this library). However, I'll check where we missed attribution for it and make it fix asap.

3. You can't know what kind of contribution I do for this project. So I don't understand how you a say what you say. And, I never said anything like that, because I don't know how much revenues other apps do, and to be honest, I don't care much. As you don't know how much revenues my product makes.

**Comment by kingslay** [comment]
这个开源项目现在参与的人越来越多了。有很多的bug和feature被提出来。但是目前主要代码编写者只有我一个人，我都是用周末的时候，或是晚上的时间来进行维护（因为我有一份八小时的工作）。所以我会按照优先级来解决问题。就像我的捐赠计划页面说的那样，我会优先解决捐赠者提出的bug和feature。我一开始开发这个业余项目，主要服务目标是iOS系统(因为我是一个iOS开发者，只熟悉iOS)，只是我一开始有做了Apple全平台的兼容，所以也支持tvOS/macOS。后来很多人提了tvOS的问题，甚至捐赠一台tvOS设备给这个项目，导致tvOS现在成为这个项目主要服务目标。这个项目成长成这样有各位参与者的功劳，甚至有的参与者还不是开发者，只是一个普通的用户。他完全是无私的帮这个项目进行测试，并且也一起捐赠了音箱给这个项目。对于他的这个行为我是感到很诧异的，因为他完全没有用那这个项目去开发一个app，然后从中盈利。自由软件之“父”——Richard. M. Stallman 说过 “GUN代表自由的思想，但不是免费的午餐”。我很赞同这句话，开源不等于免费。基于开源的精神，我欢迎任何人来使用这个SDK，并提出bug和feature。我有一个很宏大并且很难达到的目标：这个项目以后能够成为跟mpv一样家喻户晓的项目。这个目标只靠我一个人是完全不可能达成的，因为我的能力很有限，我的能力还只停留在对ffmpeg的API调用，还没有深入的去优化ffmpeg。所以这个目标是需要这个项目的所有参与者一起来努力达到的。我也希望有更多人能够一起来为这个项目贡献代码、设备、资金，一起努力达成这个艰巨伟大的目标。
