### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nightfall708** [kingslay/KSPlayer#605]
Hi, 

we're experiencing this crash:

Fatal Exception: com.apple.coreaudio.avfaudio
required condition is false: nullptr == Tap()

AudioEnginePlayer.swift - Line 174
AudioEnginePlayer.prepare(audioFormat:) + 174

AudioEnginePlayer.swift - Line 236
closure #1 in AudioEnginePlayer.audioPlayerShouldInputData(ioData:numberOfFrames:) + 236

Any idea?

**Comment by kingslay** [comment]
这个一般是音频格式有问题，导致crash了。你是用最新的代码。之前有解决过一次音频格式不规范的问题。你能否提供下url或日志吗？

**Comment by nightfall708** [comment]
I tried streams where this has happened but was unable to reproduce. Also it seems the crash occurs to users only once (for the same stream). So it's unlikely to be the stream itself, rather some random error in the stream itself. 
This is a new problem that hasn't happened to be in an older version (that had other crashes though, such as #564).

**Comment by kingslay** [comment]
这个问题应该解决了。你试下最新的代码
