### ISSUE TITLE
Airplay volume stopped working with KSMEPlayer

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#606]
Hello Kingslay, 
do you know if any of the commits done in the last few days, could be related to the airplay volume in `KSMEPlayer`?
Apparently now is working with the other players, but not with KSME.

Thanks!

**Comment by kingslay** [comment]
是tvOS 17.0的Airplay不能工作吗？这个只要把tvOS升级到17.1就可以了

**Comment by matteogobbi** [comment]
From the test made,
Airplay audio works, and using the Apple TV remote controller to change audio also work on VLC and AVPlayer frameworks, but doesn’t work on KSMEPlayer.

**Comment by kingslay** [comment]
用我的demo也会有这个问题吗？这个是只有在airplay才会有这个问题吗？目前这块是改动过的。你可以看下是那个commit引起这个问题。
