### ISSUE TITLE
Optimising sound dynamics

### ISSUE THREAD

**Issue by JeremTM93** [kingslay/KSPlayer#607]
When we compare the sound of KSplayer with MPV on tvOS (LillyPlayer, Plex...) or ExoPlayer on Android TV, the sound is not the same:

-Sound dynamics are deficient overall, regardless of the multichannel sound tracks played.
-Some surround effects between the speakers are absent.
-The subwoofer's bass reproduction is not at the expected level (underpowered).

You can help yourself with the film "ready player one" in Atmos TrueHD, and more particularly the scene from 12:40 to 13:30 of the film.

**Comment by djokt** [comment]
I can confirm. It's as if the sound were limited or lacking in power.

**Comment by cdguy** [comment]
> When we compare the sound of KSplayer with MPV on tvOS (LillyPlayer, Plex...) or ExoPlayer on Android TV, the sound is not the same:
> 
> -Sound dynamics are deficient overall, regardless of the multichannel sound tracks played. -Some surround effects between the speakers are absent. -The subwoofer's bass reproduction is not at the expected level (underpowered).
> 
> You can help yourself with the film "ready player one" in Atmos TrueHD, and more particularly the scene from 12:40 to 13:30 of the film.



https://www.imdb.com/title/tt1677720/

**Comment by kingslay** [comment]
@JeremTM93 我先简单的增加了一个音频输出，AudioUnit。 你可以到demo app的设置/音频。进行选择。这个音频输出做的还比较简单，无法静音和倍数播放。但是你可以用它来实验下你说的问题。看下有没有改善。这个音频输出我是仿照mpv来写的，看下能否达到跟mpv一样的效果

**Comment by cdguy** [comment]
> @JeremTM93 我先简单的增加了一个音频输出，AudioUnit。 你可以到demo app的设置/音频。进行选择。这个音频输出做的还比较简单，无法静音和倍数播放。但是你可以用它来实验下你说的问题。看下有没有改善。这个音频输出我是仿照mpv来写的，看下能否达到跟mpv一样的效果

You have to update the testflight app, @JeremTM93 is not a developper

**Comment by JeremTM93** [comment]
> @JeremTM93 我先简单的增加了一个音频输出，AudioUnit。 你可以到demo app的设置/音频。进行选择。这个音频输出做的还比较简单，无法静音和倍数播放。但是你可以用它来实验下你说的问题。看下有没有改善。这个音频输出我是仿照mpv来写的，看下能否达到跟mpv一样的效果

Indeed, there is a real difference in dynamics with the “AudioUnit” option.  I need more time to compare correctly but you are on the right track I think 🙏👌

**Comment by JeremTM93** [comment]
We agree @kingslay , you also feel a big difference ?

**Comment by cdguy** [comment]
The sound difference is amazing!! AudioUnit shouls be the default “audio framework” for Ksplayer! I advise you to push a commit for that. This thread can be closed!! 🥳🥳

**Comment by kingslay** [comment]
AudioUnit 是直接把音频输出到音响的，中间少了很多处理。所以效果是会最好的。但是这样的话，也就只有播放、暂停、静音的功能。没有倍数播放，音量调节，AudioDynamicsProcessor相关功能。

**Comment by cdguy** [comment]
> AudioUnit 是直接把音频输出到音响的，中间少了很多处理。所以效果是会最好的。但是这样的话，也就只有播放、暂停、静音的功能。没有倍数播放，音量调节，AudioDynamicsProcessor相关功能。

@kingslay for multi stream playback (so more than 2 streams played on a split screen) VLC is always the safest option

**Comment by cdguy** [comment]
> AudioUnit 是直接把音频输出到音响的，中间少了很多处理。所以效果是会最好的。但是这样的话，也就只有播放、暂停、静音的功能。没有倍数播放，音量调节，AudioDynamicsProcessor相关功能。

And perhaps mentioning what you just said, in the read me file (welcome page), would help new people willing to use KsPlayer

**Comment by JeremTM93** [comment]
The sound dynamics are the same as with the MPV player or exoplayer, this subject can indeed be closed.  nice work @kingslay.

Now let's focus on ticket #609

**Comment by cdguy** [comment]
@kingslay do not forget to close this thread
