### ISSUE TITLE
Reset srt label not work

### ISSUE THREAD

**Issue by Alanko5** [kingslay/KSPlayer#608]
**Describe the bug**
the subtitles are displayed until I change the text.

**To Reproduce**
any source with forced subtitles.
for example, the name of the city is displayed in the 1st minute. it will not be lost until it is overwritten by other subtitles in the 5th minute.

**Expected behavior**
deleting the text after the subtitle timing has expired.

**Platform (please complete the following information):**
 - Device: [apple tv 4k 3th gen]
 - OS: [tvos 17]

**Comment by kingslay** [comment]
我刚用swiftui的demo工程。试了下外挂字幕是不会有问题题的。你可以提供下这个字幕。
