### ISSUE TITLE
部分视频通过网络传输会频繁缓冲

### ISSUE THREAD

**Issue by FantasyKingdom** [kingslay/KSPlayer#612]
K神，你好。这两个视频把它保存到手机本地播放很流畅，但是把它放到NAS上面通过http流或者ftp流进行播放就会频繁缓冲，特别是拖动进度条之后。在同一个设备上使用VLC播放非常流畅，可以优化一下。

https://web.ugreen.cloud/web/#/share/EC-rGEP554JJ422FaJs-201468 提取码：64HM

**Comment by kingslay** [comment]
用mpv内核播放的话，也会流畅吗？

**Comment by FantasyKingdom** [comment]
> 用mpv内核播放的话，也会流畅吗？

我试了下，iina也是会频繁缓冲的

**Comment by FantasyKingdom** [comment]
貌似和音频播放有关系，把音轨禁用就流畅了

**Comment by kingslay** [comment]
那这个很难优化了。要让ffmepg那边改下才可以。mpv的网络请求是用ffmpeg的。只有vlc的网络请求是自己优化的，不是用原生的ffmpeg。

**Comment by kingslay** [comment]
> 貌似和音频播放有关系，把音轨禁用就流畅了

这么神奇吗？那我看下

**Comment by FantasyKingdom** [comment]
大佬有发现什么猫腻的地方吗。目前单独播放音轨或者视频都是正常的。两者一起就卡顿。

**Comment by kingslay** [comment]
还没，最近的issue太多了，优先去解决别人提的issue了。

**Comment by kingslay** [comment]
你可以把这个视频裁剪成几分钟的片段上传到github，这样我好进行测试。

**Comment by FantasyKingdom** [comment]
这个视频本身就只有几分钟，文件几百兆，上传到github比较麻烦。我重新分享了下，下载速度应该比较快的，你看看能不能下载。
https://web.ugreen.cloud/web/#/share/EC-1ulb554JJ422kbLx-201468 提取码：J386

**Comment by kingslay** [comment]
好的

**Comment by kingslay** [comment]
是从两分钟开始会频繁的缓冲吗

**Comment by kingslay** [comment]
这个找到原因了。前几分钟音频和视频的pos都是顺序增加的，但是后面就变成音频和视频的pos是交叉，所以游标的位置就要一会往前，一会往后。这就会导致频繁的seek，所以就会频繁的缓存。所以你如果只播放音频或只播放视频就不会问题，但是两个一起播放就会有问题。目前ffmpeg针对这样特殊清楚是无法处理的，只有vlc才能处理这种特殊情况。
