### ISSUE TITLE
Test Files to check

### ISSUE THREAD

**Issue by cdguy** [kingslay/KSPlayer#613]
Hello @kingslay 

I gathered a few video test files for you as you might need them at any time:
https://collect.wetransfer.com/board/smzf8ll657okoyjmg20231105161537/latest?token=48d229bc-3d85-4e46-8d4a-6cc3700739d0

Can you please check the following videos:

"4-2-2 Pure Satellite Feed": the stream gets constant buffering and the colours are completely broken. Only Qmplay2 app can play the stream correctly.

->> look at the screen record named "RPReplay_Final1699200498" that I took using tracy player using the last commits.

"25p transcoded Live Stream (bad trascoding)" Although the transcoding quality is bad (25fps), VLC Tvos handles better the sliding text. Still, it is not perfect too on VLC Tvos, but "slightly better" than Tracy Player.

Thank you

**Comment by chillout23** [comment]
Sorry this is a bit off topic but @cdguy can you reach me on email: kenth.kvien@gmail.com?
