### ISSUE TITLE
No voice/dialogue with 5.1 track on stereo system

### ISSUE THREAD

**Issue by djokt** [kingslay/KSPlayer#614]
I've noticed a problem with the playback of 5.1 audio tracks when played back on a stereo sound system.

In fact, when this type of 5.1 track is played back on a conventional stereo system, the dialogue is completely absent, leaving only the music and sound effects.

**Comment by kingslay** [comment]
是tvOS吗？是外接音箱吗？ 那你的音频输出需要设置为stereo。不然系统会判断你是多声道的音箱。

**Comment by djokt** [comment]
Sorry for the lack of information!
Yes, I'm on TvOS 17.1. In the settings I am in stereo. I don't have a system, it's the tv sound.

**Comment by kingslay** [comment]
你是用最新的代码吗？我昨晚有修复了这个问题。

**Comment by djokt** [comment]
I'm not a developer so I don't use the code but directly the apps on tvOS. I think I'm using the penultimate version.
I don't have an iPhone so I can't use the testflight invitation link to try on Tracy ... Can you email me an invitation code so I can check?
Thanks

**Comment by kingslay** [comment]
在tvOS上也是可以用testflight的啊。 https://testflight.apple.com/join/eNmYbmZN

**Comment by djokt** [comment]
I've sent you an email.
In order to add a testflight application via a link, you must use an iPhone... Since I only have an Apple TV, I need a code that I can enter in the testflight tvOS application...

**Comment by kingslay** [comment]
我邀请你了

**Comment by djokt** [comment]
Thanks, I'm not at home at the moment, I'll test later 👍

**Comment by cdguy** [comment]
this issue is fixed. you can close the thread. thank you @kingslay

**Comment by chillout23** [comment]
5.1 soundtrack, no sound from rear speakers with latest version of Tracy Player. Tried every option under Audio in "audio player type". So if you fixed something for stereo systems, now it does not work properly with 5.1 systems.

**Comment by anrtiger** [comment]
> @kingslay 5.1 soundtrack, no sound from rear speakers with latest version of Tracy Player. Tried every option under Audio in "audio player type". So if you fixed something for stereo systems, now it does not work properly with 5.1 systems.

"No, the surround works perfectly with Tracy's latest update."

**Comment by djokt** [comment]
@kingslay I did not receive any code or invitation by e-mail so I can't test ...

**Comment by kingslay** [comment]
我现在又重新发送邀请了 你在看下

**Comment by djokt** [comment]
It's good ! Thanks

**Comment by chillout23** [comment]
It doesn't for me. My setup reports 5.1 but no sound from rear speakers at all.

**Comment by kingslay** [comment]
@djokt 我昨天晚上帮你删除那个公共的m3u了。但是因为我的邮件有问题，不能发出邮件，所以我回复你了，但是没有发送成功。所以我在这边回复你一下。

**Comment by djokt** [comment]
@kingslay thank you !
