### ISSUE TITLE
pod 方法安装 出现编译问题

### ISSUE THREAD

**Issue by TushningJJ** [kingslay/KSPlayer#617]
使用spm 安装后 编译 通过。
因为其他原因必须使用pods安装，编译后error，提示 ：
ld: Undefined symbols:
  __vbi_bit_reverse, referenced from:
      _teletext_decode_frame in Libavcodec[x86_64][220](libzvbi-teletextdec.o)
  __vbi_hamm8_fwd, referenced from:
      _teletext_decode_frame in Libavcodec[x86_64][220](libzvbi-teletextdec.o)
  __vbi_hamm8_inv, referenced from:
      _teletext_decode_frame in Libavcodec[x86_64][220](libzvbi-teletextdec.o)
  _vbi_decode, referenced from:
      _teletext_decode_frame in Libavcodec[x86_64][220](libzvbi-teletextdec.o)
  _vbi_decoder_delete, referenced from:
      _teletext_decode_frame in Libavcodec[x86_64][220](libzvbi-teletextdec.o)
      _teletext_close_decoder in Libavcodec[x86_64][220](libzvbi-teletextdec.o)
  _vbi_decoder_new, referenced from:
      _teletext_decode_frame in Libavcodec[x86_64][220](libzvbi-teletextdec.o)
  _vbi_draw_vt_page_region, referenced from:
      _gen_sub_bitmap in Libavcodec[x86_64][220](libzvbi-teletextdec.o)
  _vbi_event_handler_register, referenced from:
      _teletext_decode_frame in Libavcodec[x86_64][220](libzvbi-teletextdec.o)
  _vbi_fetch_vt_page, referenced from:
      _handler in Libavcodec[x86_64][220](libzvbi-teletextdec.o)
  _vbi_print_page_region, referenced from:
      _gen_sub_text in Libavcodec[x86_64][220](libzvbi-teletextdec.o)
  _vbi_teletext_set_default_region, referenced from:
      _teletext_decode_frame in Libavcodec[x86_64][220](libzvbi-teletextdec.o)
  _vbi_unref_page, referenced from:
      _handler in Libavcodec[x86_64][220](libzvbi-teletextdec.o)
  _vbi_version, referenced from:
      _teletext_init_decoder in Libavcodec[x86_64][220](libzvbi-teletextdec.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

发给chatgpt后 回答是：
这个错误通常是由于链接器（ld）无法找到相关的符号（symbols）而导致的。在这个情况下，错误消息表明以下符号未找到：

__vbi_bit_reverse
__vbi_hamm8_fwd
__vbi_hamm8_inv
vbi_decode
vbi_decoder_delete
vbi_decoder_new
vbi_draw_vt_page_region
vbi_event_handler_register
vbi_fetch_vt_page
vbi_print_page_region
vbi_teletext_set_default_region
vbi_unref_page
vbi_version
这些符号通常是与zvbi库（ZVBI，用于解析电视上的文本数据，包括电视字幕和电视文字信息）相关的。要解决这个问题，你需要确保正确链接zvbi库。

以下是一些解决方法：

检查链接库是否正确：确保你的项目配置中包含了正确的zvbi库。你应该在项目设置中的 "Link Binary With Libraries" 部分添加zvbi库。如果你没有将zvbi库添加到项目中，链接器将无法找到这些符号。

检查库搜索路径：确保项目设置中的 "Library Search Paths" 包含zvbi库的路径，以便链接器能够找到库文件。

检查依赖项：确保zvbi库及其依赖项都已正确安装。如果zvbi库是从源代码构建的，确保它已经构建并安装在系统中。有关如何正确构建和安装zvbi库的信息，可以参考zvbi库的官方文档或相关文档。

检查架构：确保你正在构建的代码和zvbi库都支持相同的架构，例如x86_64。

希望作者能解决下，感谢！

**Comment by kingslay** [comment]
改好了
