### ISSUE TITLE
CircularBuffer push 的时候会触发 assert

### ISSUE THREAD

**Issue by strangeliu** [kingslay/KSPlayer#619]
**Describe the bug**
CircularBuffer push 的时候会触发 assert

```
if _buffer[Int(tailIndex & mask)] != nil {
            assertionFailure("value is not nil of headIndex: \(headIndex),tailIndex: \(tailIndex), bufferCount: \(_buffer.count), mask: \(mask)")
        }
```

Fatal error: value is not nil of headIndex: 26,tailIndex: 256, bufferCount: 256, mask: 255

**To Reproduce**
播放时随机出现

**Comment by strangeliu** [comment]
`CircularBuffer` 的 `expanding` 为 `true`

**Comment by strangeliu** [comment]
栈信息：
<img width="395" alt="Screenshot 2023-11-06 at 17 26 26" src="https://github.com/kingslay/KSPlayer/assets/5244588/6537a796-1d8a-4a8b-80d6-1c04a6a26651">

每次出现时，都是 tailIndex: 256, bufferCount: 256, mask: 255
headIndex 每次都不同

**Comment by kingslay** [comment]
可以提供这个url吗？

**Comment by strangeliu** [comment]
好像文字字幕就可能出现，偶发的，我先看看有什么规律没有
