### ISSUE TITLE
Dolby Vision no longer detected

### ISSUE THREAD

**Issue by JeremTM93** [kingslay/KSPlayer#621]
A Dolby Vision stream I was playing with TracyPlayer version 36 now plays in HDR10.  However, this stream is actually in DV

**Comment by JeremTM93** [comment]
> > A Dolby Vision stream I was playing with TracyPlayer version 36 now plays in HDR10. However, this stream is actually in DV
> 
> This is the commit that broke it:
> 
> https://github.com/kingslay/KSPlayer/commits/develop
> 
> before this commit, HDR10 content was always displayed in DV, and now on the contrary after this commit, all content is displayed in HDR10

#615 ?

I don't understand, isn't HDR HLG just for live streams ?

**Comment by kingslay** [comment]
可以提供下url吗？

**Comment by cdguy** [comment]
> 可以提供下url吗？

I will send you a few DV movies link via e-mail

**Comment by cdguy** [comment]
@kingslay looking at your last commit, I don’t know if it might help:
Real 4K live streams/DV content/HDR/HDR10+ are always progressive. As per the live satellite broadcast standards and movie production , those content wouls never be in interlaced format

**Comment by kingslay** [comment]
是的，这个其实跟interlaced没有关心，只是因为现在interlaced的逻辑，我们已经真正实现了。所以我顺便把interlaced 的逻辑从MEOptions移到KSOptions。这样所以这个库的人都能用到了。一些实验的功能，我会先在MEOptions实验。等打磨好了。在放到KSOptions。其实这个改动的核心点是    override func updateVideo(refreshRate: Float, isDovi: Bool, formatDescription: CMFormatDescription?) {
专门传递了isDovi 这个信息。因为从CMFormatDescription是无法判断是不是isDovi的。
