### ISSUE TITLE
Deinterlacing does not work with .m3u8 streams

### ISSUE THREAD

**Issue by chillout23** [kingslay/KSPlayer#622]
If the stream is encapsulated into HLS (.m3u8) TracyPlayer does not automatically enable deinterlacing on interlaced streams.

Currently this work perfect with mpegts (.ts) streams. @kingslay can you please fix this so it also detects .m3u8?

**Comment by kingslay** [comment]
可以提供下url吗

**Comment by chillout23** [comment]
@kingslay http://prens.full57.site:8000/live/ankara/a4GageR6WUDu/254.m3u8

**Comment by chillout23** [comment]
@kingslay I emailed you the url.

**Comment by kingslay** [comment]
看了下是因为流信息里面没有说他是interlaced 流。所以就不会进行处理了。下面是ffmpeg打印出来的信息
 Duration: N/A, start: 5087.080000, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
  Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn
    Metadata:
      variant_bitrate : 0
  Stream #0:1: Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, s16p, 256 kb/s
    Metadata:
      variant_bitrate : 0

**Comment by chillout23** [comment]
@kingslay, I understand. In that case I have no suggestions how to solve this.
This works in VLC media player, both .ts and .m3u8 can auto detect interlaced.

**Comment by kingslay** [comment]
mpv可以自动检测出来吗？因为mpv也是基于ffmpeg的。如果mpv可以的话，那可以去看下他们的代码。看下他们是怎么实现的。但是vlc是针对ffmpeg做了很多的优化。所以一般vlc的的功能更强大，比较难把vlc的实现方案应用我的这个库里。

**Comment by chillout23** [comment]
I understand, I think we can ask Lillyplayer developer if MPV can autodetect both .mpegts and .m3u8 streams as he has experience with this player. @skrew is this possible for both streaming formats?

**Comment by chillout23** [comment]
@skrew can you take a look at this?

**Comment by chillout23** [comment]
@kingslay this works also in MPV. I have checked. Can you implement it into KSPlayer?

**Comment by chillout23** [comment]
Grab this file: https://www.transfernow.net/dl/202407268y2HJdr0

**Comment by chillout23** [comment]
@kingslay it looks like this being detected as mpegts even though I put .m3u8 on the file extension. So you need to try this with a live stream. I will find you another link shortly. Thank you.

**Comment by chillout23** [comment]
Thank you for checking. Unfortunately I do not have any clues either.

**Comment by chillout23** [comment]
Currently not possible.

**Comment by chillout23** [comment]
Perfect, thank you @kingslay! Good job.

**Comment by chillout23** [comment]
Completed.
