### ISSUE TITLE
能否支持在线播放NAS上面SMB的视频，目前尝试了不可行。

### ISSUE THREAD

**Issue by wowiwj** [kingslay/KSPlayer#625]
NAS上面的SMB视频地址如下：
smb://root:paasword@192.168.31.100/media/video.mp4
目前尝试无法正常播放。

**Comment by kingslay** [comment]
要支持smb的话，需要能够编译出libsmbclient。但是目前https://github.com/samba-team/samba 在apple系统上无法编译成功。我在我的另外一个项目FFmpegKit里面有写了libsmbclient，但是我尝试了无法成功。你可以试下看可不可以把libsmbclient编译出来。

**Comment by kingslay** [comment]
目前libsmbclient 可以编译成功了。但是编译出来的是动态库，所以无法使用。目前还没找到如何编译成静态库的方式。离成功又近一步了。你可以一起看下如何改成是静态库

**Comment by wowiwj** [comment]
可以，感谢，我在mac也试一下

**Comment by FantasyKingdom** [comment]
可以结合这个开源库https://github.com/amosavian/AMSMB2，稍微修改一下，拿到里面的FileHandle，就能操作io流了。然后使用avio_alloc_context实现播放smb链接。
