### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by charsdavy** [kingslay/KSPlayer#626]
![Screenshot 2023-11-10 at 18 46 30](https://github.com/kingslay/KSPlayer/assets/13601929/9ce178e6-a93c-4c32-b86e-ee67bdff21ee)
![Screenshot 2023-11-10 at 18 46 41](https://github.com/kingslay/KSPlayer/assets/13601929/43e85ed0-e502-4fdb-a911-1897bd496497)
![Screenshot 2023-11-10 at 18 46 14](https://github.com/kingslay/KSPlayer/assets/13601929/7c14e86e-6104-47ba-aa5b-0540e8b7ac7e)

When I play mp4 files on macOS, I have several memory leaks in the image above, how do I solve them?

**Comment by kingslay** [comment]
是任意的一个mp4都有问题吗？

**Comment by charsdavy** [comment]
> 是任意的一个mp4都有问题吗？
> 
> 

是的

**Comment by charsdavy** [comment]
> 是任意的一个mp4都有问题吗？
> 
> 

如果有需要，我可以分享我使用的mp4文件

**Comment by kingslay** [comment]
我用Xcode  15.0 播放https://github.com/kingslay/KSPlayer/raw/develop/Tests/KSPlayerTests/Resources/h264.mp4 这个url不会泄漏

**Comment by charsdavy** [comment]
> 我用Xcode  15.0 播放https://github.com/kingslay/KSPlayer/raw/develop/Tests/KSPlayerTests/Resources/h264.mp4 这个url不会泄漏

我是用Xcode 15.0.1,播放的本地视频文件。今天我把我这边的文件传到云，麻烦你用来调试看看吧。

**Comment by charsdavy** [comment]
> 我用Xcode 15.0 播放https://github.com/kingslay/KSPlayer/raw/develop/Tests/KSPlayerTests/Resources/h264.mp4 这个url不会泄漏

链接: https://pan.baidu.com/s/1HnoloJzo0-sLubEw3pwgRQ?pwd=7qrf 提取码: 7qrf

**Comment by kingslay** [comment]
你可以把视频截断下，只要上传个2分钟的片段到github。就可以了。这样也比较方便。

**Comment by kingslay** [comment]
百度云那个太大了，还要下载客户端。

**Comment by charsdavy** [comment]
可以给个邮箱地址吗？github这边对文件的限制在10MB。太小了。

**Comment by charsdavy** [comment]
https://github.com/kingslay/KSPlayer/assets/13601929/05f951a7-dab5-4f24-ad8f-7a72029c4559

我截图了能出现问题的这段，反复使用本地文件播放的方式，就能遇到我反馈的问题。

**Comment by charsdavy** [comment]
@kingslay 可以复现到问题吗？

**Comment by kingslay** [comment]
我用最新的代码播放了三次。无法复现这个问题。你用最新的代码试下，因为昨晚更新了ffmpeg6.1.

**Comment by charsdavy** [comment]
使用你项目中的demo-macOS，instruments无法检测。但是在使用最新的代码后，我使用发给你的测试视频，依旧还有之前那个内存泄漏问题。

**Comment by charsdavy** [comment]
> https://github.com/kingslay/KSPlayer/raw/develop/Tests/KSPlayerTests/Resources/h264.mp4

Xcode15.0 是有一个不能检测内存泄漏问题的bug，Apple在Xcode15.0.1修复了。

**Comment by charsdavy** [comment]
请问这个问题有进展了吗

**Comment by kingslay** [comment]
还没

**Comment by charsdavy** [comment]
能用附件视频，在Xcode15.0.1上复现问题了吗？
