### ISSUE TITLE
Live Stream with 2 different audio tracks can go out of sync

### ISSUE THREAD

**Issue by cdguy** [kingslay/KSPlayer#627]
In order replicate the issue, please use my test video named "LiveTV with 5-1 sound and Stereo Sound"
https://go.wetransfer.com/b-zvg8ImxsWw

how to replicate:

1- Start the stream with the 5.1 audio track.
-> no issues here
2- switch to the Stereo Audio Track
-> Sometimes the audio track change is instant.
->Sometimes it takes time to change the audio track (and the video stops playing during this time) but the audio is still in sync
-> Sometimes after the audio track is changed, the video and audio goes out of sync
3- when I switch back to the 5.1 audio track, the sound outputted from KSplayer is Stereo (I mean the active audio channel is sterero).

Thanks!

**Comment by kingslay** [comment]
你使用那个audio player type

**Comment by cdguy** [comment]
> 你使用那个audio player type

I used both AudioUnit and AvAudioEngine; and I got the same issue @kingslay
