### ISSUE TITLE
Some 4:2:2 streams are not identified as interlaced streams

### ISSUE THREAD

**Issue by cdguy** [kingslay/KSPlayer#628]
Here is the test files folder:
https://go.wetransfer.com/b-zvg8ImxsWw

Video File to Test:
4-2-2 pure satellite feed_second video

Most of the time, when I open this stream with Yadif Filter (x1 or x2 doesn't matter) Tracy Player identifies the stream as progressive; however the stream is interlaced. Qmplay2 player always labels this stream as interlaced.

When Tracy Player identifies this stream as interlaced, you see this constant buffering (10112023_When Tracy Player identifies the interlaced stream correctly_yadifx2 used video)

Thank you!

**Comment by kingslay** [comment]
要判断是不是interlaced。你可以直接用ffmpeg的命令来判断。
ffmpeg -I xxx

信息里面有top first, bottom first,top coded first (swapped), bottom coded first (swapped) 就代表是interlaced

当视频是identified的话，那就会输出下面的信息 
  Stream #0:0[0x100]: Video: h264 (High 4:2:2) ([27][0][0][0] / 0x001B), yuv422p10le(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 50 tbr, 90k tbn

**Comment by cdguy** [comment]
> 要判断是不是interlaced。你可以直接用ffmpeg的命令来判断。 ffmpeg -I xxx
> 
> 信息里面有top first, bottom first,top coded first (swapped), bottom coded first (swapped) 就代表是interlaced
> 
> 当视频是identified的话，那就会输出下面的信息 Stream #0:0[0x100]: Video: h264 (High 4:2:2) ([27][0][0][0] / 0x001B), yuv422p10le(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 50 tbr, 90k tbn

Input #0, mpegts, from 'C:\ffmpeg\1\4-2-2 pure satellite feed_second video.ts':
  Duration: 00:01:15.66, start: 5133.861756, bitrate: 16078 kb/s
  Program 1
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
  Stream #0:0[0x100]: Video: h264 (High 4:2:2) ([27][0][0][0] / 0x001B), yuv422p10le(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 50 tbr, 90k tbn
  Stream #0:1[0x101](eng): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 384 kb/s
  Stream #0:2[0x102](eng): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 384 kb/s
  Stream #0:3[0x103](eng): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 384 kb/s
  Stream #0:4[0x104](eng): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 384 kb/s

**Comment by cdguy** [comment]
However most of the time, Tracy Player identifies the stream as Progressive


https://github.com/kingslay/KSPlayer/assets/123307657/e8ffe1ce-93e3-475b-ad08-b9936cadafc6

**Comment by cdguy** [comment]
and when Tracy Player can correctly identify the stream as interlaced, that is how the playback is:
Check this video in the collect/wetransfer link: "10112023_When Tracy Player identifies the interlaced stream correctly_yadifx2 used"

**Comment by kingslay** [comment]
@cdguy 是在线的流会判断不准，如果是下载到本地的流应该是可以判断准的吧

**Comment by cdguy** [comment]
> @cdguyIf it is an online stream, it will not be judged accurately. If it is a stream downloaded to a local, it should be able to be judged accurately.

I recorded from a live stream.
However, as you can see here https://github.com/kingslay/KSPlayer/issues/628#issuecomment-1806768793 when I play the stream recording tracy player sees it as progressive

**Comment by cdguy** [comment]
@kingslay can you please update tracy player too?
