### ISSUE TITLE
[BUG]: ControllerTimeModel values are not updating

### ISSUE THREAD

**Issue by nazar-41** [kingslay/KSPlayer#629]
After last update ControllerTimeModel values are not updating. I've tested with .m3u8 HLS file, Xcode 15, iOS 17

![Simulator Screen Recording - iPhone 14 Pro - 2023-11-11 at 16 16 37](https://github.com/kingslay/KSPlayer/assets/89843408/49926fc2-ad30-4815-96aa-a431dff4dc9d)

**Comment by kingslay** [comment]
我用http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8 这个m3u8是可以的
