### ISSUE TITLE
ffmpeg update to 6.1

### ISSUE THREAD

**Issue by cdguy** [kingslay/KSPlayer#630]
Hello @kingslay ffmpeg has been updated to 6.1

I don't know if that would improve the performances of ksplayer, I just wanted to let you know about the update

Thanks

**Comment by kingslay** [comment]
好的。谢谢你的告知。我升级下

**Comment by Alanko5** [comment]
<img width="700" alt="FFmpeg kit 6" src="https://github.com/kingslay/KSPlayer/assets/71501260/d847958f-cedf-482f-a993-5626bcdb0bfe">

@kingslay pods not updating FFmpeg to 6.0.1

**Comment by kingslay** [comment]
pod用的库是spm的一样的。目前也是用6.1了。只是podspec里面的版本号没有改。
