### ISSUE TITLE
我如何在后台初始化多个KSMEPlayer,来同时播放多个音频呢?

### ISSUE THREAD

**Issue by birdmichael** [kingslay/KSPlayer#631]
```
let op = KSOptions()
        op.isAutoPlay = true
        op.videoDisable = true
        music = KSMEPlayer(url: .init(string: "https://miobox-1318984022.cos.ap-nanjing.myqcloud.com/demo/Mat%20Eric%20Hart%20-%20Pure%20Nature%20-%20Morning%20Forest%20Ambience%20Songbirds.wav")!, options: op)
        music?.isMuted = false
        music?.playbackVolume = 1
        music?.play()
```
我这样设置的我 没有效果呢?

**Comment by kingslay** [comment]
你可以看我的iOS-demo。 那个就是可以同时播放多个音频

**Comment by birdmichael** [comment]
我看了.我意思如何不需要view的播放呢?

**Comment by birdmichael** [comment]
Libavfilter.framework/Libavfilter[arm64e][64](yadif_common.o)': found architecture 'arm64e', required architecture 'arm64'

**Comment by kingslay** [comment]
你是什么设备呢？

**Comment by birdmichael** [comment]
m2 tvos 模拟器

**Comment by birdmichael** [comment]
如何不需要view的后台播放音频呢? @kingslay

**Comment by birdmichael** [comment]
还有一个问题..我记得之前是可以预览模式..
现在报错

**Comment by kingslay** [comment]
你只要不将播放器的view加到你的view上面。就不会显示视频了。

**Comment by birdmichael** [comment]
> 你只要不将播放器的view加到你的view上面。就不会显示视频了。

let op = KSOptions()
        op.isAutoPlay = true
        op.videoDisable = true
        music = KSMEPlayer(url: .init(string: "https://miobox-1318984022.cos.ap-nanjing.myqcloud.com/demo/Mat%20Eric%20Hart%20-%20Pure%20Nature%20-%20Morning%20Forest%20Ambience%20Songbirds.wav")!, options: op)
        music?.isMuted = false
        music?.playbackVolume = 1
        music?.play()
        
 我这样写就是你的说法呀...好像没有成功播放

**Comment by kingslay** [comment]
我用我的swiftUI的demo。试了是可以的

**Comment by birdmichael** [comment]
是不是因为setAudioSession
导致只能一个有效啊?
