### ISSUE TITLE
PGS Subtitle Text Remains on the Screen after the Dialogue Ends

### ISSUE THREAD

**Issue by cdguy** [kingslay/KSPlayer#634]
https://github.com/kingslay/KSPlayer/assets/123307657/6641703b-f7a6-4234-9b6f-f52fcd5fcc60

I will send you the link via e-mail.

To reproduce: choose a PGS subtitle

**Comment by Alanko5** [comment]
https://github.com/kingslay/KSPlayer/issues/608
is similar problem

**Comment by cdguy** [comment]
> #608 is similar problem

I shared the VOD link with @kingslay hope he finds a fix

**Comment by kingslay** [comment]
@cdguy 是用swiftUI还是UIKit呢？

**Comment by cdguy** [comment]
> 是用swiftUI还是UIKit呢？

SwiftUI, the video record is from tracy player testflight version,

**Comment by Alanko5** [comment]
There is probably a problem in data parsing, end_display_time is too long.

<img width="437" alt="end time" src="https://github.com/kingslay/KSPlayer/assets/71501260/c8755283-419d-44e6-920d-253efb79504b">
<img width="763" alt="Snímka obrazovky 2023-11-14 o 9 53 15" src="https://github.com/kingslay/KSPlayer/assets/71501260/3ea68b7a-4903-4796-a550-64ac213bea02">

**Comment by kingslay** [comment]
好的，谢谢你提供的信息，晚上下班回去之后，我改下这个bug。

**Comment by JeremTM93** [comment]
Not really annoying, but often after selecting the full subtitles PGS we have to backtrack to get them to activate on screen.
With the latest bits of stream provided by @cdguy I think you could easily reproduce @kingslay

**Comment by kingslay** [comment]
@JeremTM93 这是有一个开关的，isSeekImageSubtitle 把这个设置为true就不会有这个问题了。但是用户选了图片字幕的时候，会loading一下。其实就是我自动帮你们做了seek了。我稍晚把这个开关做到我的testflight里面。这样你就可以用了。
