### ISSUE TITLE
textFontSize = SubtitleModel.Size.smaller.rawValue not working

### ISSUE THREAD

**Issue by Alanko5** [kingslay/KSPlayer#635]
**Describe the bug**
If change font size on apple tv will not effect

**To Reproduce**
textFontSize = SubtitleModel.Size.large.rawValue
textFontSize = SubtitleModel.Size.smaller.rawValue
no difference

**Screenshots**
![Smaller text font size](https://github.com/kingslay/KSPlayer/assets/71501260/67126630-077e-4154-976a-46006a564e5c)

**Platform (please complete the following information):**
 - Device: Apple TV 4k 3gen
 - OS: tvOS 17

**Additional context**
On UIKit player

**Comment by Alanko5** [comment]
Similar
https://github.com/kingslay/KSPlayer/issues/568

**Comment by kingslay** [comment]
看下代码有没有进入到这里
```
  if let text = part.text as? NSMutableAttributedString {
                    text.addAttributes([.font: SubtitleModel.textFont],
                                       range: NSRange(location: 0, length: text.length))
                }
```

**Comment by kingslay** [comment]
还有看下这个字幕是不是文字字幕，如果是图片字幕的话，是无法调整字体大小的
