### ISSUE TITLE
播放抖音直播视频出现错误

### ISSUE THREAD

**Issue by pcccccc** [kingslay/KSPlayer#636]
测试平台： tvOS 17.0

测试链接：http://pull-hs-f5.flive.douyincdn.com/game/stream-7301215242267167522/index.m3u8

当将firstPlayerType和secondPlayerType KSMEPlayer时反馈的错误为：

`Domain=KSPlayerErrorDomain Code=2 "avformat can't open input" UserInfo={NSLocalizedDescription=avformat can't open input`

当firstPlayerType设置为KSMEPlayer，secondPlayerType设置为KSAVPlayer时，错误为：

`502 Bad Gateway`

使用IINA则没有任何问题。

**Comment by pcccccc** [comment]
这可能是个偶发性问题。

**Comment by kingslay** [comment]
这个在iina也会有这个问题吗？

**Comment by pcccccc** [comment]
> 当firstPlayerType设置为KSMEPlayer，secondPlayerType设置为KSAVPlayer时，错误为：
> 
> `502 Bad Gateway`
> 
> 使用IINA则没有任何问题。

没有，但是并不好复现，看起来和视频编码格式有关。
