### ISSUE TITLE
Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio'

### ISSUE THREAD

**Issue by trial** [kingslay/KSPlayer#637]
**Describe the bug**
新建的prj，pods安装，单个view用示例的代码简单设置播放器来播放m3u8
https://nhkwlive-ojp.akamaized.net/hls/live/2003459/nhkwlive-ojp-en/index.m3u8

*** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: node1 != node2'

**Platform (please complete the following information):**
 - Device: iPhone 13 pro
 - OS: [e.g. iOS15.2]

**Comment by trial** [comment]
设置KSOptions.secondPlayerType = KSMEPlayer.self没问题，设置 KSOptions.firstPlayerType = KSMEPlayer.self 就会报上述错误

**Comment by charsdavy** [comment]
> **Describe the bug** 新建的prj，pods安装，单个view用示例的代码简单设置播放器来播放m3u8 https://nhkwlive-ojp.akamaized.net/hls/live/2003459/nhkwlive-ojp-en/index.m3u8
> 
> *** Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: node1 != node2'
> 
> **Platform (please complete the following information):**
> 
> * Device: iPhone 13 pro
> * OS: [e.g. iOS15.2]

我也遇到了同样的问题。

**Comment by UnknownCoder807** [comment]
I suspect this is the same crash I reported here https://github.com/kingslay/KSPlayer/issues/624

Thankfully someone has a proper report for you.
