### ISSUE TITLE
avcodec error

### ISSUE THREAD

**Issue by wertpoiu** [kingslay/KSPlayer#64]
Player crashed attaching image
<img width="895" alt="Screen Shot 2020-08-23 at 8 14 47 PM" src="https://user-images.githubusercontent.com/66154481/90994175-9283b800-e57d-11ea-8d24-839968ea4ac6.png">

**Comment by wertpoiu** [comment]
its happening in repeat

**Comment by wertpoiu** [comment]
@kingslay i got so many crashes, can you please look into it?

**Comment by kingslay** [comment]
you need to download the video. and then Send me that video.

**Comment by wertpoiu** [comment]
> you need to download the video. and then Send me that video.

i dont know which videos are doing that
