### ISSUE TITLE
Audio stops on streams if it changes from 2.0 to 5.1

### ISSUE THREAD

**Issue by edge261** [kingslay/KSPlayer#644]
**Describe the bug**
Some streams have different audio configs depending on the content that the channel is broadcasting at the moment, so an ad could be 2.0 and the show itself is 5.1. When the stream is opened, and 5.1 audio is available, it will switch to 2.0 in the ad break seamlessly, but after the ad break, it should go back to 5.1 and instead, no audio is being sent to the tv or audio receiver. Reopening the stream will give the audio back, but will happen again.

**To Reproduce**
1. Open a stream with 5.1 audio
2. Wait for an ad break (usually ads are in stereo)
3. after the ad break, just silence.

**Expected behavior**
Clean switch between audio sources.

**Screenshots**

**Platform (please complete the following information):**
 - Device: Apple TV 4K 2022
 - OS: tvOS 17.1
 - Version: latest tracyplayer

**Comment by kingslay** [comment]
可以提供下视频片段吗

**Comment by edge261** [comment]
> 可以提供下视频片段吗

let me try to get a clip, i don't know if ffmpeg will catch the change from 2.0 to 5.1 and adjust...

**Comment by edge261** [comment]
thanks @kingslay , seems to be fixed.

however, it drops frames when the switch is made (it was happening before this broke) ... is it expected, or is it a bug?

**Comment by kingslay** [comment]
这是不符合预期的，这个丢帧是丢视频帧还是音频帧呢？是会丢多久呢？

**Comment by edge261** [comment]
> This is not expected, is this lost frame a video frame or an audio frame? How long will it take to lose it?

both, but I believe the video frame loss is more noticeable since it takes a second to recover. 

in the audio i just notice a quick mute (and i'm not sure if it's because of my soundbar).

**Comment by kingslay** [comment]
你可以试下 KSOptions.audioPlayerType=AudioUnitPlayer.self 。然后看会不会有这个问题

**Comment by edge261** [comment]
> 你可以试下 KSOptions.audioPlayerType=AudioUnitPlayer.self 。然后看会不会有这个问题

Well, tried to change the audio mode in TracyPlayer to AudioUnit and still get the same 17 dropped frames, and the audio switch being sloppy...

However, in another app that uses KSplayer, it works flawlessly.

So far, I will consider this bug as solved. If it reappears in the future on another app that's not TracyPlayer, I'll let you know.

**Comment by edge261** [comment]
Sorry to bring it back again. 

I'm checking on a UHD stream and I get lost frames when the audio switches...

Hard to reproduce because not many channels does what this channel do with ads.

Probably will just deal with it until I can find a way to show @kingslay what is happening.

**Comment by kingslay** [comment]
用其他的播放器也会有这个问题吗？例如mpv

**Comment by edge261** [comment]
> 用其他的播放器也会有这个问题吗？例如mpv

Unable to test in MPV because in tvOS the media appears as a blue screen.

Will try with VLC.

**Comment by cdguy** [comment]
> Hard to reproduce because not many channels does what this channel do with ads.

@kingslay please try with the last stream link I shared with you (SDR BT.709)

When I change the audio track using the last tracyplayer on ios, the image freezes, however the audio track continues to play

**Comment by cdguy** [comment]
@kingslay can you please update tracy player? I am sure @djokt and @JeremTM93 would want to try it

**Comment by djokt** [comment]
> @kingslay can you please update tracy player? I am sure @djokt and @JeremTM93 would want to try it

Try tommorow

**Comment by djokt** [comment]
> @kingslay can you please update tracy player? I am sure @djokt and @JeremTM93 would want to try it

As soon as it's available, I'll give it a try and report back here.

**Comment by kingslay** [comment]
已经更新了test flight了
