### ISSUE TITLE
KSOptions.yadifMode = 0/1

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#646]
I would like to offer my users the option to change deinterlace filters in real time.

I offer yadif1x and yadif2x and I set it at playback with 

`KSOptions.yadifMode = 0`
or
`KSOptions.yadifMode = 1`

Is it possible to have this change happen in realtime, like changing the aspect ratio does?

thanks.

**Comment by kingslay** [comment]
KSOptions.yadifMode 不支持实时修改。但你可以实时修改videoFilters里面的filter。这样就可以实现实时效果了。

**Comment by UnknownCoder807** [comment]
How can I do that inside a Button() ?

**Comment by kingslay** [comment]
if let index = videoFilters.firstIndex(where: { $0.hasPrefix("yadif=mode=")}) {
                    videoFilters[index] = "yadif=mode=1:parity=-1:deint=1"
                }

**Comment by UnknownCoder807** [comment]
Thanks, how do I access videoFilters?  it's not found.

**Comment by kingslay** [comment]
通过ksoption

**Comment by UnknownCoder807** [comment]
Thanks, that works.
