### ISSUE TITLE
visionOS compliance

### ISSUE THREAD

**Issue by nightfall708** [kingslay/KSPlayer#648]
Hi,

So while supporting directly UI for visionOS is one thing, we should be able to just compile the raw player component for visionOS.
right now there are multiple errors, some of which are:

'UIScreen' is unavailable in visionOS (PlayerDefines.swift)
'MTKView' is unavailable in visionOS (MetalPlayerView.swift)
Cannot find type 'PlayerViewFullScreenDelegate' in scope (because it is not compiled for visionOS)

and more.
To reveal all error you need to compile for a native visionOS target.

**Comment by kingslay** [comment]
你是用最新的代码吗？MTKView这个问题已经改了。

**Comment by kingslay** [comment]
我之前是有专门修复过visionOS编译的问题，visionOS是可以运行的。但是现在Xcode 15.1 是不支持intel的mac。所以我现在无法验证visionOS是否可以运行

**Comment by nightfall708** [comment]
Yes this is different this time, you have to have an Apple based Mac to compile native visionOS binary. Maybe start a "gofundme" to raise money for a new Mac?

**Comment by nightfall708** [comment]
I've sent you an email
