### ISSUE TITLE
Top bar how to.

### ISSUE THREAD

**Issue by wertpoiu** [kingslay/KSPlayer#65]
How to do custom actions with top bar back button?
How to show airplay button in top bar?
How to hide back button in top bar?

**Comment by wertpoiu** [comment]
@kingslay can you please answer?

**Comment by kingslay** [comment]
PlayerView.backBlock
airplayStatusView.isHidden = !(layer.player?.isExternalPlaybackActive ?? false)
backButton.isHidden = true

**Comment by wertpoiu** [comment]
> PlayerView.backBlock

in landscape airplay button in not touchable seems like theres something overlay.

**Comment by wertpoiu** [comment]
> > PlayerView.backBlock
> 
> in landscape airplay button in not touchable seems like theres something overlay.

Can you please look into it? @kingslay

**Comment by kingslay** [comment]
you can use KSVideoPlayerView. it is swiftUI
