### ISSUE TITLE
是否可以支持拖动进度条时实时画面实时变化

### ISSUE THREAD

**Issue by FantasyKingdom** [kingslay/KSPlayer#650]
系统自带的AVPlayer及第三方的NPlayer支持拖动进度条时播放画面实时变化，并且十分顺滑，是否可以支持，不是那种另外开一个线程在进度条上方进行预览。
我自己简单尝试了下，但是遇到非i帧会回跳，效果非常不好。不知道他们是不是拖动进度条时把所有的非关键帧都解码出来。

**Comment by kingslay** [comment]
他们应该是另外一个线程。把所有的关键帧都解出来。存在本地
