### ISSUE TITLE
请求如何讲视频缓存在本地呢?

### ISSUE THREAD

**Issue by birdmichael** [kingslay/KSPlayer#652]

**Comment by kingslay** [comment]
// ffmpeg only cache http
    public var cache = false

可以把这个改成true

**Comment by birdmichael** [comment]
我试过
但是没有缓存上呢?
还有是只能cache http?

**Comment by kingslay** [comment]
只支持缓存http。这个是ffmpeg提供的能力。

**Comment by birdmichael** [comment]
那我理解的这个其实更像预加载?

**Comment by kingslay** [comment]
就是下次播放同一个url的话，可以用缓存。需要有播放过了。才有缓存。跟预加载还不一样。

**Comment by birdmichael** [comment]
<img width="1780" alt="image" src="https://github.com/kingslay/KSPlayer/assets/12954743/f7394962-e740-4e3a-8984-af012477b214">
我改成http直接崩溃了
地址: http://miobox-dev-1318984022.cos.ap-nanjing.myqcloud.com/scene/%E4%B8%8B%E9%9B%A8%E6%A0%91%E6%9E%97/video.mp4

**Comment by kingslay** [comment]
这个崩溃好奇怪。我本地也是可以复现出来。
