### ISSUE TITLE
Make time in ControllerTimeModel Double(TimeInterval), not Int

### ISSUE THREAD

**Issue by romanyczn1** [kingslay/KSPlayer#655]
Most of swiftui funcs prefer TimeInterval's, like animation

**Describe the solution you'd like**
I would prefer that ControllerTimeModel will not convert TimeInterval to Int

p.s. I know that i can just get duration from Player;)

**Comment by kingslay** [comment]
改成int是为了降低cpu占用率。因为swiftui是值有变化的话，都会刷新界面。所以如果用TimeInterval's的话，那一秒就会刷新好几次。如果使用int，那一秒只会刷新一次。
