### ISSUE TITLE
运算符overflow,RT

### ISSUE THREAD

**Issue by hippiefox** [kingslay/KSPlayer#658]
<img width="784" alt="截屏2023-11-23 15 11 01" src="https://github.com/kingslay/KSPlayer/assets/47681432/5f58e37c-281a-4fb8-878b-689853fd13d6">

**Comment by hippiefox** [comment]
Another Question:
https://github.com/kingslay/KSPlayer 多久会进行一次：main分支 merge from Develop？

**Comment by kingslay** [comment]
这个不确定，有人提需求的话，那我就merge一次。你可以用tag。 2.2.1这个tag解决这个问题了

**Comment by hippiefox** [comment]
> 这个不确定，有人提需求的话，那我就merge一次。你可以用tag。 2.2.1这个tag解决这个问题了

主要是我想基于KSPlayer做一个二次封装的pod，podspec语法上不支持指定分支。em...
