### ISSUE TITLE
Can set video, audio and subtitles track before playing

### ISSUE THREAD

**Issue by skrew** [kingslay/KSPlayer#661]
**Is your feature request related to a problem? Please describe.**

User can select a track (eg, audio track) and want to have it selected immediately when playing the same file again. Setting the selected tracks after file loading make a freeze because the track are changed 1,2 or 3 times (for audio, sub or video).

**Describe the solution you'd like**

Like MEOoptions.startPlayTime, an option the set the wanted track number at start, instead of default one. As the file can change over the time, you have to check if the track exists before forcing it (to avoid crashs)

**Comment by nazar-41** [comment]
@kingslay how to switch video track to auto while video is playing in (swiftUI)
