### ISSUE TITLE
Circular buffer crash

### ISSUE THREAD

**Issue by parski** [kingslay/KSPlayer#666]
**Describe the bug**

While streaming a 50 minute video the player crashed three times with maybe 15-20 minutes between crashes.

```
KSPlayer/CircularBuffer.swift:46: Fatal error: value is not nil of headIndex: 252,tailIndex: 256, bufferCount: 256, mask: 255
```

**To Reproduce**

1. Play the video for 15-20 minutes.
2. 💥

**Expected behavior**

Plays the video until completion.

**Platform (please complete the following information):**
 - Device: Apple TV HD (the latest non-4K one with a USB-C port)
 - OS: tvOS 17
 - Version of what?

**Additional context**

After the crash, opening the app again and fast forwarding to right before where it crashed before and playing the same segment where it previously crashed would not crash the app again. Instead it would crash after another 15-20 minutes of playback.

Using `KSPlayerLayer` for playback. Other videos work fine, never had the crash before.

According to the metadata the media was encoded using libebml v1.4.4 + libmatroska v1.7.1. Not sure how to get more data about the file and I'm not sure I'm allowed to link the source.

Is there a way to handle `_buffer[Int(tailIndex & mask)] != nil` more gracefully? Not even sure I understand why this would happen.

**Comment by kingslay** [comment]
assertionFailure("value is not nil of headIndex: \(headIndex),tailIndex: \(tailIndex), bufferCount: \(_buffer.count), mask: \(mask)")
 这个只是会在开发环境才会crash吧，在release环境应该是不会有问题的吧

**Comment by parski** [comment]
The crash, sure, but isn't this some kind of problem with the buffer that's causing it?

**Comment by kingslay** [comment]
这个问题之前有改过了，是因为文字字幕导致的，你的视频有文字字幕吗？你是用最新的代码吗？

**Comment by parski** [comment]
Yes, I'm using subtitles. I'm using `KSPlayerLayer` to display the video and `SubtitleModel` to render subtitles to a `UILabel`. I'm pointing to the `develop` branch but I have not updated it for a couple of weeks probably. The app is experimental but when I'm getting ready to distribute it I'm gonna point it to the latest release. Is this fixed in [2.2.0](https://github.com/kingslay/KSPlayer/releases/tag/2.2.0)?

**Comment by kingslay** [comment]
在2.2.0 修复了

**Comment by andrefmsilva** [comment]
@kingslay  never tried but apple has some circular buffer implementation:
https://github.com/apple/swift-collections/blob/main/Documentation/Deque.md

**Comment by kingslay** [comment]
我这个CircularBuffer的功能会更复杂。里面还包含 生产者和消费模式，并且需要有排序能力。所以我就自己实现了。但是这个应该还是有优化空间了。目前里面用到了NSCondition。如果能够搞个无锁的版本，那性能应该会提升很多。

**Comment by parski** [comment]
I will build with 2.2.0 and see if I can reproduce the issue.
