### ISSUE TITLE
本地音频播放到最后自动重新播放时，拖动timesilder后会卡住不动

### ISSUE THREAD

**Issue by dreeye** [kingslay/KSPlayer#67]
demo-ios中的本地音频播放完后会自动从头播放，这时往后拖动timesilder后会卡住，需要再拖动下timesilder才会恢复。
试了下本地视频，播放完后自动播放，这时拖动timesilder会卡一会但是会继续播放，不过再次播放完后就不会自动从头播放而是卡住。

**Comment by kingslay** [comment]
可以先把KSOptions.isLoopPlay 给设置为false。就不会有这个问题了

**Comment by kingslay** [comment]
更新下最新代码，我修复了

**Comment by dreeye** [comment]
您好，我更新了代码，本地音频直接拖到结尾还是会卡住。目前KSOptions.isLoopPlay = true，是要更新代码后再设置成false么？

**Comment by kingslay** [comment]
是的。更新代码之后把KSOptions.isLoopPlay = false

**Comment by dreeye** [comment]
明白了
