### ISSUE TITLE
Updating KSNowPlayableMetadata

### ISSUE THREAD

**Issue by Alanko5** [kingslay/KSPlayer#670]
KSNowPlayableMetadata have private initialisers and properties.

I need update artwork or initialise with image url.

but you are initialise only with name:
nowPlayingInfo = KSNowPlayableMetadata(title: name)

I have no way to set other values.

**Comment by kingslay** [comment]
nowPlayingInfo这个变量是可以改的。你可以在KSPlayerResource init方法之后。重新为nowPlayingInfo 赋值。

**Comment by Alanko5** [comment]
<img width="568" alt="Snímka obrazovky 2023-11-27 o 13 07 02" src="https://github.com/kingslay/KSPlayer/assets/71501260/c0a4e11d-8748-4576-b182-0d5a4f25ede7">

<img width="473" alt="Snímka obrazovky 2023-11-27 o 13 10 07" src="https://github.com/kingslay/KSPlayer/assets/71501260/3a62cfed-9306-43f6-b7b1-10d5f8f99919">

**Comment by trial** [comment]
Does anyone experience an issue that MPNowPlayingInfoCenter only works for once?
My player view is on the top and my channel table view is on the bottom, every time I press the table cell, I update the nowPlayingInfo. But it only works for the first time I press the cell.
When I press the cell the second time, MPNowPlayingInfoCenter disappears.
