### ISSUE TITLE
rtsp 播放十几秒就会 buffering

### ISSUE THREAD

**Issue by joy2helloworld** [kingslay/KSPlayer#674]
我们这边 播放 rtsp 实时流，播放十几秒就回bufferring，有明显的卡顿，用其他播放器不会这样，有啥建议吗

**Comment by kingslay** [comment]
配置的参数是一样的吗？

**Comment by kingslay** [comment]
你可以看下用ffplay会不会卡断。

**Comment by joy2helloworld** [comment]
ffplay 也会，但是频率低很多

**Comment by kingslay** [comment]
有url可以测试吗？

**Comment by kingslay** [comment]
用我的最新的tf包试下 https://testflight.apple.com/join/eNmYbmZN
