### ISSUE TITLE
部分设备在播放时没有人声只有背景声

### ISSUE THREAD

**Issue by FaiChou** [kingslay/KSPlayer#678]
可以试下这个影片：

```
【快传】我给你发了 [初...CT.mkv, 快来看看 https://www.alipan.com/t/xiEx3r9DoESoFQkuOrJQ 点击链接即可保存。「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。
```

音轨: `ac3, fltp, 48000Hz, 5.1(side), 640.0Kbs`

部分设备只有背景声，没有人声。

我的设备（模拟器和真机）都是有声音的。

没有声音的设备其中包括一个索尼电视，非 5.1 。

**Comment by kingslay** [comment]
你可以上传那个有问题的片段到github吗？我调试下

**Comment by FaiChou** [comment]
下面视频你试下，我的设备上并没有出现没有人声的问题。但有几个用户反馈是有这问题的。一般都是有两个音轨，第一个音轨是5.1：

https://github.com/kingslay/KSPlayer/assets/18500846/b6d286ae-7d05-479a-8864-c933b8607ce6

**Comment by kingslay** [comment]
这个是用最新的代码吗？之前有解决过 两个音轨，第一个音轨是5.1，第二个音轨是2的 问题

**Comment by kingslay** [comment]
> 刚才将视频使用命令`ffmpeg -ss 00:03:15 -i input-2160p.WEB-DL.HEVC.DDP5.1.2Audios-PanWEB.mp4 -t 5 -c copy output.mp4` 裁剪时候生成的5秒视频5.1音轨丢失了。原视频是有两个音轨的:
> 
> <img alt="image" width="675" src="https://private-user-images.githubusercontent.com/18500846/287648823-b967541a-ee12-4341-905b-4742ea67fe85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2ODI3NjUsIm5iZiI6MTcwMTY4MjQ2NSwicGF0aCI6Ii8xODUwMDg0Ni8yODc2NDg4MjMtYjk2NzU0MWEtZWUxMi00MzQxLTkwNWItNDc0MmVhNjdmZTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDA5MzQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlODY5NDQzMzAxYWRmNTgzYTViYTQ3MGQyY2U5Y2Y2OTUzZDRjOWM2NGY2ZDk0OTk3ZWI0OGI3NmViOGQ5YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TsbaHztKstnbhtXmyjX9unnBJKey6OGpWkcwqhiczM8">

你可以用我的bug模版里面的ffmpeg脚本。他就可以把所有的音频都导出。

**Comment by kingslay** [comment]
53e589e7d232dfa06f3bcef610b1d8ffec69cd70

**Comment by FaiChou** [comment]
OK 我测试下
