### ISSUE TITLE
Airplay Issue

### ISSUE THREAD

**Issue by wertpoiu** [kingslay/KSPlayer#68]
it only plays audio not video. Can you please look into it? @kingslay

**Comment by kingslay** [comment]
the KSMEPlayer only can airplay  audio. can not play video. only the KSAVPlayer can play video

**Comment by wertpoiu** [comment]
ok, when i set av player as a first player it dont switch to ksmeplayer automatically, can you please tell me why?

**Comment by kingslay** [comment]
only when the KSAVPlayer can not play the url.  then switch to ksmeplayer automatically

**Comment by wertpoiu** [comment]
Yes i have some videos that player dont switch to ksmeplayer

**Comment by wertpoiu** [comment]
![IMG_2799](https://user-images.githubusercontent.com/66154481/91476299-6bb9d000-e862-11ea-88ff-f94bc604dc0c.jpg)


Its working with ksme player but its very tricky to make it work.

**Comment by wertpoiu** [comment]
Airplay dont even work with avplayer @kingslay

**Comment by kingslay** [comment]
now the KSMEPlayer can Airplay

**Comment by UnknownCoder807** [comment]
Can airplay work with the new swiftui demo?  if so, how please?

**Comment by UnknownCoder807** [comment]
Maybe I am misunderstanding something, but that code looks like it's for PictureInPicture and not AirPlay ?

**Comment by UnknownCoder807** [comment]
Thanks for the continued work on this.   Is the code now working?  because when I test it, pressing the airplay button just hides the control screen controls.  thanks.

**Comment by kingslay** [comment]
> Thanks for the continued work on this. Is the code now working? because when I test it, pressing the airplay button just hides the screen controls. thanks.

you can long  pressing the airplay button , then i can working. i find the  airplay button conflict with onTapGesture.  I haven't found a solution yet

**Comment by kingslay** [comment]
> Thanks for the continued work on this. Is the code now working? because when I test it, pressing the airplay button just hides the screen controls. thanks.

i fixed it

**Comment by UnknownCoder807** [comment]
Thanks for fixing it.  Does only audio airplay?

**Comment by UnknownCoder807** [comment]
When trying to airplay from iPhone to Apple TV I get the following log entry :

`[NowPlaying] [MRNowPlaying] Ignoring setPlaybackState because application does not contain entitlement com.apple.mediaremote.set-playback-state for platform
`
And there is no video.

**Comment by kingslay** [comment]
> Thanks for fixing it. Does only audio airplay?

the KSMEPlayer is only audio. the KSAVPlayer is can video airplay
