### ISSUE TITLE
FFMepgAssetTrack tcrash

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#681]
**Describe the bug**
Playing any media with latest ksplayer causes the following crash

`KSPlayer_MEPlayerItem_open (9): Fatal error: Range requires lowerBound <= upperBound`

**Screenshots**
![Screenshot 2023-12-04 at 17 40 20](https://github.com/kingslay/KSPlayer/assets/56231066/e8fd99e2-d35f-473c-841a-a5a1cddbc3af)

**Platform (please complete the following information):**
All

**Comment by kingslay** [comment]
可以提供下url给我吗

**Comment by UnknownCoder807** [comment]
> 可以提供下url给我吗

Any url crashes.   on tvos.

**Comment by kingslay** [comment]
我在tvOS的模拟器不会遇到这个问题。是一定要tvos真机才会有这个问题吗？

**Comment by UnknownCoder807** [comment]
Yes, crashes on real device.

**Comment by UnknownCoder807** [comment]
Sorry @kingslay I found the reason for the crash.  I added MPV to my app and I accidentally left the ffmpegkit and libass frameworks it comes with loaded in my app.  once I removed them all is working.  Sorry to trouble you.

**Comment by UnknownCoder807** [comment]
I spoke too soon, it hasn't fixed it.  Looks like a conflict with libmpv + libraries and ksplayer libraries.

**Comment by kingslay** [comment]
你的libmpv 是用我的ffmpegkit这个库的吗？如果不是的话，那就会出问题了

**Comment by UnknownCoder807** [comment]
> 你的libmpv 是用我的ffmpegkit这个库的吗？如果不是的话，那就会出问题了

You are right.  I copied the ffmpegkit xcframeworks from ksplayer across to my libMPV folder (overwriting my own libs) and now it seems to work.  thanks.
