### ISSUE TITLE
新版本编译失败

### ISSUE THREAD

**Issue by birdmichael** [kingslay/KSPlayer#683]
hklkzrmznzcweecslexrlcbxhtxy/Build/Intermediates.noindex/KSPlayer.build/Debug-appletvsimulator/KSPlayer.build/Objects-normal/arm64/KSPlayer.swiftmodule

ld: framework '-lbz2' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kingslay** [comment]
运行环境是什么呢？我这个项目在github action上有配置了各个环境了。都会去做检查的。

**Comment by birdmichael** [comment]
mac air tv 模拟器
好像是FFmpegKit

**Comment by birdmichael** [comment]
现在是 
No such file or directory: 'AudioToolbox'

**Comment by birdmichael** [comment]
-Xlinker -add_ast_path -Xlinker /Users/bm/Library/Developer/Xcode/DerivedData/MIOBOX-hklkzrmznzcweecslexrlcbxhtxy/Build/Intermediates.noindex/KSPlayer.build/Debug-appletvsimulator/KSPlayer.build/Objects-normal/arm64/KSPlayer.swiftmodule

clang: error: no such file or directory: 'AudioToolbox'

**Comment by kingslay** [comment]
连系统库AudioToolbox都没有。那这个就是你的环境有问题了。

**Comment by kingslay** [comment]
你可以试下跑iOS或macos会不会有问题
