### ISSUE TITLE
关于多路视频流

### ISSUE THREAD

**Issue by Ant1mage** [kingslay/KSPlayer#688]
大佬对多路视频流拼接有没有好的想法...
目前能想到的是多个 rtsp 解包保存 frame, 渲染前做帧同步. 不知道这种方式是否靠谱呢?

**Comment by kingslay** [comment]
多路视频流拼接是什么意思呢？你是要把多个视频合并起来一起显示吗？

**Comment by Ant1mage** [comment]
> 多路视频流拼接是什么意思呢？你是要把多个视频合并起来一起显示吗？

是的, 类似于多路监控, 多屏幕时间戳需要一致

**Comment by kingslay** [comment]
那你可以搞多个播放器的view，然后同时显示，如果要保证时间戳一致是比较难的。因为有网络传输的问题，但是如果是内部局域网的话，那时间戳应该相差不会很大。也有一个方式是用ffmpeg在后台把多个流合并成一个流。然后播放合并之后的那个流

**Comment by Ant1mage** [comment]
> 那你可以搞多个播放器的view，然后同时显示，如果要保证时间戳一致是比较难的。因为有网络传输的问题，但是如果是内部局域网的话，那时间戳应该相差不会很大。也有一个方式是用ffmpeg在后台把多个流合并成一个流。然后播放合并之后的那个流

ffmpeg 合并消耗应该挺大的吧...因为要支持至少 16 路的视频流, 在客户端做合并应该延迟很大了.

**Comment by kingslay** [comment]
16路流，如果不在服务端做合并的，那同时播放16路流的话，那客户端的压力也很大，需要设备很好。所以最好是在服务端做合并。

**Comment by Ant1mage** [comment]
> 16路流，如果不在服务端做合并的，那同时播放16路流的话，那客户端的压力也很大，需要设备很好。所以最好是在服务端做合并。

目前只考虑在 M1 M2 的 MacOS 下做

**Comment by kingslay** [comment]
那你可以简单的试下，同时播放16流的效果怎么样。如果很卡的话，那你就只能先用ffmpeg进行合流了。

**Comment by Ant1mage** [comment]
> 那你可以简单的试下，同时播放16流的效果怎么样。如果很卡的话，那你就只能先用ffmpeg进行合流了。

好, 感谢大佬
