### ISSUE TITLE
Airplay button

### ISSUE THREAD

**Issue by wertpoiu** [kingslay/KSPlayer#69]
how to hide airplay button?

**Comment by wertpoiu** [comment]
@kingslay

**Comment by wertpoiu** [comment]
@kingslay can you please help?

**Comment by kingslay** [comment]
airplayStatusView.isHidden = true

**Comment by wertpoiu** [comment]
> airplayStatusView.isHidden = true

This dont work. I wanna hide airplay button from top bar.

**Comment by kingslay** [comment]
airplayStatusView.alpha = 0

**Comment by ManyLattice** [comment]
I think you need routeButton in IOSVideoPlayerView
