### ISSUE TITLE
One specific interlaced stream does not play smoothly

### ISSUE THREAD

**Issue by cdguy** [kingslay/KSPlayer#692]
Using the latest untouched swiftUI player.

I will send the link via e-mail

https://github.com/kingslay/KSPlayer/assets/123307657/a3a4b927-d0a5-4cf5-b835-aed70f19ae5b

**Comment by cdguy** [comment]
@kingslay do you want me to share another recording or the file that I sent via e-mail is enough?

**Comment by kingslay** [comment]
你上次分享给我的，只有前面一小段会有不丝滑的感觉。如果你有遇到不丝滑更明显的视频的话。那可以分享给我。这样更好排查问题

**Comment by cdguy** [comment]
> 你上次分享给我的，只有前面一小段会有不丝滑的感觉。如果你有遇到不丝滑更明显的视频的话。那可以分享给我。这样更好排查问题

Sent via e-mail

**Comment by cdguy** [comment]
the issue is happening when I use yadifx2/yadifx2 spatial skip

**Comment by cdguy** [comment]
@kingslay can you please update the tracy player, someone would like to try the fix with interlaced streams?
thank you

**Comment by kingslay** [comment]
tvos的打包一直出问题 暂时无法打出test flight包 我排查下

**Comment by cdguy** [comment]
> tvos的打包一直出问题 暂时无法打出test flight包 我排查下

No problem :) also check my last e-mail about the video player ui, it might help @kingslay

**Comment by cdguy** [comment]
@kingslay unfortunately it is not fixed.

be sure to use the video file named “ record2 “

thanks

**Comment by kingslay** [comment]
是iOS和tvOS都还会有这个问题吗？

**Comment by cdguy** [comment]
> mvp会有这样的问题吗？

MPV has the issue too

**Comment by kingslay** [comment]
@cdguy 这个问题，昨天的testflight。我有尝试修复了下。你看下有没有好一点。
