### ISSUE TITLE
Client disconnected. Terminating the processes. streamlink process exited with code null

### ISSUE THREAD

**Issue by parryhotter007** [kingslay/KSPlayer#693]
**Describe the bug**
I am running an m3u8 file through a localhost proxy using streamlink, and the video, after running for about 30-40 seconds, goes 5-10 seconds back, and on the console, I get the following message,

**Client disconnected. Terminating the processes.
streamlink process exited with code null**

This is a repeated behavior that happens every 2-3 minutes.

I have tested the same video with both vlc and mpv, and they both work fine.

Can we check what is causing this behavior?

the file URL is something like this http://somewebsite.com:80/username/password/stream.m3u8

**Comment by kingslay** [comment]
那你用ffplay播放会有这个问题吗？

**Comment by parryhotter007** [comment]
No. It runs fine with ffplay as well. Just checked.

**Comment by kingslay** [comment]
你把这些配置注释掉。看还会不会有这些问题

```
    // 参数的配置可以参考protocols.texi 和 http.c
        formatContextOptions["scan_all_pmts"] = 1
        formatContextOptions["auto_convert"] = 0
        formatContextOptions["fps_probe_size"] = 3
        // 默认情况下允许所有协议，只有嵌套协议才需要指定这个协议子集，例如m3u8里面有http。
//        formatContextOptions["protocol_whitelist"] = "file,http,https,tcp,tls,crypto,async,cache,data,httpproxy"
//        formatContextOptions["max_analyze_duration"] = 300 * 1000
        formatContextOptions["reconnect"] = 1
        // 开启这个，纯ipv6地址会无法播放。并且有些视频结束了，但还会一直尝试重连。所以这个值默认不设置
//        formatContextOptions["reconnect_at_eof"] = 1
        formatContextOptions["reconnect_streamed"] = 1
        formatContextOptions["multiple_requests"] = 1
        // 开启这个，会导致tcp Failed to resolve hostname 还会一直重试
//        formatContextOptions["reconnect_on_network_error"] = 1
        // There is total different meaning for 'listen_timeout' option in rtmp
        // set 'listen_timeout' = -1 for rtmp、rtsp
//        formatContextOptions["listen_timeout"] = 3
        formatContextOptions["rw_timeout"] = 10_000_000
```

**Comment by parryhotter007** [comment]
I am afraid I cannot test by changing code as I am running the stream on two IOS IPTV apps and for both it is the same behavior if played through ksplayer. If I play the stream on the same app but chose internal vlc player it works fine without any issues.

**Comment by kingslay** [comment]
那你可以提供对应的url给我吗？不然我无法排查问题。或是你可以找你用的app的开发者，让他们来修改下代码，调试下。

**Comment by parryhotter007** [comment]
I am running nginx as reverse proxy, and passing it through to flash app where I run the URL. The player sends multiple connections to nginx and this disrupts the video being played. I will email you the details, but this can be resolved if client does not repeatedly connect to the server

**Comment by kingslay** [comment]
你用我的testflight 包试下。看下会不会有问题  https://testflight.apple.com/join/eNmYbmZN
