### ISSUE TITLE
Support for iCloud and Remote files support (WebDAV/FTP/Google Drive/etc)

### ISSUE THREAD

**Issue by cdguy** [kingslay/KSPlayer#695]
Since watching video content became very popular using cloud web storage using apps like Infuse, Plex; I thought it would be a great idea to be able to access to remote files using Ksplayer.

I found a library that might you help speeding the implementation of such feature:

https://github.com/amosavian/FileProvider

Thank you!

**Comment by cdguy** [comment]
![IMG_8367](https://github.com/kingslay/KSPlayer/assets/123307657/49829a11-282b-4897-8641-e7eeadc920c6)
![IMG_8368](https://github.com/kingslay/KSPlayer/assets/123307657/48558a4d-4766-4858-ac25-04214a159cca)
![IMG_8369](https://github.com/kingslay/KSPlayer/assets/123307657/bf93ea06-a3ac-44f7-ba63-0a9f0277341e)
![IMG_8370](https://github.com/kingslay/KSPlayer/assets/123307657/734e2428-e0e4-4be7-8ba5-d8311d4a757a)


Screenshots from VLC app and Infuse

**Comment by FaiChou** [comment]
I think this is a function that should be handled by the application, not a feature that a player needs to have. For instance, webdav is actually just HTTP. The application layer needs to obtain the video link and add the auth header, then it can be played normally.

As for the Samba protocol, the developers are probably researching it. So, I also want to ask how the progress is going.
