### ISSUE TITLE
tvOS 中播放这个视频会 crash

### ISSUE THREAD

**Issue by FaiChou** [kingslay/KSPlayer#696]
```
KSVideoPlayerView(url: item.url, options: KSOptions())
```

<img width="1512" alt="Xnip2023-12-20_18-27-17" src="https://github.com/kingslay/KSPlayer/assets/18500846/56be55e6-64dd-4fff-839a-db09ba19cb23">

https://github.com/kingslay/KSPlayer/assets/18500846/9a93cddc-5765-4bfc-8e69-1c0e7ae2174f

**Comment by FaiChou** [comment]
这个视频是我用 iPhone 拍摄的 HDR 视频。在之前的版本中是正常播放的，今天是将代码更新到最新，再测试会闪退（仅测试了模拟器）。

**Comment by kingslay** [comment]
这个在真机是不会crash的，只是模拟器才会
