### ISSUE TITLE
AudioUnit crashes

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#699]
For some reason AudioUnit seems be very unstable these days.

I am getting lots of crashes with it.

Here is the info I have for it, I don't experience the crashes myself and I do not have url's.

![Screenshot 2023-12-21 at 12 17 05](https://github.com/kingslay/KSPlayer/assets/56231066/ba75ef1b-af33-4b1b-b5be-3bfc0ae83e96)

![Screenshot 2023-12-21 at 12 17 18](https://github.com/kingslay/KSPlayer/assets/56231066/8e5979a4-0fb2-4eda-a88a-e4d998755105)

**Comment by kingslay** [comment]
我在e37c42586a18df50f659aebf743d4bb6942fdb8f 这个commit尝试修复了下。你试下。看行不行

**Comment by UnknownCoder807** [comment]
I am already using that commit.  My app uses ksplayer codebase up to wednesday morning.
