### ISSUE TITLE
KSPlayer_vide (2): EXC_BAD_ACCESS (code=1, address=0x8)

### ISSUE THREAD

**Issue by azureplus** [kingslay/KSPlayer#7]
av_buffer_unref(&deviceCtx)
 var framesCtx = av_hwframe_ctx_alloc(deviceCtx)
if let framesCtx = framesCtx {

KSPlayer_vide (2): EXC_BAD_ACCESS (code=1, address=0x8)

ffmpeg:4.2.2

你好，这个需要做什么调整，才能兼容FFmpeg4.2.2

**Comment by kingslay** [comment]
是兼容FFmpeg4.2.2的。 你提供下播放的url。我看下问题

**Comment by azureplus** [comment]
> 是兼容FFmpeg4.2.2的。 你提供下播放的url。我看下问题

任意地址和视频，将你的代码分离出来了，自行封装，估计是配置没有配对的语言

**Comment by azureplus** [comment]
> 是兼容FFmpeg4.2.2的。 你提供下播放的url。我看下问题

好像OK了，最新的代码出现视频图像抖动，一直在颤抖

**Comment by kingslay** [comment]
提供下url。我试下

**Comment by kingslay** [comment]
> > 是兼容FFmpeg4.2.2的。 你提供下播放的url。我看下问题
> 
> 硬件加速OK了，不过最新的代码出现视频图像抖动，一直在颤抖
这个问题解决了。你更新下最新的代码试试看。如果还是不行，麻烦提供下播放地址或是视频。
