### ISSUE TITLE
OpenSSL not enabled by default

### ISSUE THREAD

**Issue by elliots** [kingslay/KSPlayer#702]
I'm trying to add KSPlayer to an existing project (https://github.com/jellyfin/Swiftfin). As it doesn't use cocoapods, i added it as a swift dependency (develop branch)

When trying to play an https url i get "https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled." but i can't work out how to pass `enable-openssl` to the ffmpeg build.

I have basically no experience with ios dev, so apologies if this is an obvious one, but I couldn't see anything about it.

Thankyou for providing this project, looks like it'll be very useful :)

**Comment by kingslay** [comment]
默认是有带openssl的 你可以用我的demo试下。应该是你工程有问题

**Comment by elliots** [comment]
You're right, probably my project. 

When I added cocoapod to it, and added the dependency using that (instead of the git url), it worked.
