### ISSUE TITLE
Can't seek forward/bakwards with a pre-recorded .ts stream (TVOS)

### ISSUE THREAD

**Issue by cdguy** [kingslay/KSPlayer#703]
When I open a pre-recorded .ts stream via WEBDAV, or any remote server, when I seek back with the slider the video does not resume from the minute I choose

also, what you mentioned here (https://github.com/kingslay/KSPlayer/issues/700#issuecomment-1867336325) does not apply to TVOS; I still see the interlace stream info as 25 fps. (only TVOS)

**Comment by kingslay** [comment]
用mpv会有这个问题吗

**Comment by UnknownCoder807** [comment]
> 用mpv会有这个问题吗

I posted to you before about this issue.  on tvos, the MPV app scrolls perfectly.  I sent you a short video of it.

**Comment by kingslay** [comment]
@kingslay 我用你的提供的ts链接是可以进行seek的。之前ts文件的seek确实是有问题，我已经修复好了。录制文件最好不要用ts。因为ts的seek方式比较特殊，有时会出现问题。

**Comment by UnknownCoder807** [comment]
Saved ts files are used for tv catchup (replay/timeshift) on iptv servers.

**Comment by cdguy** [comment]
> @cdguy 我用你的提供的ts链接是可以进行seek的。之前ts文件的seek确实是有问题，我已经修复好了。录制文件最好不要用ts。因为ts的seek方式比较特殊，有时会出现问题。

I guess I did not understand correctly due to the translator. You say that you fixed this issue but I did not see a new commit?

**Comment by kingslay** [comment]
这个问题上个月就已经解决了。我用过最新的代码试了，是可以进行seek的。

**Comment by cdguy** [comment]
> 这个问题上个月就已经解决了。我用过最新的代码试了，是可以进行seek的。

I will check
In the meantime can you please update the new tracyplayer Testflight app if possible? thanks!

**Comment by kingslay** [comment]
好的。可以。tracyplayer有一个比较大的改版。目前支持upnp了。

**Comment by UnknownCoder807** [comment]
> 这个问题上个月就已经解决了。我用过最新的代码试了，是可以进行seek的。

You tried on tvOS?

**Comment by cdguy** [comment]
@kingslay yes the issue is on TVOS

**Comment by kingslay** [comment]
是的，我在tvos上试的

**Comment by cdguy** [comment]
@kingslay thank you, I am closing the thread.

You said that testflight was updated however it is not updated, still the build 97 is on testflight

Thank you!

**Comment by kingslay** [comment]
我知道问题出在哪里了。Xcode Cloud出现问题了。 一直处于这个阶段(等待 Beta 版审核)。不知道是不是因为圣诞放假导致的。

**Comment by UnknownCoder807** [comment]
What I do for beta releases is this.  If my current app is is on version 1.3.4 - I have a testflight version 2.0.0

when I want to release to the app store, I change my version in xcode to 1.3.5

Then I change the version back to 2.0.0 in xcode and I am able to continue issuing beta's without having to go through review all the time.

**Comment by cdguy** [comment]
@kingslay it seems that the update got stuck. Can you please upload the newest version of the Testflight app? Thank you

**Comment by kingslay** [comment]
我我前天提交了一个2.1.4的新版本了 但是还是背卡住了 只能等审核人员来审核了
