### ISSUE TITLE
Small subtitles on iPad

### ISSUE THREAD

**Issue by neckaros** [kingslay/KSPlayer#708]
**Describe the bug**
iPad fall in the iOS category but usually has larger screen

**To Reproduce**
Play a video with subtitle on iPad

**Additional context**
from my understanding issue comes from here:
```
            case .standard:
                #if os(tvOS)
                return 58
                #elseif os(macOS)
                return 26
                #else
                return 16
                #endif
```

maybe adding a if iPadOS would solve the issue?
```
            case .standard:
                #if os(tvOS)
                return 58
                #elseif os(macOS)
                return 26
                #else
                if UIDevice.current.userInterfaceIdiom == .pad {
                  return 26
                } else {
                  return 16
                }
                #endif
```

Also not sure how we are supposed to use the other sizes has 
`    public static var textFontSize = SubtitleModel.Size.standard.rawValue`
is a static

**Comment by kingslay** [comment]
你可以发起个Pull requests 改下pad的字体大小

**Comment by neckaros** [comment]
Submitted PR.

What about the possibility to switch from smaller/small/larger size?

**Comment by kingslay** [comment]
可以的。这个size属性是一个全局静态变量。外面可以任意更改
