### ISSUE TITLE
添加 Package 无法将最新的 FFmpegKit 添加进去

### ISSUE THREAD

**Issue by FaiChou** [kingslay/KSPlayer#709]
我尝试了

```
dependencies: [
    .package(url: "https://github.com/kingslay/KSPlayer.git", .branch("develop"))
]
```

它会将 FFmpetKit 6.1.0 作为依赖添加进项目。

也尝试了手动 `git clone --depth 1 https://github.com/kingslay/KSPlayer.git && git submodule update --init --recursive`, 再添加本地的依赖库到 Xcode 项目，但最终还是将 FFmpetKit 6.1.0 添加到项目里。并且 KSPlayer/FFmpegKit 下是最新的 commit。

<img width="763" alt="image" src="https://github.com/kingslay/KSPlayer/assets/18500846/6e6d27d7-26ed-432a-a0fa-fd812fecbf20">

**Comment by FaiChou** [comment]
<img width="1037" alt="image" src="https://github.com/kingslay/KSPlayer/assets/18500846/d3403488-f1ea-4f2e-aa22-d55310f12872">

**Comment by FaiChou** [comment]
尝试 reset package caches 和 resolve package version, 清除 DerivedData 都没效果。

**Comment by kingslay** [comment]
如果你想用最新的。那你就用

**Comment by FaiChou** [comment]
用最新版后报错 fftools 链接失败

<img width="1049" alt="image" src="https://github.com/kingslay/KSPlayer/assets/18500846/bda8a5b2-5ac0-4d69-ba6b-05992f366608">
