### ISSUE TITLE
Broken subtitle track names

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#710]
**Describe the bug**
On my app and in tracyplayer, the names of the subtitles tracks are wrong.  In the 2 images below, top one is tracyplayer, the 2nd one is the same movie in VLC.

**Screenshots**
TracyPlayer
![tracyplayer](https://github.com/kingslay/KSPlayer/assets/56231066/28597c5d-1c2d-4256-93e0-6c8121f87f97)

VLC
![vlc](https://github.com/kingslay/KSPlayer/assets/56231066/fd8300cb-207b-41e0-8d91-edbedd0ec24c)

**Comment by kingslay** [comment]
这个是因为字幕的 name 没有把languageCode 给加进去。可以提供url给我下。然后我调试下吗？或是你可以直接改FFmpegAssetTrack 这个类。
改下下面这个片段

```
  if let value = metadata["title"] {
            name = value
        } else {
            name = codecName
        }
        // AV_DISPOSITION_DEFAULT
        if mediaType == .subtitle {
            isEnabled = !isImageSubtitle || stream.pointee.disposition & AV_DISPOSITION_FORCED == AV_DISPOSITION_FORCED
            if stream.pointee.disposition & AV_DISPOSITION_HEARING_IMPAIRED == AV_DISPOSITION_HEARING_IMPAIRED {
                name += "(hearing impaired)"
            }
        }
```

**Comment by FaiChou** [comment]
> metadata["title"



> name = codecName

建议`metadata["title"]`为空时候将 language 作为字幕的名字, 而不是` codecName`:

```
 if let value = metadata["title"] {
            name = value
        } else {
            name = languageCode ?? codecName
        }
```
