### ISSUE TITLE
SwiftUI player view 没有初始化 PIPController

### ISSUE THREAD

**Issue by MarveleE** [kingslay/KSPlayer#712]
**Describe the bug**
使用swiftui版的player在开始播放后调动pipcontroller return nil

 - OS: [tvOS17.2]
 - Version [2.2.1]

**Additional context**
Add any other context about the problem here. or Using FFmpeg to extract problematic video segments and upload them to GitHub.(ffmpeg -i http://xxx.com/123.mkv -map 0 -c copy -ss 00:00:50 -to 00:04:10 1.mkv)

**Comment by kingslay** [comment]
tvos是无法使用pip的。只有iOS才可以
