### ISSUE TITLE
Unable to use the remote in tvOS

### ISSUE THREAD

**Issue by edge261** [kingslay/KSPlayer#715]
**Describe the bug**
After the last update (2.1.2 (97)), no controls are displayed in livestreams. Tried all buttons of the remote, no luck.

I can't even return to the main screen of the app. If I go to the tvOS menu, the audio keeps playing in the background.

**To Reproduce**
1. Open a stream
2. Click down button on the remote
3. nothing happens

**Expected behavior**
I expect it to show the player UI.

**Screenshots**

**Platform (please complete the following information):**
 - Device: Apple TV 4K 2022
 - OS: tvOS 17.2

**Comment by kingslay** [comment]
最新的test flight包解决这个问题了。你可以更新下

**Comment by edge261** [comment]
hi @kingslay , i'm not able to see the info of the current stream in tvOS. It only shows the dynamic range and the type of stream (progressive, interlaced)

Also, the menus close themselves without input to do it.

**Comment by kingslay** [comment]
我只是把音频和字幕的信息放到外面的控制条那边了。 其他信息应该还是可以看到的。

**Comment by kingslay** [comment]
嗯，确实会有自动消息的问题。我正在想要怎么优化下这块的交互。视频的info应该需要有一个更方便的打开方式。

**Comment by kingslay** [comment]
> hi @kingslay , i'm not able to see the info of the current stream in tvOS. It only shows the dynamic range and the type of stream (progressive, interlaced)
> 
> Also, the menus close themselves without input to do it.

@edge261  app store上的版本更新了。 优化了下tvos的交互了。
