### ISSUE TITLE
在播放途中闪退

### ISSUE THREAD

**Issue by pcccccc** [kingslay/KSPlayer#717]
播放m3u8直播中，出现了闪退问题。

`Thread 1: Fatal error: Double value cannot be converted to Int because it is either infinite or NaN`

崩溃位置：

KSVideoPlayer

行数： 

238

播放器内核：

KSAVPlayer

**Comment by kingslay** [comment]
给个KSAVPlayer可以播放的直播链接

**Comment by pcccccc** [comment]
> 给个KSAVPlayer可以播放的直播链接

主要是不太好给，，，一般都是有时间限制的。。

**Comment by kingslay** [comment]
那你就看下current time 和total time的值分别是什么

**Comment by pcccccc** [comment]
https://d1--cn-gotcha204-4.bilivideo.com/live-bvc/199432/live_3951100_7420655_minihevc/index.m3u8?expires=1704943897&len=0&oi=3708725859&pt=h5&qn=0&trid=1007abd386422c4440f19f36f1c40e57aa97&sigparams=cdn,expires,len,oi,pt,qn,trid&cdn=cn-gotcha204&sign=924ceb3af44b42119406965d89c412ae&sk=657866af8fc16d8b2b84dfdde3e98143970e231f4ba7166220a3354568f1c7c7&p2p_type=4294967295&sl=4&free_type=0&mid=0&pp=rtmp&source=onetier&trace=20&site=95c47bd032b4ed5670e2fa1f8febf436&order=2

不知道直接给你是否可用，而且这个问题也不是必现的
