### ISSUE TITLE
tvos17.2播放某些格式视频会闪退

### ISSUE THREAD

**Issue by sunzongzheng** [kingslay/KSPlayer#720]
**Describe the bug**
在tvos17.2上播放Demo工程中的m3u8视频会闪退，同样的代码，tvos17.0上不会

**To Reproduce**
1. 直接使用本仓库的`Demo`工程
2. 运行在模拟器tvos17.2上，选择内置的m3u8视频进行播放即可，等待一段时间后就会报错

**Expected behavior**
正常播放

**Screenshots**
<img width="1656" alt="image" src="https://github.com/kingslay/KSPlayer/assets/12635613/6fc669c6-ff69-4b82-8611-9fc29d29c230">

下面这是我自己的项目中播放另外一个m3u8视频时的报错，不知道是不是一个问题，由于视频地址具有时效性，所以不贴上来了
<img width="1437" alt="image" src="https://github.com/kingslay/KSPlayer/assets/12635613/fe297b81-3d37-484c-acab-6d826daebc59">

**Platform (please complete the following information):**
 - Device: 模拟器Apple TV 4K (3rd generation)
 - OS: tvOS 
 - Version: 17.2

**Additional context**
Add any other context about the problem here. or Using FFmpeg to extract problematic video segments and upload them to GitHub.(ffmpeg -i http://xxx.com/123.mkv -map 0 -c copy -ss 00:00:50 -to 00:04:10 1.mkv)

**Comment by sunzongzheng** [comment]
我再测试了fmp4、https、mkv视频也会，其他的视频类型好像都无法加载只在日志中报警告。

会报错的这些视频，在tvOS 17.0上正常

**Comment by kingslay** [comment]
这是模拟器tvOS 17.2的bug 需要等待苹果修复。真机的 tvOS 17.2不会有问题
