### ISSUE TITLE
关于滤镜的问题

### ISSUE THREAD

**Issue by hippiefox** [kingslay/KSPlayer#721]
**Describe the bug**
代码配置：
        KSOptions.firstPlayerType = KSMEPlayer.self
        KSOptions.secondPlayerType = KSMEPlayer.self

       let options = KSOptions()
        options.hardwareDecode = false
        options.isAutoPlay = true
        options.videoFilters = ["gblur=sigma=5"]
        let resource = KSPlayerResource(url: fileURL, options: options, name: filename)
        playerView.set(resource: resource)
控制台输出：
error KSPlayer: MEPlayerItem.swift:131 MEPlayerItem | No such filter: 'gblur'
error KSPlayer: MEPlayerItem.swift:131 MEPlayerItem | Error creating filters

- 无法施加高斯模糊的效果。请问如何处理？
- 或者说 我想给视频添加模糊效果，如何实现？

**Comment by kingslay** [comment]
需要改下FFmpegKit

**Comment by hippiefox** [comment]
> 需要改下FFmpegKit

方便解决嘛？或者给我个Guide，我自行解决。

**Comment by kingslay** [comment]
这属于技术支持，需要成为Sponsors才可以享受。你可以参考下这个项目的Sponsor tier。

**Comment by hippiefox** [comment]
tier？这个选项$30 a month吗？

**Comment by kingslay** [comment]
是的

**Comment by hippiefox** [comment]
> 是的

没问题。我先描述一下我的需求：
1. 可以对视频实时使用滤镜效果：boxblur 和 gblur。
2. 可以动态的修改模糊参数，以展示不同的模糊效果。
上述需求可以解决和满足吗？成为赞助者随时执行。
期待您的回复。

**Comment by kingslay** [comment]
我只是能够为这个库增加boxblur 和 gblur这两个filter。具体filter要如何操作是要你这里来实现。我提供的是ffmpeg标准的filter。

**Comment by hippiefox** [comment]
> 我只是能够为这个库增加boxblur 和 gblur这两个filter。具体filter要如何操作是要你这里来实现。我提供的是ffmpeg标准的filter。

没问题。
关于我需求的第二条的意思是，ffmpeg支持动态修改滤镜的参数吧。 比如模糊半径，需要确认一下。

**Comment by hippiefox** [comment]
<img width="1892" alt="截屏2024-01-19 11 55 06" src="https://github.com/kingslay/KSPlayer/assets/47681432/eeea5c3f-8a40-462a-ac8f-1c6ea4b9ac85">

**Comment by hippiefox** [comment]
已赞助，滤镜的需求问题，期待您的技术支持。
有进展请及时沟通。

**Comment by kingslay** [comment]
@hippiefox  filter已经添加了。你试下。videoFilters是可以实时修改的

**Comment by hippiefox** [comment]
<img width="914" alt="截屏2024-01-22 10 47 05" src="https://github.com/kingslay/KSPlayer/assets/47681432/af4ab0a0-13a2-4cba-8aa9-c74cdf10e1c0">
<img width="397" alt="截屏2024-01-22 10 47 59" src="https://github.com/kingslay/KSPlayer/assets/47681432/21ce1151-03bf-4f23-bdac-d45dbe78b2e4">
<img width="489" alt="截屏2024-01-22 10 48 15" src="https://github.com/kingslay/KSPlayer/assets/47681432/6c1640ab-d486-44b8-a823-94af149a6f26">
<img width="662" alt="截屏2024-01-22 10 48 34" src="https://github.com/kingslay/KSPlayer/assets/47681432/f8dcbab1-7631-43bf-a53a-fef05be5edd4">
<img width="870" alt="截屏2024-01-22 10 49 19" src="https://github.com/kingslay/KSPlayer/assets/47681432/0134dcb8-e26b-4fd6-874c-a6fbf442a5ec">
还是没有滤镜的效果呢？求指点。

**Comment by kingslay** [comment]
FFmpegKit 你先用 f411a5ef5f3c84a1828c4b752a652b298c8ad07b 这个commit。 最新的分支，没有包含boxblur这个 filter

**Comment by hippiefox** [comment]
代码：        options.videoFilters = ["boxblur=50:5"]  [语法参照的地址](https://ffmpeg.org/ffmpeg-filters.html#boxblur)
控制台：error KSPlayer: MEPlayerItem.swift:131 MEPlayerItem | Impossible to convert between the formats supported by the filter 'in' and the filter 'auto_scale_0'
表现：视频无模糊效果。
Q：是我的使用方法不对吗？或者能否给我一下使用boxblur再KSPlayer应用的写法示例吗？

**Comment by kingslay** [comment]
你有设置     options.hardwareDecode = false
了吧

**Comment by hippiefox** [comment]
> 你有设置 options.hardwareDecode = false 了吧

设置后就好了。
Q1: em...我目前的理解是：用滤镜就把硬件解码给关掉，这个理解对不对。
Q2：这个滤镜的特性，后续啥时候会加入到主流的版本，以保持项目可以用到最新的特性的FFMpegKit的包。
