### ISSUE TITLE
播放多音轨视频出错

### ISSUE THREAD

**Issue by fandongtongxue** [kingslay/KSPlayer#722]
拿URL给KSPlayer播放出错
第一张图是写的代码
![WX20240116-140214@2x](https://github.com/kingslay/KSPlayer/assets/21986591/6d048d11-7fea-40a6-9414-dd6821139ac9)
第二张图是报错位置
![WX20240116-140032@2x](https://github.com/kingslay/KSPlayer/assets/21986591/3d29c29f-dd70-4d91-8551-e39c65f010ca)
附上控制台日志
[ksplayer.log](https://github.com/kingslay/KSPlayer/files/13945967/ksplayer.log)

**Comment by fandongtongxue** [comment]
控制台打印 
po codecpar.field_order.rawValue
3516692992

超出了UInt8的最大值

**Comment by kingslay** [comment]
可以提供下url吗？报错的是音轨还是视频轨呢？

**Comment by fandongtongxue** [comment]
感谢关注，后来用你这个demo-iOS测试了下可以播放，没啥问题，我用的是develop分支，直接把你的detailvc复制过来了，
方法也同步了
`
let resource = KSPlayerResource(url: URL(string: resp.url!)!)
 self.play(resource: resource)
`

`
func play(resource: KSPlayerResource?) {
        let controller = KSPlayerVC()
        controller.resource = resource
        self.actionPS.onNext(VMActionType.push(vc: controller, animated: true))
    }
`
Appdelegate里
`
KSOptions.canBackgroundPlay = true
        KSOptions.logLevel = .debug
        KSOptions.firstPlayerType = KSMEPlayer.self
        KSOptions.secondPlayerType = KSMEPlayer.self
//        KSOptions.supportedInterfaceOrientations = .all
        KSOptions.isAutoPlay = true
        KSOptions.isSecondOpen = true
        KSOptions.isAccurateSeek = true
`
一会我写个demo看看

**Comment by fandongtongxue** [comment]
你的demo我测试没问题，我写的就不行呢，我用spm，你用pod的缘故？
我的demo
[KSDemo.zip](https://github.com/kingslay/KSPlayer/files/13957364/KSDemo.zip)

**Comment by kingslay** [comment]
我的demo里面都有pod和spm的例子。你可以用我的spm的例子试下。如果demo没有问题的话，那你就要检查你的代码，看是哪里有问题。如果你一直找不到问题的话，那可以找我寻求技术支持。

**Comment by fandongtongxue** [comment]
作者，您好，我找到问题了，我在项目里也集成了百度网盘的播放器sdk，所以出现了这个问题，你的ffmpeg被他的ffmpeg影响了
