### ISSUE TITLE
播放8K视频出现系统杀进程问题

### ISSUE THREAD

**Issue by charsdavy** [kingslay/KSPlayer#723]
![Screenshot 2024-01-17 at 15 20 41](https://github.com/kingslay/KSPlayer/assets/13601929/f250b51a-42ba-4da7-ae6c-943cbb64a93f)

在 iPhone6s, iOS15 真机上，播放8K或4K视频，会出现系统杀进程问题，原因是内存消耗太大。
测试视频：
https://www.alipan.com/s/sQjsZ5Mf4Fj
https://www.alipan.com/s/u73nkSiD6Mv

**Comment by kingslay** [comment]
不要debug。看下正常播放会不会有问题

**Comment by charsdavy** [comment]
使用Release build到 iPhone6s设备上，依旧会被杀进程。

**Comment by kingslay** [comment]
不要连接着xcode来进行播放。

**Comment by charsdavy** [comment]
没有连着Xcode。Release buid到 iPhone6s 上，播放大概10秒后，被系统杀进程。

**Comment by kingslay** [comment]
使用我的demo会有这个问题

**Comment by charsdavy** [comment]
你项目的uikit demo下，在iPhone6s也会被杀进程。
swiftui的demo需要iOS16，而iPhone6s最高只能支持iOS15，无法验证。

**Comment by kingslay** [comment]
iPhone6s这个机型也太古老了。性能应该无法带不动8k的。我的demo是可以运行在macos上的。你在macos上播放8k的试试。

**Comment by charsdavy** [comment]
主要是内存吃太多了，无解吗？

**Comment by kingslay** [comment]
可以做一些内存优化的处理，但是整个播放体验也不会很好。因为硬件的内存就不够。你可以试下把这个视频转为iOS系统播放可以播放的格式。然后看下用系统播放器。播放的效果怎么样。

**Comment by charsdavy** [comment]
可以通过 formatContextOptions 配置降低 fps 吗？可以的话，配置哪个参数？

**Comment by charsdavy** [comment]
感觉还是想优化下内存，至少做到不被系统杀进程吧。播放卡一点好过被杀进程。

**Comment by kingslay** [comment]
用系统播放器效果怎么样呢
