### ISSUE TITLE
是否可以增加缓冲时长的功能？

### ISSUE THREAD

**Issue by FaiChou** [kingslay/KSPlayer#725]
像 infuse 那种提前缓存几分钟的时长，可以在进度条展示给用户，这样用户拖动进度条到已缓冲的位置可立即跳转。

看了源码，使用 CircularBuffer 来存储 ffmpeg 读取的 packet，是否可以将 Capacity 做大一点或者接收外部参数，存储未被解码的 packet，内存占用应该不会特别大。

**Comment by kingslay** [comment]
可以的 你修改最大缓存时长就可以了

**Comment by 275080225** [comment]
修改maxBufferDuration后会爆内存闪退

**Comment by kingslay** [comment]
需要在一个合理的范围。不能太大

**Comment by 275080225** [comment]
我设置5分钟，就爆了，有办法做成本地存储不

**Comment by kingslay** [comment]
5分钟太长了，你搞个3分钟试下。 本地存储也是可以的，但是目前还没做。有人提了这个feature。
