### ISSUE TITLE
你好 我是个菜鸟 请问一下 想要添加字幕的话 应该如何用呢

### ISSUE THREAD

**Issue by Mikebanana** [kingslay/KSPlayer#726]
例如有个http://img.cdn.guoshuyu.cn/subtitle2.srt 的字幕  

```
 let asset = KSPlayerResource(url: URL(string: "https://media6.smartstudy.com/ae/07/3997/2/dest.m3u8")!,name: "sss",cover: URL(string: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Big_buck_bunny_poster_big.jpg/848px-Big_buck_bunny_poster_big.jpg"),subtitleURLs: [URL(string: "http://img.cdn.guoshuyu.cn/subtitle2.srt")!])
```
我这样写完全没用 应该如何用呢 或者 我哪里少写了设置

**Comment by kingslay** [comment]
你可以用我的macos demo试下。看下传入url行不行，不行的话，你可以把字幕下载下来。然后用本地路径的方式。看下行不行。

**Comment by Mikebanana** [comment]
本地路径也可以往上面subtitleURLs传是吧

**Comment by Mikebanana** [comment]
下载下来了 用本地URL也一样 
<img width="862" alt="image" src="https://github.com/kingslay/KSPlayer/assets/14835999/1457ac9e-8c3c-45cb-afda-ed4cbb21280d">

**Comment by Mikebanana** [comment]
这里面空的  字幕按钮一直隐藏

**Comment by Mikebanana** [comment]
我把 这里注释掉 就出现字幕了 这里为啥会移除掉啊
<img width="778" alt="image" src="https://github.com/kingslay/KSPlayer/assets/14835999/b68f1752-e17a-443c-b9c8-ac5447d2280d">
