### ISSUE TITLE
Get metadata for playing media

### ISSUE THREAD

**Issue by snappycode1** [kingslay/KSPlayer#73]
Is it possible to get info such as bitrate, video format, video & audio buffer from a playing video?

**Comment by kingslay** [comment]
9c2398054aaf80919e77ace37be4ac6d14af2fa9
you can use MediaPlayerTrack to get bitrate,   playableTime to get the buffer

**Comment by wertpoiu** [comment]
> [9c23980](https://github.com/kingslay/KSPlayer/commit/9c2398054aaf80919e77ace37be4ac6d14af2fa9)
> you can use MediaPlayerTrack to get bitrate, playableTime to get the buffer

Can you please give provide code?

**Comment by snappycode1** [comment]
> [9c23980](https://github.com/kingslay/KSPlayer/commit/9c2398054aaf80919e77ace37be4ac6d14af2fa9)
> you can use MediaPlayerTrack to get bitrate, playableTime to get the buffer

Thanks
