### ISSUE TITLE
How can I write a UDP connection in Swiftui

### ISSUE THREAD

**Issue by uguraltinsoy** [kingslay/KSPlayer#733]
Since I don't know how to use swiftui, I am writing in this way, but I couldn't run it, can I watch UDP live broadcast and how should I use swiftui?

```Swift
import SwiftUI
import KSPlayer

struct ContentView: View {
    let playerCoordinator = KSVideoPlayer.Coordinator()
    let options: KSOptions = {
        var option = KSOptions()
        
        return option
    }()
    
    var body: some View {
        VStack {            
            KSVideoPlayer(coordinator: playerCoordinator, url: URL(string: "udp://@127.0.0.1:6000")!, options: options)
                .frame(width: 300, height: 200)            
        }
    }
}
```

**Comment by kingslay** [comment]
你可以用我的swiftUI的demo试下。输入这个udp的url。看下行不行。

**Comment by uguraltinsoy** [comment]
The code I broadcast and the code I test the broadcast are as follows, but the application stays like this

Brodcast WebCam :
```
ffmpeg -f avfoundation -video_size 1280x720 -framerate 30 -i "0" -pixel_format uyvy422 -c:v libx264 -preset medium -tune zerolatency -f mpegts "udp://127.0.0.1:6000?pkt_size=1316"
```
Test Live Video
```
ffplay -fflags nobuffer -flags low_delay -probesize 32 -analyzeduration 1 -strict experimental -framedrop -f mpegts -vf setpts=0 udp://127.0.0.1:6000
```

```Swift
import SwiftUI
import KSPlayer

struct ContentView: View {
    // udp://@127.0.0.1:6000
        
    let options: KSOptions = {
        var option = KSOptions()
        option.isAutoPlay = true
        option.cache = false
        option.probesize = 32
        return option
    }()
    
    var body: some View {
        VStack {
            KSVideoPlayerView(url: URL(string: "udp://127.0.0.1:6000")!, options: options)
        }
    }
}
```

<img width="436" alt="Ekran Resmi 2024-02-15 13 31 33" src="https://github.com/kingslay/KSPlayer/assets/48494791/fd1881e6-387b-4a69-beb9-1a09654682b2">

**Comment by kingslay** [comment]
我的demo里面的Player可以播放你的udp吗？

**Comment by uguraltinsoy** [comment]
I'm not that good at Swift, your demo project seemed very confused to me, I tried to do as much as I could understand. I don't know how I can test with your demo project

**Comment by kingslay** [comment]
你直接运行我的demo。然后在app的界面上会有一个地方可以输入url。你把你的url给输入进去就可以进行测试了。

**Comment by uguraltinsoy** [comment]
The application in TestFlight is connecting, there is a lot of delay but it works

**Comment by kingslay** [comment]
如果我的demo是可以的，那就是你写的代码，有些地方的配置有问题了。你可以先自己排查下，如果还是找不到的原因的话，那我可以提供需要收费的技术支持服务。详细价格可以参考这个项目的Sponsor tiers。

**Comment by uguraltinsoy** [comment]
Paid support because I can't use the library you wrote?
Could your library be giving an "unsupported URL" error?

warning KSPlayer: KSPlayerLayer.swift:423 finish(player:error:) | Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL, NSUnderlyingError=0x600000cbe670 {Error Domain=NSOSStatusErrorDomain Code=-1002 "(null)"}}

<img width="1411" alt="Ekran Resmi 2024-02-15 14 51 38" src="https://github.com/kingslay/KSPlayer/assets/48494791/5e50f8a1-bb54-4ebe-96a4-6d9249d8f8a2">

**Comment by uguraltinsoy** [comment]
How can I contact you privately? I got a Monthly Sponsorship and I only have 1 problem

**Comment by kingslay** [comment]
> Paid support because I can't use the library you wrote? Could your library be giving an "unsupported URL" error?
> 
> warning KSPlayer: KSPlayerLayer.swift:423 finish(player:error:) | Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL, NSUnderlyingError=0x600000cbe670 {Error Domain=NSOSStatusErrorDomain Code=-1002 "(null)"}}
> 
> <img alt="Ekran Resmi 2024-02-15 14 51 38" width="1411" src="https://private-user-images.githubusercontent.com/48494791/305062781-5e50f8a1-bb54-4ebe-96a4-6d9249d8f8a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMDA3NTcsIm5iZiI6MTcwODAwMDQ1NywicGF0aCI6Ii80ODQ5NDc5MS8zMDUwNjI3ODEtNWU1MGY4YTEtYmI1NC00ZWJlLTk2YTQtNmQ5MjQ5ZDhmOGEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDEyMzQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZDhhMjBiYTkyZTJmYmRkMDg0NDkxNWNhYWM3Nzk4YjZhOTUwYmQwMjZlZWM2N2ZiYjdiMTljYmFmNGQzOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pv3R4_9wCqgN2qavZi8iuSnNrBcMWWEoymLdxfD9d8k">

我看了你的日志。你需要加一行代码
`        KSOptions.secondPlayerType = KSMEPlayer.self
`

**Comment by kingslay** [comment]
```
option.codecLowDelay  = true
options.probesize = 32
options.maxAnalyzeDuration = 1


```

**Comment by uguraltinsoy** [comment]
Is it normal that there is so much difference? Isn't this much delay too much when running on localhost?
FFPlay delay 10ms
KSPlayer 17.75s

```Swift
private let options: KSOptions = {
        var options = KSOptions()
        options.isAutoPlay = true
        options.codecLowDelay  = true
        options.probesize = 32
        options.maxAnalyzeDuration = 1
        return options
    }()
```

<img width="1680" alt="Ekran Resmi 2024-02-15 16 16 21" src="https://github.com/kingslay/KSPlayer/assets/48494791/939275a1-c321-4c2e-8e73-9c4b373f5176">

<img width="1680" alt="Ekran Resmi 2024-02-15 16 15 17" src="https://github.com/kingslay/KSPlayer/assets/48494791/53a8f73f-1fc3-461e-95c2-4c800ee685a3">

**Comment by kingslay** [comment]
在加一下             options.formatContextOptions["fflags"] = ["nobuffer"]

**Comment by uguraltinsoy** [comment]
Do you have any other ideas? 10 seconds doesn't seem normal in general. 

<img width="1680" alt="Ekran Resmi 2024-02-15 17 21 22" src="https://github.com/kingslay/KSPlayer/assets/48494791/4b005ccb-8294-407a-bc90-7b4dfc33da0e">

**Comment by kingslay** [comment]
```
            options.preferredForwardBufferDuration = 0.02
option.codecLowDelay  = true
options.probesize = 32
options.maxAnalyzeDuration = 1
options.formatContextOptions["fflags"] = ["nobuffer"]
```

**Comment by uguraltinsoy** [comment]
Unfortunately it doesn't work, there is still a serious delay like 10s.

**Comment by kingslay** [comment]
你试下不要用模拟器，直接用mac或是真实的iPhone运行下。

**Comment by uguraltinsoy** [comment]
dropped to 3-4 seconds between the real device and the mac via wifi from the phone hotspot

**Comment by uguraltinsoy** [comment]
I solved the smoothness problem by downgrading the ffmpeg stream packet, but this error still occurs

```
ffmpeg -f avfoundation -video_size 1280x720 -framerate 30 -i "2" -pixel_format uyvy422 -vf hflip -c:v libx264 -preset ultrafast -tune zerolatency -vf "hflip,crop=in_w/1. 33333:in_h, scale=960:720" -f mpegts "udp://192.168.0.1:6000?pkt_size=32"
```

I get this error and the stream freezes, do you have any advice for this? "error KSPlayer: MEPlayerItem.swift:131 MEPlayerItem | hardware accelerator failed to decode picture"

<img width="1680" alt="Ekran Resmi 2024-02-16 23 54 30" src="https://github.com/kingslay/KSPlayer/assets/48494791/5dc5d0f7-03ce-4d94-b899-9a3f8eebc8bb">

**Comment by kingslay** [comment]
这个报错是说不能硬件解码，所以用的是软件解码。一般直播流要为插入解码信息，这样才能用硬解，但是这样也会导致延迟和流大小增加。
