### ISSUE TITLE
Delay subtitles

### ISSUE THREAD

**Issue by snappycode1** [kingslay/KSPlayer#74]
Is it possible to delay subtitles in milliseconds?  so I can adjust them to appear sooner or later depending on how out of sync they are?

**Comment by wertpoiu** [comment]
yes thats really important

**Comment by kingslay** [comment]
53ae688bd8605b5a43146b6a6d0d3556873f3a83
you can override showSubtile
```
  open func showSubtile(from subtitle: KSSubtitleProtocol, at time: TimeInterval) {
        if let text = subtitle.search(for: time) {
            subtitleBackView.isHidden = false
            subtitleLabel.attributedText = text
        } else {
            subtitleBackView.isHidden = true
        }
    }
```

**Comment by wertpoiu** [comment]
> [53ae688](https://github.com/kingslay/KSPlayer/commit/53ae688bd8605b5a43146b6a6d0d3556873f3a83)
> you can override showSubtile
> 
> ```
>   open func showSubtile(from subtitle: KSSubtitleProtocol, at time: TimeInterval) {
>         if let text = subtitle.search(for: time) {
>             subtitleBackView.isHidden = false
>             subtitleLabel.attributedText = text
>         } else {
>             subtitleBackView.isHidden = true
>         }
>     }
> ```

Thank you

**Comment by wertpoiu** [comment]
> [53ae688](https://github.com/kingslay/KSPlayer/commit/53ae688bd8605b5a43146b6a6d0d3556873f3a83)
> you can override showSubtile
> 
> ```
>   open func showSubtile(from subtitle: KSSubtitleProtocol, at time: TimeInterval) {
>         if let text = subtitle.search(for: time) {
>             subtitleBackView.isHidden = false
>             subtitleLabel.attributedText = text
>         } else {
>             subtitleBackView.isHidden = true
>         }
>     }
> ```

Please reply to other issues as soon well

**Comment by snappycode1** [comment]
thanks
