### ISSUE TITLE
Picture in Picture (PiP) on tvOS

### ISSUE THREAD

**Issue by truckclancy** [kingslay/KSPlayer#741]
It would be really useful to have Picture in Picture (PiP) on tvOS. Documentation: https://developer.apple.com/documentation/avkit/adopting_picture_in_picture_in_a_custom_player

**Comment by kingslay** [comment]
我是有在tvos加了pip能力。但是tvos和macos的pip都只有用系统播放器内核才可以用pip，用ksplayer播放内核是无法用pip的。只有iOS用ksplayer播放内核也可以用pip。这个需要苹果官方才可以。

**Comment by truckclancy** [comment]
Oh, thank you. Do you know why TracyPlayer can pip this stream on macOS/iOS but not tvOS if it's using AVPlayer? https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8

**Comment by kingslay** [comment]
好的，我下班回去看下这个问题。看下是什么原因导致的。

**Comment by kingslay** [comment]
这个问题改好了。你可以用最新的TestFlight包

**Comment by john-dududu** [comment]
> https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8

@kingslay  为啥AVPlayer 起播速度很快，3秒就播了， 而KSPlayer 要十几秒才行

**Comment by Kimentanm** [comment]
这个视频是多分辨率的，AVPlayer会从分辨率最低的视轨开始播起，然后慢慢切换到最高的分辨率，所以快
KSPlayer会直播加载码率最高的那个

> > https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8
> 
> @kingslay 为啥AVPlayer 起播速度很快，3秒就播了， 而KSPlayer 要十几秒才行， 测试用的TracyPlayer
