### ISSUE TITLE
Demo project not working on visionOS 1.1 / iOS 17.4 simulators - libharfbuzz.framework

### ISSUE THREAD

**Issue by ianmagallan** [kingslay/KSPlayer#742]
**Description**
I've just downloaded Xcode 15.3, and my app stopped working on the visionOS 1.1 simulator. The result is that the app can't be installed in the simulator. In order to verify if it's an issue on my end, I decided to launch the demo project from KSPlayer and I noticed that it doesn't work, neither in visionOS 1.1 nor iOS 17.4 -- The error that I receive is the same in both cases.

At this point, I wouldn't rule out that it's an issue with Xcode 15.3 rather in KSPlayer/ffmpeg itself, but I thought that creating an issue for this could help others report if they are experiencing the same issues. 

**How to reproduce**
1. Install Xcode 15.3
2. Launch the "Player" target from KSPlayer, either in iOS 17.4 or visionOS 1.1

**Expected behavior**
Player is installed successfully and can be opened.

**Screenshots and error logs**
<img src="https://github.com/kingslay/KSPlayer/assets/24428301/06072199-93c0-464b-9910-b668e86c86cc" width="666"/>
> App installation failed: Unable to Install “Player”
Domain: IXUserPresentableErrorDomain
Code: 1
Failure Reason: Please try again later.
Recovery Suggestion: Player.app/Frameworks/libharfbuzz.framework is missing its bundle executable. Please check your build settings to make sure that a bundle executable is produced at the path "Player.app/Frameworks/libharfbuzz.framework/libharfbuzz".
User Info: {
    DVTErrorCreationDateKey = "2024-03-06 13:17:20 +0000";
    IDERunOperationFailingWorker = IDELaunchiPhoneSimulatorLauncher;
    SimCallingSelector = "installApplication:withOptions:error:";
}
--
App installation failed: Unable to Install “Player”
Domain: IXUserPresentableErrorDomain
Code: 1
Failure Reason: Please try again later.
Recovery Suggestion: Player.app/Frameworks/libharfbuzz.framework is missing its bundle executable. Please check your build settings to make sure that a bundle executable is produced at the path "Player.app/Frameworks/libharfbuzz.framework/libharfbuzz".
User Info: {
    IDERunOperationFailingWorker = IDELaunchiPhoneSimulatorLauncher;
    SimCallingSelector = "installApplication:withOptions:error:";
}
--
Unable to Install “Player”
Domain: IXUserPresentableErrorDomain
Code: 1
Failure Reason: Please try again later.
Recovery Suggestion: Player.app/Frameworks/libharfbuzz.framework is missing its bundle executable. Please check your build settings to make sure that a bundle executable is produced at the path "Player.app/Frameworks/libharfbuzz.framework/libharfbuzz".
--
Player.app/Frameworks/libharfbuzz.framework is missing its bundle executable. Please check your build settings to make sure that a bundle executable is produced at the path "Player.app/Frameworks/libharfbuzz.framework/libharfbuzz".
Domain: MIInstallerErrorDomain
Code: 71
User Info: {
    FunctionName = "-[MIExecutableBundle executableExistsWithError:]";
    SourceFileLine = 1580;
}
--
lstat of /Users/ian/Library/Developer/CoreSimulator/Devices/FF195797-2331-4FDD-8C8C-7F913D785BC1/data/Library/Caches/com.apple.mobile.installd.staging/temp.MdD1DR/extracted/Player.app/Frameworks/libharfbuzz.framework/libharfbuzz failed: No such file or directory
Domain: NSPOSIXErrorDomain
Code: 2
Failure Reason: No such file or directory
User Info: {
    FunctionName = "-[MIFileManager itemExistsAtURL:error:]";
    SourceFileLine = 1340;
}
--
Event Metadata: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_model" = "iPhone16,1";
    "device_osBuild" = "17.4 (21E213)";
    "device_platform" = "com.apple.platform.iphonesimulator";
    "dvt_coredevice_version" = "355.24";
    "dvt_mobiledevice_version" = "1643.100.58";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 1;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 69095;
    "operation_errorCode" = 1;
    "operation_errorDomain" = IXUserPresentableErrorDomain;
    "operation_errorWorker" = IDELaunchiPhoneSimulatorLauncher;
    "operation_name" = IDERunOperationWorkerGroup;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 3;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.iphonesimulator";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_checker_tpc_enable" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 0;
    "param_launcher_substyle" = 0;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_structuredConsoleMode" = 1;
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "iphonesimulator17.4";
    "sdk_osVersion" = "17.4";
    "sdk_variant" = iphonesimulator;
}
--
System Information
macOS Version 14.3.1 (Build 23D60)
Xcode 15.3 (22618) (Build 15E204a)
Timestamp: 2024-03-06T14:17:20+01:00

**Platform (please complete the following information):**
 - Device: Simulators
 - OS: iOS 17.4 and visionOS 1.1

**Comment by kingslay** [comment]
是的，这个是Xcode 15.3的问题。你可以先用xcode 15.2

**Comment by ianmagallan** [comment]
You are totally right. I downgraded to 15.2 and both OS that I reported can be installed successfully 👍
