### ISSUE TITLE
iOS13 dyld: Library not loaded: /usr/lib/libexpat.1.dylib

### ISSUE THREAD

**Issue by charsdavy** [kingslay/KSPlayer#743]
iOS13的设备，无法启动，控制台提示错误：
iOS13 dyld: Library not loaded: /usr/lib/libexpat.1.dylib
Reason: image not found

推测FFmpeg在编译时，开启了 "--enable-libxml2" 所致。
请问需要如何处理？自行编译FFmpegKit 吗？

**Comment by kingslay** [comment]
你试着把FFmpegKit中的 .linkedLibrary("expat") 给注释掉。看下能不能编的过

**Comment by charsdavy** [comment]
可以编译成功。问题解决。
