### ISSUE TITLE
TracyPalyer支持avi格式视频吗

### ISSUE THREAD

**Issue by FantasyKingdom** [kingslay/KSPlayer#747]
随手测了几个视频，发现avi格式视频只有声音没有画面，用MPV可以播
https://web.ugreen.cloud/web/#/share/EC-WB3W554JJ422IvYg-201468 提取码：7WJK

**Comment by kingslay** [comment]
我在Mac上用TracyPalyer 进行播放是可以的啊。你使用那个端的TracyPalyer呢？

**Comment by FantasyKingdom** [comment]
是ios手机端，用的最新的TestFlight版本

**Comment by FantasyKingdom** [comment]
上面发错链接了，不好意思，我重新发一下，文件不大，只有50M。
https://web.ugreen.cloud/web/#/share/EC-i0sb554JJ422GAhZ-201468 提取码：H6QE

**Comment by kingslay** [comment]
我的app的tf包修复了这个问题了 你可以更新下
