### ISSUE TITLE
用我的TracyPalyer app会有这个问题吗？

### ISSUE THREAD

**Issue by builderxyc01** [kingslay/KSPlayer#749]
用我的TracyPalyer app会有这个问题吗？

_Originally posted by @kingslay in https://github.com/kingslay/KSPlayer/issues/748#issuecomment-1996972753_
           继承KSPlayer库进行测试，没有TracyPalyer进行验证。

**Comment by kingslay** [comment]
你用TracyPalyer进行验证下吧。
