### ISSUE TITLE
Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=AGXMetalA10 Code=3 "Target OS is incompatible.

### ISSUE THREAD

**Issue by azureplus** [kingslay/KSPlayer#75]
Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=AGXMetalA10 Code=3 "Target OS is incompatible.

struct YUVMetalRenderPipeline: MetalRenderPipeline {

        descriptor.fragmentFunction = library.makeFunction(name: "displayYUVTexture")
        // swiftlint:disable force_try
        try! state = device.makeRenderPipelineState(descriptor: descriptor) error

**Comment by kingslay** [comment]
What is your device? If it is an simulator, it needs to be ios13 or higher. If the phone is real, there is no limit

**Comment by azureplus** [comment]
> What is your device? If it is an simulator, it needs to be ios13 or higher. If the phone is real, there is no limit

Apple TV 4k

**Comment by kingslay** [comment]
https://developer.apple.com/forums/thread/105719
