### ISSUE TITLE
SwiftUI Demo无法运行

### ISSUE THREAD

**Issue by hstdt** [kingslay/KSPlayer#752]
**Describe the bug**
1. libsmbclient.xcframework 缺少 info.plist(已经通过手动添加解决)
![CleanShot 2024-03-16 at 22 49 51](https://github.com/kingslay/KSPlayer/assets/10215098/04bba3f3-3f00-41b6-ab77-a24bbca4fa45)
2. Libshaderc_combined.xcframework报错，这个不知道怎么解决
![CleanShot 2024-03-16 at 23 13 58](https://github.com/kingslay/KSPlayer/assets/10215098/10ee7202-67bb-4f8c-a0aa-e55dbd0cb098)

> Please try again later. Player.app/Frameworks/libshaderc_combined.framework is missing its bundle executable. Please check your build settings to make sure that a bundle executable is produced at the path "Player.app/Frameworks/libshaderc_combined.framework/libshaderc_combined".

**To Reproduce**
1. 运行SwiftUI Demo

**Expected behavior**
正常运行demo

**Screenshots**
见上图

**Platform (please complete the following information):**
Xcode 15.3

**Additional context**
无

**Comment by kingslay** [comment]
现在Xcode 15.3有问题，可以先用Xcode 15.2。这个问题很多sdk都有遇到。还没找到解决的方式

**Comment by hstdt** [comment]
好的，那issue要关闭嘛

**Comment by kingslay** [comment]
可以先不关。

**Comment by kingslay** [comment]
你用最新的代码代码试下。看下xcode 15.3还会不会有这个问题

**Comment by hstdt** [comment]
还是不行

**Comment by kingslay** [comment]
你把FFmpegKit 文件夹删除了。然后重新拉一下

**Comment by hstdt** [comment]
确实是submodule没拉到最新代码，不过libfontconfig.xcframework还是缺少info.plist，手动加上之后就能运行了
