### ISSUE TITLE
帧率识别错误

### ISSUE THREAD

**Issue by Kimentanm** [kingslay/KSPlayer#755]
帧率识别成了600帧
test url：https://live-streams-ssai-01.tonton.com.my/live/a884c33b-6b11-4433-8bf9-a8899939e224/cmaf.isml/.m3u8

![image](https://github.com/kingslay/KSPlayer/assets/25970284/a2b7b264-d294-426f-a15c-5a5f3444e6d6)

**Comment by kingslay** [comment]
用ffmpeg打印出来的流信息也是 600. 这个应该是本身流的信息有问题
  Stream #0:2(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 640x360 [SAR 1:1 DAR 16:9], 600 fps, 25 tbr, 600 tbn (default)
