### ISSUE TITLE
Stream error not detected

### ISSUE THREAD

**Issue by nightfall708** [kingslay/KSPlayer#759]
Hi,

These URLs fail to stream, but the player doesn't seem to detect it:

`http://eco.caststream.net/mediacp/system/playlist.php?id=72`
`http://mobile.broadcastmatrix.com/kahm/stream.php?port=8020`

I already set

`formatContextOptions["reconnect_on_network_error"] = 0`

and no change.

Thanks!

**Comment by kingslay** [comment]
这个问题可以通过修改最大的重试时间，来解决

**Comment by nightfall708** [comment]
How do I do that?
