### ISSUE TITLE
请问如何获取音频中的专辑封面呢？

### ISSUE THREAD

**Issue by dreeye** [kingslay/KSPlayer#76]
如何获取音频中的封面并存储成png格式？

**Comment by eximpression** [comment]
Maybe some build error, I copy the function directly form my project. but this func works well in my own app.



public static func getAlbumImage(path: String) -> UIImage? {
        guard let encodingPath = path.cString(using: String.Encoding.utf8) else {
            return nil
        }

        var albumImage:UIImage? = nil
        
        var formatContext = avformat_alloc_context()
        
        let sucess = avformat_open_input(&formatContext, encodingPath, nil, nil)
        if sucess != 0 {
            if formatContext != nil{
                avformat_free_context(formatContext)
            }
            return nil
        }
        
        if avformat_find_stream_info(formatContext, nil) < 0 {
            avformat_close_input(&formatContext)
            return nil
        }
        
        for i in 0..<Int((formatContext!.pointee.nb_streams)){
            if AVMEDIA_TYPE_AUDIO == formatContext!.pointee.streams[i]?.pointee.codecpar.pointee.codec_type {
                continue
            }
            if AVMEDIA_TYPE_VIDEO == formatContext!.pointee.streams[i]?.pointee.codecpar.pointee.codec_type {
                if 0 != ((formatContext!.pointee.streams[i]?.pointee.disposition)! & AV_DISPOSITION_ATTACHED_PIC) {
                    
                    if let picPacket = formatContext!.pointee.streams[i]?.pointee.attached_pic {
                        albumImage = UIImage(data: Data(bytes: picPacket.data, count: Int(picPacket.size)))
                    }
                    break
                }else {
                    if formatContext?.pointee.streams[i]?.pointee.codecpar.pointee.codec_id == AV_CODEC_ID_PNG || formatContext?.pointee.streams[i]?.pointee.codecpar.pointee.codec_id == AV_CODEC_ID_MJPEG{
                        guard let codec = avcodec_find_decoder(formatContext!.pointee.streams[i]!.pointee.codecpar.pointee.codec_id) else {
                            continue
                        }
                        var videoCodecContext = avcodec_alloc_context3(codec)
                        guard videoCodecContext != nil else {
                            continue
                        }
                        if avcodec_parameters_to_context(videoCodecContext, formatContext!.pointee.streams[i]?.pointee.codecpar) < 0 {
                            avcodec_free_context(&videoCodecContext)
                            continue
                        }
                        if avcodec_open2(videoCodecContext, codec, nil) < 0 {
                            avcodec_free_context(&videoCodecContext)
                            continue
                        }
                        var videoFrame:UnsafeMutablePointer<AVFrame>? = av_frame_alloc()
                        defer {
                            av_frame_unref(videoFrame)
                            av_frame_free(&videoFrame)
                        }
                        
                        var packet: UnsafeMutablePointer<AVPacket>? = av_packet_alloc()
                        defer {
                            av_packet_unref(packet)
                            av_packet_free(&packet)
                        }
                        while av_read_frame(formatContext, packet) >= 0 {
                            if packet!.pointee.stream_index == i{
                                break
                            }
                            
                        }
                        var ret = avcodec_send_packet(videoCodecContext, packet)
                        if ret < 0 {
                            avcodec_free_context(&videoCodecContext)
                            continue
                        }
                        while (ret >= 0) {
                            defer {
                                avcodec_free_context(&videoCodecContext)
                            }
                            ret = avcodec_receive_frame(videoCodecContext, videoFrame);
                            if (ret == AVERROR(EAGAIN) || ret == AVERROR_EOF){
                                
                            }else if (ret < 0) {
                                print("Error during decoding")
                                break
                            }
                            //handle videoFrame
                            let width = videoCodecContext!.pointee.width
                            let height = videoCodecContext!.pointee.height
                            // Allocate an AVFrame structure
                            var pFrameRGB=av_frame_alloc()
                            if pFrameRGB == nil {
                                break
                            }
                            defer {
                                av_frame_unref(pFrameRGB)
                                av_frame_free(&pFrameRGB)
                            }
                            // Determine required buffer size and allocate buffer
                            //let numBytes=avpicture_get_size(AV_PIX_FMT_RGB24, width,height);
                            let numBytes = av_image_get_buffer_size(AV_PIX_FMT_RGB24, width, height, 1)
                            let buffer = av_malloc(Int(numBytes) * MemoryLayout<UInt8>.stride).assumingMemoryBound(to: UInt8.self)
                            
                            var swsContext = sws_getContext(width, height, videoCodecContext!.pointee.pix_fmt, width, height, AV_PIX_FMT_RGB24, SWS_BILINEAR, nil, nil, nil)
                            if swsContext == nil {
                                break
                            }
                            defer {
                                sws_freeContext(swsContext)
                            }
                            
                            let data = UnsafeMutablePointer<UnsafeMutablePointer<UInt8>?>.allocate(capacity: 4)
                            //let rgbDataPtr = withUnsafeMutablePointer(to: &data){$0}
                            let linesize = UnsafeMutablePointer<Int32>.allocate(capacity: 4)
                            //let rgbLinesizePtr = withUnsafeMutablePointer(to: &linesize){$0}
                            
                            if av_image_fill_arrays(data, linesize, buffer, AV_PIX_FMT_RGB24, width, height, 1) < 0 {
                                break
                            }
                            
                            var srcData =  UnsafePointer(videoFrame!.pointee.data.0)
                            let srcDataPtr = withUnsafePointer(to: &srcData){$0}
                            var srcLinesize = videoFrame!.pointee.linesize.0
                            let srcLinesizePtr = withUnsafeMutablePointer(to: &srcLinesize){$0}
                            
                            sws_scale(swsContext, srcDataPtr, srcLinesizePtr, 0, height, data, linesize)
                            albumImage = imageFromFrame(buffer: data[0], linesize: Int(linesize[0]), width: Int(width), height: Int(height))
                            break
                        }
                    }
                }
                continue
                //break
            }
        }
        avformat_close_input(&formatContext)
        return albumImage
    }

**Comment by kingslay** [comment]
@dreeye 
```
  override open func player(layer: KSPlayerLayer, state: KSPlayerState) {
        super.player(layer: layer, state: state)
        if state == .readyToPlay, let player = layer.player {
            player.thumbnailImageAtCurrentTime { image in
                print(image)
            }
       }
}
```
