### ISSUE TITLE
前后台切换bug

### ISSUE THREAD

**Issue by FantasyKingdom** [kingslay/KSPlayer#775]
用TracyPlayer播放视频
暂停播放切到后台，然后再切回前台。videotoolbox貌似会解码失败。下一个I帧前的视频packet数据全都会解码失败被丢弃。
如果视频I帧间隔较长的话，就会导致视频缺少这几秒的数据，然后画面卡住好几秒。
不管是使用FFmpeg的硬解还是KSPlayer的硬解都会有这个问题。
不知道这个bug有没有可能修复或者优化一下。

**Comment by FantasyKingdom** [comment]
我发现infuse每次从后台切换到前台都会seek一下，估计也是为了规避这个bug。我直接用infuse的方案好了。

**Comment by CloudlessMoon** [comment]
> 我发现infuse每次从后台切换到前台都会seek一下，估计也是为了规避这个bug。我直接用infuse的方案好了。

infuse的方案是进入前台后seek到当前时间吗
