### ISSUE TITLE
Xcode 12

### ISSUE THREAD

**Issue by wertpoiu** [kingslay/KSPlayer#78]
Mac catalyst not compiling in xcode 12, please resolve issue.

**Comment by wertpoiu** [comment]
@kingslay can you please fix this?

**Comment by kingslay** [comment]
I tried the release of xcode12 yesterday with the demo, no problems.  Version 12.0 (12A7209)

**Comment by wertpoiu** [comment]
> I tried the release of xcode12 yesterday with the demo, no problems. Version 12.0 (12A7209)
you can build but cant archive to release to app store.

**Comment by kingslay** [comment]
What's the error message?

**Comment by wertpoiu** [comment]
> What's the error message?

there are total 54 errors

**Comment by kingslay** [comment]
you is use  xcode Version 12.0 (12A7209) ?

**Comment by wertpoiu** [comment]
> you is use xcode Version 12.0 (12A7209) ?

Sorry my bad i was using beta version, its working fine in Version 12.0 (12A7209)
