### ISSUE TITLE
Invalid bundle identifier when pushing to testflight using KSPlayer via SPM (doesnt happen over ccoapods)

### ISSUE THREAD

**Issue by bgoncal** [kingslay/KSPlayer#781]
**Describe the bug**

"This bundle is invalid. The bundle at path /Frameworks/libshaderc_combined.framework has an invalid CFBundleIdentifier 'com.kintan.ksplayer.libshaderc_combined' There are invalid characters(characters that are not dots, hyphen and alphanumerics) that have been replaced with their code point 'com.kintan.ksplayer.libshaderc\u005fcombined' CFBundleIdentifier must be present, must contain only alphanumerics, dots, hyphens and must not end with a dot. [see the Core Foundation Keys at https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-102070-TPXREF105]"

**To Reproduce**
1. Use KSPlayer through SPM
2. Archive App
3. Upload App

**Expected behavior**
App is uploaded successfully

**Screenshots**

**Platform (please complete the following information):**

**Additional context**
Add any other context about the problem here. or Using FFmpeg to extract problematic video segments and upload them to GitHub.(ffmpeg -i http://xxx.com/123.mkv -map 0 -c copy -ss 00:00:50 -to 00:04:10 1.mkv)

**Comment by bgoncal** [comment]
Thanks, another workaround was to put the SPM inside a framework and then importing this framework into the main target

**Comment by nicolastinkl** [comment]
> 这个问题在lgpl分支解决了。
没有看到呢？ 具体在哪里呢

**Comment by nicolastinkl** [comment]
> lgpl分支是要加入到lgpl小组的人才能看到。
我已经修复了，很简单的一个小问题，就是编译太麻烦，命名的问题导致：https://github.com/nicolastinkl/FFmpegKit

**Comment by theirfanshah** [comment]
@nicolastinkl How can I use "https://github.com/nicolastinkl/FFmpegKit" with KSPlayer Package?

**Comment by niallwatchorn** [comment]
This still exists on master if used through SPM. I don't want to use Cocoapods.
