### ISSUE TITLE
Xcode 15.4上传App Store报错

### ISSUE THREAD

**Issue by pcccccc** [kingslay/KSPlayer#782]
日志：

`This bundle is invalid. The bundle at path Payload/xxxx.app/Frameworks/libshaderc_combined.framework has an invalid CFBundleIdentifier 'com.kintan.ksplayer.libshaderc_combined' There are invalid characters(characters that are not dots, hyphen and alphanumerics) that have been replaced with their code point 'com.kintan.ksplayer.libshaderc\u005fcombined' CFBundleIdentifier must be present, must contain only alphanumerics, dots, hyphens and must not end with a dot. [see the Core Foundation Keys at https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-102070-TPXREF105] (ID: 652ca0bb-4e7e-4779-a8db-23eb6595af5d)`

**Comment by rswilem** [comment]
你是如何解决这个问题的？

**Comment by pcccccc** [comment]
> How did you fix this problem? 你是如何解决这个问题的？

用15.2 然后等KSPlayer更新
