### ISSUE TITLE
Question - Sound change to Reduce Loud Sounds

### ISSUE THREAD

**Issue by Alanko5** [kingslay/KSPlayer#80]
@kingslay  How to switch between "Reduce Loud Sounds" and "Full Dynamic Range"?

**Comment by Alanko5** [comment]
@kingslay it is possible?

https://d2nwkt1g6n1fev.cloudfront.net/skydocu/wp-content/uploads/content/appletv/images/appletv-en-S0309_NightMode.png

**Comment by kingslay** [comment]
The audio output is implemented with AudioUnit, which should do both functions. But I'm not very familiar with audio. I don't know how to implement it.
