### ISSUE TITLE
Stream does not open on apps

### ISSUE THREAD

**Issue by edge261** [kingslay/KSPlayer#817]
**Describe the bug**
This stream (link below) opens on TracyPlayer, but it doesn't open on other iptv apps.

https://venevision.akamaized.net/hls/live/2098814/VENEVISION/master.m3u8

This stream includes different video tracks, with different resolutions.

Also, I believe it should open in the highest resolution available in TracyPlayer or other apps.

**To Reproduce**
1. Open the stream. It won't play (in apps that use KSPlayer as engine)

**Expected behavior**
It should open, in the highest resolution available.

**Platform (please complete the following information):**
 - Device: Apple TV 4K last gen
 - OS: tvOS 18
 - Version: latest TracyPlayer version.

**Comment by edge261** [comment]
> 你使用的那个iptv的app呢？ 需要问下那个app的作者，看下他是不是用最新的代码。目前TracyPlayer使用的lgpl分支最新的代码。你可以让作者更新下代码，看下能不能播放。

I understand. Just thought it was related to the engine.

However, about TracyPlayer (that's the app I'm using right now to watch that content), there is something that could be done to load automatically the highest quality feed when a stream that contains multiple video tracks is opened?

**Comment by DrHurt** [comment]
This is another excellent feature! Thanks

**Comment by edge261** [comment]
> 我增加了一个开关 Is Select Max BitRate Track 。你用最新的testfligh包试下。

Works perfectly, thank you very much!
