### ISSUE TITLE
Subtitle button not clickable

### ISSUE THREAD

**Issue by ridhabnj** [kingslay/KSPlayer#84]
Hello,

The player show automatically  one subtitle but want to change and the button not clickable and no menu to show audio track or subtitle.

We need to create buttons to do that ?

**Comment by wertpoiu** [comment]
same problem here i made my own buttons

**Comment by ridhabnj** [comment]
@wertpoiu do you have the code to change audio track and subtile?

**Comment by ridhabnj** [comment]
any answer ?

**Comment by ridhabnj** [comment]
Made my own buttons.
