### ISSUE TITLE
Cant add button to select audio track

### ISSUE THREAD

**Issue by ridhabnj** [kingslay/KSPlayer#87]
Hello,

want to add button to change audio track.

how to access  class CustomVideoPlayerView: IOSVideoPlayerView  to select track?

 @IBAction func AudioTrackClick(sender:UIButton)
    {
!!!

}

**Comment by Alanko5** [comment]
Check in this issue:
https://github.com/kingslay/KSPlayer/issues/85

**Comment by ridhabnj** [comment]
> Check in this issue:
> #85

Hi,

Thanks, but not working.

How to change this :

`guard let player = self.playerLayer.player else { return [] }
`

i have :
`let LivePlayer = CustomVideoPlayerView()
`
Can you help ?

**Comment by ridhabnj** [comment]
Hi,

Cannot find type 'CustomVideoPlayerView' in scope

**Comment by Alanko5** [comment]
Yes not in scope CustomVideoPlayerView is child of VideoPlayerView.

**Comment by ridhabnj** [comment]
Resolved, Thanks.
