### ISSUE TITLE
appletv with xcode Version 12.2 beta 2 (12B5025f)

### ISSUE THREAD

**Issue by Alanko5** [kingslay/KSPlayer#88]
duplicate symbol '_IS_AVERROR_EOF' in:
    .../Library/Developer/Xcode/DerivedData/StreamCinema.atv-cmmgejnmqlvccqaehtbtwpnhstxn/Build/Products/Debug-appletvsimulator/KSPlayer/KSPlayer.framework/KSPlayer(MEPlayerItem.o)
    .../Library/Developer/Xcode/DerivedData/StreamCinema.atv-cmmgejnmqlvccqaehtbtwpnhstxn/Build/Products/Debug-appletvsimulator/KSPlayer/KSPlayer.framework/KSPlayer(SoftwareDecode.o)
ld: 1 duplicate symbol for architecture x86_64

**Comment by Alanko5** [comment]
If test run on tvOS.

duplicate symbol '_IS_AVERROR_EOF' in:
    .../Library/Developer/Xcode/DerivedData/StreamCinema.atv-cmmgejnmqlvccqaehtbtwpnhstxn/Build/Products/Debug-appletvos/KSPlayer/KSPlayer.framework/KSPlayer(MEPlayerItem.o)
    /Library/Developer/Xcode/DerivedData/StreamCinema.atv-cmmgejnmqlvccqaehtbtwpnhstxn/Build/Products/Debug-appletvos/KSPlayer/KSPlayer.framework/KSPlayer(SoftwareDecode.o)
ld: 1 duplicate symbol for architecture arm64

**Comment by kingslay** [comment]
fix by ad10c89780835efed928bfc5abcc86a8f6258a0c
