### ISSUE TITLE
Using tvos slider

### ISSUE THREAD

**Issue by wertpoiu** [kingslay/KSPlayer#89]
Can i use your tvos slider with another player independently?

**Comment by kingslay** [comment]
yes . you can

**Comment by wertpoiu** [comment]
> yes . you can

How? Can you please guide with code?

**Comment by Alanko5** [comment]
I use player.seek(time: TimeInterval)

**Comment by wertpoiu** [comment]
> I use player.seek(time: TimeInterval)

but i want to use it with vlc

**Comment by kingslay** [comment]
public var timeSlider = KSSlider()
