### ISSUE TITLE
initial overlay display when video starts playing

### ISSUE THREAD

**Issue by snappycode1** [kingslay/KSPlayer#9]
I have managed to implement ksplayer into a project of mine, but find whenever a video starts to play there is an overlay displayed at the bottom of the screen.  It is a progress bar and there is some chinese(?) language text at the bottom right.  It does disappear after a few seconds.

Is it possible to disable this overlay from appearing?

**Comment by prikshitgupta** [comment]
Same issue here video is starting from 10 mins not 0:00.

**Comment by kingslay** [comment]
> I have managed to implement ksplayer into a project of mine, but find whenever a video starts to play there is an overlay displayed at the bottom of the screen. It is a progress bar and there is some chinese(?) language text at the bottom right. It does disappear after a few seconds.
> 
> Is it possible to disable this overlay from appearing?

The toolbar is automatically hidden during playback. The default value is 5s. You can change the default value with KSPlayerManager.imateDelayTimeInterval
You can control the button hiding yourself

```
class CustomVideoPlayerView: IOSVideoPlayerView {
    override func updateUI(isLandscape: Bool) {
        super.updateUI(isLandscape: isLandscape)
        toolBar.playbackRateButton.isHidden = true
    }
}
```

**Comment by kingslay** [comment]
> Same issue here video is starting from 10 mins not 0:00.

Is it live or on-demand? Please provide the URL.

**Comment by prikshitgupta** [comment]
> > Same issue here video is starting from 10 mins not 0:00.
> 
> Is it live or on-demand? Please provide the URL.

how i can contact you privately? cant send you link publicly.

**Comment by prikshitgupta** [comment]
> > Same issue here video is starting from 10 mins not 0:00.
> 
> Is it live or on-demand? Please provide the URL.

yes its happening in live video and on demand both.

**Comment by kingslay** [comment]
> privately

yes. you can . What's your email address?

**Comment by prikshitgupta** [comment]
> > privately
> 
> yes. you can . What's your email address?

prikshitgupta@outlook.com

**Comment by kingslay** [comment]
> > > privately
> > 
> > 
> > yes. you can . What's your email address?
> 
> [prikshitgupta@outlook.com](mailto:prikshitgupta@outlook.com)

This is due to the timestamp of the first frame of the audio. the pkt_pts is 54000000
  <frame media_type="audio" stream_index="1" key_frame="1" pkt_pts="54000000" pkt_pts_time="600.000000" pkt_dts="54000000" pkt_dts_time="600.000000" best_effort_timestamp="54000000" best_effort_timestamp_time="600.000000" pkt_duration="2089" pkt_duration_time="0.023211" pkt_pos="39668" pkt_size="13" sample_fmt="fltp" nb_samples="1024" channels="2" channel_layout="stereo"/>

**Comment by prikshitgupta** [comment]
> > > > privately
> > > 
> > > 
> > > yes. you can . What's your email address?
> > 
> 
> This is due to the timestamp of the first frame of the audio. the pkt_pts is 54000000

So what is the fix?

**Comment by prikshitgupta** [comment]
Theres no such issue with other plyers

**Comment by kingslay** [comment]
> > > > > privately
> > > > 
> > > > 
> > > > yes. you can . What's your email address?
> > 
> > 
> > This is due to the timestamp of the first frame of the audio. the pkt_pts is 54000000
> 
> So what is the fix?

I have found a solution. There's a start_time field inside the video. 
I'll fix this tomorrow.

**Comment by prikshitgupta** [comment]
> > > > > > privately
> > > > > 
> > > > > 
> > > > > yes. you can . What's your email address?
> > > 
> > > 
> > > This is due to the timestamp of the first frame of the audio. the pkt_pts is 54000000
> > 
> > 
> > So what is the fix?
> 
> I have found a solution. There's a start_time field inside the video.
> I'll fix this tomorrow.

Great Thank you

**Comment by snappycode1** [comment]
> > I have managed to implement ksplayer into a project of mine, but find whenever a video starts to play there is an overlay displayed at the bottom of the screen. It is a progress bar and there is some chinese(?) language text at the bottom right. It does disappear after a few seconds.
> > Is it possible to disable this overlay from appearing?
> 
> The toolbar is automatically hidden during playback. The default value is 5s. You can change the default value with KSPlayerManager.imateDelayTimeInterval
> You can control the button hiding yourself
> 
> ```
> class CustomVideoPlayerView: IOSVideoPlayerView {
>     override func updateUI(isLandscape: Bool) {
>         super.updateUI(isLandscape: isLandscape)
>         toolBar.playbackRateButton.isHidden = true
>     }
> }
> ```

Thanks, this has helped a little.  The overlay is still shown, but for much less time.  Ideally, it would be perfect if it could be disabled totally.

**Comment by kingslay** [comment]
> > > > > > > privately
> > > > > > 
> > > > > > 
> > > > > > yes. you can . What's your email address?
> > > > 
> > > > 
> > > > This is due to the timestamp of the first frame of the audio. the pkt_pts is 54000000
> > > 
> > > 
> > > So what is the fix?
> > 
> > 
> > I have found a solution. There's a start_time field inside the video.
> > I'll fix this tomorrow.
> 
> Great Thank you

it fixed

**Comment by prikshitgupta** [comment]
> > > > > > > > privately
> > > > > > > 
> > > > > > > 
> > > > > > > yes. you can . What's your email address?
> > > > > 
> > > > > 
> > > > > This is due to the timestamp of the first frame of the audio. the pkt_pts is 54000000
> > > > 
> > > > 
> > > > So what is the fix?
> > > 
> > > 
> > > I have found a solution. There's a start_time field inside the video.
> > > I'll fix this tomorrow.
> > 
> > 
> > Great Thank you
> 
> it fixed

issue is still there i have updated library. now i am getting ffmpeg warnings but issue is not fixed.

**Comment by kingslay** [comment]
> imateDelayTimeInterval

After updating the latest code.  it could be disabled totally.  According to the code below

```
class CustomVideoPlayerView: IOSVideoPlayerView {
    override func updateUI(isLandscape: Bool) {
        super.updateUI(isLandscape: isLandscape)
        bottomMaskView.isHidden = true
    }
}

```

**Comment by snappycode1** [comment]
Thank you, setting the bottomMaskView to hidden does the trick
