### ISSUE TITLE
ToolBar not clickable on landscape

### ISSUE THREAD

**Issue by ridhabnj** [kingslay/KSPlayer#90]
Hello,

On landscape, all toolBar no clickable, only volume , brightness and lock.

Need to enable landscapeButton.

Thanks.

**Comment by kingslay** [comment]
you can click the backButton

**Comment by ridhabnj** [comment]
Resolved. Subview problem.

**Comment by wertpoiu** [comment]
> Resolved. Subview problem.

How did you resolve it?
