### ISSUE TITLE
Could not find codec parameters for stream

### ISSUE THREAD

**Issue by ridhabnj** [kingslay/KSPlayer#94]
Hello,
I have this error on same live stream :

` KSPlayer: KSMEPlayer.swift:245 prepareToPlay() | prepareToPlay KSPlayer.KSMEPlayer
KSPlayer: KSPlayerLayer.swift:99 state | playerStateDidChange - notSetURL
KSPlayer: KSPlayerLayer.swift:99 state | playerStateDidChange - buffering
KSPlayer: MEPlayerItem.swift:88 init(url:options:) | PES packet size mismatch

KSPlayer: MEPlayerItem.swift:88 init(url:options:) | Packet corrupt (stream = 0, dts = 686392925)
KSPlayer: MEPlayerItem.swift:88 init(url:options:) | .

KSPlayer: MEPlayerItem.swift:394 shutdown() | 清空formatCtx
KSPlayer: MEPlayerItem.swift:88 init(url:options:) | Header missing

KSPlayer: MEPlayerItem.swift:88 init(url:options:) | Could not find codec parameters for stream 0 (Audio: mp3 (mp3float) ([4][0][0][0] / 0x0004), 0 channels, fltp): unspecified frame size
Consider increasing the value for the 'analyzeduration' and 'probesize' options

KSPlayer: MEPlayerItem.swift:394 shutdown() | 清空formatCtx `

Please Help.

**Comment by Alanko5** [comment]
Show your code.

**Comment by kingslay** [comment]
you can change the  formatContextOptions
```
  public init() {
        formatContextOptions["auto_convert"] = 0
        formatContextOptions["fps_probe_size"] = 3
        formatContextOptions["reconnect"] = 1
        // There is total different meaning for 'timeout' option in rtmp
        // remove 'timeout' option for rtmp、rtsp
        formatContextOptions["timeout"] = 30_000_000
        formatContextOptions["rw_timeout"] = 30_000_000
        formatContextOptions["user_agent"] = "ksplayer"
        decoderOptions["threads"] = "auto"
        decoderOptions["refcounted_frames"] = "1"
        var timebaseInfo = mach_timebase_info_data_t()
        mach_timebase_info(&timebaseInfo)
        // 间隔0.1s
        throttleDiff = UInt64(100_000_000 * timebaseInfo.denom / timebaseInfo.numer)
    }
```

**Comment by kingslay** [comment]
you can r increasing the value for the  probesize and analyzeduration
 let options = KSOptions()
options.formatContextOptions["probesize"] = 10000000
options.formatContextOptions["analyzeduration"] = 10000000
