### ISSUE TITLE
Is TRUEHD and DollbyAttmos supported?

### ISSUE THREAD

**Issue by Alanko5** [kingslay/KSPlayer#95]
According to the description ffmpeg should be supported.

@kingslay I switch to TRUEHD audio:
KSPlayer: KSPlayerLayer.swift:99 state | playerStateDidChange - buffering
KSPlayer: SoftwareDecode.swift:29 init(assetTrack:options:) | Error Domain=KSPlayerErrorDomain Code=7 "unknown" UserInfo={NSUnderlyingError=0x28270b930 {Error Domain=FFmpegDomain Code=0 "Undefined error: 0" UserInfo={NSLocalizedDescription=Undefined error: 0}}, NSLocalizedDescription=unknown}

**Comment by Alanko5** [comment]
FFMPG support TRUEHD and DTS:
https://itectec.com/superuser/how-to-use-ffmpeg-to-downmix-5-1-dts-hd-ma-or-dolby-truehd-to-stereo-aac-with-dolby-pro-logic-ii/

@kingslay please fix it.

**Comment by kingslay** [comment]
@Alanko5 Can you provide that play link for me to test？
