### ISSUE TITLE
When archiving i got no No such module 'ffmpeg' error with Xcode 12.2

### ISSUE THREAD

**Issue by byMohamedali** [kingslay/KSPlayer#96]
Before it was working fine, the error appears only when archiving

<img width="859" alt="image" src="https://user-images.githubusercontent.com/6490189/99444755-160f3400-2936-11eb-9171-bddbcce56388.png">

**Comment by byMohamedali** [comment]
@kingslay ?

**Comment by kingslay** [comment]
the KSPlayer not support archiving for armv7. only support arm64

**Comment by kingslay** [comment]
@byMohamedali you can change the IPHONEOS_DEPLOYMENT_TARGET to  11.0.  and it can archiving in Xcode 12.2

**Comment by byMohamedali** [comment]
Even by doing this it doesn't work i try to put manually armv7 but still the same result.

**Comment by byMohamedali** [comment]
As you can see below,  it's compiling with armv7 
<img width="818" alt="image" src="https://user-images.githubusercontent.com/6490189/99887756-8680c280-2c60-11eb-8227-ee89ab5c0bad.png">

**Comment by byMohamedali** [comment]
I found the fix, you have to put ios 11.0 on ksplayer target 
<img width="863" alt="image" src="https://user-images.githubusercontent.com/6490189/99888120-98b03000-2c63-11eb-8e47-f7189a62c671.png">
