### ISSUE TITLE
Cannot build project to the OpenSSL change

### ISSUE THREAD

**Issue by byMohamedali** [kingslay/KSPlayer#97]
I tried on last commit on develop and master, both doesn't work
<img width="644" alt="image" src="https://user-images.githubusercontent.com/6490189/99888651-e7f85f80-2c67-11eb-99f3-db6fadf03a97.png">

**Comment by kingslay** [comment]
clean Build Folder

**Comment by byMohamedali** [comment]
Ok i find the fix i had to put ios deployment targent to 11.0 for openssl target, thank you anyway
