### ISSUE TITLE
Unable to pod update since changes

### ISSUE THREAD

**Issue by snappycode1** [kingslay/KSPlayer#98]
Since the changes in the last commit, it's no longer possible to pod update or pod install anymore.

I created a new project and install Cocoapods.  I then added  to the Podfile

```
pod 'KSPlayer',:git => 'https://github.com/kingslay/KSPlayer.git', :branch => 'develop'
pod 'Openssl',:git => 'https://github.com/kingslay/KSPlayer.git', :branch => 'master'
```

I then do pod install and get the following error :

```
Analyzing dependencies
Pre-downloading: `KSPlayer` from `https://github.com/kingslay/KSPlayer.git`, branch `develop`
Pre-downloading: `Openssl` from `https://github.com/kingslay/KSPlayer.git`, branch `master`
[!] The platform of the target `test` (tvOS 14.2) is not compatible with `OpenSSL (1.0.210)`, which does not support `tvOS`.
```

**Comment by kingslay** [comment]
try chang to

`pod 'Openssl',:git => 'https://github.com/kingslay/KSPlayer.git', :branch => 'develop'
`

**Comment by snappycode1** [comment]
It now gets further but now I have the following error :

```
Removing Openssl
Generating Pods project
[!] Attempt to read non existent folder `/Users/blah/Programming/myCode/Test/Pods/OpenSSL`.
```

If I create the OpenSSL directory manually, it is removed during the pod update

**Comment by kingslay** [comment]
`rm -rf /Users/blah/Programming/myCode/Test/Pods  && pod install`

**Comment by snappycode1** [comment]
Thanks all working now.
